<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi relative au cadre national sur le diabète</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Cadre national sur le diabète</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Rapports au Parlement</span></a>
</li></ul>
</li></ul>

</nav>

