<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi électorale du Canada (financement politique)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-2"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-3"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

