<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi maritime du Canada, la Loi sur les transports au Canada, la Loi sur le pilotage et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">LOI MARITIME DU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES TRANSPORTS AU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE PILOTAGE</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-4"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-5"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-6"><span class="HTitleText2">Loi sur la sûreté du transport maritime</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="#h-8"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

