<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Accord de libre-échange Canada–Costa Rica, Loi de mise en oeuvre de l’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MISE EN OEUVRE DE L’ACCORD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approbation de l’Accord</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText2">Groupes spéciaux, comités, sous-comités et groupes de travail</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Décrets et règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-13"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-14"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-15"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-16"><span class="HTitleText2">Loi sur les licences d’exportation et d’importation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-17"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-18"><span class="HTitleText2">Loi sur l’importation des boissons enivrantes</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-19"><span class="HTitleText2">Loi sur l’Office national de l’énergie</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-20"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

