<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel et le Code canadien du travail</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

