<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant les frais d'utilisation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">CONSULTATION OBLIGATOIRE</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-5"><span class="HTitleText1">PLAINTES</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText1">EXAMEN PAR LE COMITÉ</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="#h-7"><span class="HTitleText1">RÉDUCTION DES FRAIS D'UTILISATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText1">RÉSOLUTION DE LA CHAMBRE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText1">RAPPORT ANNUEL DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-10"><span class="HTitleText1">EXAMEN DE LA LOI</span></a>
</li></ul>
</li></ul>

</nav>

