<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur le droit d’auteur (accès des personnes ayant des déficiences perceptuelles aux oeuvres ou autres objets du droit d’auteur protégés)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le droit d’auteur</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

