<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur des mesures en réponse à la COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les prestations canadiennes de relance économique</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-3"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-2.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les mesures d’urgence visant la COVID-19</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-7"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement du Canada sur les normes du travail</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-8"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement modifiant le Règlement du Canada sur les normes du travail</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-3.html#h-11"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Paiements relatifs aux événements de santé publique d’intérêt national</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-3.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements relatifs aux événements de santé publique d’intérêt national</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures d’urgence visant la COVID-19</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-4.html#h-16"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

