<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Charte des droits des victimes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CHARTE CANADIENNE DES DROITS DES VICTIMES</cite></span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-2.html#h-3"><span class="HTitleText1">EXAMEN DE LA LOI </span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-6.html#h-6"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-6.html#h-7"><span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LE SYSTÈME CORRECTIONNEL ET LA MISE EN LIBERTÉ SOUS CONDITION</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-7.html#h-8"><span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LA PREUVE AU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-9"><span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR L’ASSURANCE-EMPLOI</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-10"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-8.html#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

