<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des phares patrimoniaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJET ET APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">DÉSIGNATION DES PHARES PATRIMONIAUX</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText1">PROTECTION DES PHARES PATRIMONIAUX</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText1">ENTRETIEN DES PHARES PATRIMONIAUX</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES À LA LOI SUR L’AGENCE PARCS CANADA</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

