<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Antiterroriste, Loi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">CODE CRIMINEL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23.1 - </span><a href="page-5.html#h-3"><span class="HTitleText2">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23.1 - </span><a href="page-5.html#h-4"><span class="HTitleText3">Loi sur l’identification des criminels</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-5.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LOI SUR LES SECRETS OFFICIELS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-7.html#h-6"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-7.html#h-7"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-7.html#h-8"><span class="HTitleText3">Loi sur l’identification des criminels</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-7.html#h-9"><span class="HTitleText3">Loi sur les brevets</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-7.html#h-10"><span class="HTitleText3">Loi sur les forces étrangères présentes au Canada</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-7.html#h-11"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="page-7.html#h-12"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI SUR LA PREUVE AU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-8.html#h-13"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-8.html#h-14"><span class="HTitleText3">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-8.html#h-15"><span class="HTitleText3">Loi sur l’immigration</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-8.html#h-16"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">LOI SUR LE RECYCLAGE DES PRODUITS DE LA CRIMINALITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="page-11.html#h-17"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="page-11.html#h-18"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-11.html#h-19"><span class="HTitleText3">Loi sur la Société canadienne des postes</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-11.html#h-20"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-11.html#h-21"><span class="HTitleText3">Loi sur la protection des renseignements personnels et les documents électroniques</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-11.html#h-22"><span class="HTitleText3">Loi sur l’administration des biens saisis</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-11.html#h-23"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">MODIFICATIONS À D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-11.html#h-24"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-12.html#h-25"><span class="HTitleText2">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-12.html#h-26"><span class="HTitleText2">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-12.html#h-27"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-12.html#h-28"><span class="HTitleText2">Loi sur la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-12.html#h-29"><span class="HTitleText2">Loi sur les armes à feu</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-12.html#h-30"><span class="HTitleText2">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-14.html#h-31"><span class="HTitleText2">Loi sur la protection des renseignements personnels et les documents électroniques</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-14.html#h-32"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-14.html#h-33"><span class="HTitleText2">Loi sur l’administration des biens saisis</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-15.html#h-34"><span class="HTitleText2">Loi sur les Nations Unies</span></a>
</li></ul>
</li><li><span class='sectionRange'>113 - </span><a href="page-15.html#h-35"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">ENREGISTREMENT DES ORGANISMES DE BIENFAISANCE (RENSEIGNEMENTS DE SÉCURITÉ)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>114 - </span><a href="page-16.html#h-36"><span class="HTitleText2">Modification de la Loi de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="page-16.html#h-37"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION, DE RÉVISION ET D’ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="page-16.html#h-38"><span class="HTitleText2">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="page-16.html#h-39"><span class="HTitleText3">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-16.html#h-40"><span class="HTitleText3">Projet de loi S-23</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-16.html#h-41"><span class="HTitleText3">Projet de loi C-11</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-18.html#h-42"><span class="HTitleText3">Projet de loi C-15B</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-18.html#h-43"><span class="HTitleText3">Projet de loi C-24</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-20.html#h-44"><span class="HTitleText3">Projet de loi C-30</span></a>
</li></ul>
</li><li><span class='sectionRange'>145 - </span><a href="page-21.html#h-45"><span class="HTitleText2">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-21.html#h-46"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-22.html#h-47"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-23.html#h-48"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

