<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">AIDE AU PLACEMENT</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-4"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">SERVICES DE RÉADAPTATION, ASSISTANCE PROFESSIONNELLE ET AVANTAGES FINANCIERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Services de réadaptation et assistance professionnelle</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Allocation pour perte de revenus</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-8"><span class="HTitleText2">Prestation de retraite supplémentaire</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Allocation de soutien du revenu</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-10"><span class="HTitleText2">Allocation pour déficience permanente</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-11"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-4.html#h-12"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">INVALIDITÉ, DÉCÈS ET CAPTIVITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-14"><span class="HTitleText2">Indemnité d’invalidité</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-15"><span class="HTitleText2">Indemnité de décès</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-6.html#h-16"><span class="HTitleText2">Allocation vestimentaire</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-17"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Indemnité de captivité</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="page-6.html#h-19"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">GÉNÉRALITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="page-6.html#h-20"><span class="HTitleText2">Soins de santé</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-6.html#h-21"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-7.html#h-22"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-23"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-24"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-7.html#h-25"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-7.html#h-26"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-8.html#h-27"><span class="HTitleText2">Trop-perçu</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-8.html#h-28"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-8.html#h-29"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="page-8.html#h-30"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CONNEXES, DISPOSITION DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="page-8.html#h-31"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-9.html#h-32"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="page-9.html#h-33"><span class="HTitleText3">Loi sur l’aide en matière d’éducation aux enfants des anciens combattants décédés</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-9.html#h-34"><span class="HTitleText3">Loi sur le ministère des Anciens Combattants</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-9.html#h-35"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-9.html#h-36"><span class="HTitleText3">Loi d’indemnisation des militaires ayant subi des blessures</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-9.html#h-37"><span class="HTitleText3">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-9.html#h-38"><span class="HTitleText3">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-10.html#h-39"><span class="HTitleText3">Loi sur le Tribunal des anciens combattants (révision et appel)</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-10.html#h-40"><span class="HTitleText3">Loi sur l’emploi dans la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="page-10.html#h-41"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-10.html#h-42"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-11.html#h-43"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - ALLOCATION DE SOUTIEN DU REVENU</span></a>
</li>
<li><a href="page-12.html#h-44"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - ALLOCATIONS ET INDEMNITÉ</span></a>
</li>
<li><a href="page-13.html#h-45"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - INDEMNITÉ D’INVALIDITÉ</span></a>
</li></ul>
</li></ul>

</nav>

