<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’équité à la pompe</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR L’INSPECTION DE L’ÉLECTRICITÉ ET DU GAZ</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-3"><span class="HTitleText1">LOI SUR LES POIDS ET MESURES</span></a>
</li>
<li><span class='sectionRange'>29.1 - </span><a href="page-5.html#h-4"><span class="HTitleText1">RAPPORT</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-5.html#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

