<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant certains textes législatifs et abrogeant la Loi sur le soutien des prix des produits de la pêche</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">MODIFICATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence de promotion économique du Canada atlantique</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société de développement de l’industrie cinématographique canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de retraite des lieutenants-gouverneurs</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la capitale nationale</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le cinéma</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sûreté et la réglementation nucléaires</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les régimes de retraite particuliers</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’autonomie gouvernementale des premières nations du Yukon</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-2.html#h-16"><span class="HTitleText1">ABROGATION DE LA LOI SUR LE SOUTIEN DES PRIX DES PRODUITS DE LA PÊCHE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="page-2.html#h-17"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-18"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-3.html#h-19"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-4.html#h-20"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

