<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2021 sur les opérations au port de Montréal</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Opérations au port de Montréal</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Prorogation de la convention collective</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Médiateur-arbitre</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-6"><span class="HTitleText1">Nouvelle convention collective</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-7"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-8"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

