<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes, la Loi de l’impôt sur le revenu et une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LE RECYCLAGE DES PRODUITS DE LA CRIMINALITÉ ET LE FINANCEMENT DES ACTIVITÉS TERRORISTES</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-3"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence des services frontaliers du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

