<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi instituant une journée nationale de commémoration de la bataille de la crête de Vimy</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">JOUR DE LA BATAILLE DE VIMY</span></a>
</li></ul>
</li></ul>

</nav>

