<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les transports au Canada (transport ferroviaire)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES TRANSPORTS AU CANADA</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI MODIFIANT LA LOI SUR LES TRANSPORTS AU CANADA ET LA LOI SUR LA SÉCURITÉ FERROVIAIRE ET D’AUTRES LOIS EN CONSÉQUENCE</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-3"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li></ul>
</li></ul>

</nav>

