<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la participation publique au capital d’Air Canada et comportant d’autres mesures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Loi sur la participation publique au capital d’Air Canada</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Modification des statuts</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

