<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le cadre visant à réduire la récidive</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Cadre fédéral visant à réduire la récidive</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Rapports au Parlement</span></a>
</li></ul>
</li></ul>

</nav>

