<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi canadienne sur les sociétés par actions, la Loi canadienne sur les coopératives, la Loi canadienne sur les organisations à but non lucratif et la Loi sur la concurrence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Gouvernance de personnes morales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les coopératives</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les organisations à but non lucratif</cite></span></a>
</li>
<li><span class='sectionRange'>107.1 - </span><a href="#h-5"><span class="HTitleText2">Examen par un comité</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-6"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Application de la <cite class="XRefExternalAct">Loi sur la concurrence</cite> à d’autres entités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

