<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le soutien de la croissance de l’économie et de l’emploi au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET DE RÈGLEMENTS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-15.html#h-4"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-18.html#h-5"><span class="HTitleText2">Règlement sur l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-18.html#h-6"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-18.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LOI DE 2006 SUR LES DROITS D’EXPORTATION DE PRODUITS DE BOIS D’OEUVRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="page-18.html#h-8"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-18.html#h-9"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="page-18.html#h-10"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">SIMPLIFICATION DU TARIF DES DOUANES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="page-18.html#h-11"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-23.html#h-12"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>146 - </span><a href="page-23.html#h-13"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">FACILITATION DES IMPORTATIONS DE FAIBLE VALEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="page-23.html#h-14"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-23.html#h-15"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>148 - </span><a href="page-23.html#h-16"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI CANADIENNE SUR L’ÉPARGNE-ÉTUDES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>148 - </span><a href="page-23.html#h-17"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-23.html#h-18"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="page-23.html#h-19"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">ALLOCATIONS SPÉCIALES POUR ENFANTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="page-23.html#h-20"><span class="HTitleText2">Loi sur les allocations spéciales pour enfants</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-23.html#h-21"><span class="HTitleText2">Règlement sur les allocations spéciales pour enfants</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="page-23.html#h-22"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">AIDE FINANCIÈRE OFFERTE AUX ÉTUDIANTS PAR LE GOUVERNEMENT FÉDÉRAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="page-23.html#h-23"><span class="HTitleText2">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-23.html#h-24"><span class="HTitleText2">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-24.html#h-25"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="page-24.html#h-26"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">LOI SUR L’ASSURANCE-EMPLOI</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-24.html#h-27"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">FONDS SUR LA TAXE SUR L’ESSENCE — FINANCEMENT DES INFRASTRUCTURES MUNICIPALES</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-24.html#h-28"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">LOI SUR LE BUREAU DE TRANSITION VERS UN RÉGIME CANADIEN DE RÉGLEMENTATION DES VALEURS MOBILIÈRES</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-24.html#h-29"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">LOI SUR LE PROGRAMME DE PROTECTION DES SALARIÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="page-24.html#h-30"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-24.html#h-31"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-24.html#h-32"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES À L’EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="page-24.html#h-33"><span class="HTitleText2">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-24.html#h-34"><span class="HTitleText2">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-24.html#h-35"><span class="HTitleText2">Loi sur les conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-24.html#h-36"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="page-24.html#h-37"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">LOI SUR LES JUGES</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-24.html#h-38"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">LOI AUTORISANT L’ALIÉNATION DE NORDION ET DE THERATRONICS</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-24.html#h-39"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">RÉGIME DE PENSIONS DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172 - </span><a href="page-24.html#h-40"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-25.html#h-41"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="page-25.html#h-42"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">LOI SUR L’EMPLOI ET LA CROISSANCE ÉCONOMIQUE</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-25.html#h-43"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">LOI SUR LE MINISTÈRE DES ANCIENS COMBATTANTS</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-25.html#h-44"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">LOI ÉLECTORALE DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>181 - </span><a href="page-25.html#h-45"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-25.html#h-46"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="page-25.html#h-47"><span class="HLabel1">PARTIE 19</span> - <span class="HTitleText1">RÉGIMES DE RETRAITE PARTICULIERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="page-25.html#h-48"><span class="HTitleText2">Loi sur les régimes de retraite particuliers</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-25.html#h-49"><span class="HTitleText2">Loi modifiant certaines lois en matière de pensions et édictant la Loi sur les régimes de retraite particuliers et la Loi sur le partage des prestations de retraite</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-25.html#h-50"><span class="HLabel1">PARTIE 20</span> - <span class="HTitleText1">LOI SUR LA SÉCURITÉ AUTOMOBILE</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-25.html#h-51"><span class="HLabel1">PARTIE 21</span> - <span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-26.html#h-52"><span class="HLabel1">PARTIE 22</span> - <span class="HTitleText1">LOI SUR LE MINISTÈRE DES RESSOURCES HUMAINES ET DU DÉVELOPPEMENT DES COMPÉTENCES</span></a>
</li>
<li><a href="page-27.html#h-53"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - LISTE DES PAYS ET TRAITEMENTS TARIFAIRES QUI LEUR SONT ACCORDÉS</span></a>
</li>
<li><a href="page-28.html#h-54"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-29.html#h-55"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

