<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur l’assurance-emploi (prestations régulières supplémentaires), la Loi sur les prestations canadiennes de relance économique (restriction de l’admissibilité) et une autre loi en réponse à la COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les prestations canadiennes de relance économique</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

