<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence de la santé publique du Canada,</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">AGENCE DE LA SANTÉ PUBLIQUE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">ADMINISTRATEUR EN CHEF DE LA SANTÉ PUBLIQUE</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText1">MODIFICATIONS CONNEXE ET CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de la Santé</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la quarantaine</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

