<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">MODIFICATION DES ANNEXES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">SENSIBILISATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">CODE DE CONDUITE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">ACTES RÉPRÉHENSIBLES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText1">DIVULGATION</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-8"><span class="HTitleText1">PROTECTION DES DIVULGATEURS</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-9"><span class="HTitleText1">ATTRIBUTIONS DU COMMISSAIRE</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-10"><span class="HTitleText1">ENQUÊTES</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-11"><span class="HTitleText1">RAPPORTS</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-12"><span class="HTitleText1">COMMISSARIAT À L’INTÉGRITÉ DU SECTEUR PUBLIC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Commissaire à l’intégrité du secteur public</span></a>
</li>
<li><span class='sectionRange'>39.3 - </span><a href="page-5.html#h-14"><span class="HTitleText2">Personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="page-5.html#h-15"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-16"><span class="HTitleText1">CARACTÈRE CONFIDENTIEL</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-17"><span class="HTitleText1">IMMUNITÉ</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-18"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-19"><span class="HTitleText1">ORGANISMES EXCLUS</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-20"><span class="HTitleText1">EXAMEN QUINQUENNAL</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="page-5.html#h-21"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-22"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-25"><span class="HTitleText2">Loi sur la protection des renseignements personnels et les documents électroniques</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-6.html#h-26"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="page-6.html#h-27"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-6.html#h-28"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-7.html#h-29"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-8.html#h-30"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-9.html#h-31"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

