<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur l’accessibilité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Principes</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Organisation canadienne d’élaboration de normes d’accessibilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Attributions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Ministre</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-16"><span class="HTitleText2">Président-directeur général</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-17"><span class="HTitleText2">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-19"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-20"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Commissaire à l’accessibilité</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-21"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Obligations des entités réglementées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-22"><span class="HTitleText2">Entités réglementées qui exploitent une entreprise de radiodiffusion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-23"><span class="HTitleText3">Plans sur l’accessibilité — Exigences prévues au titre de la <cite class="XRefExternalAct">Loi sur la radiodiffusion</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-24"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-25"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-26"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-27"><span class="HTitleText3">Exemptions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-28"><span class="HTitleText3">Plans sur l’accessibilité — Règlements pris sous le régime de la présente loi</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-29"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-30"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-31"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-32"><span class="HTitleText2">Entités réglementées qui sont des entreprises canadiennes ou des fournisseurs de services de télécommunication</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-33"><span class="HTitleText3">Plans sur l’accessibilité — Exigences prévues au titre de la <cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-34"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-35"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-36"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-37"><span class="HTitleText3">Exemptions</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-38"><span class="HTitleText3">Plans sur l’accessibilité — Règlements pris sous le régime de la présente loi</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-39"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-40"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-41"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-42"><span class="HTitleText2">Entités réglementées dans le réseau des transports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-43"><span class="HTitleText3">Plans sur l’accessibilité — Règlements pris sous le régime de la <cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-44"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-45"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-46"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-47"><span class="HTitleText3">Exemptions</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-48"><span class="HTitleText3">Plans sur l’accessibilité — Règlements pris sous le régime de la présente loi</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-49"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-50"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-51"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="#h-52"><span class="HTitleText2">Autres entités réglementées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-53"><span class="HTitleText3">Plans sur l’accessibilité — Règlements pris sous le régime de la présente loi</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-54"><span class="HTitleText3">Rétroaction</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-55"><span class="HTitleText3">Rapports d’étape</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-56"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-57"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-58"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-59"><span class="HTitleText2">Ordre de communication</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-60"><span class="HTitleText2">Ordre de conformité</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-61"><span class="HTitleText2">Sanctions administratives pécuniaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="#h-62"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Recours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94 - </span><a href="#h-63"><span class="HTitleText2">Dépôt des plaintes</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-64"><span class="HTitleText2">Examen des plaintes</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-65"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-66"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Dirigeant principal de l’accessibilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-67"><span class="HTitleText2">Nomination</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-68"><span class="HTitleText2">Rémunération et frais</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-69"><span class="HTitleText2">Attributions</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-70"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-71"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-72"><span class="HTitleText2">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-73"><span class="HTitleText2">Semaine nationale de l’accessibilité</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-74"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Entités parlementaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-75"><span class="HTitleText2">Définition et application</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-76"><span class="HTitleText2">Pouvoirs, privilèges et immunités parlementaires</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-77"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-78"><span class="HTitleText2">Avis aux présidents</span></a>
</li></ul>
</li><li><span class='sectionRange'>147 - </span><a href="#h-79"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-80"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil de la radiodiffusion et des télécommunications canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-81"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-82"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-83"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la radiodiffusion</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-84"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-85"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-86"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail dans le secteur public fédéral</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-87"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="#h-88"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Modifications corrélatives et dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="#h-89"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="#h-90"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-91"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-92"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-93"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-94"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

