<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à aider les familles dans le besoin</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CODE CANADIEN DU TRAVAIL</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-3"><span class="HTitleText1">LOI SUR L’ASSURANCE-EMPLOI</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-4"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-5.html#h-5"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-5.html#h-6"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-5.html#h-7"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-5.html#h-8"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-6.html#h-9"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

