<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la radiation de condamnations constituant des injustices historiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Attributions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Radiation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Effets</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Ordonnance</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Destruction et suppression</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Communication de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-10"><span class="HTitleText1">Modifications à l’annexe</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-11"><span class="HTitleText1">Critères</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-12"><span class="HTitleText1">Infractions d’ordre sexuel entre des personnes du même sexe</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-13"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li></ul>
</li><li><a href="page-3.html#h-16"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

