<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le cadre fédéral de prévention du suicide</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">CADRE FÉDÉRAL DE PRÉVENTION DU SUICIDE</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">CONSULTATIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">RAPPORT</span></a>
</li></ul>
</li></ul>

</nav>

