<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi de 1994 sur la convention concernant les oiseaux migrateurs et la Loi canadienne sur la protection de l’environnement (1999)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI DE 1994 SUR LA CONVENTION CONCERNANT LES OISEAUX MIGRATEURS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-4.html#h-2"><span class="HTitleText1">LOI CANADIENNE SUR LA PROTECTION DE L’ENVIRONNEMENT (1999)</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-7.html#h-3"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-8.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

