<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 1 sur le plan d’action économique de 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI DE L’IMPÔT SUR LE REVENU</cite> ET DE TEXTES CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur le Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la rémunération assurable et la perception des cotisations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-8"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LA TAXE D’ACCISE</cite> (MESURES RELATIVES À LA TPS/TVH)</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-9"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI DE 2001 SUR L’ACCISE</cite>, DE LA <cite class="XRefExternalAct">LOI SUR LA TAXE D’ACCISE</cite> (SAUF LES DISPOSITIONS CONCERNANT LA TPS/TVH) ET DE LA <cite class="XRefExternalAct">LOI SUR LE DROIT POUR LA SÉCURITÉ DES PASSAGERS DU TRANSPORT AÉRIEN</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-11"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-12"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit pour la sécurité des passagers du transport aérien</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-15"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">TARIF DES DOUANES</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-16"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-17"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-18"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI DE MISE EN OEUVRE DE L’ACCORD CANADA–ÉTATS-UNIS POUR UN MEILLEUR ÉCHANGE DE RENSEIGNEMENTS FISCAUX</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-19"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-20"><span class="HTitleText2">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="#h-21"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">DIVERSES MESURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-22"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Paiements  —  Anciens Combattants</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-23"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Société d’assurance-dépôts du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-26"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Initiative du Conseil de coopération en matière de réglementation concernant les produits chimiques dans les lieux de travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-27"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur les produits dangereux</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-28"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-29"><span class="HTitleText3">Modification du <cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-30"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-31"><span class="HTitleText3">Modification de la<cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-32"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-33"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-34"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>163 - </span><a href="#h-35"><span class="HLabel2">Section 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-36"><span class="HLabel2">Section 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-37"><span class="HLabel2">Section 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations de retraite des parlementaires</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-38"><span class="HTitleText3">Modifications de la loi</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-39"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-40"><span class="HLabel2">Section 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-41"><span class="HTitleText3">Modifications de la loi</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-42"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="#h-43"><span class="HLabel2">Section 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-44"><span class="HLabel2">Section 9</span> - <span class="HTitleText2">Agence de promotion économique du Canada atlantique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence de promotion économique du Canada atlantique</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-46"><span class="HTitleText3">Dissolution du conseil</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-47"><span class="HLabel2">Section 10</span> - <span class="HTitleText2">Société d’expansion du Cap-Breton</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-48"><span class="HTitleText3">Dissolution</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-49"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence de promotion économique du Canada atlantique</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-50"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="#h-54"><span class="HTitleText3">Abrogation</span></a>
</li></ul>
</li><li><span class='sectionRange'>193 - </span><a href="#h-55"><span class="HLabel2">Section 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les musées</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-56"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-57"><span class="HTitleText3">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-58"><span class="HTitleText4">Définitions</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-59"><span class="HTitleText4">Ouvrages de référence en ligne</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-60"><span class="HTitleText4">Musée virtuel du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-61"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-62"><span class="HLabel2">Section 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi autorisant l’aliénation de Nordion et de Theratronics</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-63"><span class="HLabel2">Section 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-64"><span class="HLabel2">Section 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-65"><span class="HLabel2">Section 15</span> - <span class="HTitleText2">Coopération en matière de réglementation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>212 - </span><a href="#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sécurité automobile</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-67"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 1992 sur le transport des marchandises dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-69"><span class="HTitleText3"><cite class="XRefExternalAct">Loi assurant aux Canadiens la sécurité des véhicules importés du Mexique</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-70"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la salubrité des aliments au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-71"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-72"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-73"><span class="HLabel2">Section 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-74"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="#h-75"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>242 - </span><a href="#h-76"><span class="HLabel2">Section 17</span> - <span class="HTitleText2">Prestations de maladie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>242 - </span><a href="#h-77"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-79"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-80"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="#h-81"><span class="HLabel2">Section 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence canadienne d’inspection des aliments</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>252 - </span><a href="#h-82"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-83"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="#h-84"><span class="HLabel2">Section 19</span> - <span class="HTitleText2">Recyclage des produits de la criminalité et financement des activités terroristes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>254 - </span><a href="#h-85"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-86"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’emploi et la croissance économique</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-87"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="#h-88"><span class="HLabel2">Section 20</span> - <span class="HTitleText2">Immigration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="#h-89"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-90"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-91"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>308 - </span><a href="#h-92"><span class="HLabel2">Section 21</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Relations de travail dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-93"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-94"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="#h-95"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>311 - </span><a href="#h-96"><span class="HLabel2">Section 22</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2006 sur les droits d’exportation de produits de bois d’oeuvre</cite></span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-97"><span class="HLabel2">Section 23</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi d’exécution du budget de 2009</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-98"><span class="HLabel2">Section 24</span> - <span class="HTitleText2">Titrisation de prêts hypothécaires assurés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>314 - </span><a href="#h-99"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de l’assurance hypothécaire résidentielle</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-100"><span class="HTitleText3"><cite class="XRefExternalAct">Loi nationale sur l’habitation</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="#h-101"><span class="HLabel2">Section 25</span> - <span class="HTitleText2">Modifications liées aux traités internationaux sur les marques de commerce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>317 - </span><a href="#h-102"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="#h-103"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>364 - </span><a href="#h-104"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les marques olympiques et paralympiques</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>366 - </span><a href="#h-105"><span class="HTitleText3">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="#h-106"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-107"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>369 - </span><a href="#h-108"><span class="HLabel2">Section 26</span> - <span class="HTitleText2">Mesure de réduction des postes pourvus par le gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="#h-109"><span class="HLabel2">Section 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité de la vieillesse</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="#h-110"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>374 - </span><a href="#h-111"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="#h-112"><span class="HLabel2">Section 28</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi visant le nouveau pont pour le Saint-Laurent</cite></span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="#h-113"><span class="HLabel2">Section 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Service canadien d’appui aux tribunaux administratifs</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="#h-114"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-115"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="#h-116"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="#h-117"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>389 - </span><a href="#h-118"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-119"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’exportation et l’importation de biens culturels</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-120"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-121"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-122"><span class="HTitleText4"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-123"><span class="HTitleText4"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="#h-124"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>428 - </span><a href="#h-125"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les mesures spéciales d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="#h-126"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>447 - </span><a href="#h-127"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal de la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-128"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les produits agricoles au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-129"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="#h-130"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>459 - </span><a href="#h-131"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-132"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le statut de l’artiste</cite></span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="#h-133"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’équité en matière d’emploi</cite></span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="#h-134"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-135"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-136"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li>
<li><span class='sectionRange'>469 - </span><a href="#h-137"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal des revendications particulières</cite></span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="#h-138"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>480 - </span><a href="#h-139"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="#h-140"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="#h-141"><span class="HLabel2">Section 30</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les prêts aux apprentis</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="#h-142"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="#h-143"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>484 - </span><a href="#h-144"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>485 - </span><a href="#h-145"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>486 - </span><a href="#h-146"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-147"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-148"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-149"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-150"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-151"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="#h-152"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>

