<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel et la Loi sur le ministère de la Justice et apportant des modifications corrélatives à une autre loi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Code criminel</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le ministère de la Justice</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-3"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-4"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le casier judiciaire</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-6"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-7"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

