<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la révision du système financier</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES BANQUES</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-9.html#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES ASSOCIATIONS COOPÉRATIVES DE CRÉDIT</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-10.html#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES SOCIÉTÉS D’ASSURANCES</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-14.html#h-5"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES SOCIÉTÉS DE FIDUCIE ET DE PRÊT</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-15.html#h-6"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">MODIFICATION D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="page-15.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-16.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-18.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les paiements</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-18.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-19.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Bureau du surintendant des institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-19.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="page-19.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence de la consommation en matière financière du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="page-20.html#h-14"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="page-20.html#h-15"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-21.html#h-16"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

