<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence de développement économique du Canada pour les régions du Québec</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">MINISTRE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">AGENCE DE DÉVELOPPEMENT ÉCONOMIQUE DU CANADA POUR LES RÉGIONS DU QUÉBEC</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">MISSION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">POUVOIR RÉGLEMENTAIRE</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText1">RAPPORTS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Loi sur le vérificateur général</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Loi sur le ministère de l’Industrie</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-14"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Loi sur les traitements</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

