<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel (produits de la criminalité) et la Loi réglementant certaines drogues et autres substances et modifiant une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI RÉGLEMENTANT CERTAINES DROGUES ET AUTRES SUBSTANCES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Loi sur l’administration des biens saisis</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

