<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur le Parlement du Canada, la Loi sur les allocations de retraite des parlementaires et la Loi sur les traitements</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LE PARLEMENT DU CANADA</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI SUR LES ALLOCATIONS DE RETRAITE DES PARLEMENTAIRES</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-5.html#h-3"><span class="HTitleText1">LOI SUR LES TRAITEMENTS</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-5.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

