<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Exportation et l’importation des diamants bruts, Loi sur l’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">ATTRIBUTIONS DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText1">EXPORTATION DE DIAMANTS BRUTS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText1">DIAMANTS BRUTS IMPORTÉS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText1">DIAMANTS BRUTS EN TRANSIT</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText1">INSPECTIONS</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">ENQUÊTES</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText1">MESURES CONSÉCUTIVES À LA SAISIE</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-10"><span class="HTitleText1">CONFISCATION</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HTitleText1">RESPONSABILITÉ POUR FRAIS</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-12"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-13"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-14"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-15"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - PARTICIPANTS</span></a>
</li></ul>
</li></ul>

</nav>

