<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel (infractions relatives aux moyens de transport) et apportant des modifications corrélatives à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Infractions relatives au transport — drogue</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Modification du <cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-3.html#h-3"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-3.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Infractions relatives aux moyens de transport — alcool et drogue</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-3.html#h-6"><span class="HTitleText2">Modification du <cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="page-5.html#h-7"><span class="HTitleText2">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-8"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-9"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-6.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le casier judiciaire</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-6.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-7.html#h-16"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-7.html#h-17"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-7.html#h-18"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

