<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les licences d’exportation et d’importation et le Code criminel (modifications permettant l’adhésion au Traité sur le commerce des armes et autres modifications)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-3"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-4"><span class="HTitleText1">Modification au <cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-5"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

