<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi favorisant l’activité physique et le sport</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">POLITIQUES</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">OBJETS ET MESURES CONNEXES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">ACCORDS ET ARRANGEMENTS AUTORISÉS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText1">CENTRE DE RÈGLEMENT DES DIFFÉRENDS SPORTIFS DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Mission et attributions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-11"><span class="HTitleText2">Directeur général</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-12"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-13"><span class="HTitleText2">Vérification</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Arbitres et médiateurs</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText2">Plan d’entreprise et rapport annuel</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText2">Dissolution</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-18"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-20"><span class="HTitleText2">Loi sur le ministère du Patrimoine canadien</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-21"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-22"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-23"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

