<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la sécurité des rues et des communautés</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">LOI SUR LA JUSTICE POUR LES VICTIMES D’ACTES DE TERRORISME</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Modification de la Loi sur l’immunité des États</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">DÉTERMINATION DE LA PEINE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-7"><span class="HTitleText2">Loi réglementant certaines drogues et autres substances</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-8"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-5.html#h-9"><span class="HTitleText3">Loi modifiant le Code criminel (armes à feu) et la Loi sur les armes à feu</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-10"><span class="HTitleText3">Loi sur la défense nationale</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-6.html#h-11"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-6.html#h-12"><span class="HTitleText3">Loi sur le casier judiciaire</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-13"><span class="HTitleText3">Loi sur la défense nationale</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-6.html#h-14"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-6.html#h-15"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MESURES SUIVANT LA DÉTERMINATION DE LA PEINE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-6.html#h-16"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-6.html#h-17"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-12.html#h-18"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-12.html#h-19"><span class="HTitleText2">Loi sur le casier judiciaire</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-14.html#h-20"><span class="HTitleText2">Loi sur le transfèrement international des délinquants</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-14.html#h-21"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>137 - </span><a href="page-14.html#h-22"><span class="HTitleText3">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-14.html#h-23"><span class="HTitleText3">Loi sur les contraventions</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-15.html#h-24"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-15.html#h-25"><span class="HTitleText3">Loi sur l’identification par les empreintes génétiques</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-15.html#h-26"><span class="HTitleText3">Loi sur l’immigration et la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-15.html#h-27"><span class="HTitleText3">Loi limitant l’admissibilité à la réhabilitation pour des crimes graves</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-15.html#h-28"><span class="HTitleText3">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-16.html#h-29"><span class="HTitleText3">Loi sur le système de justice pénale pour les adolescents</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="page-16.html#h-30"><span class="HTitleText2">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-16.html#h-31"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-17.html#h-32"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>167 - </span><a href="page-17.html#h-33"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">SYSTÈME DE JUSTICE PÉNALE POUR LES ADOLESCENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-17.html#h-34"><span class="HTitleText2">Loi sur le système de justice pénale pour les adolescents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-17.html#h-35"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-18.html#h-36"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="page-19.html#h-37"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-19.html#h-38"><span class="HTitleText3">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-19.html#h-39"><span class="HTitleText3">Loi sur les prisons et les maisons de correction</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="page-19.html#h-40"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="page-19.html#h-41"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-19.html#h-42"><span class="HTitleText3">Loi sur l’identification par les empreintes génétiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>204 - </span><a href="page-19.html#h-43"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="page-19.html#h-44"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>205 - </span><a href="page-19.html#h-45"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-20.html#h-46"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-21.html#h-47"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

