<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur la concurrence et la Loi sur le Tribunal de la concurrence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LA CONCURRENCE</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-2"><span class="HTitleText1">LOI SUR LE TRIBUNAL DE LA CONCURRENCE</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-5.html#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

