<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Mise en oeuvre de conventions fiscales, Loi de 2002 pour la</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">ACCORD FISCAL CANADA–KOWEÏT</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–MONGOLIE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–ÉMIRATS ARABES UNIS</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–MOLDOVA</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">CONVENTIONS FISCALES CANADA–NORVÈGE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2002 sur la convention fiscale Canada–Norvège</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1967 sur la Convention entre le Canada et la Norvège en matière d’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–BELGIQUE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre des conventions conclues entre le Canada et la France, entre le Canada et la Belgique et entre le Canada et Israël, tendant à éviter les doubles impositions en matière d’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-11"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–ITALIE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre des conventions conclues entre le Canada et l’Espagne, le Canada et la République d’Autriche, le Canada et l’Italie, le Canada et la République de Corée, le Canada et la République Socialiste de Roumanie et le Canada et la République d’Indonésie et des accords conclus entre le Canada et la Malaisie, le Canada et la Jamaïque et le Canada et la Barbade ainsi que d’une convention conclue entre le Canada et le Royaume-Uni de Grande-Bretagne et d’Irlande du Nord, tendant à éviter les doubles impositions en matière d’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-13"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–VIÊTNAM</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1998 pour la mise en oeuvre de conventions fiscales</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-15"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–PORTUGAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1999 pour la mise en oeuvre de conventions fiscales</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-17"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA–SÉNÉGAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 pour la mise en oeuvre de conventions fiscales</cite></span></a>
</li></ul>
</li><li><a href="#h-19"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-20"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="#h-24"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li>
<li><a href="#h-25"><span class="scheduleLabel">ANNEXE 7</span> </a>
</li></ul>
</li></ul>

</nav>

