<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi antiterroriste (2015)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA COMMUNICATION D’INFORMATION AYANT TRAIT À LA SÉCURITÉ DU CANADA</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Pêches et des Océans</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de mise en oeuvre de la Convention sur les armes chimiques</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-13"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA SÛRETÉ DES DÉPLACEMENTS AÉRIENS</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-3.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-3.html#h-19"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-3.html#h-20"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-5.html#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les prisons et les maisons de correction</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-5.html#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-6.html#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-6.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le système de justice pénale pour les adolescents</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="page-7.html#h-29"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE SERVICE CANADIEN DU RENSEIGNEMENT DE SÉCURITÉ</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-8.html#h-30"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-8.html#h-31"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-9.html#h-32"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-9.html#h-33"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-10.html#h-34"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

