<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi constituant un nouveau musée canadien de l’immigration au Quai 21</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR LES MUSÉES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Loi sur le contrôle des dépenses</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-1.html#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

