<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en oeuvre de l’Accord économique et commercial global entre le Canada et l’Union européenne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’Accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approbation et représentation au sein du Comité mixte de l’AÉCG</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Tribunaux, groupes spéciaux d’arbitrage et groupes d’experts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-1.html#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les aliments et drogues</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-12.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-13.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-13.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-13.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-14.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-17.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits antiparasitaires</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-17.html#h-24"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="page-18.html#h-25"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="page-18.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les corporations canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-18.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’énergie nucléaire</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-18.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-18.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-18.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la production de défense</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-19.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-19.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les inventions des fonctionnaires</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-19.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques olympiques et paralympiques</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-19.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la croissance économique et la prospérité — Canada-Corée</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-19.html#h-35"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-19.html#h-36"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-19.html#h-37"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-20.html#h-38"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-21.html#h-39"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-22.html#h-40"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-23.html#h-41"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-24.html#h-42"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-25.html#h-43"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-26.html#h-44"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

