<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi canadienne sur les organisations à but n<?Pub Caret?>on lucratif</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">DÉFINITIONS ET APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Désignation du ministre</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="page-2.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">CONSTITUTION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-8"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">CAPACITÉ ET POUVOIRS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-9"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">SIÈGE ET LIVRES</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-4.html#h-10"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">FINANCEMENT</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-11"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">TITRES DE CRÉANCE, CERTIFICATS, REGISTRES ET TRANSFERT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-13"><span class="HTitleText2">Certificats de titres de créance</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-14"><span class="HTitleText2">Registres</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-15"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-16"><span class="HTitleText2">Livraison des titres de créance</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-17"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-8.html#h-18"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">ACTES DE FIDUCIE</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-9.html#h-19"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">SÉQUESTRES ET SÉQUESTRES-GÉRANTS</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-10.html#h-20"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">ADMINISTRATEURS ET DIRIGEANTS</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-13.html#h-21"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">RÈGLEMENTS ADMINISTRATIFS ET MEMBRES</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-15.html#h-22"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">PRÉSENTATION DES RENSEIGNEMENTS D’ORDRE FINANCIER</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-15.html#h-23"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">EXPERT-COMPTABLE</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-17.html#h-24"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">MODIFICATION DE STRUCTURE</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="page-19.html#h-25"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">LIQUIDATION ET DISSOLUTION</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="page-23.html#h-26"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">ENQUÊTE</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-23.html#h-27"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">RECOURS, INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-25.html#h-28"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">DOCUMENTS SOUS FORME ÉLECTRONIQUE OU AUTRE</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="page-25.html#h-29"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>272 - </span><a href="page-25.html#h-30"><span class="HTitleText2">Avis, certificats et autres documents</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-26.html#h-31"><span class="HTitleText2">Directeur</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-27.html#h-32"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>294 - </span><a href="page-27.html#h-33"><span class="HLabel1">PARTIE 19</span> - <span class="HTitleText1">PERSONNES MORALES SANS CAPITAL-ACTIONS CONSTITUÉES PAR UNE LOI SPÉCIALE</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-28.html#h-34"><span class="HLabel1">PARTIE 20</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES, DISPOSITIONS DE COORDINATION, ABROGATIONS ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="page-28.html#h-35"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-28.html#h-36"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="page-28.html#h-37"><span class="HTitleText3">Loi constituant en corporation « St. Mary’s River Bridge Company »</span></a>
</li>
<li><span class='sectionRange'>303 - </span><a href="page-28.html#h-38"><span class="HTitleText3">Loi sur la Fondation Jules et Paul-Émile Léger</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="page-28.html#h-39"><span class="HTitleText3">Acte pour incorporer la Compagnie du Havre de Pickering, (à responsabilité limitée) et pour l’autoriser à percevoir des péages</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="page-28.html#h-40"><span class="HTitleText3">Loi permettant la création par fusion de L’Église Wesleyenne du Canada</span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-28.html#h-41"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="page-28.html#h-42"><span class="HTitleText3">Loi d’exécution du budget de 1997</span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="page-28.html#h-43"><span class="HTitleText3">Loi d’exécution du budget de 1998</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-28.html#h-44"><span class="HTitleText3">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="page-29.html#h-45"><span class="HTitleText3">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-29.html#h-46"><span class="HTitleText3">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-29.html#h-47"><span class="HTitleText3">Loi sur l’Office de financement de l’assurance-emploi du Canada</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-29.html#h-48"><span class="HTitleText3">Loi sur la Fondation du Canada pour l’appui technologique au développement durable</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="page-29.html#h-49"><span class="HTitleText3">Loi sur l’Office d’investissement du régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="page-29.html#h-50"><span class="HTitleText3">Loi sur l’Agence canadienne d’inspection des aliments</span></a>
</li>
<li><span class='sectionRange'>319 - </span><a href="page-29.html#h-51"><span class="HTitleText3">Loi sur les Instituts de recherche en santé du Canada</span></a>
</li>
<li><span class='sectionRange'>320 - </span><a href="page-29.html#h-52"><span class="HTitleText3">Loi canadienne sur les paiements</span></a>
</li>
<li><span class='sectionRange'>321 - </span><a href="page-29.html#h-53"><span class="HTitleText3">Loi sur les coopératives de l’énergie</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="page-29.html#h-54"><span class="HTitleText3">Loi sur les Cris et les Naskapis du Québec</span></a>
</li>
<li><span class='sectionRange'>323 - </span><a href="page-29.html#h-55"><span class="HTitleText3">Loi sur l’Église évangélique luthérienne au Canada</span></a>
</li>
<li><span class='sectionRange'>324 - </span><a href="page-29.html#h-56"><span class="HTitleText3">Loi sur l’Église missionnaire évangélique, section de l’Ouest canadien</span></a>
</li>
<li><span class='sectionRange'>327 - </span><a href="page-30.html#h-57"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="page-30.html#h-58"><span class="HTitleText3">Loi sur la gestion financière et statistique des premières nations</span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="page-30.html#h-59"><span class="HTitleText3">Loi sur l’association personnalisée le Bouclier vert du Canada</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="page-30.html#h-60"><span class="HTitleText3">Loi sur le règlement de la revendication territoriale des Gwich’in</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="page-30.html#h-61"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="page-30.html#h-62"><span class="HTitleText3">Loi relative aux répercussions du projet gazier Mackenzie</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="page-30.html#h-63"><span class="HTitleText3">Loi sur l’éducation des Mi’kmaq</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="page-30.html#h-64"><span class="HTitleText3">Loi sur l’activité physique et le sport</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="page-30.html#h-65"><span class="HTitleText3">Loi sur le pilotage</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="page-30.html#h-66"><span class="HTitleText3">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="page-30.html#h-67"><span class="HTitleText3">Loi sur le règlement de la revendication territoriale des Dénés et Métis du Sahtu</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="page-30.html#h-68"><span class="HTitleText3">Loi sur l’Union des producteurs de grain</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="page-30.html#h-69"><span class="HTitleText3">Loi sur le règlement des revendications territoriales des premières nations du Yukon</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="page-30.html#h-70"><span class="HTitleText3">Autres lois</span></a>
</li></ul>
</li><li><span class='sectionRange'>341 - </span><a href="page-30.html#h-71"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="page-31.html#h-72"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="page-31.html#h-73"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

