<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la réforme de la non-responsabilité criminelle</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-3"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA DÉFENSE NATIONALE</cite></span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="#h-5"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

