<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la réforme de la non-responsabilité criminelle</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="page-3.html#h-3"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA DÉFENSE NATIONALE</cite></span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="page-5.html#h-5"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-6.html#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

