<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accord définitif sur l’autonomie gouvernementale de Deline</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">ACCORD DE DELINE</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HTitleText1">GOUVERNEMENT GOTINE DE DELINE</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText1">APPLICATION D’AUTRES LOIS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">FISCALITÉ</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES ET CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des ressources de la vallée du Mackenzie</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe sur les produits et services des premières nations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-12"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-13"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

