<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur la pension de retraite de la Gendarmerie royale du Canada, validant certains calculs et modifiant d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LA PENSION DE RETRAITE DE LA GENDARMERIE ROYALE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-2"><span class="HTitleText1">VALIDATION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES ET CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Loi modifiant certaines lois en matière de pensions et édictant la Loi sur les régimes de retraite particuliers et la Loi sur le partage des prestations de retraite</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Loi modifiant la Loi sur la pension de retraite des Forces canadiennes et d’autres lois en conséquence</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-2.html#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

