<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Cheval national du Canada, Loi sur le</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LE CHEVAL NATIONAL</span></a>
</li></ul>
</li></ul>

</nav>

