<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Journée Sir John A. Macdonald et la Journée Sir Wilfrid Laurier, Loi sur la</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">JOURNÉE SIR JOHN A. MACDONALD</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">JOURNÉE SIR WILFRID LAURIER</span></a>
</li></ul>
</li></ul>

</nav>

