<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les élections au sein de premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">AJOUT À L’ANNEXE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">DATES DES ÉLECTIONS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">CONSEIL</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText1">CANDIDATS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">BULLETINS DE VOTE</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText1">EXERCICE DU DROIT DE VOTE</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText1">BUREAUX DE SCRUTIN</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">ATTRIBUTION DES POSTES</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText1">ÉLECTION PARTIELLE</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText1">ENTRAVE À LA TENUE D’ÉLECTIONS</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText1">MANDAT DES ÉLUS</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText1">CONTESTATION DE L’ÉLECTION</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-15"><span class="HTitleText1">PÉTITION VISANT LA RÉVOCATION DU CHEF OU D’UN CONSEILLER</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-16"><span class="HTitleText1">INFRACTIONS</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText1">PEINES</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-18"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-19"><span class="HTitleText1">RETRAIT DE L’ANNEXE</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-20"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA <cite class="XRefExternalAct">LOI SUR LES INDIENS</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - PREMIÈRES NATIONS PARTICIPANTES</span></a>
</li></ul>
</li></ul>

</nav>

