<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la protection des renseignements personnels numériques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA PROTECTION DES RENSEIGNEMENTS PERSONNELS ET LES DOCUMENTS ÉLECTRONIQUES</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-3"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-4.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-4.html#h-5"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-6"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

