<h2>FORMULE B</h2>

<p>Le pr&eacute;sent document atteste que la personne nomm&eacute;e ci-dessous a choisi d'&ecirc;tre un participant aux termes de la partie ii de la loi sur la pension de la fonction publique.</p>

<p>Le pr&eacute;sent document est d&eacute;livr&eacute; &agrave;: Nom (ci -apr&egrave;s d&eacute;sign&eacute; « le participant »)</p>

<p>Adresse</p>

<p>Pour certifier que ladite personne, un participant en vertu de la Partie II de la Loi sur la pension de la fonction publique, a cess&eacute; son emploi &agrave; la fonction publique le __jour, de (mois), (ann&eacute;e) et a droit a toutes les prestations et est assujettie &agrave; toutes les obligations pr&eacute;vues, dans son cas, par la Loi sur la pension de la fonction publique.</p>

<ol>
	<li>Prestations<br />La prestation payable au d&eacute;c&egrave;s du participant est de ____$ sous r&eacute;serve des r&eacute;ductions suivantes :<ol class="upperAlpha">
		<li>La prestation est r&eacute;duite de 10% le premier avril ou le premier octobre suivant imm&eacute;diatement  chaque anniversaire de naissance du participant et cela, a compter de son soixante et uni&egrave;me anniversaire.</li>

		<li>Le participant peut choisir de façon irr&eacute;vocable de faire r&eacute;duire sa prestation a 500$ (toute demande de renseignements concernant ce choix  doit &ecirc;tre adress&eacute;e &agrave; approvisionnements et services Canada, direction des pensions de retraite C.P. 5010, Moncton, (N.-B.) E1C 8Z5).</li>

		<li>La prestation ne sera jamais inf&eacute;rieur &agrave; 500$ si le participant a pay&eacute; ses contributions jusqu'au 31 mars ou jusqu'au 30 septembre, suivant on soixante cinqui&egrave;me anniversaire soit la date qui suit de plus pr&egrave;s l'anniversaire de naissance du participant.</li>
	</ol></li>

	<li>Contributions:<ol class="upperAlpha">
		<li>Le versement de la prestation au d&eacute;c&egrave;s du participant d&eacute;pend du paiement d'une contribution mensuelle de ____$ sous r&eacute;serve d'une r&eacute;duction de 10% pour chaque ann&eacute;e suivant le soixanti&egrave;me anniversaire de naissance du participant. Cette r&eacute;duction est op&eacute;r&eacute;e le 1er avril ou le 1er octobre soit la date qui suit de plus pr&egrave;s le soixante et uni&egrave;me anniversaire de naissance du participant.</li>
		<li>D&eacute;s que le participant atteint l'âge de 65 ans, une r&eacute;duction suppl&eacute;mentaire de 0.20$ par mois est payable le 1ier avril ou le 1er octobre, soit la date  qui suit de plus pr&egrave;s le soixante cinqui&egrave;me anniversaire de naissance du participant.</li>
		<li>Si le participant choisit de faire r&eacute;duire sa prestation &agrave; 500$, sa contribution mensuelle sera 0.20$  jusqu'&agrave; la date mentionn&eacute;e a la disposition (B), apr&egrave;s quoi aucune contribution  ne sera requise.</li>
		<li>Les contributions sont pr&eacute;lev&eacute;s par  acomptes mensuels &eacute;gaux sur la pension payable au  participant en vertu de la Partie I de la Loi sur la pension de la fonction publique.</li>
	</ol></li>
	
	<li>Date de Naissance<br />La preuve que la date de naissance du participant est le ___(jour) de (mois), (ann&eacute;e) a &eacute;t&eacute; accept&eacute;e.</li>

	<li>R&eacute;emploi ou nouvelle nomination<br />Le pr&eacute;sent document cesse d'avoir effet et la prestation indiqu&eacute;e cesse d'&ecirc;tre payable &agrave; compter du jour où le participant cesse d'&ecirc;tre  un participant volontaire et devient un participant (autre qu'un participant volontaire) en vertu de la Partie II de la Loi sur la pension de la fonction publique.</li>
</ol>

<h3>Dispositions g&eacute;n&eacute;rales</h3>

<ol class="upperAlpha">
	<li>Si un participant d&eacute;c&egrave;de et qu'il a d&eacute;sign&eacute; un b&eacute;ni ficaire valide conform&eacute;ment &agrave; l'article 26 du R&egrave;glement sur les prestations suppl&eacute;mentaires de d&eacute;c&egrave;s, la prestation est payable au b&eacute;n&eacute;ficiaire. Dans tous les autres cas la prestation est payable aux termes de la Partie II de la Loi sur la pension de la fonction publique.</li>
	<li>Le paiement d'une prestation vis&eacute;e &agrave; la disposition (A) est soumis &agrave; la preuve du d&eacute;c&egrave;s du participant et du droit du r&eacute;clamant.</li>
	<li>Les dispositions de la Partie II de la Loi sur la pension de la fonction publique et de ses r&egrave;glements d'application s'appliquent au pr&eacute;sent document.</li>
</ol>

<p>Émis le ___ jour de (mois), (ann&eacute;e).</p>

<p>Directeur de la direction des pensions de retraite, minist&egrave;re des approvisionnements et services.</p>