<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à fournir un soutien supplémentaire en réponse à la COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Modifications connexes au <cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-2.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la prestation canadienne pour les travailleurs en cas de confinement</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-3.html#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-3.html#h-9"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-3.html#h-10"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les prestations canadiennes de relance économique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Modification connexe du <cite class="XRefExternalRegulation">Règlement sur les prestations canadiennes de relance économique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>19.1 - </span><a href="page-3.html#h-13"><span class="HLabel1">PARTIE 3.1</span> - <span class="HTitleText1">Examen des lois</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-14"><span class="HLabel1">PARTIE 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-16"></span> - </a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-5.html#h-18"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

