<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’instrument multilatéral relatif aux conventions fiscales</a><ul class="TocIndent"><li><a href="#h-1"><span class="scheduleLabel">Annexe</span> <span class="scheduleTitleText"> - Convention multilatérale pour la mise en oeuvre des mesures relatives aux conventions fiscales pour prévenir l’érosion de la base d’imposition et le transfert de bénéfices</span></a>
</li></ul>
</li></ul>

</nav>

