<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Bibliothèque et les Archives du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET CHAMP D'APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CONSTITUTION ET ORGANISATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MISSION ET ATTRIBUTIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-5"><span class="HTitleText1">DÉPÔT LÉGAL</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-6"><span class="HTitleText1">OBTENTION D'ENREGISTREMENTS DE QUALITÉ ARCHIVISTIQUE À DES FINS DE PRÉSERVATION</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-7"><span class="HTitleText1">GESTION DES DOCUMENTS FÉDÉRAUX ET MINISTÉRIELS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-8"><span class="HTitleText1">LOI SUR LES BIENS DE SURPLUS DE LA COURONNE</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-9"><span class="HTitleText1">DISPOSITIONS FINANCIÈRES</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-10"><span class="HTitleText1">DISPOSITION GÉNÉRALE</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-11"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-12"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LE DROIT D'AUTEUR</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-13"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l'accès à l'information</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit d'auteur</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Anciens Combattants</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d'accise</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les lieux et monuments historiques</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l'impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d'indemnisation des militaires ayant subi des blessures</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi concernant l'Accord sur les revendications territoriales du Nunavut</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-3.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations aux anciens combattants</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le système de justice pénale pour les adolescents</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le règlement des revendications territoriales des premières nations du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l'autonomie gouvernementale des premières nations du Yukon</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-4.html#h-33"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-4.html#h-34"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-4.html#h-35"><span class="HTitleText1">ABROGATIONS</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-4.html#h-36"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

