<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 2 sur le plan d’action économique de 2013</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MESURES RELATIVES À L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-18.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le soutien de la croissance de l’économie et de l’emploi au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-19.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-21.html#h-6"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="page-21.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA TAXE D’ACCISE</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-22.html#h-8"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DIVERSES MESURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="page-22.html#h-9"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="page-22.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-23.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Office de financement de l’assurance-emploi du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-23.html#h-12"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="page-23.html#h-13"><span class="HTitleText4"><cite class="XRefExternalAct">Loi canadienne sur les organisations à but non lucratif</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-23.html#h-14"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’emploi, la croissance et la prospérité durable</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-23.html#h-15"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de 2012 sur l’emploi et la croissance</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="page-24.html#h-16"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur l’assurance-emploi (pêche)</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-24.html#h-17"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="page-24.html#h-18"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Institutions financières (conflits d’intérêts)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-24.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Bureau du surintendant des institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-24.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-24.html#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-24.html#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-24.html#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence de la consommation en matière financière du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>167 - </span><a href="page-24.html#h-24"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Institutions financières (investissements)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-24.html#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-24.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-24.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-24.html#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>174 - </span><a href="page-24.html#h-29"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Passeports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="page-24.html#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-25.html#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Affaires étrangères, du Commerce et du Développement</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="page-25.html#h-32"><span class="HLabel2">Section 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>176 - </span><a href="page-25.html#h-33"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-28.html#h-34"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-28.html#h-35"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="page-28.html#h-36"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’Office national de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-28.html#h-37"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-28.html#h-38"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="page-29.html#h-39"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>204 - </span><a href="page-29.html#h-40"><span class="HLabel2">Section 6</span> - <span class="HTitleText2">Modifications au Conseil des ministres du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="page-29.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Ressources humaines et du Développement des compétences</cite></span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="page-29.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les traitements</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="page-30.html#h-43"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-30.html#h-44"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>221 - </span><a href="page-30.html#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="page-30.html#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-30.html#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-30.html#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Loi d’aide à l’exécution des ordonnances et des ententes familiales</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-30.html#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-30.html#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-30.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi fédérale sur l’aide financière aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="page-30.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>236 - </span><a href="page-30.html#h-53"><span class="HTitleText3">Modifications terminologiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="page-31.html#h-54"><span class="HLabel2">Section 7</span> - <span class="HTitleText2">Réserve fédérale de charbon</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="page-32.html#h-55"><span class="HLabel2">Section 8</span> - <span class="HTitleText2">Réorganisation de certaines sociétés d’État  —  ponts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>249 - </span><a href="page-32.html#h-56"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-32.html#h-57"><span class="HTitleText3">Fusion</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="page-32.html#h-58"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>261 - </span><a href="page-32.html#h-59"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="page-32.html#h-60"><span class="HTitleText4"><cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="page-32.html#h-61"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les ponts et tunnels internationaux</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>264 - </span><a href="page-32.html#h-62"><span class="HTitleText3">Abrogations</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-33.html#h-63"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="page-33.html#h-64"><span class="HLabel2">Section 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-33.html#h-65"><span class="HLabel2">Section 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil national de recherches</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-33.html#h-66"><span class="HLabel2">Section 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite></span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="page-33.html#h-67"><span class="HLabel2">Section 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office d’investissement du régime de pensions du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>277 - </span><a href="page-33.html#h-68"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-33.html#h-69"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>279 - </span><a href="page-33.html#h-70"><span class="HLabel2">Section 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>279 - </span><a href="page-33.html#h-71"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-33.html#h-72"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>282 - </span><a href="page-33.html#h-73"><span class="HLabel2">Section 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Fonds relatif aux répercussions du projet gazier Mackenzie</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>282 - </span><a href="page-33.html#h-74"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-34.html#h-75"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>283 - </span><a href="page-34.html#h-76"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="page-34.html#h-77"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="page-34.html#h-78"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="page-34.html#h-79"><span class="HTitleText4"><cite class="XRefExternalAct">Loi d’exécution du budget de 2006</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>287 - </span><a href="page-34.html#h-80"><span class="HTitleText3">Abrogation</span></a>
</li></ul>
</li><li><span class='sectionRange'>288 - </span><a href="page-34.html#h-81"><span class="HLabel2">Section 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les conflits d’intérêts</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="page-34.html#h-82"><span class="HLabel2">Section 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>290 - </span><a href="page-34.html#h-83"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-35.html#h-84"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>294 - </span><a href="page-35.html#h-85"><span class="HLabel2">Section 17</span> - <span class="HTitleText2">Relations de travail dans la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>294 - </span><a href="page-35.html#h-86"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>294 - </span><a href="page-35.html#h-87"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="page-38.html#h-88"><span class="HTitleText4">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>340 - </span><a href="page-39.html#h-89"><span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>340 - </span><a href="page-39.html#h-90"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="page-39.html#h-91"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>342 - </span><a href="page-39.html#h-92"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="page-39.html#h-93"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="page-40.html#h-94"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>361 - </span><a href="page-40.html#h-95"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’équité dans la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="page-40.html#h-96"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="page-40.html#h-97"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>365 - </span><a href="page-40.html#h-98"><span class="HLabel2">Section 18</span> - <span class="HTitleText2">Réorganisation de tribunaux fédéraux en matière de relations de travail et d’emploi dans la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>365 - </span><a href="page-40.html#h-99"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Commission des relations de travail et de l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="page-41.html#h-100"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>366 - </span><a href="page-41.html#h-101"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>391 - </span><a href="page-42.html#h-102"><span class="HTitleText4">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="page-43.html#h-103"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="page-43.html#h-104"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="page-44.html#h-105"><span class="HTitleText4">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>425 - </span><a href="page-44.html#h-106"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>425 - </span><a href="page-44.html#h-107"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="page-45.html#h-108"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>439 - </span><a href="page-45.html#h-109"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>439 - </span><a href="page-45.html#h-110"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="page-45.html#h-111"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>441 - </span><a href="page-45.html#h-112"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’équité dans la rémunération du secteur public</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="page-45.html#h-113"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="page-45.html#h-114"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>446 - </span><a href="page-45.html#h-115"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>446 - </span><a href="page-45.html#h-116"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>448 - </span><a href="page-45.html#h-117"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="page-46.html#h-118"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite></span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="page-46.html#h-119"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>459 - </span><a href="page-46.html#h-120"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="page-46.html#h-121"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="page-46.html#h-122"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="page-46.html#h-123"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le statut de l’artiste</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>467 - </span><a href="page-46.html#h-124"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>470 - </span><a href="page-47.html#h-125"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>471 - </span><a href="page-47.html#h-126"><span class="HLabel2">Section 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Cour suprême</cite></span></a>
</li></ul>
</li><li><a href="page-48.html#h-127"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

