<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la compétence des premières nations en matière d’éducation en Colombie-Britannique,</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">OBJET ET EFFET</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">EFFET DE L’ACCORD SPÉCIFIQUE</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText1">AUTORITÉ SCOLAIRE DES PREMIÈRES NATIONS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-6"><span class="HTitleText1">MISSION ET ATTRIBUTIONS DE L’AUTORITÉ SCOLAIRE</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HTitleText1">ADMINISTRATION SCOLAIRE COMMUNAUTAIRE</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">CADRE LÉGISLATIF</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">RESPONSABILITÉ</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText1">ATTRIBUTIONS DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText1">DÉCRETS ET RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-14"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - PREMIÈRES NATIONS PARTICIPANTES</span></a>
</li></ul>
</li></ul>

</nav>

