<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur l’accès à l’information, la Loi sur la protection des renseignements personnels et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-3"><span class="HTitleText2">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-4"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-6"><span class="HTitleText1">Validation de décrets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-9"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels et les documents électroniques</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-12"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-13"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

