<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant certaines lois et un règlement relatifs aux armes à feu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur les armes à feu</cite>, du <cite class="XRefExternalAct">Code criminel</cite> et du <cite class="XRefExternalRegulation">Règlement désignant des armes à feu, armes, éléments ou pièces d’armes, accessoires, chargeurs, munitions et projectiles comme étant prohibés, à autorisation restreinte ou sans restriction</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les armes à feu</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement désignant des armes à feu, armes, éléments ou pièces d’armes, accessoires, chargeurs, munitions et projectiles comme étant prohibés, à autorisation restreinte ou sans restriction</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-5"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-3.html#h-6"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’abolition du registre des armes d’épaule</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-8"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

