<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en oeuvre de l’Accord de continuité commerciale Canada–Royaume-Uni</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’Accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approbation et représentation au sein du Comité mixte Canada–R.-U.</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Tribunaux, groupes spéciaux d’arbitrage et groupes d’experts</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes et disposition transitoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="page-3.html#h-21"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-3.html#h-22"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Disposition de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-3.html#h-23"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-24"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-4.html#h-25"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-5.html#h-26"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-6.html#h-27"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

