<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Mois du patrimoine latino-américain</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Mois du patrimoine latino-américain</span></a>
</li></ul>
</li></ul>

</nav>

