<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’abolition de la libération anticipée des criminels</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR LE SYSTÈME CORRECTIONNEL ET LA MISE EN LIBERTÉ SOUS CONDITION</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Loi modifiant la Loi sur le système correctionnel et la mise en liberté sous condition, le Code criminel, la Loi sur le casier judiciaire, la Loi sur les prisons et les maisons de correction et la Loi sur le transfèrement des délinquants</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Loi modifiant le Code criminel (délinquants présentant un risque élevé de récidive), la Loi sur le système correctionnel et la mise en liberté sous condition, la Loi sur le casier judiciaire, la Loi sur les prisons et les maisons de correction et la Loi sur le ministère du Solliciteur général</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Loi antiterroriste</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-8"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-9"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

