<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 d’exécution du budget de 2016</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Règles concernant l’application de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-6"><span class="HTitleText2">Modifications corrélatives au <cite class="XRefExternalRegulation">Règlement sur le Régime de pensions du Canada</cite> découlant du paragraphe 27(1), chapitre 7 des Lois du Canada (2016)</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-7"><span class="HTitleText2">Modifications terminologiques découlant du paragraphe 27(1), chapitre 7 des Lois du Canada (2016)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>86 - </span><a href="#h-8"><span class="HTitleText3">Mentions dans la <cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-9"><span class="HTitleText3">Mentions dans les règlements</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-10"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> (mesures relatives à la TPS/TVH) et d’autres textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-13"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-14"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les personnes morales étroitement liées (TPS/TVH)</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la comptabilité abrégée (TPS/TVH)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-17"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-18"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-19"><span class="HLabel2">SECTION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-20"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-21"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-22"><span class="HLabel2">SECTION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité de la vieillesse</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-23"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-24"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>107 - </span><a href="#h-25"><span class="HLabel2">SECTION 3</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur l’épargne-études</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-26"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-27"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-28"><span class="HLabel2">SECTION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur l’épargne-invalidité</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>114 - </span><a href="#h-29"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-30"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-31"><span class="HLabel2">Section 5</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Monnaie royale canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-32"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Gestion de fonds</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-34"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-35"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Société canadienne d’hypothèques et de logement</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-36"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

