<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’emploi et la croissance dans le Nord</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’AMÉNAGEMENT DU TERRITOIRE ET L’ÉVALUATION DES PROJETS AU NUNAVUT</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les eaux du Nunavut et le Tribunal des droits de surface du Nunavut</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’OFFICE DES DROITS DE SURFACE DES TERRITOIRES DU NORD-OUEST</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Modifications connexes à la <cite class="XRefExternalAct">Loi sur l’Office des droits de surface du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-3.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les opérations pétrolières au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-4.html#h-17"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

