<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi de 1987 sur les transports routiers et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI DE 1987 SUR LES TRANSPORTS ROUTIERS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’urgence sur les approvisionnements d’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les grains du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-6"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

