<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la modernisation de l’obligation de présentation et de déclaration relative à des moyens de transport</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Disposition de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

