<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi corrective de 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modifications</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi sur l’aéronautique</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Loi canadienne sur la santé</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Loi sur la concurrence</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Loi sur les ouvrages destinés à l’amélioration des cours d’eau internationaux</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Loi sur la sécurité automobile</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Loi sur l’équité en matière d’emploi</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Loi sur le tabac</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Loi canadienne sur la protection de l’environnement (1999)</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Loi sur les parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Loi de 2001 sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Loi sur le Yukon</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Loi sur les espèces en péril</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Loi sur la gestion financière des premières nations</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Loi sur le ministère de l’Emploi et du Développement social</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-21"><span class="HTitleText2">Loi sur le Programme de protection des salariés</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Loi sur l’emploi, la croissance et la prospérité durable</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Loi sur les Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2014</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-5.html#h-25"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-6.html#h-26"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Abrogations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Loi de 1986 sur les opérations portuaires</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Loi de 1987 sur le maintien des services postaux</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-6.html#h-29"><span class="HTitleText2">Loi de 1991 sur le maintien des services postaux</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-6.html#h-30"><span class="HTitleText2">Loi de 1994 sur les opérations portuaires de la côte ouest</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-6.html#h-31"><span class="HTitleText2">Loi de 1995 sur les opérations portuaires de la côte ouest</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Loi de 1995 sur le maintien des services ferroviaires</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-6.html#h-33"><span class="HTitleText2">Loi de 1997 sur le maintien des services postaux</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-6.html#h-34"><span class="HTitleText2">Loi de 2007 sur le maintien des services ferroviaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="page-6.html#h-35"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

