<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en œuvre de la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles et du Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques à la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">FORCE DE LOI</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText1">INCOMPATIBILITÉ</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-7"><span class="HTitleText1">TRIBUNAUX</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-8"><span class="HTitleText1">DEMANDES DE DÉCLARATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-9"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-10"><span class="HTitleText1">MODIFICATIONS À CERTAINES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Loi sur les liquidations et les restructurations</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-2.html#h-15"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-3.html#h-16"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - CONVENTION RELATIVE AUX GARANTIES INTERNATIONALES PORTANT SUR DES MATÉRIELS D’ÉQUIPEMENT MOBILES</span></a>
</li>
<li><a href="page-4.html#h-17"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - PROTOCOLE PORTANT SUR LES QUESTIONS SPÉCIFIQUES AUX MATÉRIELS D’ÉQUIPEMENT AÉRONAUTIQUES À LA CONVENTION RELATIVE AUX GARANTIES INTERNATIONALES PORTANT SUR DES MATÉRIELS D’ÉQUIPEMENT MOBILES</span></a>
</li>
<li><a href="page-5.html#h-18"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - TEXTE REFONDU DE LA CONVENTION RELATIVE AUX GARANTIES INTERNATIONALES PORTANT SUR DES MATÉRIELS D’ÉQUIPEMENT MOBILES ET DE SON PROTOCOLE PORTANT SUR LES QUESTIONS SPÉCIFIQUES AUX MATÉRIELS D’ÉQUIPEMENT AÉRONAUTIQUES</span></a>
</li></ul>
</li></ul>

</nav>

