<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la gestion du pétrole et du gaz et des fonds des Premières Nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DEMANDES DE TRANSFERT</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-4"><span class="HTitleText1">EXIGENCES RELATIVES AU TRANSFERT</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-5"><span class="HTitleText1">PROCÉDURE D’APPROBATION</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-6"><span class="HTitleText1">TRANSFERTS À LA PREMIÈRE NATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Pétrole et gaz</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-8"><span class="HTitleText2">Fonds</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-3.html#h-9"><span class="HTitleText1">POUVOIRS RELATIFS AU PÉTROLE ET AU GAZ</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-10"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-4.html#h-11"><span class="HTitleText1">RÉGIME JURIDIQUE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Pétrole et gaz</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-5.html#h-13"><span class="HTitleText2">Fonds</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-5.html#h-14"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-5.html#h-15"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-6.html#h-16"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-7.html#h-17"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

