<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les ponts et tunnels internationaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET APPLICATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CONSTRUCTION ET MODIFICATION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-4"><span class="HTitleText1">ENTRETIEN ET RÉPARATION</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-5"><span class="HTitleText1">EXPLOITATION ET USAGE</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-6"><span class="HTitleText1">SÛRETÉ</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-7"><span class="HTitleText1">CHANGEMENT CONCERNANT LA PROPRIÉTÉ, L’EXPLOITATION OU LE CONTRÔLE</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-8"><span class="HTitleText1">CONSTITUTION DE PERSONNES MORALES PAR LETTRES PATENTES</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-9"><span class="HTitleText1">ACTIONS D’UNE PERSONNE MORALE</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-10"><span class="HTitleText1">MESURES DE CONTRAINTE</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-11"><span class="HTitleText1">PÉNALITÉS</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-12"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-13"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-5.html#h-14"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="page-5.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="page-5.html#h-16"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-6.html#h-17"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - LOIS RELATIVES À CERTAINS PONTS ET TUNNELS</span></a>
</li></ul>
</li></ul>

</nav>

