<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le cadre du choix provincial en matière fiscale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LA TAXE D’ACCISE</span></a>
</li>
<li><a href="#h-3"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

