<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces et édictant la Loi concernant l’octroi d’une aide financière à l’égard d’équipements diagnostiques et médicaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25.91 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Communiqués</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">LOI CONCERNANT L’OCTROI D’UNE AIDE FINANCIÈRE À L’ÉGARD D’ÉQUIPEMENTS DIAGNOSTIQUES ET MÉDICAUX</span></a>
</li></ul>
</li></ul>

</nav>

