<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la modernisation des transports</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-9.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la commercialisation du CN</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-9.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-10.html#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-10.html#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’Administration canadienne de la sûreté du transport aérien</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-10.html#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-11.html#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-11.html#h-9"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-12.html#h-10"><span class="HTitleText1">Modifications connexes et corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="page-12.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-12.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-12.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-13.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la participation publique au capital d’Air Canada</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-13.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’exécution du budget de 2009</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-13.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le transport ferroviaire équitable pour les producteurs de grain</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="page-13.html#h-17"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-14.html#h-18"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

