<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur l’expansion des exportations et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR L’EXPANSION DES EXPORTATIONS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-2"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-3"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les accords de Bretton Woods et des accords connexes</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-10"><span class="HTitleText2">Autres lois fédérales</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-11"><span class="HTitleText2">Règlements et autres textes d’application</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-12"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

