<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Agence de la consommation en matière financière du Canada, Loi sur l’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">MISE EN PLACE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">COMMISSAIRE DE L’AGENCE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">ATTRIBUTIONS DU COMMISSAIRE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-6"><span class="HTitleText1">ACCORDS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-7"><span class="HTitleText1">COMMISSAIRES ADJOINTS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-8"><span class="HTitleText1">EXERCICE DES ATTRIBUTIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-9"><span class="HTitleText1">PERSONNEL DE L’AGENCE</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-10"><span class="HTitleText1">FINANCES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-11"><span class="HTitleText1">CONFLITS D’INTÉRÊTS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-12"><span class="HTitleText1">CARACTÈRE CONFIDENTIEL DES RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-13"><span class="HTitleText1">COTISATIONS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-14"><span class="HTitleText1">PÉNALITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="page-2.html#h-15"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Ouverture des procédures</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Responsabilité et pénalité</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Appel à la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-19"><span class="HTitleText2">Recouvrement des pénalités</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-20"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-21"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-3.html#h-22"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-23"><span class="HTitleText1">ABSENCE DE RESPONSABILITÉ</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-24"><span class="HTitleText1">RAPPORT ANNUEL</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-25"><span class="HTitleText1">MODIFICATION DE LOIS RELATIVES AUX INSTITUTIONS FINANCIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-3.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-20.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="page-21.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="page-22.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Association canadienne des paiements</cite></span></a>
</li></ul>
</li><li><a href="page-26.html#h-30"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">SYSTÈMES DE PAIEMENT DÉSIGNÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="page-27.html#h-31"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="page-28.html#h-32"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-29.html#h-33"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-30.html#h-34"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-31.html#h-35"><span class="HTitleText2">Lignes directrices et instructions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-32.html#h-36"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-33.html#h-37"><span class="HTitleText2">Participants</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="page-34.html#h-38"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>248 - </span><a href="page-35.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>343 - </span><a href="page-38.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’association personnalisée le Bouclier vert du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="page-39.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="page-54.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Bureau du surintendant des institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>478 - </span><a href="page-57.html#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li></ul>
</li><li><a href="page-66.html#h-44"><span class="HTitleText1">MODIFICATION D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>572 - </span><a href="page-67.html#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>575 - </span><a href="page-67.html#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>578 - </span><a href="page-67.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>581 - </span><a href="page-67.html#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les lettres et billets de dépôt</cite></span></a>
</li>
<li><span class='sectionRange'>583 - </span><a href="page-67.html#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1985 sur les normes de prestation de pension</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>584 - </span><a href="page-67.html#h-50"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>584 - </span><a href="page-67.html#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>586 - </span><a href="page-67.html#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les lettres de change</cite></span></a>
</li>
<li><span class='sectionRange'>587 - </span><a href="page-67.html#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le financement des petites entreprises du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="page-67.html#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>589 - </span><a href="page-67.html#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>590 - </span><a href="page-67.html#h-56"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>591 - </span><a href="page-67.html#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="page-67.html#h-58"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>593 - </span><a href="page-67.html#h-59"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-68.html#h-60"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-69.html#h-61"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-70.html#h-62"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

