<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Régime de pensions du Canada et la Loi sur l’Office d’investissement du régime de pensions du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">RÉGIME DE PENSIONS DU CANADA</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI SUR L’OFFICE D’INVESTISSEMENT DU RÉGIME DE PENSIONS DU CANADA</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

