<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les océans et la Loi fédérale sur les hydrocarbures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les océans</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-4.html#h-3"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-4.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Loi fédérale sur les hydrocarbures</cite></span></a>
</li></ul>
</li></ul>

</nav>

