<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
L<?Pub Caret?>oi portant mise en vigueur de l’Entente sur la gouvernance de la nation crie entre les Cris d’Eeyou Istchee et le gouvernement du Canada, modifiant la Loi sur les Cris et les Naskapis du Québec et apportant des modifications connexes et corrélatives à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’accord concernant la gouvernance de la nation crie d’Eeyou Istchee</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Édiction de la Loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les Cris et les Naskapis du Québec</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">Modification de la Loi</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-5"><span class="HTitleText2">Modifications terminologiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-6"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions transitoires, modifications connexes, modifications corrélatives et dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-7"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-8"><span class="HTitleText2">Modifications connexes à la <cite class="XRefExternalAct">Loi sur la modernisation de certains régimes d’avantages et d’obligations</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-9"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les terres destinées aux anciens combattants</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’expropriation</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’arpentage des terres du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Office national de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Tribunal des revendications particulières</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-18"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

