<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur l’assurance-emploi et le Règlement sur l’assurance-emploi (pêche)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR L’ASSURANCE-EMPLOI</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-3"><span class="HTitleText1">RÈGLEMENT SUR L’ASSURANCE-EMPLOI (PÊCHE)</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

