<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi améliorant la sécurité ferroviaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR LA SÉCURITÉ FERROVIAIRE</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-3"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES À LA LOI SUR LES TRANSPORTS AU CANADA</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-7.html#h-4"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-7.html#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

