<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’évaluation environnementale et socioéconomique au Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET DISPOSITIONS D’INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">OFFICE D’ÉVALUATION ENVIRONNEMENTALE ET SOCIOÉCONOMIQUE DU YUKON ET BUREAUX DÉSIGNÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Office d’évaluation environnementale et socioéconomique du Yukon</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-6"><span class="HTitleText2">Circonscriptions et bureaux désignés</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-7"><span class="HTitleText2">Budgets et rapports</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-8"><span class="HTitleText2">Règles et règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-9"><span class="HTitleText2">Obligation générale</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-10"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">PROCESSUS D’ÉVALUATION ET DÉCISIONS ÉCRITES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-11"><span class="HTitleText2">Dispositions générales sur le processus</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-12"><span class="HTitleText2">Activités visées</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-13"><span class="HTitleText2">Saisine</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-14"><span class="HTitleText2">Examen par le bureau désigné</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-15"><span class="HTitleText2">Avis et préétude par le comité de direction</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-16"><span class="HTitleText2">Demande d’étude</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-17"><span class="HTitleText2">Pouvoirs du ministre de l’Environnement</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-18"><span class="HTitleText2">Comité restreint</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-19"><span class="HTitleText2">Comité mixte</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-20"><span class="HTitleText2">Étude du projet de développement</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-21"><span class="HTitleText2">Examen des recommandations et prise des décisions écrites</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-22"><span class="HTitleText2">Mise en oeuvre des décisions écrites</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-23"><span class="HTitleText2">Versant nord du Yukon</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-24"><span class="HTitleText2">Coopération</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-25"><span class="HTitleText2">Ouvrages</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-26"><span class="HTitleText2">Plans</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-27"><span class="HTitleText2">Mesures de contrôle et de vérification</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-28"><span class="HTitleText2">Études et recherches</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-29"><span class="HTitleText2">Violation des prescriptions des décisions écrites</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-30"><span class="HTitleText2">Compétence judiciaire</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-31"><span class="HTitleText2">Dossiers et accès à l’information</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-32"><span class="HTitleText2">Règlements et décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-33"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CONNEXES, DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-34"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-35"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-36"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-37"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-38"><span class="HTitleText3">Loi sur l’autonomie gouvernementale des premières nations du Yukon</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-39"><span class="HTitleText3">Loi sur l’Office des droits de surface du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-40"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-41"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-42"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

