<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les Cris et les Naskapis du Québec</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES CRIS ET LES NASKAPIS DU QUÉBEC</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-2"><span class="HTitleText1">PUBLICATION</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

