<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la protection des collectivités et des personnes victimes d’exploitation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-3"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-4.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le casier judiciaire</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le système de justice pénale pour les adolescents</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le transfèrement international des délinquants</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>45.1 - </span><a href="page-5.html#h-10"><span class="HTitleText1">EXAMEN ET RAPPORT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-11"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-6.html#h-12"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

