<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur l’enregistrement des lobbyistes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR L’ENREGISTREMENT DES LOBBYISTES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-2"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Déclarations des lobbyistes-conseils</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Déclarations des lobbyistes salariés (personnes morales)</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Déclarations des lobbyistes salariés (organisations)</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-2.html#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

