<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant à mettre fin à la captivité des baleines et des dauphins</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la protection d’espèces animales ou végétales sauvages et la réglementation de leur commerce international et interprovincial</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Disposition connexe</span></a>
</li></ul>
</li></ul>

</nav>

