<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le règlement des revendications particulières</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">CENTRE CANADIEN DU RÈGLEMENT INDÉPENDANT DES REVENDICATIONS PARTICULIÈRES DES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Constitution, composition et fonctions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Premier dirigeant</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-2.html#h-9"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LA COMMISSION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Composition et attributions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-2.html#h-11"><span class="HTitleText3">Composition</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-12"><span class="HTitleText3">Rémunération</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-13"><span class="HTitleText3">Administration</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-14"><span class="HTitleText3">Attributions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-15"><span class="HTitleText3">Restriction</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-2.html#h-16"><span class="HTitleText2">Processus relatif aux revendications particulières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-2.html#h-17"><span class="HTitleText3">Dépôt des revendications</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-18"><span class="HTitleText3">Réunions préparatoires</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-19"><span class="HTitleText3">Bien-fondé des revendications</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-20"><span class="HTitleText3">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-21"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-3.html#h-22"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LE TRIBUNAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-3.html#h-23"><span class="HTitleText2">Composition et attributions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-3.html#h-24"><span class="HTitleText3">Composition</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-25"><span class="HTitleText3">Rémunération</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-26"><span class="HTitleText3">Administration</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-27"><span class="HTitleText3">Attributions</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-4.html#h-28"><span class="HTitleText2">Formations, audiences et décisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="page-5.html#h-29"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>77.1 - </span><a href="page-6.html#h-30"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">DISPOSITION TRANSITOIRE, MODIFICATIONS CORRÉLATIVES, DISPOSITION DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77.1 - </span><a href="page-6.html#h-31"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="page-6.html#h-33"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-6.html#h-34"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-6.html#h-35"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-6.html#h-36"><span class="HTitleText3">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-6.html#h-37"><span class="HTitleText3">Loi sur la pension de la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="page-6.html#h-38"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-6.html#h-39"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-7.html#h-40"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

