<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi fédérale sur le développement durable et la Loi sur le vérificateur général (participation du Parlement)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI FÉDÉRALE SUR LE DÉVELOPPEMENT DURABLE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LE VÉRIFICATEUR GÉNÉRAL</span></a>
</li></ul>
</li></ul>

</nav>

