<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi relative à une stratégie nationale sur la maladie d’Alzheimer et d’autres démences</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Stratégie nationale sur la maladie d’Alzheimer et d’autres démences</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Rapport d’examen</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

