<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en oeuvre de l’Accord de partenariat transpacifique global et progressiste</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’Accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approbation et représentation au sein de la Commission</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Groupes spéciaux et Conseil du travail</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes et disposition transitoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-6.html#h-21"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-6.html#h-22"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-7.html#h-25"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-8.html#h-26"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-9.html#h-27"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-10.html#h-28"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-11.html#h-29"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-12.html#h-30"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li>
<li><a href="page-13.html#h-31"><span class="scheduleLabel">ANNEXE 7</span> </a>
</li>
<li><a href="page-14.html#h-32"><span class="scheduleLabel">ANNEXE 8</span> </a>
</li>
<li><a href="page-15.html#h-33"><span class="scheduleLabel">ANNEXE 9</span> </a>
</li>
<li><a href="page-16.html#h-34"><span class="scheduleLabel">ANNEXE 10</span> </a>
</li>
<li><a href="page-17.html#h-35"><span class="scheduleLabel">ANNEXE 11</span> </a>
</li>
<li><a href="page-18.html#h-36"><span class="scheduleLabel">ANNEXE 12</span> </a>
</li>
<li><a href="page-19.html#h-37"><span class="scheduleLabel">ANNEXE 13</span> </a>
</li></ul>
</li></ul>

</nav>

