<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi fédérale sur la responsabilité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">CONFLITS D’INTÉRÊTS, FINANCEMENT ÉLECTORAL, LOBBYING ET PERSONNEL MINISTÉRIEL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les conflits d’intérêts</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-4"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-2.html#h-7"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-8"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-9"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-10"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion financière et statistique des premières nations</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-11"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-12"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-13"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-14"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-15"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-16"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-5.html#h-17"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-5.html#h-18"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-5.html#h-19"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="page-5.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-5.html#h-21"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-22"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-23"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="page-7.html#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="page-8.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement des lobbyistes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="page-8.html#h-26"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-10.html#h-27"><span class="HTitleText3">Terminologie</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-11.html#h-28"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-11.html#h-29"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="page-11.html#h-30"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-11.html#h-31"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-12.html#h-32"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-12.html#h-33"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="page-12.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-12.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>100 - </span><a href="page-12.html#h-36"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-13.html#h-37"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-13.html#h-38"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="page-13.html#h-39"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">APPUI AU PARLEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="page-13.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-13.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le vérificateur général</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-13.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-15.html#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-16.html#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-17.html#h-45"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><a href="page-18.html#h-46"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DIRECTEUR DES POURSUITES PÉNALES, TRANSPARENCE ADMINISTRATIVE ET DIVULGATION DES ACTES RÉPRÉHENSIBLES</span></a>
<ul class="TocIndent"><li>
<a href="page-19.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le directeur des poursuites pénales</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="page-20.html#h-48"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-21.html#h-49"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><a href="page-22.html#h-50"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-23.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-24.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-25.html#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère de la Justice</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-26.html#h-54"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-27.html#h-55"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li></ul>
</li><li><a href="page-28.html#h-56"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="page-29.html#h-57"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><a href="page-30.html#h-58"><span class="HTitleText3">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172.1 - </span><a href="page-31.html#h-59"><span class="HTitleText4">Loi sur la Commission canadienne du blé</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>76.1 - </span><a href="page-32.html#h-60"><span class="HTitleText2">Examen ministériel</span></a>
</li>
<li><a href="page-33.html#h-61"><span class="HTitleText2">Loi électorale du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="page-34.html#h-62"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-35.html#h-63"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="page-36.html#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
</li>
<li><span class='sectionRange'>179.1 - </span><a href="page-37.html#h-65"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Bibliothèque et les Archives du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-38.html#h-66"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><a href="page-39.html#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="page-40.html#h-68"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-41.html#h-69"><span class="HTitleText3">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="page-42.html#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les traitements</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-43.html#h-71"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-44.html#h-72"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">SUPERVISION ADMINISTRATIVE ET RESPONSABILISATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="page-45.html#h-73"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque de développement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-46.html#h-74"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil des Arts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-47.html#h-75"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne d’hypothèques et de logement</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-48.html#h-76"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="page-49.html#h-77"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence du revenu du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-50.html#h-78"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Corporation commerciale canadienne</cite></span></a>
</li>
<li><a href="page-51.html#h-79"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Commission canadienne du lait</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="page-52.html#h-80"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="page-53.html#h-81"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="page-54.html#h-82"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Fondation canadienne des relations raciales</cite></span></a>
</li>
<li><span class='sectionRange'>244.1 - </span><a href="page-55.html#h-83"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Commission canadienne du tourisme</cite></span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-56.html#h-84"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société de développement du Cap-Breton</cite></span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="page-57.html#h-85"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><a href="page-58.html#h-86"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’expansion du Cap-Breton</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="page-59.html#h-87"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-60.html#h-88"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="page-61.html#h-89"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-62.html#h-90"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Financement agricole Canada</cite></span></a>
</li>
<li><a href="page-63.html#h-91"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>257 - </span><a href="page-64.html#h-92"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-65.html#h-93"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>276 - </span><a href="page-66.html#h-94"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la commercialisation du poisson d’eau douce</cite></span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="page-67.html#h-95"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les musées</cite></span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-68.html#h-96"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre national des Arts</cite></span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-69.html#h-97"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la capitale nationale</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="page-70.html#h-98"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le pilotage</cite></span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="page-71.html#h-99"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office d’investissement des régimes de pensions du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-72.html#h-100"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Monnaie royale canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-73.html#h-101"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil canadien des normes</cite></span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-74.html#h-102"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-75.html#h-103"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">CONTRATS ET APPROVISIONNEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>301 - </span><a href="page-76.html#h-104"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le vérificateur général</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-77.html#h-105"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><a href="page-78.html#h-106"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="page-79.html#h-107"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-80.html#h-108"><span class="HTitleText3">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>314 - </span><a href="page-81.html#h-109"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-82.html#h-110"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

