<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi fédérale sur le développement durable</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Loi fédérale sur le développement durable</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-2"><span class="HTitleText1">Modifications corrélatives à la Loi sur le vérificateur général</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

