<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la gestion des urgences</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">RESPONSABILITÉS MINISTÉRIELLES</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">RESPONSABILITÉS DES MINISTRES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">DÉCRETS OU RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de la Sécurité publique et de la Protection civile</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-2.html#h-9"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-10"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

