<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi portant exécution de certaines dispositions du budget déposé au Parlement le 18 février 2003</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">ÉQUIPEMENT DIAGNOSTIQUE ET MÉDICAL</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">PRÊTS D’ÉTUDES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText2">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText2">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">ASSURANCE-EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Règlement sur l’assurance-emploi (pêche)</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-13"><span class="HTitleText3">Code canadien du travail</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-15"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">GÉNÉRALITÉS : MESURES NON FISCALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-16"><span class="HTitleText2">Fondations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText3">Loi d’exécution du budget de 1997</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText3">Loi d’exécution du budget de 1998</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-19"><span class="HTitleText3">Loi sur la Fondation du Canada pour l’appui technologique au développement durable</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-20"><span class="HTitleText2">Subventions accordées à certains organismes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-21"><span class="HTitleText3">Fondation du Canada pour l’appui technologique au développement durable</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-22"><span class="HTitleText3">Fondation canadienne pour les sciences du climat et de l’atmosphère</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-23"><span class="HTitleText3">Inforoute Santé du Canada Inc.</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-24"><span class="HTitleText3">Fondation canadienne de la recherche sur les services de santé</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-25"><span class="HTitleText3">Institut canadien d’information sur la santé</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-26"><span class="HTitleText3">Fondation canadienne pour l’innovation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-27"><span class="HTitleText3">Génome Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-28"><span class="HTitleText2">Modification de la Loi sur Financement agricole Canada</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-29"><span class="HTitleText2">Abrogation de la Loi sur le compte de service et de réduction de la dette</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-30"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LE DROIT POUR LA SÉCURITÉ DES PASSAGERS DU TRANSPORT AÉRIEN</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-31"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">MODIFICATIONS TOUCHANT LA TAXATION DES PRODUITS DU TABAC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-32"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-33"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-34"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-35"><span class="HTitleText2">Entrée en vigueur et application</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-36"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">MODIFICATIONS TOUCHANT LA TAXE D’ACCISE SUR LE COMBUSTIBLE, LA TAXE SUR LES PRODUITS ET SERVICES ET LA TAXE DE VENTE HARMONISÉE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-37"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-38"><span class="HTitleText2">Modification corrélative à la Loi de 2001 sur l’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="#h-39"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">TAXES SUR LES PRODUITS ET SERVICES DES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-40"><span class="HTitleText2">Loi sur la taxe sur les produits et services des premières nations</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-41"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-42"><span class="HTitleText3">Loi sur la taxe d’accise</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="#h-43"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET D’UNE LOI CONNEXE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-44"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-45"><span class="HTitleText2">Loi sur les allocations spéciales pour enfants</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-46"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA COMPTABILITÉ NORMALISÉE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-47"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-48"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-49"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-50"><span class="HTitleText2">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-51"><span class="HTitleText3">Loi de 2001 sur l’accise</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-52"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

