<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi prévoyant une procédure accélérée et sans frais de suspension de casier judiciaire pour la possession simple de cannabis</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le casier judiciaire</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-2"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-3"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-4"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

