<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’amélioration de la réglementation au Yukon et au Nunavut</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">LOI SUR L’ÉVALUATION ENVIRONNEMENTALE ET SOCIOÉCONOMIQUE AU YUKON</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-4.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LOI SUR LES EAUX DU NUNAVUT ET LE TRIBUNAL DES DROITS DE SURFACE DU NUNAVUT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-7"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-8"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-9"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

