<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel (protection des enfants et d’autres personnes vulnérables) et la Loi sur la preuve au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-2"><span class="HTitleText1">LOI SUR LA PREUVE AU CANADA</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="page-4.html#h-3"><span class="HTitleText1">EXAMEN ET RAPPORT AU PARLEMENT</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-5.html#h-4"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-5.html#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

