<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’harmonisation n° 3 du droit fédéral avec le droit civil</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE CERTAINES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi sur les chambres de commerce</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-6"><span class="HTitleText2">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-9.html#h-7"><span class="HTitleText2">Loi sur l’emballage et l’étiquetage des produits de consommation</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-9.html#h-8"><span class="HTitleText2">Loi sur l’inspection de l’électricité et du gaz</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-10.html#h-9"><span class="HTitleText2">Loi sur l’expropriation</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-14.html#h-10"><span class="HTitleText2">Loi sur le poinçonnage des métaux précieux</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-14.html#h-11"><span class="HTitleText2">Loi sur les documents publics</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-14.html#h-12"><span class="HTitleText2">Loi sur le Conseil canadien des normes</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-14.html#h-13"><span class="HTitleText2">Loi sur l’étiquetage des textiles</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-14.html#h-14"><span class="HTitleText2">Loi sur les poids et mesures</span></a>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="page-14.html#h-15"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="page-14.html#h-16"><span class="HTitleText2">Loi sur les forces hydrauliques du Canada</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-14.html#h-17"><span class="HTitleText2">Loi sur les subventions aux bassins de radoub</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-14.html#h-18"><span class="HTitleText2">Loi sur les commissions portuaires</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-14.html#h-19"><span class="HTitleText2">Loi sur les ponts et tunnels internationaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-14.html#h-20"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><a href="page-15.html#h-21"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-16.html#h-22"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

