<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la transparence financière des Premières Nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">ÉTATS FINANCIERS ET ANNEXE DES RÉMUNÉRATIONS ET DES DÉPENSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Préparation et vérification indépendante</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Divulgation</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HTitleText1">RECOURS JUDICIAIRES ET MESURES ADMINISTRATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Ordonnances</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Mesures administratives</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

