<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la défense nationale, le Code criminel, la Loi sur l’enregistrement de renseignements sur les délinquants sexuels et la Loi sur le casier judiciaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA DÉFENSE NATIONALE</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’ENREGISTREMENT DE RENSEIGNEMENTS SUR LES DÉLINQUANTS SEXUELS</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE CASIER JUDICIAIRE</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-5"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-6"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

