<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code canadien du travail, la Loi sur les relations de travail au Parlement, la Loi sur les relations de travail dans la fonction publique et la Loi de l’impôt sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Loi sur les relations de travail au Parlement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-3"><span class="HTitleText1">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-4"><span class="HTitleText1">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-5"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-6"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

