<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant la déclaration obligatoire de la pornographie juvénile sur Internet par les personnes qui fournissent des services Internet<?Pub Caret?></a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">OBLIGATIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-3"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

