<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Kanesatake, Loi sur le gouvernement du territoire provisoire de</a><ul class="TocIndent"><li><span class='sectionRange'>24 - </span><a href="page-2.html#h-1"><span class="HTitleText1">MODIFICATION DE LA LOI SUR L’ARPENTAGE DES TERRES DU CANADA</span></a>
</li>
<li><a href="page-3.html#h-2"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - TERRITOIRE PROVISOIRE DE KANESATAKE</span></a>
</li></ul>
</li></ul>

</nav>

