<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel et apportant des modifications connexes à d’autres lois (aide médicale à mourir)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Code criminel</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-2"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText2">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText2">Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</span></a>
</li></ul>
</li><li><span class='sectionRange'>9.1 - </span><a href="#h-6"><span class="HTitleText1">Examen indépendant</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Examen de la loi</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

