<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur l’immigration et la protection des réfugiés</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

