<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’intégrité des élections</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI ÉLECTORALE DU CANADA</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-4"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA RÉVISION DES LIMITES DES CIRCONSCRIPTIONS ÉLECTORALES</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES TÉLÉCOMMUNICATIONS</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES CONFLITS D’INTÉRÊTS</cite></span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-8"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la révision des limites des circonscriptions électorales</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le directeur des poursuites pénales</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-14"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-15"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

