<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant certaines lois en conséquence de l’accession de la République populaire de Chine à l’Accord instituant l’Organisation mondiale du commerce</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LE TRIBUNAL CANADIEN DU COMMERCE EXTÉRIEUR</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-2"><span class="HTitleText1">TARIF DES DOUANES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-3"><span class="HTitleText1">LOI SUR LES LICENCES D’EXPORTATION ET D’IMPORTATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-4"><span class="HTitleText1">LOI SUR LES MESURES SPÉCIALES D’IMPORTATION</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-4.html#h-5"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-4.html#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

