<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi relative au cadre sur les soins palliatifs au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Cadre sur les soins palliatifs au Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">État des soins palliatifs au Canada</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

