<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi réglementant certaines drogues et autres substances et apportant des modifications connexes à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Loi réglementant certaines drogues et autres substances</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-8.html#h-2"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-8.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-8.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-8.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-11.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’administration des biens saisis</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-11.html#h-7"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-12.html#h-8"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-13.html#h-9"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

