<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le transfert de responsabilités aux Territoires du Nord-Ouest</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">LOI SUR LES TERRITOIRES DU NORD-OUEST</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Modifications apportées à d’autres lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText3">Loi sur la prévention de la pollution des eaux arctiques</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-7"><span class="HTitleText3">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-8"><span class="HTitleText3">Loi sur les ressources en eau du Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-9"><span class="HTitleText3">Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-10"><span class="HTitleText3">Loi sur la révision des limites des circonscriptions électorales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-11"><span class="HTitleText3">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-12"><span class="HTitleText3">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-13"><span class="HTitleText3">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-14"><span class="HTitleText3">Loi sur l’importation des boissons enivrantes</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-15"><span class="HTitleText3">Loi sur le ministère des Affaires indiennes et du Nord canadien</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-16"><span class="HTitleText3">Loi d’interprétation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-3.html#h-17"><span class="HTitleText3">Loi sur l’arpentage des terres du Canada</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-18"><span class="HTitleText3">Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-19"><span class="HTitleText3">Loi sur le pipe-line du Nord</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-20"><span class="HTitleText3">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-21"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-22"><span class="HTitleText3">Loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-4.html#h-23"><span class="HTitleText3">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-24"><span class="HTitleText3">Loi sur les terres territoriales</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-25"><span class="HTitleText3">Loi sur les forces hydrauliques du Canada</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-26"><span class="HTitleText3">Loi sur le divorce</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-27"><span class="HTitleText3">Loi fédérale sur les hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-28"><span class="HTitleText3">Loi sur le multiculturalisme canadien</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-29"><span class="HTitleText3">Loi sur les langues officielles</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-30"><span class="HTitleText3">Loi sur l’exploitation du champ Hibernia</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-5.html#h-31"><span class="HTitleText3">Loi sur les immeubles fédéraux et les biens réels fédéraux</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-32"><span class="HTitleText3">Loi sur le Nunavut</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-33"><span class="HTitleText3">Loi d’abrogation de la Loi sur les titres de biens-fonds</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-34"><span class="HTitleText3">Loi sur les océans</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-35"><span class="HTitleText3">Loi canadienne sur la protection de l’environnement (1999)</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-36"><span class="HTitleText3">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-37"><span class="HTitleText3">Loi sur les parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-38"><span class="HTitleText3">Loi sur le système de justice pénale pour les adolescents</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-39"><span class="HTitleText3">Loi sur les eaux du Nunavut et le Tribunal des droits de surface du Nunavut</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-40"><span class="HTitleText3">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-41"><span class="HTitleText3">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-42"><span class="HTitleText3">Loi sur les revendications territoriales et l’autonomie gouvernementale du peuple tlicho</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="page-6.html#h-43"><span class="HTitleText2">Modification du décret sur les serments d’allégeance et d’office et le siège du gouvernement (t.n.-o.)</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-6.html#h-44"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-45"><span class="HTitleText2">Abrogations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="page-6.html#h-46"><span class="HTitleText3">Lois</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-6.html#h-47"><span class="HTitleText3">Décrets et règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-6.html#h-48"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="page-6.html#h-49"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LES TERRES TERRITORIALES</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-50"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI SUR LES EAUX DES TERRITOIRES DU NORD-OUEST</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="page-7.html#h-51"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-10.html#h-52"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-10.html#h-53"><span class="HTitleText2">Modification corrélative à la Loi sur la gestion des ressources de la vallée du Mackenzie</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-10.html#h-54"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="page-10.html#h-55"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">LOI SUR LA GESTION DES RESSOURCES DE LA VALLÉE DU MACKENZIE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-10.html#h-56"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-29.html#h-57"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>238 - </span><a href="page-29.html#h-58"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-29.html#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="page-29.html#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les revendications territoriales et l’autonomie gouvernementale du peuple tlicho</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>241 - </span><a href="page-29.html#h-61"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-30.html#h-62"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

