<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les pêches et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-2"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-3"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les opérations pétrolières au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve-et-Labrador</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi concernant un pont destiné à favoriser le commerce</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-9"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-10"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

