<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur l’évaluation environnementale et socioéconomique au Yukon et modifiant une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’évaluation environnementale et socioéconomique au Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-2"><span class="HTitleText1">Modification corrélative à la <cite class="XRefExternalAct">Loi sur l’amélioration de la réglementation au Yukon et au Nunavut</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

