<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en oeuvre de l’Accord de libre-échange Canada–AELÉ</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MISE EN OEUVRE DE L’ACCORD ET DES ACCORDS BILATÉRAUX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approbation de l’Accord et des accords bilatéraux</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Sous-comités et groupes de travail</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-12"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Tarif des douanes</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-5.html#h-15"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-6.html#h-16"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-7.html#h-17"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-8.html#h-18"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-9.html#h-19"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-10.html#h-20"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-11.html#h-21"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li>
<li><a href="page-12.html#h-22"><span class="scheduleLabel">ANNEXE 7</span> </a>
</li></ul>
</li></ul>

</nav>

