<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi prévoyant l’indemnisation des militaires ayant subi des blessures pendant leur service</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">DÉSIGNATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">INDEMNISATION</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

