<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’emploi et la croissance économique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET DE LOIS ET RÈGLEMENTS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-4"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-5"><span class="HTitleText2">Loi canadienne sur l’épargne-invalidité</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-6"><span class="HTitleText2">Règlement sur l’épargne-invalidité</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-7"><span class="HTitleText2">Loi canadienne sur l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-8"><span class="HTitleText2">Règlement sur l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-9"><span class="HTitleText2">Règlement sur le Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-10"><span class="HTitleText2">Règlement sur la rémunération assurable et la perception des cotisations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-11"><span class="HTitleText2">Règlement sur l’exclusion de certains actes criminels de la définition de « infraction désignée »</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX DROITS D’ACCISE ET AUX TAXES DE VENTE ET D’ACCISE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-13"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-14"><span class="HTitleText2">Modifications relatives à la Loi de 2001 sur l’accise</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-15"><span class="HTitleText3">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-16"><span class="HTitleText3">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-17"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-18"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-19"><span class="HTitleText2">Règlement sur les services de santé (TPS/TVH)</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-20"><span class="HTitleText2">Règlement sur les méthodes d’attribution des crédits de taxe sur les intrants (TPS/TVH)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-21"><span class="HTitleText3">Prise du règlement</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-22"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="#h-23"><span class="HTitleText2">Règlement sur les taux d’intérêt (Loi de 2001 sur l’accise)</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-24"><span class="HTitleText2">Règlement sur les taux d’intérêt (Loi sur la taxe d’accise)</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-25"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="#h-26"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AU DROIT POUR LA SÉCURITÉ DES PASSAGERS DU TRANSPORT AÉRIEN</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="#h-27"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-28"><span class="HTitleText2">Règlement sur les taux d’intérêt (Loi sur le droit pour la sécurité des passagers du transport aérien)</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-29"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">LOI DE 2006 SUR LES DROITS D’EXPORTATION DE PRODUITS DE BOIS D’OEUVRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-30"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-31"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-32"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">TARIF DES DOUANES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-33"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1645 - </span><a href="#h-34"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1646 - </span><a href="#h-35"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>1649 - </span><a href="#h-36"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">LOI SUR LE CONTRÔLE DES DÉPENSES</span></a>
</li>
<li><span class='sectionRange'>1650 - </span><a href="#h-37"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT DES ORGANISMES D’ÉTAT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="#h-38"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Modifications relatives à des nominations faites par le gouverneur en conseil</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="#h-39"><span class="HTitleText3">Loi de 1974 concernant la frontière entre l’Alberta et la Colombie-Britannique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="#h-40"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1653 - </span><a href="#h-41"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1654 - </span><a href="#h-42"><span class="HTitleText3">Loi sur la Fondation Asie-Pacifique du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1654 - </span><a href="#h-43"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1655 - </span><a href="#h-44"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1656 - </span><a href="#h-45"><span class="HTitleText3">Loi sur la procréation assistée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1656 - </span><a href="#h-46"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1657 - </span><a href="#h-47"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1658 - </span><a href="#h-48"><span class="HTitleText3">Loi d’exécution du budget de 1997</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1658 - </span><a href="#h-49"><span class="HTitleText4">Modification de la loi (Fondation canadienne pour l’innovation)</span></a>
</li>
<li><span class='sectionRange'>1659 - </span><a href="#h-50"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1660 - </span><a href="#h-51"><span class="HTitleText3">Loi sur la Banque de développement du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1660 - </span><a href="#h-52"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1661 - </span><a href="#h-53"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1662 - </span><a href="#h-54"><span class="HTitleText3">Loi sur les grains du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1662 - </span><a href="#h-55"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1664 - </span><a href="#h-56"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1665 - </span><a href="#h-57"><span class="HTitleText3">Loi sur la Société canadienne d’hypothèques et de logement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1665 - </span><a href="#h-58"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1667 - </span><a href="#h-59"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1668 - </span><a href="#h-60"><span class="HTitleText3">Régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1668 - </span><a href="#h-61"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1670 - </span><a href="#h-62"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1671 - </span><a href="#h-63"><span class="HTitleText3">Loi sur l’École de la fonction publique du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1671 - </span><a href="#h-64"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1674 - </span><a href="#h-65"><span class="HTitleText4">Modification connexe à la Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>1675 - </span><a href="#h-66"><span class="HTitleText4">Modifications connexes à la Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>1676 - </span><a href="#h-67"><span class="HTitleText4">Modification connexe à la Loi sur les langues officielles</span></a>
</li>
<li><span class='sectionRange'>1677 - </span><a href="#h-68"><span class="HTitleText4">Modification connexe à la Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>1678 - </span><a href="#h-69"><span class="HTitleText4">Modifications connexes à la Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</span></a>
</li>
<li><span class='sectionRange'>1683 - </span><a href="#h-70"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1684 - </span><a href="#h-71"><span class="HTitleText3">Loi sur le Centre canadien d’hygiène et de sécurité au travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1684 - </span><a href="#h-72"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1686 - </span><a href="#h-73"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1687 - </span><a href="#h-74"><span class="HTitleText3">Loi sur le Centre canadien de lutte contre les toxicomanies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1687 - </span><a href="#h-75"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1692 - </span><a href="#h-76"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1693 - </span><a href="#h-77"><span class="HTitleText3">Loi sur les Instituts de recherche en santé du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1693 - </span><a href="#h-78"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1694 - </span><a href="#h-79"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1695 - </span><a href="#h-80"><span class="HTitleText3">Loi sur le Tribunal canadien du commerce extérieur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1695 - </span><a href="#h-81"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1696 - </span><a href="#h-82"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1697 - </span><a href="#h-83"><span class="HTitleText3">Loi sur la Fondation canadienne des relations raciales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1697 - </span><a href="#h-84"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1699 - </span><a href="#h-85"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1700 - </span><a href="#h-86"><span class="HTitleText3">Loi sur le Conseil de la radiodiffusion et des télécommunications canadiennes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1700 - </span><a href="#h-87"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1710 - </span><a href="#h-88"><span class="HTitleText4">Modification corrélative à la Loi sur la radiodiffusion</span></a>
</li>
<li><span class='sectionRange'>1711 - </span><a href="#h-89"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1712 - </span><a href="#h-90"><span class="HTitleText3">Loi sur l’Agence spatiale canadienne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1712 - </span><a href="#h-91"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1716 - </span><a href="#h-92"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1717 - </span><a href="#h-93"><span class="HTitleText3">Loi sur la Commission canadienne du tourisme</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1717 - </span><a href="#h-94"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1722 - </span><a href="#h-95"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1723 - </span><a href="#h-96"><span class="HTitleText3">Loi sur le ministère des Ressources humaines et du Développement des compétences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1723 - </span><a href="#h-97"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1724 - </span><a href="#h-98"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1725 - </span><a href="#h-99"><span class="HTitleText3">Loi d’urgence sur les approvisionnements d’énergie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1725 - </span><a href="#h-100"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1728 - </span><a href="#h-101"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1729 - </span><a href="#h-102"><span class="HTitleText3">Loi sur le développement des exportations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1729 - </span><a href="#h-103"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1730 - </span><a href="#h-104"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1731 - </span><a href="#h-105"><span class="HTitleText3">Loi sur les offices des produits agricoles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1731 - </span><a href="#h-106"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1732 - </span><a href="#h-107"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1733 - </span><a href="#h-108"><span class="HTitleText3">Loi sur la gestion financière et statistique des premières nations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1733 - </span><a href="#h-109"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1737 - </span><a href="#h-110"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1738 - </span><a href="#h-111"><span class="HTitleText3">Loi sur la commercialisation du poisson d’eau douce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1738 - </span><a href="#h-112"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1739 - </span><a href="#h-113"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1740 - </span><a href="#h-114"><span class="HTitleText3">Loi sur les lieux et monuments historiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1740 - </span><a href="#h-115"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1742 - </span><a href="#h-116"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1743 - </span><a href="#h-117"><span class="HTitleText3">Loi sur la Commission frontalière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1743 - </span><a href="#h-118"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1745 - </span><a href="#h-119"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1746 - </span><a href="#h-120"><span class="HTitleText3">Loi sur le Centre de recherches pour le développement international</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1746 - </span><a href="#h-121"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1754 - </span><a href="#h-122"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1755 - </span><a href="#h-123"><span class="HTitleText3">Loi sur la défense nationale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1755 - </span><a href="#h-124"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1756 - </span><a href="#h-125"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1757 - </span><a href="#h-126"><span class="HTitleText3">Loi sur le Conseil national de recherches</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1757 - </span><a href="#h-127"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1758 - </span><a href="#h-128"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1759 - </span><a href="#h-129"><span class="HTitleText3">Loi sur la Table ronde nationale sur l’environnement et l’économie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1759 - </span><a href="#h-130"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1760 - </span><a href="#h-131"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1761 - </span><a href="#h-132"><span class="HTitleText3">Loi sur le Conseil de recherches en sciences naturelles et en génie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1761 - </span><a href="#h-133"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1762 - </span><a href="#h-134"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1763 - </span><a href="#h-135"><span class="HTitleText3">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1763 - </span><a href="#h-136"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1764 - </span><a href="#h-137"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1765 - </span><a href="#h-138"><span class="HTitleText3">Loi sur la Commission du parc international Roosevelt de Campobello</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1765 - </span><a href="#h-139"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1766 - </span><a href="#h-140"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1767 - </span><a href="#h-141"><span class="HTitleText3">Loi sur le Conseil de recherches en sciences humaines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1767 - </span><a href="#h-142"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1768 - </span><a href="#h-143"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1769 - </span><a href="#h-144"><span class="HTitleText3">Loi sur le Conseil canadien des normes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1769 - </span><a href="#h-145"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1773 - </span><a href="#h-146"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1774 - </span><a href="#h-147"><span class="HTitleText3">Loi sur le statut de l’artiste</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1774 - </span><a href="#h-148"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1775 - </span><a href="#h-149"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1776 - </span><a href="#h-150"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Loi de mise en oeuvre de l’Accord de libre-échange nord-américain</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1776 - </span><a href="#h-151"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1778 - </span><a href="#h-152"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>1779 - </span><a href="#h-153"><span class="HTitleText3">Modifications corrélatives à la Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>1782 - </span><a href="#h-154"><span class="HTitleText3">Modification corrélative à la Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>1783 - </span><a href="#h-155"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1784 - </span><a href="#h-156"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Loi de la caisse de prévoyance des employés des chemins de fer Intercolonial et de l’Ile-du-Prince-Edouard</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1784 - </span><a href="#h-157"><span class="HTitleText3">Abrogation de la loi</span></a>
</li>
<li><span class='sectionRange'>1785 - </span><a href="#h-158"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1786 - </span><a href="#h-159"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">LOI DE 1985 SUR LES NORMES DE PRESTATION DE PENSION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1786 - </span><a href="#h-160"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1826 - </span><a href="#h-161"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>1827 - </span><a href="#h-162"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1828 - </span><a href="#h-163"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">ENTRÉE EN VIGUEUR RÉTROACTIVE DE L’ACCORD SUR LA SÉCURITÉ SOCIALE ENTRE LE CANADA ET LA RÉPUBLIQUE DE POLOGNE</span></a>
</li>
<li><span class='sectionRange'>1831 - </span><a href="#h-164"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">LOI SUR LE DÉVELOPPEMENT DES EXPORTATIONS</span></a>
</li>
<li><span class='sectionRange'>1834 - </span><a href="#h-165"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">RÉSEAUX DE CARTES DE PAIEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1834 - </span><a href="#h-166"><span class="HTitleText2">Édiction de la Loi sur les réseaux de cartes de paiement</span></a>
</li>
<li><span class='sectionRange'>1835 - </span><a href="#h-167"><span class="HTitleText2">Modifications connexes à la Loi sur l’Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>1850 - </span><a href="#h-168"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1851 - </span><a href="#h-169"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">LOI SUR L’AGENCE DE LA CONSOMMATION EN MATIÈRE FINANCIÈRE DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1851 - </span><a href="#h-170"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1858 - </span><a href="#h-171"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1858 - </span><a href="#h-172"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>1859 - </span><a href="#h-173"><span class="HTitleText3">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>1860 - </span><a href="#h-174"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>1861 - </span><a href="#h-175"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1862 - </span><a href="#h-176"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">LOI SUR LE RECYCLAGE DES PRODUITS DE LA CRIMINALITÉ ET LE FINANCEMENT DES ACTIVITÉS TERRORISTES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1862 - </span><a href="#h-177"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1883 - </span><a href="#h-178"><span class="HTitleText2">Modification corrélative à la Loi sur le Bureau du surintendant des institutions financières</span></a>
</li>
<li><span class='sectionRange'>1884 - </span><a href="#h-179"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1885 - </span><a href="#h-180"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">LOI SUR LA SOCIÉTÉ CANADIENNE DES POSTES</span></a>
</li>
<li><span class='sectionRange'>1886 - </span><a href="#h-181"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">LOI SUR LA SOCIÉTÉ D’ASSURANCE-DÉPÔTS DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1886 - </span><a href="#h-182"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>1893 - </span><a href="#h-183"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>1894 - </span><a href="#h-184"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">COOPÉRATIVES DE CRÉDIT FÉDÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1894 - </span><a href="#h-185"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>2094 - </span><a href="#h-186"><span class="HTitleText2">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>2108 - </span><a href="#h-187"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>2110 - </span><a href="#h-188"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2110 - </span><a href="#h-189"><span class="HTitleText3">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>2113 - </span><a href="#h-190"><span class="HTitleText3">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>2114 - </span><a href="#h-191"><span class="HTitleText3">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>2116 - </span><a href="#h-192"><span class="HTitleText3">Loi sur l’Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>2117 - </span><a href="#h-193"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>2122 - </span><a href="#h-194"><span class="HTitleText3">Loi sur le Bureau du surintendant des institutions financières</span></a>
</li>
<li><span class='sectionRange'>2123 - </span><a href="#h-195"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>2126 - </span><a href="#h-196"><span class="HTitleText3">Loi sur les liquidations et les restructurations</span></a>
</li></ul>
</li><li><span class='sectionRange'>2135 - </span><a href="#h-197"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>2136 - </span><a href="#h-198"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>2137 - </span><a href="#h-199"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">ÉNERGIE ATOMIQUE DU CANADA LIMITÉE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2137 - </span><a href="#h-200"><span class="HTitleText2">Réorganisation et dessaisissement</span></a>
</li>
<li><span class='sectionRange'>2147 - </span><a href="#h-201"><span class="HTitleText2">Loi sur l’énergie nucléaire</span></a>
</li>
<li><span class='sectionRange'>2148 - </span><a href="#h-202"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>2149 - </span><a href="#h-203"><span class="HLabel1">PARTIE 19</span> - <span class="HTitleText1">PROGRAMMES D’AIDE FINANCIÈRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2149 - </span><a href="#h-204"><span class="HTitleText2">Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>2150 - </span><a href="#h-205"><span class="HTitleText2">Loi sur la sûreté et la réglementation nucléaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>2152 - </span><a href="#h-206"><span class="HLabel1">PARTIE 20</span> - <span class="HTitleText1">ÉVALUATION ENVIRONNEMENTALE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2152 - </span><a href="#h-207"><span class="HTitleText2">Loi canadienne sur l’évaluation environnementale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2152 - </span><a href="#h-208"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>2162 - </span><a href="#h-209"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>2164 - </span><a href="#h-210"><span class="HTitleText2">Règlement de 2007 sur la liste d’exclusion</span></a>
</li>
<li><span class='sectionRange'>2167 - </span><a href="#h-211"><span class="HTitleText2">Règlement modifiant le Règlement de 2007 sur la liste d’exclusion</span></a>
</li>
<li><span class='sectionRange'>2171 - </span><a href="#h-212"><span class="HTitleText2">Règlement visant à adapter le processus d’évaluation environnementale des projets d’infrastructure</span></a>
</li></ul>
</li><li><span class='sectionRange'>2172 - </span><a href="#h-213"><span class="HLabel1">PARTIE 21</span> - <span class="HTitleText1">CODE CANADIEN DU TRAVAIL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2172 - </span><a href="#h-214"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>2178 - </span><a href="#h-215"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>2179 - </span><a href="#h-216"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>2180 - </span><a href="#h-217"><span class="HLabel1">PARTIE 22</span> - <span class="HTitleText1">PAIEMENTS À CERTAINES ENTITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2180 - </span><a href="#h-218"><span class="HTitleText2">Fondation canadienne des jeunes entrepreneurs</span></a>
</li>
<li><span class='sectionRange'>2181 - </span><a href="#h-219"><span class="HTitleText2">Génome Canada</span></a>
</li>
<li><span class='sectionRange'>2182 - </span><a href="#h-220"><span class="HTitleText2">Passeport pour ma réussite Canada</span></a>
</li>
<li><span class='sectionRange'>2183 - </span><a href="#h-221"><span class="HTitleText2">Fondation Rick Hansen</span></a>
</li></ul>
</li><li><span class='sectionRange'>2184 - </span><a href="#h-222"><span class="HLabel1">PARTIE 23</span> - <span class="HTitleText1">LOI SUR LES TÉLÉCOMMUNICATIONS</span></a>
</li>
<li><span class='sectionRange'>2185 - </span><a href="#h-223"><span class="HLabel1">PARTIE 24</span> - <span class="HTitleText1">FINANCEMENT DE L’ASSURANCE-EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2185 - </span><a href="#h-224"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2185 - </span><a href="#h-225"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>2195 - </span><a href="#h-226"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>2201 - </span><a href="#h-227"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2201 - </span><a href="#h-228"><span class="HTitleText4">Loi sur le ministère des Ressources humaines et du Développement des compétences</span></a>
</li>
<li><span class='sectionRange'>2202 - </span><a href="#h-229"><span class="HTitleText4">Règlement sur l’assurance-emploi</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>2204 - </span><a href="#h-230"><span class="HTitleText2">Loi d’exécution du budget de 2008</span></a>
</li>
<li><span class='sectionRange'>2207 - </span><a href="#h-231"><span class="HTitleText2">Loi sur l’Office de financement de l’assurance-emploi du Canada</span></a>
</li>
<li><span class='sectionRange'>2208 - </span><a href="#h-232"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-233"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-234"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-235"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

