<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 1 sur le plan d’action économique de 2015</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI DE L’IMPÔT SUR LE REVENU</cite> ET DE TEXTES CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur le Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-5.html#h-6"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la rémunération assurable et la perception des cotisations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-5.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">SOUTIEN AUX FAMILLES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-5.html#h-8"><span class="HLabel2">Section 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-6.html#h-9"><span class="HLabel2">Section 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la prestation universelle pour la garde d’enfants</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-6.html#h-10"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-6.html#h-11"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi sur les allocations spéciales pour enfants</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-12"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-6.html#h-13"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DIVERSES MESURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-6.html#h-14"><span class="HLabel2">Section 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi fédérale sur l’équilibre budgétaire</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-6.html#h-15"><span class="HTitleText3">Édiction de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-7.html#h-16"><span class="HLabel2">Section 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la prévention des voyages de terroristes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-7.html#h-17"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-7.html#h-18"><span class="HTitleText3">Modification connexe à la <cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-7.html#h-19"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Propriété intellectuelle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-7.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les dessins industriels</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-8.html#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-9.html#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-9.html#h-23"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-10.html#h-24"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-10.html#h-25"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Congé et prestations de soignant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="page-10.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-10.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-10.html#h-28"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-10.html#h-29"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="page-11.html#h-30"><span class="HLabel2">Section 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit d’auteur</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-11.html#h-31"><span class="HLabel2">Section 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="page-11.html#h-32"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-11.html#h-33"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-11.html#h-34"><span class="HLabel2">Section 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-11.html#h-35"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-12.html#h-36"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-12.html#h-37"><span class="HLabel2">Section 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations de retraite des parlementaires</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-12.html#h-38"><span class="HLabel2">Section 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office national de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-12.html#h-39"><span class="HLabel2">Section 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-12.html#h-40"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-12.html#h-41"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-14.html#h-42"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="page-14.html#h-43"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-14.html#h-44"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-14.html#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-14.html#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-15.html#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-15.html#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-15.html#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-15.html#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-16.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-16.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-16.html#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-16.html#h-54"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-16.html#h-55"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le contrôle des dépenses</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-16.html#h-56"><span class="HLabel2">Section 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="page-16.html#h-57"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-16.html#h-58"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-16.html#h-59"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-16.html#h-60"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la modernisation de certains régimes d’avantages et d’obligations</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-16.html#h-61"><span class="HTitleText4"><cite class="XRefExternalAct">Loi d’exécution du budget de 2000</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="page-16.html#h-62"><span class="HLabel2">Section 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le financement des petites entreprises du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-17.html#h-63"><span class="HLabel2">Section 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels et les documents électroniques</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-17.html#h-64"><span class="HLabel2">Section 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-17.html#h-65"><span class="HLabel2">Section 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="page-17.html#h-66"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-18.html#h-67"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="page-18.html#h-68"><span class="HLabel2">Section 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion financière des premières nations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="page-18.html#h-69"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="page-20.html#h-70"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="page-20.html#h-71"><span class="HLabel2">Section 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="page-20.html#h-72"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-22.html#h-73"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-22.html#h-74"><span class="HTitleText3">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-22.html#h-75"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>230 - </span><a href="page-22.html#h-76"><span class="HLabel2">Section 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’abolition du registre des armes d’épaule</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-22.html#h-77"><span class="HLabel2">Section 19</span> - <span class="HTitleText2">Protection de renseignements relatifs à la supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="page-22.html#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-23.html#h-79"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="page-23.html#h-80"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-24.html#h-81"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-24.html#h-82"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>253 - </span><a href="page-24.html#h-83"><span class="HLabel2">Section 20</span> - <span class="HTitleText2">Congés de maladie et programmes d’invalidité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>253 - </span><a href="page-24.html#h-84"><span class="HTitleText3">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-25.html#h-85"><span class="HTitleText3">Congés de maladie</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-25.html#h-86"><span class="HTitleText3">Programme d’invalidité de courte durée</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="page-25.html#h-87"><span class="HTitleText3">Programmes d’invalidité de longue durée</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="page-26.html#h-88"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-27.html#h-89"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-28.html#h-90"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

