<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi de l’impôt sur le revenu (programmes sportifs et récréatifs)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li></ul>
</li></ul>

</nav>

