<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la certitude des titres fonciers des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LE DÉVELOPPEMENT COMMERCIAL ET INDUSTRIEL DES PREMIÈRES NATIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-3"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI SUR L’ARPENTAGE DES TERRES DU CANADA</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

