<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la modernisation des élections</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="page-50.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>379 - </span><a href="page-50.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="page-50.html#h-5"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>391 - </span><a href="page-51.html#h-6"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>391 - </span><a href="page-51.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="page-51.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la révision des limites des circonscriptions électorales</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="page-51.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="page-51.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le directeur des poursuites pénales</cite></span></a>
</li>
<li><span class='sectionRange'>398 - </span><a href="page-51.html#h-11"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règles électorales spéciales</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>399 - </span><a href="page-51.html#h-12"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>401 - </span><a href="page-52.html#h-13"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-53.html#h-14"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

