<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant le soutien aux aînés vulnérables et le renforcement de l’économie canadienne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET D’UNE LOI ET D’UN RÈGLEMENT CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Loi canadienne sur l’épargne-invalidité</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Règlement sur l’épargne-invalidité</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-2.html#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MESURES RELATIVES AUX DROITS D’ACCISE ET AUX TAXES DE VENTE ET D’ACCISE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-9"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI SUR LA SÉCURITÉ DE LA VIEILLESSE</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-3.html#h-10"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">PAIEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Génome Canada</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Fondation canadienne des jeunes entrepreneurs</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-3.html#h-13"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI SUR LE VÉRIFICATEUR GÉNÉRAL</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-14"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI FÉDÉRALE SUR L’AIDE FINANCIÈRE AUX ÉTUDIANTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-3.html#h-17"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">ASSURANCE HYPOTHÉCAIRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Édiction de la Loi sur la protection de l’assurance hypothécaire résidentielle</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-4.html#h-20"><span class="HTitleText3">Loi d’exécution du budget de 2006</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-21"><span class="HTitleText3">Loi nationale sur l’habitation</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-22"><span class="HTitleText3">Loi sur le Bureau du surintendant des institutions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-4.html#h-23"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-4.html#h-24"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-25"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">LOI SUR LES SOCIÉTÉS D’ASSURANCES</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-26"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">RÈGLEMENT DE 2001 SUR LES COTISATIONS DES INSTITUTIONS FINANCIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="page-4.html#h-27"><span class="HTitleText2">Modification du règlement</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-28"><span class="HTitleText2">Validation</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-4.html#h-29"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-4.html#h-30"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-5.html#h-31"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-5.html#h-32"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">LOI DE 2001 SUR LA MARINE MARCHANDE DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-5.html#h-33"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-34"><span class="HTitleText2">Modification corrélative à la Loi sur le cabotage</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

