<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Système de justice pénale pour les adolescents, Loi sur le</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-3"><span class="HTitleText1">DÉCLARATION DE PRINCIPES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MESURES EXTRAJUDICIAIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Principes et objectifs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Avertissements, mises en garde et renvois</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Sanctions extrajudiciaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-8"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">ORGANISATION DU SYSTÈME DE JUSTICE PÉNALE POUR LES ADOLESCENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Tribunal pour adolescents</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Comités de justice pour la jeunesse</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Groupes consultatifs</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Juges de paix</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-13"><span class="HTitleText2">Greffier du tribunal pour adolescents</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Directeurs provinciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-4.html#h-15"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">PROCÉDURES JUDICIAIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Consentement préalable du procureur général</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Droit aux services d’un avocat</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Avis aux père et mère</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-5.html#h-19"><span class="HTitleText2">Détention avant le prononcé de la peine</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Comparution</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-6.html#h-21"><span class="HTitleText2">Mise en liberté ou détention sous garde</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-6.html#h-22"><span class="HTitleText2">Rapports médicaux et psychologiques</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Renvoi à un organisme de protection de la jeunesse</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-6.html#h-24"><span class="HTitleText2">Jugement</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-7.html#h-25"><span class="HTitleText2">Appels</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-7.html#h-26"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">DÉTERMINATION DE LA PEINE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="page-7.html#h-27"><span class="HTitleText2">Objectif et principes</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Rapport prédécisionnel</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-8.html#h-29"><span class="HTitleText2">Peines spécifiques</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-11.html#h-30"><span class="HTitleText2">Peine applicable aux adultes et choix de la procédure</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-14.html#h-31"><span class="HTitleText2">Conséquences de la cessation d’effet des peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="page-14.html#h-32"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">GARDE ET SURVEILLANCE</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-19.html#h-33"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">DOSSIERS ET CONFIDENTIALITÉ DES RENSEIGNEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-19.html#h-34"><span class="HTitleText2">Protection de la vie privée des adolescents</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-19.html#h-35"><span class="HTitleText2">Empreintes digitales et photographies</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-19.html#h-36"><span class="HTitleText2">Dossiers</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-20.html#h-37"><span class="HTitleText2">Accès aux dossiers</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-21.html#h-38"><span class="HTitleText2">Communication des renseignements contenus dans les dossiers</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-22.html#h-39"><span class="HTitleText2">Destruction des dossiers et interdiction d’utilisation ou d’accès</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="page-22.html#h-40"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="page-22.html#h-41"><span class="HTitleText2">Dessaisissement du juge</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-22.html#h-42"><span class="HTitleText2">Remplacement de juges</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-22.html#h-43"><span class="HTitleText2">Pouvoir d’exclusion</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-22.html#h-44"><span class="HTitleText2">Transfert de compétence</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-22.html#h-45"><span class="HTitleText2">Confiscation du montant des engagements</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-23.html#h-46"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-23.html#h-47"><span class="HTitleText2">Application du Code criminel</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-24.html#h-48"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-24.html#h-49"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-25.html#h-50"><span class="HTitleText2">Formules, règlements et règles de fonctionnement</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-25.html#h-51"><span class="HTitleText2">Accord avec les provinces</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-25.html#h-52"><span class="HTitleText2">Programmes</span></a>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="page-25.html#h-53"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-26.html#h-54"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">MODIFICATIONS CORRÉLATIVES, ABROGATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="page-26.html#h-55"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="page-26.html#h-56"><span class="HTitleText3">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-26.html#h-57"><span class="HTitleText3">Loi sur les contraventions</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-26.html#h-58"><span class="HTitleText3">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-26.html#h-59"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-27.html#h-60"><span class="HTitleText3">Loi sur l’identification par les empreintes génétiques</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-28.html#h-61"><span class="HTitleText3">Loi sur l’extradition</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-28.html#h-62"><span class="HTitleText3">Loi sur l’entraide juridique en matière criminelle</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-28.html#h-63"><span class="HTitleText3">Loi sur les prisons et les maisons de correction</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-29.html#h-64"><span class="HTitleText3">Loi sur le transfèrement des délinquants</span></a>
</li></ul>
</li><li><span class='sectionRange'>199 - </span><a href="page-29.html#h-65"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-29.html#h-66"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-30.html#h-67"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

