<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur l’immigration et la protection des réfugiés (certificat et avocat spécial) et une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-2"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-3"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI SUR LA PREUVE AU CANADA</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

