<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi électorale du Canada et la Loi sur l’emploi dans la fonction publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI ÉLECTORALE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-2"><span class="HTitleText1">LOI SUR L’EMPLOI DANS LA FONCTION PUBLIQUE</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

