<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la santé et la sécurité dans la zone extracôtière</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI DE MISE EN OEUVRE DE L’ACCORD ATLANTIQUE CANADA — TERRE-NEUVE</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-7.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI DE MISE EN OEUVRE DE L’ACCORD CANADA — NOUVELLE-ÉCOSSE SUR LES HYDROCARBURES EXTRACÔTIERS</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-12.html#h-5"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-12.html#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CANADIEN DU TRAVAIL</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-13.html#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’ACCÈS À L’INFORMATION</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-13.html#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA TAXE D’ACCISE</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-13.html#h-9"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES OPÉRATIONS PÉTROLIÈRES AU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-13.html#h-10"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA PROTECTION DES RENSEIGNEMENTS PERSONNELS</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-13.html#h-11"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE CONTRÔLE DES RENSEIGNEMENTS RELATIFS AUX MATIÈRES DANGEREUSES</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-14.html#h-12"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’EXPLOITATION DU CHAMP HIBERNIA</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-14.html#h-13"><span class="HTitleText1"><cite class="XRefExternalRegulation">RÈGLEMENT DÉTERMINANT DES AUTORITÉS FÉDÉRALES</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-14.html#h-14"><span class="HTitleText1">TERMINOLOGIE</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-15.html#h-15"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-15.html#h-16"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

