<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi d’harmonisation n<Sup>o</Sup> 2 du droit fédéral avec le droit civil</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE CERTAINES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Loi sur la généalogie des animaux</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText2">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-6"><span class="HTitleText2">Loi sur le Conseil des Arts du Canada</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-7"><span class="HTitleText2">Loi sur les grains du Canada</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-8"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-9"><span class="HTitleText2">Loi sur les espèces sauvages du Canada</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-10"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-11"><span class="HTitleText2">Loi sur la production de défense</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-12"><span class="HTitleText2">Loi sur le ministère de l’Industrie</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-13"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-14"><span class="HTitleText2">Loi d’urgence sur les approvisionnements d’énergie</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-15"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-16"><span class="HTitleText2">Loi sur les explosifs</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-17"><span class="HTitleText2">Loi sur les offices des produits agricoles</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-18"><span class="HTitleText2">Loi sur la Commission du droit du Canada</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-19"><span class="HTitleText2">Loi sur la Fondation Jules et Paul-Émile Léger</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-20"><span class="HTitleText2">Loi sur le Centre national des Arts</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-21"><span class="HTitleText2">Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-22"><span class="HTitleText2">Loi sur le Conseil national de recherches</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-23"><span class="HTitleText2">Loi sur le Conseil de recherches en sciences naturelles et en génie</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-24"><span class="HTitleText2">Loi sur l’indemnisation du dommage causé par des pesticides</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-25"><span class="HTitleText2">Loi sur le Conseil de recherches en sciences humaines</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-26"><span class="HTitleText2">Loi sur l’immunité des États</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-27"><span class="HTitleText2">Loi sur les télécommunications</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-28"><span class="HTitleText2">Loi sur les forces étrangères présentes au Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 - </span><a href="#h-29"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 - </span><a href="#h-30"><span class="HTitleText2">Loi sur le paiement anticipé des récoltes</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-31"><span class="HTitleText2">Loi sur les programmes de commercialisation agricole</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-32"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-33"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-34"><span class="HTitleText2">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-35"><span class="HTitleText2">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-36"><span class="HTitleText2">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-37"><span class="HTitleText2">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-38"><span class="HTitleText2">Loi canadienne sur les paiements</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-39"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-40"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-41"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-42"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-43"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-44"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-45"><span class="HTitleText2">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-46"><span class="HTitleText2">Loi sur les paiements anticipés pour le grain des Prairies</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-47"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>205 - </span><a href="#h-48"><span class="HTitleText2">Loi d’harmonisation n<sup>o</sup> 2 du droit fédéral avec le droit civil</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-49"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-50"><span class="HTitleText2">Loi sur les grains du Canada</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-51"><span class="HTitleText2">Loi sur les explosifs</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

