<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Aires marines nationales de conservation du Canada, Loi sur les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">AIRES MARINES DE CONSERVATION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">ADMINISTRATION</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">APPLICATION DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-10"><span class="HTitleText1">ATTÉNUATION DES DOMMAGES À L’ENVIRONNEMENT</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-11"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère du Patrimoine canadien</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence Parcs Canada</cite></span></a>
</li></ul>
</li><li><a href="#h-15"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - AIRES MARINES DE CONSERVATION</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - RÉSERVES</span></a>
</li></ul>
</li></ul>

</nav>

