<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à accroître la responsabilité de la Gendarmerie royale du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA GENDARMERIE ROYALE DU CANADA</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-7.html#h-4"><span class="HTitleText2">Modifications connexes et corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-7.html#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-7.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-7.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de l’information</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-7.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-7.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-8.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les conflits d’intérêts</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-8.html#h-14"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-9.html#h-15"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>86 - </span><a href="page-11.html#h-16"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">PERSONNES RÉPUTÉES NOMMÉES EN VERTU DE LA <cite class="XRefExternalAct">LOI SUR L’EMPLOI DANS LA FONCTION PUBLIQUE</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-11.html#h-17"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

