<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la non-discrimination génétique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-6"><span class="HTitleText1">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-7"><span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

