<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en oeuvre de l’Accord de libre-échange Canada-Colombie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText1">DROIT DE POURSUITE</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MISE EN OEUVRE DE L’ACCORD ET DES ACCORDS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Approbation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Groupes spéciaux, comités, sous-comités et groupes de travail</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Décrets</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Rapport</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-12"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-13"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Loi sur l’arbitrage commercial</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-15"><span class="HTitleText2">Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-16"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Loi sur le ministère des Ressources humaines et du Développement des compétences</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Loi sur les licences d’exportation et d’importation</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-5.html#h-21"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-6.html#h-22"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-7.html#h-23"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

