<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la représentation équitable</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI CONSTITUTIONNELLE DE 1867</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA RÉVISION DES LIMITES DES CIRCONSCRIPTIONS ÉLECTORALES</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI ÉLECTORALE DU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITION INTERPRÉTATIVE</span></a>
</li></ul>
</li></ul>

</nav>

