<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi d’exécution du budget de 1997 et la Loi sur la gestion des finances publiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI D’EXÉCUTION DU BUDGET DE 1997</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
</li></ul>
</li></ul>

</nav>

