<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi canadienne sur les droits de la personne (protection des libertés)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI CANADIENNE SUR LES DROITS DE LA PERSONNE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

