<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Propositions présentées en vue de la Loi corrective de 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">PARTIE 1 - MODIFICATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Loi sur l’aéronautique</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Loi sur les produits agricoles au Canada</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Loi maritime du Canada</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Loi sur les parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Loi canadienne sur les organisations à but non lucratif</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Loi de 2001 sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Loi de mise en oeuvre de la Convention sur les armes chimiques</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Loi sur le cabotage</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-21"><span class="HTitleText2">Loi sur la concurrence</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-22"><span class="HTitleText2">Loi sur l’emballage et l’étiquetage des produits de consommation</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-23"><span class="HTitleText2">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-6.html#h-25"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-26"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-27"><span class="HTitleText2">Loi sur la production de défense</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Loi sur le ministère des Anciens Combattants</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-29"><span class="HTitleText2">Loi sur le divorce</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-30"><span class="HTitleText2">Loi sur l’Agence de développement économique du Canada pour les régions du Québec</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-7.html#h-31"><span class="HTitleText2">Loi sur la révision des limites des circonscriptions électorales</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-7.html#h-32"><span class="HTitleText2">Loi sur l’inspection de l’électricité et du gaz</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-33"><span class="HTitleText2">Loi sur les explosifs</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-8.html#h-34"><span class="HTitleText2">Loi sur les offices des produits agricoles</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-9.html#h-35"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-9.html#h-36"><span class="HTitleText2">Loi sur les pêches</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-9.html#h-37"><span class="HTitleText2">Loi sur l’équité entre les sexes relativement à l’inscription au registre des Indiens</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-9.html#h-38"><span class="HTitleText2">Loi sur l’indemnisation des agents de l’État</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-9.html#h-39"><span class="HTitleText2">Loi sur la santé des animaux</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-10.html#h-40"><span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-10.html#h-41"><span class="HTitleText2">Loi sur les Indiens</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-11.html#h-42"><span class="HTitleText2">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-11.html#h-43"><span class="HTitleText2">Loi sur les ponts et tunnels internationaux</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-11.html#h-44"><span class="HTitleText2">Loi d’interprétation</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-11.html#h-45"><span class="HTitleText2">Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-12.html#h-46"><span class="HTitleText2">Loi sur la réédiction de textes législatifs</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Loi sur la Bibliothèque et les Archives du Canada</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-12.html#h-48"><span class="HTitleText2">Loi sur l’inspection des viandes</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-12.html#h-49"><span class="HTitleText2">Loi sur l’indemnisation des marins marchands</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-12.html#h-50"><span class="HTitleText2">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-12.html#h-51"><span class="HTitleText2">Loi relative au supplément d’aide financière à Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-12.html#h-52"><span class="HTitleText2">Loi sur la sûreté et la réglementation nucléaires</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-12.html#h-53"><span class="HTitleText2">Loi sur les océans</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-12.html#h-54"><span class="HTitleText2">Loi sur les brevets</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-13.html#h-55"><span class="HTitleText2">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-13.html#h-56"><span class="HTitleText2">Loi sur l’activité physique et le sport</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-13.html#h-57"><span class="HTitleText2">Loi sur la protection des végétaux</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-13.html#h-58"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-13.html#h-59"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-14.html#h-60"><span class="HTitleText2">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-14.html#h-61"><span class="HTitleText2">Loi sur la sécurité ferroviaire</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-14.html#h-62"><span class="HTitleText2">Loi sur le parc marin du Saguenay — Saint-Laurent</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-14.html#h-63"><span class="HTitleText2">Loi sur l’administration des biens saisis</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-14.html#h-64"><span class="HTitleText2">Loi sur les espèces en péril</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-14.html#h-65"><span class="HTitleText2">Loi sur le tabac</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-14.html#h-66"><span class="HTitleText2">Loi de 1992 sur le transport des marchandises dangereuses</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-14.html#h-67"><span class="HTitleText2">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-14.html#h-68"><span class="HTitleText2">Loi sur le Tribunal des anciens combattants (révision et appel)</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-15.html#h-69"><span class="HTitleText2">Loi sur les forces étrangères présentes au Canada</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-16.html#h-70"><span class="HTitleText2">Loi sur les allocations aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-16.html#h-71"><span class="HTitleText2">Loi sur les liquidations et les restructurations</span></a>
</li>
</ul>
<li><span class='sectionRange'>174 - </span><a href="page-16.html#h-72"><span class="HTitleText1">PARTIE 2 - TERMINOLOGIE</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-16.html#h-73"><span class="HTitleText2">PARTIE 3 - DISPOSITIONS DE COORDINATION</span></a>
</li></ul></li></ul>


</nav>

