<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le chef du développement de la littératie financière</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR L’AGENCE DE LA CONSOMMATION EN MATIÈRE FINANCIÈRE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li></ul>
</li></ul>

</nav>

