<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la reprise et le maintien des services postaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Services postaux</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Prorogation des conventions collectives</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Médiateur-arbitre</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Nouvelles conventions collectives</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

