<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les grains du Canada et la Loi sur les transports au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES GRAINS DU CANADA</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES TRANSPORTS AU CANADA</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

