<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi relative à la stratégie nationale sur l’élimination sûre et écologique des lampes contenant du mercure</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Stratégie nationale</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Rapport d’examen</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

