<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi canadienne sur les droits de la personne et le Code criminel</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

