<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi canadienne sur la protection de l’environnement (1999)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI CANADIENNE SUR LA PROTECTION DE L’ENVIRONNEMENT (1999)</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-2"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

