<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la modernisation du droit d’auteur</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LE DROIT D’AUTEUR</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

