<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel et la Loi sur la défense nationale (recrutement : organisations criminelles)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA DÉFENSE NATIONALE</cite></span></a>
</li></ul>
</li></ul>

</nav>

