<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la reprise économique (mesures incitatives)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES À L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-4"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">DIVERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-6"><span class="HTitleText2">Paiements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-7"><span class="HTitleText3">Allègement — dette multilatérale</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText3">Paiement à la Nouvelle-Écosse — hydrocarbures extracôtiers</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText2">Loi sur les accords de Bretton Woods et des accords connexes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Loi sur la radiodiffusion</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText2">Loi d’exécution du budget de 2009</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-12"><span class="HTitleText2">Régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-13"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-14"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-15"><span class="HTitleText2">Loi sur l’Office d’investissement du régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-16"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-17"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText2">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-19"><span class="HTitleText2">Tarif des douanes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-20"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-21"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="#h-22"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-23"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-24"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-25"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-26"><span class="HTitleText2">Modifications relatives à la Loi sur la faillite et l’insolvabilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-27"><span class="HTitleText3">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-28"><span class="HTitleText3">Chapitre 36 des Lois du Canada (2007)</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-29"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

