<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les épaves et les bâtiments abandonnés ou dangereux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Attributions des ministres</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">Communication d’information</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Enlèvement des épaves</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText2">Dangers</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-11"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText2">Assurance ou autre garantie financière</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-13"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Bâtiments et épaves préoccupants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-14"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-15"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-16"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-17"><span class="HTitleText2">Prise de mesures</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-18"><span class="HTitleText2">Disposition d’un bâtiment, d’une épave ou du contenu de l’un ou de l’autre</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-19"><span class="HTitleText2">Indemnisation et responsabilité</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-20"><span class="HTitleText2">Dispositions diverses</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Assistance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-23"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-24"><span class="HTitleText2">Convention sur l’assistance</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-25"><span class="HTitleText2">Assistance au moyen de bâtiments appartenant à Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-26"><span class="HTitleText2">Prescription</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-27"><span class="HTitleText2">Aéronefs</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-28"><span class="HTitleText2">Droit des assistants</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-29"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Receveur d’épaves</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-30"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-31"><span class="HTitleText2">Désignation des receveurs d’épaves</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-32"><span class="HTitleText2">Découverte ou importation d’épaves</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-33"><span class="HTitleText2">Disposition des épaves</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-34"><span class="HTitleText2">Disposition générale</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="#h-35"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-36"><span class="HTitleText2">Mesures relatives aux dangers</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-37"><span class="HTitleText2">Désignation des agents de l’autorité</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-38"><span class="HTitleText2">Mesures relatives au respect de la loi</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-39"><span class="HTitleText2">Dispositions connexes à l’entrée dans des lieux</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-40"><span class="HTitleText2">Entrave</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-41"><span class="HTitleText2">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-42"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-43"><span class="HTitleText3">Transaction et procès-verbal</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-44"><span class="HTitleText3">Recouvrement des créances</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-45"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-46"><span class="HTitleText3">Registre public</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-47"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-48"><span class="HTitleText2">Infractions et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-49"><span class="HTitleText3">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-50"><span class="HTitleText3">Confiscation, rétention ou disposition</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-51"><span class="HTitleText3">Compétence</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-52"><span class="HTitleText2">Dénonciation</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-53"><span class="HTitleText2">Injonction</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-54"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-55"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-56"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Disposition transitoire et modifications connexes et corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-57"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-58"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-59"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les océans</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les aires marines nationales de conservation du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-61"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-62"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de la navigation</cite></span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-64"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-65"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-67"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Examen</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-68"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-69"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention internationale de Nairobi sur l’enlèvement des épaves, 2007</span></a>
</li>
<li><a href="#h-70"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Certificat d’assurance ou autre garantie financière relative à la responsabilité en cas d’enlèvement d’épaves</span></a>
</li>
<li><a href="#h-71"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Assistance</span></a>
</li></ul>
</li></ul>

</nav>

