<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 2008</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES À L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-4"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-5"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-6"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-6.html#h-7"><span class="HTitleText2">Modifications conditionnelles</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-6.html#h-8"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LE DROIT D’ACCISE SUR LES PRODUITS DU TABAC ET L’ALCOOL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-6.html#h-9"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-10"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="page-6.html#h-11"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-8.html#h-12"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="page-8.html#h-13"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="page-8.html#h-14"><span class="HTitleText3">Tarif des douanes</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="page-8.html#h-15"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE SUR LES PRODUITS ET SERVICES ET LA TAXE DE VENTE HARMONISÉE (TPS/TVH)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="page-8.html#h-16"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-12.html#h-17"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">FONDATION CANADIENNE DES BOURSES D’ÉTUDES DU MILLÉNAIRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94 - </span><a href="page-12.html#h-18"><span class="HTitleText2">Dissolution de la Fondation</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-12.html#h-19"><span class="HTitleText2">Modification de la Loi d’exécution du budget de 1998</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-12.html#h-20"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-12.html#h-21"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-12.html#h-22"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="page-12.html#h-23"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="page-12.html#h-24"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">AIDE FINANCIÈRE OFFERTE AUX ÉTUDIANTS PAR LE GOUVERNEMENT FÉDÉRAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="page-12.html#h-25"><span class="HTitleText2">Modification de la Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-13.html#h-26"><span class="HTitleText2">Modification de la Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-13.html#h-27"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="page-13.html#h-28"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="page-13.html#h-29"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-14.html#h-30"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="page-14.html#h-31"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">ASSURANCE-EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="page-14.html#h-32"><span class="HTitleText2">Loi sur l’Office de financement de l’assurance-emploi du Canada</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-15.html#h-33"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-15.html#h-34"><span class="HTitleText2">Modification de la Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-16.html#h-35"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="page-16.html#h-36"><span class="HTitleText3">Loi sur le ministère des Ressources humaines et du Développement des compétences</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-16.html#h-37"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="page-16.html#h-38"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-16.html#h-39"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">PAIEMENTS À DES PROVINCES ET À DES TERRITOIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="page-16.html#h-40"><span class="HTitleText2">Fonds de recrutement de policiers</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-16.html#h-41"><span class="HTitleText2">Fiducie pour l’infrastructure du transport en commun (2008)</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-16.html#h-42"><span class="HTitleText2">Paiement à la Saskatchewan — capture et stockage du dioxyde de carbone</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-16.html#h-43"><span class="HTitleText2">Paiement à la Nouvelle-Écosse — stockage du dioxyde de carbone</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-16.html#h-44"><span class="HTitleText2">Paiement transitoire à la Saskatchewan au titre du Transfert canadien en matière de programmes sociaux</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-16.html#h-45"><span class="HTitleText2">Paiement transitoire au Nunavut au titre du Transfert canadien en matière de programmes sociaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>142 - </span><a href="page-16.html#h-46"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">PAIEMENTS À CERTAINES ENTITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142 - </span><a href="page-16.html#h-47"><span class="HTitleText2">Génome Canada</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-16.html#h-48"><span class="HTitleText2">Commission de la santé mentale du Canada</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-16.html#h-49"><span class="HTitleText2">The Gairdner Foundation</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-16.html#h-50"><span class="HTitleText2"><span class="otherLang" lang="en">University of Calgary</span></span></a>
</li></ul>
</li><li><span class='sectionRange'>146 - </span><a href="page-16.html#h-51"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">MODIFICATIONS DIVERSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="page-16.html#h-52"><span class="HTitleText2">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-17.html#h-53"><span class="HTitleText2">Loi d’exécution du budget de 2006</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-17.html#h-54"><span class="HTitleText2">Loi sur la pension de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-17.html#h-55"><span class="HTitleText2">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-17.html#h-56"><span class="HTitleText2">Loi sur les possibilités de la mise en valeur de la réserve de charbon Donkin</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-17.html#h-57"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-17.html#h-58"><span class="HTitleText2">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-17.html#h-59"><span class="HTitleText2">Loi sur l’intérêt</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-18.html#h-60"><span class="HTitleText2">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-18.html#h-61"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-18.html#h-62"><span class="HTitleText2">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-18.html#h-63"><span class="HTitleText2">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-18.html#h-64"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

