<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Juges et d’autres lois liées aux tribunaux, Loi modifiant la Loi sur les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LES JUGES</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Loi sur les juges</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-3.html#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-3.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation du dommage causé par des pesticides</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Cour canadienne de l’impôt</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-4.html#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

