<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi canadienne sur la sécurité des produits de consommation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CHAMP D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-6"><span class="HTitleText1">ESSAIS, ÉTUDES ET COMPILATION DE RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-7"><span class="HTitleText1">TENUE DE DOCUMENTS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-8"><span class="HTitleText1">OBLIGATIONS EN CAS D’INCIDENT</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-9"><span class="HTitleText1">COMMUNICATION DE RENSEIGNEMENTS PAR LE MINISTRE</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-10"><span class="HTitleText1">INSPECTEURS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-11"><span class="HTitleText1">INSPECTION</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-12"><span class="HTitleText1">MESURES CONSÉCUTIVES À LA SAISIE</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-13"><span class="HTitleText1">ANALYSE</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-14"><span class="HTitleText1">ORDRES DE RAPPEL ET DE PRISE DE MESURES</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-15"><span class="HTitleText1">RÉVISION DES ORDRES DE RAPPEL ET DE PRISE DE MESURES</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-16"><span class="HTitleText1">INJONCTION</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-17"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-18"><span class="HTitleText1">ARRÊTÉS D’URGENCE</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-19"><span class="HTitleText1">INFRACTIONS</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-20"><span class="HTitleText1">SANCTIONS ADMINISTRATIVES PÉCUNIAIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Violation</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Pouvoirs du gouverneur en conseil et du ministre</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Ouverture de la procédure</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Sanctions</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-25"><span class="HTitleText2">Transactions</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-26"><span class="HTitleText2">Contestation devant le ministre</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Exécution des sanctions</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-29"><span class="HTitleText2">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-6.html#h-30"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-31"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES À LA LOI SUR LES PRODUITS DANGEREUX</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-32"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-8.html#h-33"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-9.html#h-34"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

