<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la salubrité des aliments au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-5"><span class="HTitleText1">ENREGISTREMENTS, LICENCES ET AGRÉMENTS</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-6"><span class="HTitleText1">EXÉCUTION ET CONTRÔLE D’APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Certificat</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Mesures relatives aux choses saisies</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Autres mesures</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Analyse</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="page-4.html#h-14"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Certificats d’exportation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Échantillons</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Propriété intellectuelle</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Restriction de responsabilité</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Conseil d’arbitrage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="page-5.html#h-25"><span class="HTitleText3">Composition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-5.html#h-26"><span class="HTitleText3">Président</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-5.html#h-27"><span class="HTitleText3">Indemnités et frais</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-5.html#h-28"><span class="HTitleText3">Personnel</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-5.html#h-29"><span class="HTitleText3">Mission</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-5.html#h-30"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="page-5.html#h-31"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-5.html#h-32"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-6.html#h-33"><span class="HTitleText1">ABROGATIONS</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-6.html#h-34"><span class="HTitleText1">MODIFICATIONS CONNEXES ET CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-6.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-6.html#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emballage et l’étiquetage des produits de consommation</cite></span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-6.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-6.html#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi relative aux aliments du bétail</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-7.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les engrais</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-7.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les semences</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-7.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-7.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la santé des animaux</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-7.html#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des végétaux</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-7.html#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les contraventions</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-7.html#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-8.html#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence canadienne d’inspection des aliments</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-8.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits antiparasitaires</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-8.html#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence des services frontaliers du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="page-8.html#h-49"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-8.html#h-50"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

