<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel, la Loi sur l’identification par les empreintes génétiques et la Loi sur la défense nationale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-4.html#h-2"><span class="HTitleText1">LOI SUR L’IDENTIFICATION PAR LES EMPREINTES GÉNÉTIQUES</span></a>
</li>
<li><span class='sectionRange'>23. (1) - </span><a href="page-5.html#h-3"><span class="HTitleText1">LOI SUR LA DÉFENSE NATIONALE</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="page-6.html#h-4"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-6.html#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

