<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel, la Loi sur le système de justice pénale pour les adolescents et d’autres lois et apportant des modifications corrélatives à certaines lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Code criminel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>354 - </span><a href="#h-3"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>361 - </span><a href="#h-4"><span class="HTitleText1">Loi sur le système de justice pénale pour les adolescents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>361 - </span><a href="#h-5"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>384 - </span><a href="#h-6"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>385 - </span><a href="#h-7"><span class="HTitleText1">Loi réglementant certaines drogues et autres substances</span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="#h-8"><span class="HTitleText1">Loi modifiant le Code criminel (exploitation et traite de personnes)</span></a>
</li>
<li><span class='sectionRange'>387 - </span><a href="#h-9"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>387 - </span><a href="#h-10"><span class="HTitleText2">Loi sur la concurrence</span></a>
</li>
<li><span class='sectionRange'>388 - </span><a href="#h-11"><span class="HTitleText2">Loi sur l’identification des criminels</span></a>
</li>
<li><span class='sectionRange'>389 - </span><a href="#h-12"><span class="HTitleText2">Loi sur le Parlement du Canada</span></a>
</li>
<li><span class='sectionRange'>391 - </span><a href="#h-13"><span class="HTitleText2">Loi sur la Cour suprême</span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="#h-14"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-15"><span class="HTitleText2">Loi sur l’entraide juridique en matière criminelle</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-16"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="#h-17"><span class="HTitleText2">Loi sur les contraventions</span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="#h-18"><span class="HTitleText2">Loi sur les crimes contre l’humanité et les crimes de guerre</span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="#h-19"><span class="HTitleText2">Loi sur les espèces en péril</span></a>
</li>
<li><span class='sectionRange'>400.1 - </span><a href="#h-20"><span class="HTitleText2">Loi sur le cannabis</span></a>
</li></ul>
</li><li><span class='sectionRange'>401 - </span><a href="#h-21"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>405 - </span><a href="#h-22"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

