<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 sur le plan d’action économique de 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET D’UN TEXTE CONNEXE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-4"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>92 - </span><a href="#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA TAXE D’ACCISE (MESURES RELATIVES À LA TPS/TVH) ET D’UN TEXTE CONNEXE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-6"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-7"><span class="HTitleText2">Règlement sur la méthode d’attribution applicable aux institutions financières désignées particulières (TPS/TVH)</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-8"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI DE 2001 SUR L’ACCISE</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-9"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">DIVERSES MESURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-10"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Propriété intellectuelle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les dessins industriels</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-12"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-13"><span class="HTitleText4">Modification corrélative à la <cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-15"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="#h-16"><span class="HLabel2">Section 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-17"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Loi sur la Station canadienne de recherche dans l’Extrême-Arctique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="#h-18"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-19"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-20"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-21"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-22"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-23"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="#h-25"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-26"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="#h-27"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-28"><span class="HLabel2">Section 5</span> - <span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-29"><span class="HLabel2">Section 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-30"><span class="HLabel2">Section 7</span> - <span class="HTitleText2">Loi sur les fonds renouvelables</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-31"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-32"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-33"><span class="HLabel2">Section 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Monnaie royale canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-34"><span class="HLabel2">Section 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>186 - </span><a href="#h-35"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-36"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-37"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="#h-38"><span class="HLabel2">Section 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la radiodiffusion</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-39"><span class="HLabel2">Section 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-40"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-41"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-42"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>211 - </span><a href="#h-43"><span class="HLabel2">Section 12</span> - <span class="HTitleText2">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-44"><span class="HLabel2">Section 13</span> - <span class="HTitleText2">Loi sur les Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-45"><span class="HLabel2">Section 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-46"><span class="HLabel2">Section 15</span> - <span class="HTitleText2">Loi de mise en oeuvre de l’Accord de libre-échange Canada — Chili</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-47"><span class="HLabel2">Section 16</span> - <span class="HTitleText2">Loi maritime du Canada</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-48"><span class="HLabel2">Section 17</span> - <span class="HTitleText2">Loi sur l’identification par les empreintes génétiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="#h-49"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-50"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>249 - </span><a href="#h-53"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>250 - </span><a href="#h-54"><span class="HLabel2">Section 18</span> - <span class="HTitleText2">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250 - </span><a href="#h-55"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-56"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="#h-57"><span class="HLabel2">Section 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-58"><span class="HLabel2">Section 20</span> - <span class="HTitleText2">Loi sur l’Agence de la santé publique du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>253 - </span><a href="#h-59"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-60"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-61"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>261 - </span><a href="#h-62"><span class="HLabel2">Section 21</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-63"><span class="HLabel2">Section 22</span> - <span class="HTitleText2">Coopératives de crédit centrales et coopératives de crédit fédérales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>266 - </span><a href="#h-64"><span class="HTitleText3">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-65"><span class="HTitleText3">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-66"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-67"><span class="HTitleText3">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-68"><span class="HTitleText3">Résiliation des accords</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-69"><span class="HTitleText3">Dissolution</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-70"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="#h-71"><span class="HTitleText4">Loi sur le Bureau du surintendant des institutions financières</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="#h-72"><span class="HTitleText4">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="#h-73"><span class="HTitleText4">Loi sur les sociétés d’assurances</span></a>
</li></ul>
</li><li><span class='sectionRange'>303 - </span><a href="#h-74"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="#h-75"><span class="HLabel2">Section 23</span> - <span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>304 - </span><a href="#h-76"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-77"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>306 - </span><a href="#h-78"><span class="HLabel2">Section 24</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>306 - </span><a href="#h-79"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-80"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="#h-81"><span class="HLabel2">Section 25</span> - <span class="HTitleText2">Protonotaires de la Cour fédérale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="#h-82"><span class="HTitleText3">Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="#h-83"><span class="HTitleText3">Loi sur les Cours fédérales</span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="#h-84"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-85"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="#h-86"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>334 - </span><a href="#h-87"><span class="HLabel2">Section 26</span> - <span class="HTitleText2">Loi canadienne sur les paiements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>334 - </span><a href="#h-88"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>358 - </span><a href="#h-89"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="#h-90"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>360 - </span><a href="#h-91"><span class="HLabel2">Section 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>360 - </span><a href="#h-92"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>374 - </span><a href="#h-93"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>374 - </span><a href="#h-94"><span class="HTitleText4">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>375 - </span><a href="#h-95"><span class="HTitleText4">Loi sur les banques</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>376 - </span><a href="#h-96"><span class="HLabel2">Section 28</span> - <span class="HTitleText2">Loi sur les mesures de transparence dans le secteur extractif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="#h-97"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-98"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>378 - </span><a href="#h-99"><span class="HLabel2">Section 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi et la croissance économique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>378 - </span><a href="#h-100"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>381 - </span><a href="#h-101"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>382 - </span><a href="#h-102"><span class="HLabel2">Section 30</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Relations de travail dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="#h-103"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="#h-104"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>387 - </span><a href="#h-105"><span class="HLabel2">Section 31</span> - <span class="HTitleText2">Pension de retraite de la Gendarmerie royale du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>387 - </span><a href="#h-106"><span class="HTitleText3">Transfert de la pension de certains employés</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-107"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de retraite de la Gendarmerie royale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="#h-108"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>401 - </span><a href="#h-109"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

