<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2001 modifiant la taxe sur le tabac</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES DOUANES</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">TARIF DES DOUANES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR L’ACCISE</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText1">LOI SUR LA TAXE D’ACCISE</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-6"><span class="HTitleText1">LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-7"><span class="HTitleText1">APPLICATION</span></a>
</li></ul>
</li></ul>

</nav>

