<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Accise, Loi de 2001 sur l’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">APPLICATION ET ADMINISTRATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Personnel assurant l’exécution</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText2">Enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LICENCES, AGRÉMENTS ET AUTORISATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Licences et agréments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Autorisations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText2">Entrepôts d’accise spéciaux</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Boutiques hors taxes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">TABAC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Réglementation du tabac</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-16"><span class="HTitleText2">Droit sur le tabac</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-17"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-18"><span class="HTitleText2">Droits spéciaux sur les produits du tabac</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-19"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">ALCOOL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-20"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-21"><span class="HTitleText2">Alcool en vrac</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-22"><span class="HTitleText2">Contenants spéciaux de spiritueux</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-23"><span class="HTitleText2">Contenants spéciaux de vin</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-24"><span class="HTitleText2">Alcool emballé</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-25"><span class="HTitleText2">Alcool dénaturé et alcool spécialement dénaturé</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-26"><span class="HTitleText2">Responsabilité en matière de spiritueux en vrac</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-27"><span class="HTitleText2">Responsabilité en matière de vin en vrac</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-28"><span class="HTitleText2">Imposition et paiement du droit sur l’alcool</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-29"><span class="HTitleText2">Assujettissement des exploitants agréés d’entrepôt d’accise et des utilisateurs agréés</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-30"><span class="HTitleText2">Utilisations et sorties d’alcool non assujetties au droit</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-31"><span class="HTitleText2">Détermination du volume d’alcool</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-32"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-33"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES CONCERNANT LES DROITS ET AUTRES SOMMES EXIGIBLES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-34"><span class="HTitleText2">Mois d’exercice</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-35"><span class="HTitleText2">Déclarations et paiement des droits et autres sommes</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-36"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-37"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-38"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-39"><span class="HTitleText2">Opposition aux cotisations</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-40"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-41"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-42"><span class="HTitleText2">Faillites et réorganisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-43"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">CONTRÖLE D’APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-44"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-45"><span class="HTitleText2">Produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-46"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-47"><span class="HTitleText2">Imposition des pénalités</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="#h-48"><span class="HTitleText2">Mandats de perquisition</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-49"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-50"><span class="HTitleText2">Sort des choses saisies</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-51"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-52"><span class="HTitleText2">Révision de la pénalité imposée ou de la saisie</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-53"><span class="HTitleText2">Revendication des tiers</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="#h-54"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-55"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="#h-56"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-57"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES ET CONNEXES ET DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>305 - </span><a href="#h-58"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>321 - </span><a href="#h-59"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>321 - </span><a href="#h-60"><span class="HTitleText3"><cite class="XRefExternalAct">Loi d’exécution du budget de 2000</cite></span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-61"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence des douanes et du revenu du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>324 - </span><a href="#h-62"><span class="HTitleText3"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="#h-64"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la compétence extracôtière du Canada pour les douanes et l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="#h-65"><span class="HTitleText3"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-67"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les exportations</cite></span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-69"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="#h-70"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les mesures économiques spéciales</cite></span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-71"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Cour canadienne de l’impôt</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>408 - </span><a href="#h-72"><span class="HTitleText2">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>408 - </span><a href="#h-73"><span class="HTitleText3">Loi modifiant la Loi sur les douanes et d’autres lois en conséquence</span></a>
</li>
<li><span class='sectionRange'>409 - </span><a href="#h-74"><span class="HTitleText3">Projet de loi C-24</span></a>
</li>
<li><span class='sectionRange'>410 - </span><a href="#h-75"><span class="HTitleText3">Projet de loi C-30</span></a>
</li>
<li><span class='sectionRange'>411 - </span><a href="#h-76"><span class="HTitleText3">Projet de loi C-32</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>412 - </span><a href="#h-77"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE D’ACCISE SUR LES PRODUITS DU TABAC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>412 - </span><a href="#h-78"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>413 - </span><a href="#h-79"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>422 - </span><a href="#h-80"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LES PROVISIONS DE BORD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>422 - </span><a href="#h-81"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>423 - </span><a href="#h-82"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>424 - </span><a href="#h-83"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>425 - </span><a href="#h-84"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>426 - </span><a href="#h-85"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>427 - </span><a href="#h-86"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="#h-87"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les provisions de bord</cite></span></a>
</li>
<li><span class='sectionRange'>431 - </span><a href="#h-88"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les provisions de bord</cite></span></a>
</li>
<li><span class='sectionRange'>432 - </span><a href="#h-89"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les drawbacks accordés aux approvisionneurs de navire</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>433 - </span><a href="#h-90"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-91"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - TAUX DU DROIT SUR LES PRODUITS DU TABAC</span></a>
</li>
<li><a href="#h-92"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - DROIT ADDITIONNEL SUR LES CIGARES</span></a>
</li>
<li><a href="#h-93"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - TAUX DES DROITS SPÉCIAUX SUR CERTAINS PRODUITS DE TABAC FABRIQUÉ</span></a>
</li>
<li><a href="#h-94"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - TAUX DU DROIT SUR LES SPIRITUEUX</span></a>
</li>
<li><a href="#h-95"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - TAUX DU DROIT SPÉCIAL SUR LES SPIRITUEUX</span></a>
</li>
<li><a href="#h-96"><span class="scheduleLabel">ANNEXE 6</span> <span class="scheduleTitleText"> - TAUX DU DROIT SUR LE VIN</span></a>
</li></ul>
</li></ul>

</nav>

