<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 1 d’exécution du budget de 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2016</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-5.html#h-7"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> (mesures relatives à la TPS/TVH)</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-6.html#h-8"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur l’accise,</cite> de la <cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite> et de la <cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-6.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-7.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-9.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-9.html#h-12"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="page-9.html#h-13"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-9.html#h-14"><span class="HLabel2">SECTION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures spéciales d’importation</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-9.html#h-15"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-13.html#h-16"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-13.html#h-17"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="page-13.html#h-18"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Dette publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="page-13.html#h-19"><span class="HTitleText3">Édiction de la Loi autorisant certains emprunts</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-14.html#h-20"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-14.html#h-21"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur l’exploitation du champ Hibernia</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-14.html#h-22"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2016</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-14.html#h-23"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-14.html#h-24"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Stabilité du secteur financier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="page-14.html#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-14.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-14.html#h-27"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>113 - </span><a href="page-14.html#h-28"><span class="HLabel2">SECTION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Services partagés Canada</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-15.html#h-29"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Paiement à l’Institut canadien de recherches avancées</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-15.html#h-30"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Aide financière aux étudiants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="page-15.html#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Loi fédérale sur l’aide financière aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-15.html#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur l’épargne-études</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-15.html#h-33"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="page-15.html#h-34"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Directeur parlementaire du budget et Bureau de régie interne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="page-15.html#h-35"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="page-15.html#h-36"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-16.html#h-37"><span class="HTitleText4">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="page-17.html#h-38"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="page-17.html#h-39"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-17.html#h-40"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-18.html#h-41"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-18.html#h-42"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-18.html#h-43"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-19.html#h-44"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-19.html#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-19.html#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li>
<li><span class='sectionRange'>173.1 - </span><a href="page-19.html#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Gendarmerie royale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-19.html#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-20.html#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-20.html#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-20.html#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-20.html#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-20.html#h-53"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les conflits d’intérêts</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-20.html#h-54"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le contrôle des dépenses</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-20.html#h-55"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les compétences linguistiques</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="page-20.html#h-56"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="page-20.html#h-57"><span class="HLabel2">SECTION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>192 - </span><a href="page-20.html#h-58"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-20.html#h-59"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="page-20.html#h-60"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Financement des services de soins à domicile et de santé mentale</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-21.html#h-61"><span class="HLabel2">SECTION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-21.html#h-62"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-23.html#h-63"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-23.html#h-64"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>229 - </span><a href="page-23.html#h-65"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2">Soutien aux familles : prestations et congés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="page-23.html#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="page-23.html#h-67"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-28.html#h-68"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-28.html#h-69"><span class="HTitleText4">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="page-29.html#h-70"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>259 - </span><a href="page-29.html#h-71"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-30.html#h-72"><span class="HTitleText4">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="page-31.html#h-73"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="page-31.html#h-74"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2">Militaires et vétérans des Forces canadiennes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>270 - </span><a href="page-31.html#h-75"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="page-33.html#h-76"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="page-33.html#h-77"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Anciens Combattants</cite></span></a>
</li>
<li><span class='sectionRange'>292 - </span><a href="page-33.html#h-78"><span class="HTitleText3">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-34.html#h-79"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-34.html#h-80"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="page-34.html#h-81"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’emploi, la croissance et la prospérité durable</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-34.html#h-82"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2016</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="page-34.html#h-83"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="page-34.html#h-84"><span class="HLabel2">SECTION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-35.html#h-85"><span class="HLabel2">SECTION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>306 - </span><a href="page-35.html#h-86"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="page-35.html#h-87"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>312 - </span><a href="page-35.html#h-88"><span class="HLabel2">SECTION 15</span> - <span class="HTitleText2">Accords — ministre des Transports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>312 - </span><a href="page-35.html#h-89"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-35.html#h-90"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de la navigation</cite></span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-35.html#h-91"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-35.html#h-92"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="page-36.html#h-93"><span class="HLabel2">SECTION 16</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les aliments et drogues</cite></span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="page-36.html#h-94"><span class="HLabel2">SECTION 17</span> - <span class="HTitleText2">Lois en matière de travail et d’emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>318 - </span><a href="page-36.html#h-95"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="page-44.html#h-96"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Programme de protection des salariés</cite></span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="page-44.html#h-97"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="page-45.html#h-98"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>394 - </span><a href="page-45.html#h-99"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="page-45.html#h-100"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="page-45.html#h-101"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="page-45.html#h-102"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>398 - </span><a href="page-45.html#h-103"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="page-45.html#h-104"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="page-46.html#h-105"><span class="HLabel2">SECTION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque de l’infrastructure du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="page-46.html#h-106"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>404 - </span><a href="page-47.html#h-107"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>404 - </span><a href="page-47.html#h-108"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>405 - </span><a href="page-47.html#h-109"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="page-47.html#h-110"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>407 - </span><a href="page-47.html#h-111"><span class="HLabel2">SECTION 19</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>407 - </span><a href="page-47.html#h-112"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>436 - </span><a href="page-50.html#h-113"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>436 - </span><a href="page-50.html#h-114"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="page-50.html#h-115"><span class="HTitleText4">Modification connexe à la <cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>439 - </span><a href="page-50.html#h-116"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="page-51.html#h-117"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>442 - </span><a href="page-51.html#h-118"><span class="HLabel2">SECTION 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investir au Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>442 - </span><a href="page-51.html#h-119"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="page-52.html#h-120"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="page-52.html#h-121"><span class="HTitleText3">Modifications corrélatives et connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>444 - </span><a href="page-52.html#h-122"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="page-52.html#h-123"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>448 - </span><a href="page-52.html#h-124"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="page-52.html#h-125"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="page-52.html#h-126"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>451 - </span><a href="page-52.html#h-127"><span class="HLabel2">SECTION 21</span> - <span class="HTitleText2">Modernisation du régime de frais de service</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>451 - </span><a href="page-52.html#h-128"><span class="HTitleText3">Édiction de la <cite class="XRefExternalAct">Loi sur les frais de service</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="page-53.html#h-129"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>453 - </span><a href="page-53.html#h-130"><span class="HTitleText3">Modification connexe à la <cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>454 - </span><a href="page-53.html#h-131"><span class="HTitleText3">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="page-53.html#h-132"><span class="HTitleText3">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>456 - </span><a href="page-53.html#h-133"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>457 - </span><a href="page-53.html#h-134"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-54.html#h-135"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-55.html#h-136"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

