<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi de mise en oeuvre de l’Accord de libre-échange Canada — Israël et apportant des modifications connexes à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord de libre-échange Canada — Israël</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-2.html#h-7"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-3.html#h-8"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

