<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 1 d’exécution du budget de 2018</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-6.html#h-4"><span class="HTitleText2">Entrée en vigueur rétroactive</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-7.html#h-5"><span class="HTitleText2">Loi modifiant le <cite class="XRefExternalAct">Régime de pensions du Canada</cite>, la <cite class="XRefExternalAct">Loi sur l’Office d’investissement du régime de pensions du Canada</cite> et la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-7.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2017</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-7.html#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-7.html#h-8"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite> (taxation du tabac) et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-7.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-8.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-8.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-8.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2017</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-8.html#h-13"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="page-8.html#h-14"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite> (taxation du cannabis), de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-8.html#h-15"><span class="HTitleText2">Coordination avec la <cite class="XRefExternalAct">Loi sur le cannabis</cite></span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-9.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-13.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-13.html#h-18"><span class="HTitleText2">Modification de divers règlements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="page-13.html#h-19"><span class="HTitleText3"><cite class="XRefExternalRegulation">Décret de remise visant les importations par la poste</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-13.html#h-20"><span class="HTitleText3"><cite class="XRefExternalRegulation">Décret de remise visant les importations par messager</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-13.html#h-21"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur les remboursements aux organismes de services publics (TPS/TVH)</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-13.html#h-22"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur les licences, agréments et autorisations d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-13.html#h-23"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur la possession de produits du tabac non estampillés</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-14.html#h-24"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur l’estampillage et le marquage des produits du tabac</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-14.html#h-25"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur l’étiquetage des produits du tabac (cigarettes et petits cigares)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="page-14.html#h-26"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>114 - </span><a href="page-14.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-14.html#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="page-14.html#h-29"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-14.html#h-30"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-14.html#h-31"><span class="HTitleText2">Modification de la <cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="page-15.html#h-32"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Militaires et vétérans des Forces canadiennes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="page-15.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-15.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le bien-être des vétérans</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-21.html#h-35"><span class="HTitleText2">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162 - </span><a href="page-21.html#h-36"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-21.html#h-37"><span class="HTitleText3">Services de réadaptation et assistance professionnelle</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-21.html#h-38"><span class="HTitleText3">Allocation de soutien du revenu</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-21.html#h-39"><span class="HTitleText3">Indemnité pour douleur et souffrance</span></a>
</li></ul>
</li><li><span class='sectionRange'>178 - </span><a href="page-22.html#h-40"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>178 - </span><a href="page-22.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’aide en matière d’éducation aux enfants des anciens combattants décédés</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-22.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Anciens Combattants</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-22.html#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-22.html#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-22.html#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2016</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-22.html#h-46"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>186 - </span><a href="page-22.html#h-47"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la tarification de la pollution causée par les gaz à effet de serre</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>186 - </span><a href="page-22.html#h-48"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-23.html#h-49"><span class="HTitleText2">Prise du règlement</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-23.html#h-50"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="page-23.html#h-51"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-23.html#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Cour canadienne de l’impôt</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-23.html#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence du revenu du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-24.html#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les pénalités administratives en matière d’environnement</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>198 - </span><a href="page-24.html#h-55"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>199 - </span><a href="page-24.html#h-56"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 - </span><a href="page-24.html#h-57"><span class="HLabel2">SECTION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-24.html#h-58"><span class="HLabel2">SECTION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202 - </span><a href="page-24.html#h-59"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-26.html#h-60"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="page-26.html#h-61"><span class="HLabel2">SECTION 3</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-26.html#h-62"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Valeurs ou titres émis ou garantis par des gouvernements étrangers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="page-26.html#h-63"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-26.html#h-64"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="page-26.html#h-65"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Compte du fonds des changes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="page-26.html#h-66"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la monnaie</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="page-26.html#h-67"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Billets de banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="page-26.html#h-68"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-26.html#h-69"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la monnaie</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>231 - </span><a href="page-27.html#h-70"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Compensation et règlement des paiements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>231 - </span><a href="page-27.html#h-71"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Résolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>231 - </span><a href="page-27.html#h-72"><span class="HTitleText4">Modification de la <cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-28.html#h-73"><span class="HTitleText4">Modification corrélative à la <cite class="XRefExternalAct">Loi canadienne sur les paiements</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-28.html#h-74"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>240 - </span><a href="page-28.html#h-75"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Renseignements relatifs à la surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>240 - </span><a href="page-28.html#h-76"><span class="HTitleText4">Modification de la <cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="page-28.html#h-77"><span class="HTitleText4">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-29.html#h-78"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>245 - </span><a href="page-29.html#h-79"><span class="HLabel2">SECTION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-29.html#h-80"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Station canadienne de recherche dans l’Extrême-Arctique et application d’un décret au Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="page-29.html#h-81"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Station canadienne de recherche dans l’Extrême-Arctique</cite></span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="page-29.html#h-82"><span class="HTitleText3">Application d’un décret au Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>250 - </span><a href="page-29.html#h-83"><span class="HLabel2">SECTION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Instituts de recherche en santé du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-30.html#h-84"><span class="HLabel2">SECTION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la réduction de la paperasse</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>257 - </span><a href="page-30.html#h-85"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-30.html#h-86"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>265 - </span><a href="page-30.html#h-87"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2">Centre de la sécurité des télécommunications</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-31.html#h-88"><span class="HLabel2">SECTION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>268 - </span><a href="page-31.html#h-89"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-32.html#h-90"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>284 - </span><a href="page-32.html#h-91"><span class="HLabel2">SECTION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>284 - </span><a href="page-32.html#h-92"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>292 - </span><a href="page-33.html#h-93"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="page-34.html#h-94"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>297 - </span><a href="page-34.html#h-95"><span class="HLabel2">SECTION 15</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="page-34.html#h-96"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="page-34.html#h-97"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="page-35.html#h-98"><span class="HTitleText3">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-35.html#h-99"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>310 - </span><a href="page-35.html#h-100"><span class="HLabel2">SECTION 16</span> - <span class="HTitleText2">Examen des lois régissant le secteur financier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>310 - </span><a href="page-35.html#h-101"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Activités liées à la technologie financière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>310 - </span><a href="page-35.html#h-102"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-36.html#h-103"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="page-38.html#h-104"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="page-40.html#h-105"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’association personnalisée le Bouclier vert du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="page-40.html#h-106"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>342 - </span><a href="page-40.html#h-107"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Sociétés d’assurances (investissements liés à l’infrastructure)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="page-40.html#h-108"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>349 - </span><a href="page-41.html#h-109"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="page-41.html#h-110"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>351 - </span><a href="page-41.html#h-111"><span class="HLabel3">SOUS-SECTION C</span> - <span class="HTitleText3">Terminologie bancaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>351 - </span><a href="page-41.html#h-112"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Bureau du surintendant des institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>352 - </span><a href="page-41.html#h-113"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>354 - </span><a href="page-42.html#h-114"><span class="HLabel3">SOUS-SECTION D</span> - <span class="HTitleText3">Dispositions de temporarisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>354 - </span><a href="page-42.html#h-115"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>355 - </span><a href="page-42.html#h-116"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="page-42.html#h-117"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>359 - </span><a href="page-42.html#h-118"><span class="HLabel2">SECTION 17</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la diversification de l’économie de l’Ouest canadien</cite></span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="page-42.html#h-119"><span class="HLabel2">SECTION 18</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="page-43.html#h-120"><span class="HLabel2">SECTION 19</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>361 - </span><a href="page-43.html#h-121"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="page-51.html#h-122"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="page-51.html#h-123"><span class="HLabel2">SECTION 20</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="page-51.html#h-124"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="page-52.html#h-125"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>407 - </span><a href="page-52.html#h-126"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi sur l’administration des biens saisis</cite></span></a>
</li>
<li><span class='sectionRange'>409 - </span><a href="page-52.html#h-127"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-53.html#h-128"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-54.html#h-129"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-55.html#h-130"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-56.html#h-131"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-57.html#h-132"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-58.html#h-133"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>

