<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code canadien du travail (harcèlement et violence), la Loi sur les relations de travail au Parlement, et la Loi n<Sup>o</Sup> 1 d’exécution du budget de 2017</a><ul class="TocIndent"><li><span class='sectionRange'>0.1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>0.1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-3"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-5"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-3.html#h-6"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-8"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-4.html#h-9"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-4.html#h-10"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2017</cite></span></a>
</li></ul>
</li></ul>

</nav>

