<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les mesures d’aide liées au coût de l’énergie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">PRESTATION LIÉE AU COÛT DE L’ÉNERGIE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">RÉDUCTION DE LA CONSOMMATION ÉNERGÉTIQUE DES HABITATIONS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-7"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">TRANSPORT EN COMMUN</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-8"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li></ul>
</li></ul>

</nav>

