<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi interdisant les armes à sous-munitions</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET CHAMP D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">DÉSIGNATION DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">DÉTENTION DANS UN ENDROIT SÛR</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText1">DÉLÉGATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">MODIFICATION DE LA CONVENTION</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText1">CONTRÔLE D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-12"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - CONVENTION SUR LES ARMES À SOUS-MUNITIONS</span></a>
</li></ul>
</li></ul>

</nav>

