<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de soutien de la reprise économique au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET DE LOIS ET RÈGLEMENTS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-10.html#h-4"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-10.html#h-5"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-10.html#h-6"><span class="HTitleText2">Loi sur la prestation universelle pour la garde d’enfants</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-10.html#h-7"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-12.html#h-8"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX DROITS D’ACCISE ET AUX TAXES DE VENTE ET D’ACCISE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-12.html#h-9"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-13.html#h-10"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-13.html#h-11"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-15.html#h-12"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-17.html#h-13"><span class="HTitleText2">Règlement ministériel sur les brasseries</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-17.html#h-14"><span class="HTitleText2">Règlement sur les brasseries</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-17.html#h-15"><span class="HTitleText2">Règlement sur le nouveau régime de la taxe à valeur ajoutée harmonisée</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-17.html#h-16"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES RELATIVEMENT À L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="page-17.html#h-17"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li></ul>
</li><li><span class='sectionRange'>146 - </span><a href="page-17.html#h-18"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX ORGANISMES EXTERNES DE TRAITEMENT DES PLAINTES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="page-17.html#h-19"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-18.html#h-20"><span class="HTitleText2">Loi sur l’Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-19.html#h-21"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-19.html#h-22"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="page-19.html#h-23"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI CANADIENNE SUR L’ÉPARGNE-INVALIDITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="page-19.html#h-24"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-19.html#h-25"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-19.html#h-26"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="page-19.html#h-27"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI SUR LES DOUANES</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-19.html#h-28"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-20.html#h-29"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">LOI SUR LE BUREAU DU SURINTENDANT DES INSTITUTIONS FINANCIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="page-20.html#h-30"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-20.html#h-31"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="page-20.html#h-32"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">LOI DE 1985 SUR LES NORMES DE PRESTATION DE PENSION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="page-20.html#h-33"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-22.html#h-34"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-22.html#h-35"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-23.html#h-36"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

