<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Comité des parlementaires sur la sécurité nationale et le renseignement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Ministre désigné</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Constitution et composition du Comité</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Mandat du Comité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">Sécurité et confidentialité</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">Accès à l’information</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">Procédure</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText1">Organismes de surveillance</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">Secrétariat</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-13"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-14"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-15"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText2">Loi sur la protection de l’information</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText2">Loi sur le Parlement du Canada</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-19"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-20"><span class="HTitleText2">Loi sur les conflits d’intérêts</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-21"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Serment ou déclaration solennelle</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

