<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord Canada–États-Unis–Mexique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’Accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approbation, désignation du ministre et représentation au sein de la Commission</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Secrétariat</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Groupes spéciaux et comités</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Conseil du travail</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit d’auteur</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les engrais</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les aliments et drogues</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les grains du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures spéciales d’importation</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-28"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-29"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-35"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-36"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la radiodiffusion</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits antiparasitaires</cite></span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la régie canadienne de l’énergie</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="#h-44"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-45"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-46"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-47"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-48"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-49"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li></ul>
</li></ul>

</nav>

