<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le cadre fédéral relatif à l’état de stress post-traumatique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Cadre fédéral relatif à l’état de stress post-traumatique</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Examen et rapport</span></a>
</li></ul>
</li></ul>

</nav>

