<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi édictant la Loi sur le Programme de protection des salariés et modifiant la Loi sur la faillite et l’insolvabilité, la Loi sur les arrangements avec les créanciers des compagnies et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LE PROGRAMME DE PROTECTION DES SALARIÉS</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LA FAILLITE ET L’INSOLVABILITÉ</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-3"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LES ARRANGEMENTS AVEC LES CRÉANCIERS DES COMPAGNIES</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-4"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-5"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-6"><span class="HTitleText2">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-7"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-8"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-9"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-10"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

