<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les juges et une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES JUGES</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les prestations de retraite supplémentaires</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

