<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère des Ressources humaines et du Développement des compétences</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MINISTÈRE DES RESSOURCES HUMAINES ET DU DÉVELOPPEMENT DES COMPÉTENCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Services entre ministères</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Comités</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MINISTRE DU TRAVAIL</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">COMMISSION DE L’ASSURANCE-EMPLOI DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText2">Maintien de la Commission</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText2">Attributions de la Commission</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-13"><span class="HTitleText2">Structure et fonctionnement</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Vérification</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">PROTECTION DES RENSEIGNEMENTS PERSONNELS </span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-16"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">SUBVENTION CANADIENNE POUR L’ÉPARGNE-ÉTUDES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-17"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-19"><span class="HTitleText2">Versements</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-20"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-21"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES ET CONNEXES, DISPOSITIONS DE COORDINATION, ABROGATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-22"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-23"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-24"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-25"><span class="HTitleText3">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-26"><span class="HTitleText3">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-27"><span class="HTitleText3">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-28"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-30"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-31"><span class="HTitleText3">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-32"><span class="HTitleText3">Loi sur les traitements</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-33"><span class="HTitleText3">Règlement fédéral sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-34"><span class="HTitleText3">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-35"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-36"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-37"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

