<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur l’épargne-études</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">DÉSIGNATION DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">VERSEMENTS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Loi sur les allocations spéciales pour enfants</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Loi sur le ministère du Développement des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

