<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur le système correctionnel et la mise en liberté sous condition et une autre loi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le casier judiciaire</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-3"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-4"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-5"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

