<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le mariage civil</a><ul class="TocIndent"><li><span class='sectionRange'>5 - </span><a href="#h-1"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText2">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText2">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2">Loi sur les prestations de guerre pour les civils</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Loi sur le divorce</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Loi sur le droit fédéral et le droit civil de la province de Québec</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Loi sur le mariage (degrés prohibés)</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Loi sur la modernisation de certains régimes d’avantages et d’obligations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

