<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la responsabilité en matière maritime, la Loi sur les Cours fédérales et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LA RESPONSABILITÉ EN MATIÈRE MARITIME</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES COURS FÉDÉRALES</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-4"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-5"><span class="HTitleText2">Loi sur la prévention de la pollution des eaux arctiques</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-6"><span class="HTitleText2">Loi sur les eaux du Nunavut et le Tribunal des droits de surface du Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

