<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur des mesures de réforme équitables concernant les réfugiés</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR LES COURS FÉDÉRALES</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

