<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur Téléfilm Canada et une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR TÉLÉFILM CANADA</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-2"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li></ul>
</li></ul>

</nav>

