<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur le Parlement du Canada (conseiller sénatorial en éthique et commissaire à l’éthique) et certaines lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LE PARLEMENT DU CANADA</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Cour fédérale</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText2">Loi sur l’indemnisation des agents de l’État</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement des lobbyistes</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

