<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2016 pour la mise en oeuvre d’une convention et d’un arrangement relatifs à la fiscalité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Convention fiscale Canada-Israël</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Arrangement fiscal relatif aux territoires du Canada et de Taiwan</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1">Loi de 2013 sur l’accord fiscal Canada-Hong Kong</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

