<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les mesures d’urgence visant la COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et <cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la prestation canadienne d’urgence</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les paiements relatifs aux événements de santé publique d’intérêt national</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HLabel1">PARTIE 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HLabel1">PARTIE 5</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la Société canadienne d’hypothèques et de logement</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-14"><span class="HLabel1">PARTIE 6</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-15"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-16"><span class="HTitleText2">Suspension de certaines dispositions du <cite class="XRefExternalRegulation">Règlement sur l’exercice de certains pouvoirs par Exportation et développement Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-17"><span class="HLabel1">PARTIE 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-18"><span class="HLabel1">PARTIE 8</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-19"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-20"><span class="HTitleText2">Modifications connexes à la <cite class="XRefExternalAct">Loi autorisant certains emprunts</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-21"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-22"><span class="HLabel1">PARTIE 9</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les aliments et drogues</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-23"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-24"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-25"><span class="HLabel1">PARTIE 10</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-26"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-27"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi n<sup>o</sup> 2 d’exécution du budget de 2018</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-28"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-29"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-30"><span class="HLabel1">PARTIE 11</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi nationale sur l’habitation</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-31"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-32"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-33"><span class="HLabel1">PARTIE 12</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-34"><span class="HLabel1">PARTIE 13</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi fédérale sur les prêts aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-35"><span class="HLabel1">PARTIE 14</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur Financement agricole Canada</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-36"><span class="HLabel1">PARTIE 15</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi fédérale sur l’aide financière aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-37"><span class="HLabel1">PARTIE 16</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la Banque de développement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-38"><span class="HLabel1">PARTIE 17</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les prêts aux apprentis</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-39"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">Assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-40"><span class="HLabel2">SECTION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-41"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Certificats médicaux</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

