<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre des traités ou des ententes administratives sur le transfèrement international des personnes reconnues coupables d'infractions criminelles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJET ET PRINCIPES</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">MINISTRE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">CONSENTEMENT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">APPLICATION CONTINUE ET ADAPTATION</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">PROBATION</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">ADOLESCENTS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText1">CALCUL DES PEINES</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-10"><span class="HTitleText1">MESURES D'ORDRE HUMANITAIRE</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText1">ENTENTES ADMINISTRATIVES</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText1">DISPOSITION GÉNÉRALE</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-13"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-14"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText1">NOUVELLE TERMINOLOGIE</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

