<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les pensions et la Loi sur la pension de retraite de la Gendarmerie royale du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES PENSIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LA PENSION DE RETRAITE DE LA GENDARMERIE ROYALE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li></ul>
</li></ul>

</nav>

