<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant certaines lois environnementales et édictant des dispositions ayant trait au contrôle d’application de lois environnementales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA PROTECTION DE L’ENVIRONNEMENT EN ANTARCTIQUE</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES AIRES MARINES NATIONALES DE CONSERVATION DU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES PARCS NATIONAUX DU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES ESPÈCES SAUVAGES DU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-6"><span class="HTitleText1"><cite class="XRefExternalAct">LOI CANADIENNE SUR LA PROTECTION DE L’ENVIRONNEMENT (1999)</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-7"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES OUVRAGES DESTINÉS À L’AMÉLIORATION DES COURS D’EAU INTERNATIONAUX</cite></span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-8"><span class="HTitleText1"><cite class="XRefExternalAct">LOI DE 1994 SUR LA CONVENTION CONCERNANT LES OISEAUX MIGRATEURS</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-9"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE PARC MARIN DU SAGUENAY — SAINT-LAURENT</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-10"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA PROTECTION D’ESPÈCES ANIMALES OU VÉGÉTALES SAUVAGES ET LA RÉGLEMENTATION DE LEUR COMMERCE INTERNATIONAL ET INTERPROVINCIAL</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-11"><span class="HTitleText1"><cite class="XRefExternalAct">ÉDICTION DE LA LOI SUR LES PÉNALITÉS ADMINISTRATIVES EN MATIÈRE D’ENVIRONNEMENT</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-12"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-13"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

