<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le renforcement de la sécurité automobile pour les Canadiens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la sécurité automobile</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-3"><span class="HTitleText1">Modification corrélative à la <cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-4"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

