<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l'Agence des services frontaliers du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CONSTITUTION ET MISSION DE L’AGENCE</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MINISTRE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">PRÉSIDENT ET PREMIER VICE-PRÉSIDENT</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-6"><span class="HTitleText1">RESSOURCES HUMAINES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-7"><span class="HTitleText1">POUVOIRS DE L’AGENCE</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-8"><span class="HTitleText1">UTILISATION DES CRÉDITS</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-2.html#h-9"><span class="HTitleText1">RAPPORT ANNUEL</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-10"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Ancienne agence</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Monnaie royale canadienne</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-3.html#h-15"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Loi sur les produits agricoles au Canada</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Loi sur l’Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Loi sur l’Agence canadienne d’inspection des aliments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Loi sur le ministère de la Citoyenneté et de l’Immigration</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Loi sur l’exportation et l’importation de biens culturels</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-5.html#h-25"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-7.html#h-26"><span class="HTitleText2">Loi sur la compétence extracôtière du Canada pour les douanes et l’accise</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-27"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-7.html#h-28"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-7.html#h-29"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-7.html#h-30"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-8.html#h-31"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-9.html#h-32"><span class="HTitleText2">Loi d’aide à l’exécution des ordonnances et des ententes familiales</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-9.html#h-33"><span class="HTitleText2">Loi relative aux aliments du bétail</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-34"><span class="HTitleText2">Loi sur les engrais</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-9.html#h-35"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-10.html#h-36"><span class="HTitleText2">Loi sur l’inspection du poisson</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-10.html#h-37"><span class="HTitleText2">Loi sur la santé des animaux</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-10.html#h-38"><span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-10.html#h-39"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-10.html#h-40"><span class="HTitleText2">Loi sur l’inspection des viandes</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-10.html#h-41"><span class="HTitleText2">Loi sur la protection des végétaux</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-10.html#h-42"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-11.html#h-43"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-11.html#h-44"><span class="HTitleText2">Loi sur la Monnaie royale canadienne</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-11.html#h-45"><span class="HTitleText2">Loi sur les semences</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-11.html#h-46"><span class="HTitleText2">Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Modifications terminologiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-13.html#h-48"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-14.html#h-49"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

