<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 1 d’exécution du budget de 2021</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modifications à la Loi de l’impôt sur le revenu et autres textes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-9.html#h-4"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-9.html#h-5"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-10.html#h-6"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-10.html#h-7"><span class="HTitleText2">Loi sur la tarification de la pollution causée par les gaz à effet de serre</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-10.html#h-8"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-11.html#h-9"><span class="HTitleText2">Règlement sur l’épargne-invalidité</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="page-12.html#h-10"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Mesures relatives à la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>100 - </span><a href="page-12.html#h-11"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-14.html#h-12"></span> - </a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="page-14.html#h-13"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modifications à la Loi de 2001 sur l’accise</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="page-14.html#h-14"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="page-15.html#h-15"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-15.html#h-16"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Stabilité et efficacité du secteur financier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-15.html#h-17"><span class="HTitleText3">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-15.html#h-18"><span class="HTitleText3">Loi sur la compensation et le règlement des paiements</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-15.html#h-19"></span> - </a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-15.html#h-20"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="page-16.html#h-21"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Sommes non réclamées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="page-16.html#h-22"><span class="HTitleText3">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-16.html#h-23"><span class="HTitleText3">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-16.html#h-24"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-16.html#h-25"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-16.html#h-26"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-16.html#h-27"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="page-17.html#h-28"><span class="HLabel2">SECTION 3</span></span> - <span class="HTitleText2">Loi n<sup>o</sup> 2 d’exécution du budget de 2018</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="page-17.html#h-29"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-17.html#h-30"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-17.html#h-31"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Dispositions de temporarisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="page-17.html#h-32"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-17.html#h-33"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-17.html#h-34"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="page-17.html#h-35"><span class="HLabel2">SECTION 5</span></span> - <span class="HTitleText2">Loi sur la justice pour les victimes de dirigeants étrangers corrompus (loi de Sergueï Magnitski)</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-17.html#h-36"><span class="HLabel2">SECTION 6</span></span> - <span class="HTitleText2">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-17.html#h-37"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-18.html#h-38"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="page-18.html#h-39"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Loi sur les activités associées aux paiements de détail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="page-18.html#h-40"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-19.html#h-41"><span class="HTitleText3">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>178 - </span><a href="page-19.html#h-42"><span class="HTitleText4">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-19.html#h-43"><span class="HTitleText4">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-19.html#h-44"><span class="HTitleText4">Loi sur l’Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-19.html#h-45"><span class="HTitleText4">Loi sur les réseaux de cartes de paiement</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-19.html#h-46"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-19.html#h-47"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="page-19.html#h-48"><span class="HLabel2">SECTION 8</span></span> - <span class="HTitleText2">Loi de 1985 sur les normes de prestation de pension</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="page-19.html#h-49"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-19.html#h-50"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="page-19.html#h-51"><span class="HLabel2">SECTION 9</span></span> - <span class="HTitleText2">Loi sur la gestion financière des premières nations</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-19.html#h-52"><span class="HLabel2">SECTION 10</span></span> - <span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces (paiements de stabilisation)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="page-19.html#h-53"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-20.html#h-54"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="page-20.html#h-55"><span class="HLabel2">SECTION 11</span></span> - <span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces (versements supplémentaires en matière de santé)</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-20.html#h-56"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2">Plan d’immunisation du Canada contre la COVID-19</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-20.html#h-57"><span class="HLabel2">SECTION 13</span> - <span class="HTitleText2">Fonds pour le développement des collectivités du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>198 - </span><a href="page-20.html#h-58"><span class="HTitleText3">Versements supplémentaires</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-20.html#h-59"><span class="HTitleText3">Loi sur le soutien de la croissance de l’économie et de l’emploi au Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="page-20.html#h-60"><span class="HLabel2">SECTION 14</span> - <span class="HTitleText2">Entente sur les paiements annuels de ristournes liées au projet Hibernia</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-20.html#h-61"><span class="HLabel2">SECTION 15</span></span> - <span class="HTitleText2">Loi sur les paiements de péréquation compensatoires supplémentaires à la Nouvelle-Écosse et à Terre-Neuve-et-Labrador</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-20.html#h-62"><span class="HLabel2">SECTION 16</span></span> - <span class="HTitleText2">Loi sur les télécommunications</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="page-20.html#h-63"><span class="HLabel2">SECTION 17</span></span> - <span class="HTitleText2">Loi sur le financement des petites entreprises du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="page-20.html#h-64"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-21.html#h-65"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>209 - </span><a href="page-21.html#h-66"><span class="HLabel2">SECTION 18</span></span> - <span class="HTitleText2">Loi sur les douanes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>209 - </span><a href="page-21.html#h-67"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="page-21.html#h-68"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>219 - </span><a href="page-21.html#h-69"><span class="HLabel2">SECTION 19</span></span> - <span class="HTitleText2">Loi de mise en oeuvre de l’Accord Canada–États-Unis–Mexique</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-21.html#h-70"><span class="HLabel2">SECTION 20</span> - <span class="HTitleText2">Tribunal de la sécurité sociale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="page-21.html#h-71"><span class="HTitleText3">Loi sur le ministère de l’Emploi et du Développement social</span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="page-22.html#h-72"><span class="HTitleText3">Modification corrélative à la Loi sur les Cours fédérales</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-22.html#h-73"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-22.html#h-74"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>245 - </span><a href="page-22.html#h-75"><span class="HLabel2">SECTION 21</span></span> - <span class="HTitleText2">Code canadien du travail (protection de rémunération égale)</span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="page-23.html#h-76"><span class="HLabel2">SECTION 22</span></span> - <span class="HTitleText2">Code canadien du travail (salaire minimum fédéral)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>246 - </span><a href="page-23.html#h-77"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="page-23.html#h-78"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>249 - </span><a href="page-23.html#h-79"><span class="HLabel2">SECTION 23</span></span> - <span class="HTitleText2">Code canadien du travail (congé dans le cas du décès ou de la disparition d’un enfant)</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="page-23.html#h-80"><span class="HLabel2">SECTION 24</span> - <span class="HTitleText2">Paiement au Québec</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="page-23.html#h-81"><span class="HLabel2">SECTION 25</span></span> - <span class="HTitleText2">Loi sur les juges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>252 - </span><a href="page-23.html#h-82"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-23.html#h-83"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="page-23.html#h-84"><span class="HLabel2">SECTION 26</span> - <span class="HTitleText2">Nouvelles ressources judiciaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>254 - </span><a href="page-23.html#h-85"><span class="HTitleText3">Loi sur les Cours fédérales</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-23.html#h-86"><span class="HTitleText3">Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-23.html#h-87"><span class="HTitleText3">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="page-23.html#h-88"><span class="HLabel2">SECTION 27</span></span> - <span class="HTitleText2">Loi sur le Conseil national de recherches</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="page-23.html#h-89"><span class="HLabel2">SECTION 28</span></span> - <span class="HTitleText2">Loi sur le ministère de l’Emploi et du Développement social</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="page-23.html#h-90"><span class="HLabel2">SECTION 29</span> - <span class="HTitleText2">Prêts aux étudiants et prêts aux apprentis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>263 - </span><a href="page-23.html#h-91"><span class="HTitleText3">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-24.html#h-92"><span class="HTitleText3">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="page-24.html#h-93"><span class="HTitleText3">Loi sur les prêts aux apprentis</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="page-24.html#h-94"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>267 - </span><a href="page-24.html#h-95"><span class="HLabel2">SECTION 30</span> - <span class="HTitleText2">Élections au sein de premières nations</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-24.html#h-96"><span class="HLabel2">SECTION 31</span> - <span class="HTitleText2">Majoration de la pension de vieillesse et paiement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>268 - </span><a href="page-24.html#h-97"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="page-24.html#h-98"><span class="HTitleText3">Paiement</span></a>
</li></ul>
</li><li><span class='sectionRange'>276 - </span><a href="page-24.html#h-99"><span class="HLabel2">SECTION 32</span></span> - <span class="HTitleText2">Loi sur l’emploi dans la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>276 - </span><a href="page-24.html#h-100"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="page-24.html#h-101"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="page-24.html#h-102"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>287 - </span><a href="page-24.html#h-103"><span class="HLabel2">SECTION 33</span> - <span class="HTitleText2">Apprentissage et garde des jeunes enfants</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="page-25.html#h-104"><span class="HLabel2">SECTION 34</span> - <span class="HTitleText2">Prestations et congés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>288 - </span><a href="page-25.html#h-105"><span class="HTitleText3">Loi sur les prestations canadiennes de relance économique</span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="page-25.html#h-106"><span class="HTitleText3">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="page-25.html#h-107"><span class="HTitleText3">Loi sur des mesures en réponse à la COVID-19</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-25.html#h-108"><span class="HTitleText3">Règlement sur les prestations canadiennes de relance économique</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-25.html#h-109"><span class="HTitleText3">Règlement du Canada sur les normes du travail</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-25.html#h-110"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="page-26.html#h-111"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>302 - </span><a href="page-26.html#h-112"><span class="HLabel2">SECTION 35</span> - <span class="HTitleText2">Prestations et congés liés à l’emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>302 - </span><a href="page-26.html#h-113"><span class="HTitleText3">Loi sur l’assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>302 - </span><a href="page-26.html#h-114"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="page-28.html#h-115"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="page-28.html#h-116"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="page-28.html#h-117"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>340 - </span><a href="page-29.html#h-118"><span class="HTitleText3">Code canadien du travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>340 - </span><a href="page-29.html#h-119"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="page-29.html#h-120"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="page-29.html#h-121"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>347 - </span><a href="page-29.html#h-122"><span class="HTitleText3">Règlement sur l’assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>347 - </span><a href="page-29.html#h-123"><span class="HTitleText4">Modification du règlement</span></a>
</li>
<li><span class='sectionRange'>351 - </span><a href="page-29.html#h-124"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>352 - </span><a href="page-29.html#h-125"><span class="HTitleText3">Règlement sur l’assurance-emploi (pêche)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>352 - </span><a href="page-29.html#h-126"><span class="HTitleText4">Modification du règlement</span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="page-30.html#h-127"><span class="HTitleText4">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="page-30.html#h-128"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>361 - </span><a href="page-30.html#h-129"><span class="HLabel2">SECTION 36</span></span> - <span class="HTitleText2">Loi électorale du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>361 - </span><a href="page-30.html#h-130"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>362 - </span><a href="page-30.html#h-131"><span class="HTitleText3">Application des modifications</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-31.html#h-132"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-32.html#h-133"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-33.html#h-134"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-34.html#h-135"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li></ul>
</li></ul>

</nav>

