<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon, Loi sur le</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">GOUVERNEMENT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Pouvoir exécutif</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText2">Pouvoir législatif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText3">Assemblée législative</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText3">Législature</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText3">Compétence législative</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-9"><span class="HTitleText2">Trésor du Yukon</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-10"><span class="HTitleText2">Comptes du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-11"><span class="HTitleText1">ADMINISTRATION DE LA JUSTICE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-12"><span class="HTitleText2">Organisation judiciaire</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-13"><span class="HTitleText2">Cour suprême du Yukon</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-14"><span class="HTitleText2">Cour d’appel du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-15"><span class="HTitleText1">BIENS RÉELS, EAUX ET RESSOURCES PÉTROLIÈRES ET GAZIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-16"><span class="HTitleText2">Gestion et maîtrise</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-17"><span class="HTitleText2">Restrictions</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-18"><span class="HTitleText1">EXERCICE DE POUVOIRS FÉDÉRAUX</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-19"><span class="HTitleText1">MODIFICATION LÉGISLATIVE</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-20"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-21"><span class="HTitleText1">MODIFICATIONS APPORTÉES À LA PRÉSENTE LOI</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-22"><span class="HTitleText1">MODIFICATIONS APPORTÉES À D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la prévention de la pollution des eaux arctiques</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les chambres de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les corporations canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’arpentage des terres du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office d’investissement du régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi fédérale sur les prêts aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les ressources en eau du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Yukon sur le pétrole et le gaz</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre canadien d’hygiène et de sécurité au travail</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur l’évaluation environnementale</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur la protection de l’environnement (1999)</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le multiculturalisme canadien</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la citoyenneté</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-56"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-58"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Affaires indiennes et du Nord canadien</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-59"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-60"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le divorce</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-61"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les forces hydrauliques du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-62"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’équité en matière d’emploi</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-63"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’administration de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-65"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’expropriation</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-66"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’extradition</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-68"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les immeubles fédéraux et les biens réels fédéraux</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-69"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-71"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-72"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le règlement de la revendication territoriale des Gwich’in</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-73"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-74"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’exploitation du champ Hibernia</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-75"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les lieux et monuments historiques</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-76"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-77"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-78"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Indiens</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-79"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement industriel et régional</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-80"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-81"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’interprétation</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-82"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-83"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’abrogation de la Loi sur les titres de biens-fonds</cite></span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-84"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’aide à l’alimentation des animaux de ferme</cite></span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-85"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des ressources de la vallée du Mackenzie</cite></span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-86"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les normes de consommation de carburant des véhicules automobiles</cite></span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-87"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’entraide juridique en matière criminelle</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-88"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office national de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-89"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le pipe-line du Nord</cite></span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-90"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Territoires du Nord-Ouest</cite></span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-91"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’énergie nucléaire</cite></span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-92"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Nunavut</cite></span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-93"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les océans</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-94"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-95"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1985 sur les normes de prestation de pension</cite></span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-96"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-97"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-98"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-99"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-100"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-101"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-102"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Gendarmerie royale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-103"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les textes réglementaires</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-104"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Cour suprême</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-105"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les terres territoriales</cite></span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-106"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-107"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le règlement des revendications des Inuvialuit de la région ouest de l’Arctique</cite></span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-108"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite></span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-109"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les jeunes contrevenants</cite></span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-110"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le règlement des revendications territoriales des premières nations du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-111"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’autonomie gouvernementale des premières nations du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-112"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office des droits de surface du Yukon</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>272 - </span><a href="#h-113"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-114"><span class="HTitleText1">ABROGATIONS</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-115"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-116"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - DÉLIMITATION DU TERRITOIRE</span></a>
</li>
<li><a href="#h-117"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - LIMITE SEPTENTRIONALE DE LA ZONE ADJACENTE</span></a>
</li></ul>
</li></ul>

</nav>

