<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant certaines lois relatives aux institutions financières</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES BANQUES</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-14.html#h-2"><span class="HTitleText1">LOI SUR LES ASSOCIATIONS COOPÉRATIVES DE CRÉDIT</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-22.html#h-3"><span class="HTitleText1">LOI SUR L’ASSOCIATION PERSONNALISÉE LE BOUCLIER VERT DU CANADA</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="page-22.html#h-4"><span class="HTitleText1">LOI SUR LES SOCIÉTÉS D’ASSURANCES</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-38.html#h-5"><span class="HTitleText1">LOI SUR LES SOCIÉTÉS DE FIDUCIE ET DE PRÊT</span></a>
</li>
<li><span class='sectionRange'>453 - </span><a href="page-47.html#h-6"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-48.html#h-7"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

