<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi d’exécution du budget de 2006</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA RÉDUCTION DU TAUX DE LA TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Modifications concernant la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText3">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-5"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-6"><span class="HTitleText3">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-7"><span class="HTitleText3">Modifications concernant la taxation des produits du tabac</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-8"><span class="HTitleText4">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-9"><span class="HTitleText4">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-10"><span class="HTitleText3">Modifications concernant les produits alcoolisés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-11"><span class="HTitleText4">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-12"><span class="HTitleText4">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-13"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-14"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-15"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE D’ACCISE SUR LES BIJOUX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-16"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-17"><span class="HTitleText2">Loi d’exécution du budget de 2005</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-18"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LES POUVOIRS DE TAXATION ET LE TRAITEMENT FISCAL DES AUTOCHTONES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-19"><span class="HTitleText2">Loi sur la taxe sur les produits et services des premières nations</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-20"><span class="HTitleText2">Loi sur l’autonomie gouvernementale des premières nations du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-21"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">AUTRES MODIFICATIONS TOUCHANT LA FISCALITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-22"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-23"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-24"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-25"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-26"><span class="HTitleText2">Modifications conditionnelles</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-27"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">PRESTATION UNIVERSELLE POUR LA GARDE D’ENFANTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-28"><span class="HTitleText2">Édiction de la Loi</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-29"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="#h-30"><span class="HTitleText3">Loi sur les allocations spéciales pour enfants</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-31"><span class="HTitleText3">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-32"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-33"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li></ul>
</li><li><span class='sectionRange'>181 - </span><a href="#h-34"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 - </span><a href="#h-35"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-36"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">PAIEMENTS AUX PROVINCES ET AUX TERRITOIRES</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-37"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">ASSURANCE HYPOTHÉCAIRE</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-38"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX INSTITUTIONS FINANCIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-43"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">MODIFICATIONS EN MATIÈRE DE PENSIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>203 - </span><a href="#h-44"><span class="HTitleText2">Loi sur la pension de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-45"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-46"><span class="HTitleText2">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-47"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>208 - </span><a href="#h-48"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">LOI RELATIVE AUX RÉPERCUSSIONS DU PROJET GAZIER MACKENZIE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>208 - </span><a href="#h-49"><span class="HTitleText2">Édiction de la Loi</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-50"><span class="HTitleText2">Prélèvement</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-51"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>210 - </span><a href="#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="#h-55"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-56"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">MODIFICATIONS DIVERSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-57"><span class="HTitleText2">Loi sur l’Accord portant création de la Banque européenne pour la reconstruction et le développement</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-58"><span class="HTitleText2">Loi sur la commercialisation du poisson d’eau douce</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-59"><span class="HTitleText2">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
</li></ul>
</li><li><a href="#h-60"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-61"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

