<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la faillite et l’insolvabilité, la Loi sur les arrangements avec les créanciers des compagnies, la Loi sur le Programme de protection des salariés et le chapitre 47 des Lois du Canada (2005)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LA FAILLITE ET L’INSOLVABILITÉ</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES ARRANGEMENTS AVEC LES CRÉANCIERS DES COMPAGNIES</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR LE PROGRAMME DE PROTECTION DES SALARIÉS</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-4"><span class="HTitleText1">CHAPITRE 47 DES LOIS DU CANADA (2005)</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-5"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

