<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel (crime organisé et application de la loi) et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-3"><span class="HTitleText2">Loi réglementant certaines drogues et autres substances</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-4"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-5"><span class="HTitleText2">Loi sur la corruption d’agents publics étrangers</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-6"><span class="HTitleText2">Loi sur les crimes contre l’humanité et les crimes de guerre</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-7"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-8"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-9"><span class="HTitleText2">Loi sur l’entraide juridique en matière criminelle</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-10"><span class="HTitleText2">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-11"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-12"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-13"><span class="HTitleText2">Loi sur l’administration des biens saisis</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-14"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-15"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

