<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les systèmes de télédétection spatiale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">DÉSIGNATION DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">EXPLOITATION DES SYSTÈMES DE TÉLÉDÉTECTION SPATIALE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Obligation d’être titulaire d’une licence</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Délivrance des licences et questions connexes</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Modification, suspension et révocation des licences</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText2">Interruption des services</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Accès prioritaire</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Transfert de satellites de télédétection</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText1">INSPECTION</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-13"><span class="HTitleText1">DEMANDE DE RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-15"><span class="HTitleText1">DÉLÉGATION</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText1">IMMUNITÉ</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText1">VIOLATIONS ET PÉNALITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-18"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-19"><span class="HTitleText2">Agents verbalisateurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-20"><span class="HTitleText2">Procès-verbaux</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-21"><span class="HTitleText2">Responsabilité et pénalité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-22"><span class="HTitleText3">Paiement de la pénalité</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-23"><span class="HTitleText3">Présentation des observations</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-24"><span class="HTitleText3">Aveu de responsabilité</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-25"><span class="HTitleText2">Appel au ministre</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-26"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-27"><span class="HTitleText2">Recouvrement des pénalités et des sommes</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-28"><span class="HTitleText1">INFRACTIONS</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="#h-29"><span class="HTitleText1">EXAMEN ET RAPPORT</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-30"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-31"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

