<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les régimes de pension agréés collectifs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OBJET DE LA PRÉSENTE LOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CHAMP D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HTitleText1">ACCORDS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-6"><span class="HTitleText1">ATTRIBUTIONS DU SURINTENDANT</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-7"><span class="HTitleText1">AGRÉMENT</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-8"><span class="HTitleText1">GESTION DES RÉGIMES DE PENSION AGRÉÉS COLLECTIFS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Administrateur</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Employeur</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-3.html#h-11"><span class="HTitleText1">DIRECTIVES</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-12"><span class="HTitleText1">OPPOSITIONS ET APPELS</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-13"><span class="HTitleText1">OBLIGATIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Conditions de participation</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Immobilisation des cotisations</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Paiements variables</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Décès du participant</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Divorce, annulation du mariage, séparation ou échec de l’union de fait</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Transfert des fonds et achat de prestations viagères</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Interdiction de la discrimination sexuelle</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Droits à l’information</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-23"><span class="HTitleText2">Obligations en matière de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-5.html#h-24"><span class="HTitleText1">CESSATION ET LIQUIDATION</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-5.html#h-25"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-6.html#h-26"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-27"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-28"><span class="HTitleText1">RAPPORT AU PARLEMENT</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-29"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-7.html#h-30"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-31"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-7.html#h-32"><span class="HTitleText2">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-33"><span class="HTitleText2">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-8.html#h-34"><span class="HTitleText2">Loi sur le Bureau du surintendant des institutions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-8.html#h-35"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-8.html#h-36"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

