<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 d’exécution du budget de 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-6"><span class="HTitleText2">Règlement modifiant le <cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite> (modifications diverses, n<sup>o</sup> 3)</span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> et de textes connexes (mesures relatives à la TPS/TVH)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>106 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les remboursements aux organismes de services publics (TPS/TVH)</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les mandataires désignés (TPS/TVH)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-11"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-12"><span class="HLabel1">PARTIE 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-13"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172 - </span><a href="#h-14"><span class="HLabel2">SECTION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les accords de Bretton Woods et des accords connexes</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-15"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accord concernant la Banque asiatique d’investissement dans les infrastructures</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-16"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Accords de financement en matière de développement international</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-17"><span class="HLabel2">SECTION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>180 - </span><a href="#h-18"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-19"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-20"><span class="HLabel2">SECTION 5</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>185 - </span><a href="#h-21"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-22"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-23"><span class="HTitleText3">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="#h-24"><span class="HLabel2">SECTION 6</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-25"><span class="HLabel2">SECTION 7</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le pipe-line du Nord</cite></span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-26"><span class="HLabel2">SECTION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>195 - </span><a href="#h-27"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-28"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-29"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-30"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>217 - </span><a href="#h-31"><span class="HLabel2">SECTION 9</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2015</cite></span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-32"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Commerce au Canada et harmonisation d’exigences en matière d’efficacité énergétique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord de libre-échange canadien</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-34"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-35"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi sur l’efficacité énergétique</cite></span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-36"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>223 - </span><a href="#h-37"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-38"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-39"><span class="HTitleText4"><cite class="XRefExternalRegulation">Règlement concernant l’ombudsman de l’approvisionnement</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-40"><span class="HTitleText3">Abrogations</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-41"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>230 - </span><a href="#h-42"><span class="HLabel2">SECTION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>230 - </span><a href="#h-43"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-44"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-45"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>255 - </span><a href="#h-46"><span class="HTitleText4"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-47"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Nunavut</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-48"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Territoires du Nord-Ouest</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="#h-50"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-51"><span class="HLabel2">SECTION 12</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque de développement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-52"><span class="HLabel2">SECTION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li></ul>
</li><li><a href="#h-53"><span class="scheduleLabel">annexe</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

