<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2018 sur la convention fiscale Canada–Madagascar</a><ul class="TocIndent"><li><a href="#h-1"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention entre le Canada et la République de Madagascar en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-2"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole</span></a>
</li></ul>
</li></ul>

</nav>

