<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Mise en oeuvre de mesures concernant le règlement de revendications (Alberta et Saskatchewan), Loi sur la</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LA MISE EN OEUVRE DE MESURES CONCERNANT LE RÈGLEMENT DE REVENDICATIONS (ALBERTA ET SASKATCHEWAN)</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la mise en oeuvre de mesures concernant le règlement de revendications au Manitoba</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les droits fonciers issus de traités en Saskatchewan</cite></span></a>
</li></ul>
</li><li><a href="page-3.html#h-5"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

