<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée mondiale de sensibilisation à l’autisme</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">JOURNÉE MONDIALE DE SENSIBILISATION À L’AUTISME</span></a>
</li></ul>
</li></ul>

</nav>

