<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Accord sur les revendications territoriales des Inuit du Labrador</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">ACCORD</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">AFFECTATION DE FONDS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">FISCALITÉ</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Loi sur les parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Loi sur l’enregistrement des lobbyistes</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText2">Loi sur l’enregistrement des lobbyistes</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-18"><span class="HTitleText2">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-19"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-20"><span class="HTitleText2">Autres modifications</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-21"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

