<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Marine marchande du Canada, Loi de 2001 sur la</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Responsabilité ministérielle</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Attributions des ministres</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Inspections effectuées par les inspecteurs de la sécurité maritime et d’autres personnes</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Représentant autorisé</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Arbitres</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Documents maritimes canadiens</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-13"><span class="HTitleText2">Autres documents</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Jaugeurs</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Bureau d’examen technique en matière maritime</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Conventions internationales, protocoles et résolutions</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Ordres</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-20"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-21"><span class="HTitleText2">Droits</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-5.html#h-22"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-5.html#h-23"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">IMMATRICULATION, ENREGISTREMENT ET INSCRIPTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-5.html#h-25"><span class="HTitleText2">Registre canadien d’immatriculation des bâtiments, et registraires</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-26"><span class="HTitleText2">Immatriculation, enregistrement et inscription</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-5.html#h-27"><span class="HTitleText2">Demande</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-28"><span class="HTitleText2">Nom des bâtiments</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-29"><span class="HTitleText2">Propriété des bâtiments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-30"><span class="HTitleText2">Certificats</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-31"><span class="HTitleText2">Marques</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Avis au registraire en chef</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-6.html#h-33"><span class="HTitleText2">Tenue du Registre</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-6.html#h-34"><span class="HTitleText2">Suspension, révocation et rétablissement de l’immatriculation ou de l’enregistrement des bâtiments</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-35"><span class="HTitleText2">Garde du certificat d’immatriculation et du certificat provisoire</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-6.html#h-36"><span class="HTitleText2">Droits et obligations</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-37"><span class="HTitleText2">Hypothèques</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-7.html#h-38"><span class="HTitleText2">Transfert de bâtiments ou de parts dans un bâtiment</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-7.html#h-39"><span class="HTitleText2">Inscriptions</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-7.html#h-40"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-41"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="page-7.html#h-42"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">PERSONNEL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="page-7.html#h-43"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-7.html#h-44"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-45"><span class="HTitleText2">Capitaines</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-8.html#h-46"><span class="HTitleText2">Passagers clandestins et autres personnes</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-8.html#h-47"><span class="HTitleText2">Contrat de service</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-8.html#h-48"><span class="HTitleText2">Privilège et créances</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-8.html#h-49"><span class="HTitleText2">Certificats</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-8.html#h-50"><span class="HTitleText2">Renseignements médicaux et optométriques</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-8.html#h-51"><span class="HTitleText2">Contrats d’engagement, congédiement et registres du service en mer</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-8.html#h-52"><span class="HTitleText2">Renvoi de membres de l’équipage</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-8.html#h-53"><span class="HTitleText2">Naissances et décès</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-9.html#h-54"><span class="HTitleText2">Obligations des recruteurs d’équipage</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-9.html#h-55"><span class="HTitleText2">Règlements de différends</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-9.html#h-56"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-9.html#h-57"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-9.html#h-58"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">SÉCURITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="page-9.html#h-59"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-9.html#h-60"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-9.html#h-61"><span class="HTitleText2">Représentants autorisés</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-9.html#h-62"><span class="HTitleText2">Capitaines</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-10.html#h-63"><span class="HTitleText2">Équipage</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-10.html#h-64"><span class="HTitleText2">Passagers</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-10.html#h-65"><span class="HTitleText2">Représentants autorisés, capitaines, membres de l’équipage et autres personnes</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-10.html#h-66"><span class="HTitleText2">Construction de bâtiments</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-10.html#h-67"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-10.html#h-68"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>125 - </span><a href="page-11.html#h-69"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">SERVICES DE NAVIGATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="page-11.html#h-70"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-11.html#h-71"><span class="HTitleText2">Services de trafic maritime</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-11.html#h-72"><span class="HTitleText2">Aides à la navigation</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-11.html#h-73"><span class="HTitleText2">Opérations de recherche et de sauvetage</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-12.html#h-74"><span class="HTitleText2">Île de Sable</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-12.html#h-75"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-12.html#h-76"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-12.html#h-77"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="page-12.html#h-78"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">INCIDENTS, ACCIDENTS ET SINISTRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="page-12.html#h-79"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-12.html#h-80"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-12.html#h-81"><span class="HTitleText2">Sauvetage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142 - </span><a href="page-12.html#h-82"><span class="HTitleText3">Convention internationale de 1989 sur l’assistance</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-12.html#h-83"><span class="HTitleText3">Sauvetage par des bâtiments appartenant à Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-12.html#h-84"><span class="HTitleText3">Prescription</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-12.html#h-85"><span class="HTitleText3">Aéronefs</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-13.html#h-86"><span class="HTitleText3">Droit à la compensation</span></a>
</li></ul>
</li><li><span class='sectionRange'>148 - </span><a href="page-13.html#h-87"><span class="HTitleText2">Obligations en cas d’abordage</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-13.html#h-88"><span class="HTitleText2">Enquêtes sur les causes de décès</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-13.html#h-89"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-13.html#h-90"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-13.html#h-91"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">ÉPAVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="page-13.html#h-92"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-13.html#h-93"><span class="HTitleText2">Désignation des receveurs d’épaves</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-13.html#h-94"><span class="HTitleText2">Découverte d’épaves</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-13.html#h-95"><span class="HTitleText2">Aliénation ou destruction des épaves</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-14.html#h-96"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-14.html#h-97"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-14.html#h-98"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">POLLUTION : PRÉVENTION ET INTERVENTION — MINISTÈRE DES PÊCHES ET DES OCÉANS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="page-14.html#h-99"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-14.html#h-100"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-14.html#h-101"><span class="HTitleText2">Rejet d’hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-15.html#h-102"><span class="HTitleText2">Organismes d’intervention</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-15.html#h-103"><span class="HTitleText2">Conseils consultatifs</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-15.html#h-104"><span class="HTitleText2">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-15.html#h-105"><span class="HTitleText2">Agents chargés de la prévention de la pollution</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-16.html#h-106"><span class="HTitleText2">Détention d’un bâtiment</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-16.html#h-107"><span class="HTitleText2">Intervention</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-16.html#h-108"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-17.html#h-109"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-17.html#h-110"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">PRÉVENTION DE LA POLLUTION — MINISTÈRE DES TRANSPORTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>185 - </span><a href="page-17.html#h-111"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-17.html#h-112"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-17.html#h-113"><span class="HTitleText2">Événement de pollution</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-17.html#h-114"><span class="HTitleText2">Ordres donnés aux bâtiments</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-17.html#h-115"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-17.html#h-116"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>194 - </span><a href="page-18.html#h-117"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">EMBARCATIONS DE PLAISANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="page-18.html#h-118"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-18.html#h-119"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-18.html#h-120"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-18.html#h-121"><span class="HTitleText2">Utilisation sécuritaire des embarcations de plaisance</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-18.html#h-122"><span class="HTitleText2">Permis d’embarcation de plaisance</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-19.html#h-123"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-19.html#h-124"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>210 - </span><a href="page-19.html#h-125"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">CONTRÖLE D’APPLICATION — MINISTÈRE DES TRANSPORTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>210 - </span><a href="page-19.html#h-126"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-19.html#h-127"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-20.html#h-128"><span class="HTitleText2">Congé</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="page-20.html#h-129"><span class="HTitleText2">Voyage avec une personne à bord sans son consentement</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-20.html#h-130"><span class="HTitleText2">Dénonciation</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="page-20.html#h-131"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-20.html#h-132"><span class="HTitleText2">Analyse et examen</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="page-20.html#h-133"><span class="HTitleText2">Détention d’un bâtiment</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-21.html#h-134"><span class="HTitleText2">Vente de bâtiments</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-21.html#h-135"><span class="HTitleText2">Bâtiments étrangers en contravention de conventions internationales</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-21.html#h-136"><span class="HTitleText2">Sanctions administratives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="page-21.html#h-137"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-21.html#h-138"><span class="HTitleText3">Transactions et procès-verbaux</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-22.html#h-139"><span class="HTitleText3">Choix de poursuites</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-22.html#h-140"><span class="HTitleText3">Recouvrement des créances</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="page-22.html#h-141"><span class="HTitleText3">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-22.html#h-142"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>244 - </span><a href="page-22.html#h-143"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-22.html#h-144"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>247 - </span><a href="page-22.html#h-145"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">DISPOSITIONS DIVERSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="page-22.html#h-146"><span class="HTitleText2">Marchandises</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="page-23.html#h-147"><span class="HTitleText2">Arrimeurs</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="page-23.html#h-148"><span class="HTitleText2">Preuve des infractions par les bâtiments</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-23.html#h-149"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-23.html#h-150"><span class="HTitleText2">Mesures nécessaires</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-23.html#h-151"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="page-23.html#h-152"><span class="HTitleText2">Poursuites par procédure sommaire</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-23.html#h-153"><span class="HTitleText2">Compétence</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-23.html#h-154"><span class="HTitleText2">Avaries occasionnées par les bâtiments étrangers</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-23.html#h-155"><span class="HTitleText2">Défense</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="page-23.html#h-156"><span class="HTitleText2">Dépositions dans les procédures judiciaires</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="page-23.html#h-157"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-24.html#h-158"><span class="HTitleText2">Affectation des amendes</span></a>
</li>
<li><span class='sectionRange'>268.1 - </span><a href="page-24.html#h-159"><span class="HTitleText2">Responsabilité de l’État</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-24.html#h-160"><span class="HTitleText2">État de guerre et conflits armés</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="page-24.html#h-161"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="page-25.html#h-162"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">MODIFICATIONS CORRÉLATIVES ET DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>275 - </span><a href="page-25.html#h-163"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>275 - </span><a href="page-25.html#h-164"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-25.html#h-165"><span class="HTitleText3">Loi maritime du Canada</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-25.html#h-166"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-25.html#h-167"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="page-25.html#h-168"><span class="HTitleText3">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-25.html#h-169"><span class="HTitleText3">Loi canadienne sur la protection de l’environnement (1999)</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="page-25.html#h-170"><span class="HTitleText3">Loi sur le Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="page-25.html#h-171"><span class="HTitleText3">Loi sur le transport des marchandises par eau</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="page-25.html#h-172"><span class="HTitleText3">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>287 - </span><a href="page-25.html#h-173"><span class="HTitleText3">Loi sur la protection des pêches côtières</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="page-25.html#h-174"><span class="HTitleText3">Loi sur le cabotage</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-26.html#h-175"><span class="HTitleText3">Loi sur les contraventions</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="page-26.html#h-176"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="page-26.html#h-177"><span class="HTitleText3">Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-26.html#h-178"><span class="HTitleText3">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-26.html#h-179"><span class="HTitleText3">Loi sur les pêches</span></a>
</li>
<li><span class='sectionRange'>303 - </span><a href="page-26.html#h-180"><span class="HTitleText3">Loi sur la convention en matière de pêche dans les Grands Lacs</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="page-26.html#h-181"><span class="HTitleText3">Loi sur la santé des animaux</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="page-26.html#h-182"><span class="HTitleText3">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-26.html#h-183"><span class="HTitleText3">Loi sur la sûreté du transport maritime</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="page-26.html#h-184"><span class="HTitleText3">Loi sur l’indemnisation des marins marchands</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="page-27.html#h-185"><span class="HTitleText3">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="page-27.html#h-186"><span class="HTitleText3">Loi sur la santé des non-fumeurs</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-27.html#h-187"><span class="HTitleText3">Loi sur les eaux des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-27.html#h-188"><span class="HTitleText3">Loi sur la sûreté et la réglementation nucléaires</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-27.html#h-189"><span class="HTitleText3">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-27.html#h-190"><span class="HTitleText3">Loi sur le pilotage</span></a>
</li>
<li><span class='sectionRange'>319 - </span><a href="page-28.html#h-191"><span class="HTitleText3">Loi sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>321 - </span><a href="page-28.html#h-192"><span class="HTitleText3">Loi sur les eaux du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>322 - </span><a href="page-28.html#h-193"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>325 - </span><a href="page-29.html#h-194"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">MODIFICATIONS À LA LOI DÉROGATOIRE DE 1987 SUR LES CONFÉRENCES MARITIMES</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="page-29.html#h-195"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">MODIFICATIONS À LA LOI CANADIENNE SUR LA PROTECTION DE L’ENVIRONNEMENT (1999)</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="page-29.html#h-196"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">ABROGATIONS ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>332 - </span><a href="page-29.html#h-197"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="page-29.html#h-198"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-30.html#h-199"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - CONVENTIONS ET PROTOCOLES INTERNATIONAUX — MINISTÈRE DES TRANSPORTS</span></a>
</li>
<li><a href="page-31.html#h-200"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - CONVENTIONS ET PROTOCOLES INTERNATIONAUX — MINISTÈRE DES PÊCHES ET DES OCÉANS</span></a>
</li>
<li><a href="page-32.html#h-201"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - ASSISTANCE</span></a>
</li></ul>
</li></ul>

</nav>

