<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les conventions de Genève, la Loi constituant en corporation la Canadian Red Cross Society et la Loi sur les marques de commerce</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES CONVENTIONS DE GENÈVE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI CONSTITUANT EN CORPORATION LA <cite class="XRefExternalAct">CANADIAN RED CROSS SOCIETY</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-3"><span class="HTitleText1">LOI SUR LES MARQUES DE COMMERCE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-2.html#h-5"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

