<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code canadien du travail (congé de décès)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

