<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les aliments et drogues, la Loi sur les produits dangereux, la Loi sur les dispositifs émettant des radiations, la Loi canadienne sur la protection de l’environnement (1999), la Loi sur les produits antiparasitaires et la Loi canadienne sur la sécurité des produits de consommation et apportant des modifications connexes à une autre loi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Loi sur les aliments et drogues</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-2"><span class="HTitleText1">Loi sur les produits dangereux</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-3"><span class="HTitleText1">Loi sur les dispositifs émettant des radiations</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-4"><span class="HTitleText1">Loi canadienne sur la protection de l’environnement (1999)</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-5"><span class="HTitleText1">Loi sur les produits antiparasitaires</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-6"><span class="HTitleText1">Loi canadienne sur la sécurité des produits de consommation</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-7"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-8"><span class="HTitleText1">Modifications connexes à la <cite class="XRefExternalAct">Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-9"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-10"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

