<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi canadienne sur les sociétés par actions et la Loi canadienne sur les coopératives ainsi que d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI CANADIENNE SUR LES SOCIÉTÉS PAR ACTIONS</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-2"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">ACQUISITIONS FORCÉES</span></a>
</li>
<li><span class='sectionRange'>252.1 - </span><a href="#h-3"><span class="HLabel1">PARTIE XX.1</span> - <span class="HTitleText1">DOCUMENTS SOUS FORME ÉLECTRONIQUE OU AUTRE</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-4"><span class="HTitleText1">LOI CANADIENNE SUR LES COOPÉRATIVES</span></a>
</li>
<li><span class='sectionRange'>361.1 - </span><a href="#h-5"><span class="HLabel1">PARTIE 21.1</span> - <span class="HTitleText1">DOCUMENTS SOUS FORME ÉLECTRONIQUE OU AUTRE</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-7"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>235 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’exécution du budget de 1997</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>237 - </span><a href="#h-10"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - MODIFICATIONS MATÉRIELLES DE LA VERSION ANGLAISE DE LA LOI CANADIENNE SUR LES SOCIÉTÉS PAR ACTIONS</span></a>
</li></ul>
</li></ul>

</nav>

