<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant la protection de l’environnement en Antarctique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DISPOSITIONS INTERPRÉTATIVES</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">CHAMP D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-6"><span class="HTitleText1">PERMIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Délivrance des permis</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Évaluations environnementales</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText2">Plan de gestion des déchets et plan d’urgence</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText2">Garanties</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-12"><span class="HTitleText1">CONTRÔLE D’APPLICATION AU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText2">Agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Inspections au Canada</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-15"><span class="HTitleText2">Perquisition et saisie au Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText2">Rétention au Canada</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-17"><span class="HTitleText2">Arrêt de bâtiments canadiens</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-18"><span class="HTitleText2">Aide à donner aux agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-19"><span class="HTitleText2">Confiscation au Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText1">INSPECTIONS EN ANTARCTIQUE</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HTitleText1">ENTRAVE ET RENSEIGNEMENTS FAUX OU TROMPEURS</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-23"><span class="HTitleText1">COMMUNICATION DE RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-24"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

