<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel (courses de rue) et la Loi sur le système correctionnel et la mise en liberté sous condition en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA <cite class="XRefExternalAct">LOI SUR LE SYSTÈME CORRECTIONNEL ET LA MISE EN LIBERTÉ SOUS CONDITION</cite></span></a>
</li></ul>
</li></ul>

</nav>

