<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2017 sur la sécurité nationale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Office de surveillance des activités en matière de sécurité nationale et de renseignement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office de surveillance des activités en matière de sécurité nationale et de renseignement</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Modifications connexes et corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-2.html#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la citoyenneté</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de l’information</cite></span></a>
</li>
<li><span class='sectionRange'>37.1 - </span><a href="page-4.html#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Gendarmerie royale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-4.html#h-18"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>49.1 - </span><a href="page-5.html#h-19"><span class="HLabel1">PARTIE 1.1</span> - <span class="HTitleText1">Évitement de la complicité dans les cas de mauvais traitements infligés par des entités étrangères</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49.1 - </span><a href="page-5.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi visant à éviter la complicité dans les cas de mauvais traitements infligés par des entités étrangères</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>49.2 - </span><a href="page-6.html#h-21"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-22"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Commissaire au renseignement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="page-6.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le commissaire au renseignement</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-7.html#h-24"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-25"><span class="HTitleText2">Modifications connexes et corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="page-7.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-7.html#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-29"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-7.html#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de l’information</cite></span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-7.html#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-7.html#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-7.html#h-34"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la communication d’information ayant trait à la sécurité du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="page-7.html#h-35"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>76 - </span><a href="page-8.html#h-36"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Centre de la sécurité des télécommunications</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="page-8.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre de la sécurité des télécommunications</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-9.html#h-38"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-9.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-9.html#h-40"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="page-9.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-9.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-9.html#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-9.html#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la communication d’information ayant trait à la sécurité du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="page-9.html#h-45"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>92 - </span><a href="page-10.html#h-46"><span class="HLabel1">PARTIE 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="page-10.html#h-47"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-13.html#h-48"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="page-13.html#h-49"><span class="HLabel1">PARTIE 5</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la communication d’information ayant trait à la sécurité du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-13.html#h-50"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-14.html#h-51"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="page-14.html#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-14.html#h-53"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Pêches et des Océans</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-14.html#h-54"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-14.html#h-55"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-14.html#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de mise en oeuvre de la Convention sur les armes chimiques</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-14.html#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="page-14.html#h-58"><span class="HLabel1">PARTIE 6</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la sûreté des déplacements aériens</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-14.html#h-59"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-16.html#h-60"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="page-16.html#h-61"><span class="HLabel1">PARTIE 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Code criminel</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="page-16.html#h-62"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-17.html#h-63"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>157.1 - </span><a href="page-17.html#h-64"><span class="HTitleText2">Article 83.3 du <cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-17.html#h-65"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="page-18.html#h-66"><span class="HLabel1">PARTIE 8</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le système de justice pénale pour les adolescents</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-18.html#h-67"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Examen</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-18.html#h-68"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-20.html#h-69"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

