<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur le pétrole et le gaz des terres indiennes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LE PÉTROLE ET LE GAZ DES TERRES INDIENNES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-3.html#h-2"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

