<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi corrective de 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">MODIFICATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de la Convention sur les mines antipersonnel</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la prévention de la pollution des eaux arctiques</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence de promotion économique du Canada atlantique</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi modifiant la Loi sur les banques, la Loi sur les liquidations et les restructurations et d’autres lois relatives aux institutions financières et apportant des modifications corrélatives à certaines lois</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’exécution du budget de 1997</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque de développement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil des Arts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la marine marchande du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur la protection de l’environnement (1999)</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil de la radiodiffusion et des télécommunications canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit d’auteur</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les crimes contre l’humanité et les crimes de guerre</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’exportation et l’importation de biens culturels</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’inspection de l’électricité et du gaz</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’équité en matière d’emploi</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la surveillance du secteur énergétique</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les dessins industriels</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-3.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1994 sur la convention concernant les oiseaux migrateurs</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-3.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre national des Arts</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-3.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sûreté et la réglementation nucléaires</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-4.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-4.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le partage des prestations de retraite</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-4.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1985 sur les normes de prestation de pension</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-5.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-5.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-5.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les poids et mesures</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-5.html#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’extraction de l’or dans le Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-5.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’extraction du quartz dans le Yukon</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

