<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Jour commémoratif de la famine et du génocide ukrainiens (« l’Holodomor »)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">JOUR COMMÉMORATIF DE LA FAMINE ET DU GÉNOCIDE UKRAINIENS (« L’HOLODOMOR »)</span></a>
</li></ul>
</li></ul>

</nav>

