<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi protégeant les victimes des délinquants sexuels</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR L’ENREGISTREMENT DE RENSEIGNEMENTS SUR LES DÉLINQUANTS SEXUELS</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR LA DÉFENSE NATIONALE</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-5"><span class="HTitleText1">LOI SUR LE TRANSFÈREMENT INTERNATIONAL DES DÉLINQUANTS</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-6"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI SUR LE CASIER JUDICIAIRE</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

