<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les douanes et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES DOUANES</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>86 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-4"><span class="HTitleText2">Loi sur la Société canadienne des postes</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-5"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-6"><span class="HTitleText2">Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-7"><span class="HTitleText2">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-8"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-9"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

