<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant la délivrance simple et sécuritaire des permis d’armes à feu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES ARMES À FEU</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-4"><span class="HTitleText1">MODIFICATION CONNEXE À LA <cite class="XRefExternalAct">LOI SUR LES DOUANES</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-5"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA <cite class="XRefExternalAct">LOI SUR L’ABOLITION DU REGISTRE DES ARMES D’ÉPAULE</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

