<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel et une autre loi</a><ul class="TocIndent"><li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR LE TRANSFÈREMENT INTERNATIONAL DES DÉLINQUANTS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

