<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord de libre-échange Canada–Ukraine</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’Accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approbation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Groupes spéciaux, groupes d’experts, comités, sous-comités, groupes de travail et autres organismes</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-20"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-22"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-24"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

