<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la gestion financière et statistique des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DROITS DES AUTOCHTONES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">POUVOIRS FINANCIERS DES PREMIÈRES NATIONS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">COMMISSION DE LA FISCALITÉ DES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-8"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Attributions</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Normes et procédure</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-4.html#h-12"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">CONSEIL DE GESTION FINANCIÈRE DES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Attributions</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-17"><span class="HTitleText2">Normes et procédure</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-18"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="page-5.html#h-19"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">ADMINISTRATION FINANCIÈRE DES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="page-5.html#h-20"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-21"><span class="HTitleText2">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-6.html#h-22"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-6.html#h-23"><span class="HTitleText2">Attributions</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-7.html#h-24"><span class="HTitleText2">Disposition générale</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-7.html#h-25"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="page-8.html#h-26"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">INSTITUT DE LA STATISTIQUE DES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>90 - </span><a href="page-8.html#h-27"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-8.html#h-28"><span class="HTitleText2">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-8.html#h-29"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-8.html#h-30"><span class="HTitleText2">Attributions</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-9.html#h-31"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-9.html#h-32"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-33"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="page-9.html#h-34"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">GESTION ET CONTRÔLE FINANCIERS</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-10.html#h-35"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="page-10.html#h-36"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-11.html#h-37"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="page-11.html#h-38"><span class="HLabel1"><strong>PARTIE 8</strong></span> - <span class="HTitleText1"><strong>DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES, DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</strong></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="page-11.html#h-39"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-11.html#h-40"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="page-11.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-11.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-11.html#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les Indiens</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-11.html#h-44"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-11.html#h-45"><span class="HTitleText1"><strong><em>Loi sur l’autonomie gouvernementale de la première nation de Westbank</em></strong></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>154 - </span><a href="page-12.html#h-46"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-13.html#h-48"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

