<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 1 d’exécution du budget de 2016</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-4"><span class="HTitleText2">Modifications connexes à d’autres lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les allocations spéciales pour enfants</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la prestation universelle pour la garde d’enfants</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-7"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-9"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-10"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> (mesures relatives à la TPS/TVH)</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-11"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> (mesures relatives à l’accise), de la <cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite> et d’autres textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les licences, agréments et autorisations d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur l’estampillage et le marquage des produits du tabac</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-16"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="#h-17"><span class="HLabel2">SECTION 1</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi fédérale sur l’équilibre budgétaire</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-18"><span class="HLabel2">SECTION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="#h-19"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-20"><span class="HTitleText3">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-21"><span class="HTitleText4">Allocation pour perte de revenus</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-22"><span class="HTitleText4">Indemnité d’invalidité et indemnité de décès</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-23"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-24"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’aide en matière d’éducation aux enfants des anciens combattants décédés</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-25"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-26"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>115 - </span><a href="#h-27"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-28"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-29"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Institutions financières (dispositions de temporarisation)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>123 - </span><a href="#h-34"><span class="HLabel2">SECTION 4</span></span> - <span class="HTitleText2">Modification de la <cite class="XRefExternalAct">Loi sur les banques</cite> (coopératives de crédit fédérales)</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-35"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Régime de recapitalisation interne des banques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-36"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-37"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-38"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-39"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-40"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-41"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-42"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="#h-43"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Premier dirigeant de la Société d’assurance-dépôts du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Bureau du surintendant des institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur les paiements</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Loi nationale sur l’habitation</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-47"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-48"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-49"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-50"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-51"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-52"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de l’assurance hypothécaire résidentielle</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>180 - </span><a href="#h-53"><span class="HLabel2">SECTION 7</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-54"><span class="HLabel2">SECTION 8</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 - </span><a href="#h-55"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-56"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="#h-57"><span class="HLabel2">SECTION 9</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité de la vieillesse</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="#h-58"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-59"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="#h-60"><span class="HLabel2">SECTION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures spéciales d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-61"><span class="HLabel2">SECTION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1985 sur les normes de prestation de pension</cite></span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-62"><span class="HLabel2">SECTION 12</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>207 - </span><a href="#h-63"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-64"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-65"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-66"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2015</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-67"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="#h-68"><span class="HLabel2">SECTION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-69"><span class="HLabel2">SECTION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi, la croissance et la prospérité durable</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-70"><span class="HLabel2">SECTION 15</span> - <span class="HTitleText2">Fondation du Canada pour l’appui technologique au développement durable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>237 - </span><a href="#h-71"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Fondation du Canada pour l’appui technologique au développement durable</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-72"><span class="HTitleText3"><cite class="XRefExternalAct">Loi d’exécution du budget de 2007</cite></span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-73"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-74"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

