<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la mise en quarantaine</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">POUVOIRS DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">VOYAGEURS</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-7"><span class="HTitleText1">VÉHICULES</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-8"><span class="HTitleText1">CADAVRES, ORGANES ET RESTES HUMAINS</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-9"><span class="HTitleText1">POUVOIRS GÉNÉRAUX</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-10"><span class="HTitleText1">RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-11"><span class="HTitleText1">URGENCES</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-12"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-13"><span class="HTitleText1">LOI SUR LES TEXTES RÉGLEMENTAIRES</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-14"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-15"><span class="HTitleText1">DISPOSITIONS CONNEXES</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-16"><span class="HTitleText1">MODIFICATION CORRÉLATIVE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-17"><span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-18"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-19"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-20"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

