<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi donnant suite à la décision de la Cour suprême du Canada dans l’affaire R. c. Shoker</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE SUBSIDIAIRE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

