<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la sûreté et la sécurité en matière énergétique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODERNISATION DU RÉGIME CONCERNANT LES OPÉRATIONS PÉTROLIÈRES AU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les opérations pétrolières au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi fédérale sur les hydrocarbures</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</cite></span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-7"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-8"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les paiements de péréquation compensatoires supplémentaires à la Nouvelle-Écosse et à Terre-Neuve-et-Labrador</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-9"><span class="HTitleText3"><cite class="XRefExternalAct">Loi d’exécution du budget et de l’énoncé économique de 2007</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-10"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-11"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="#h-12"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA RESPONSABILITÉ ET L’INDEMNISATION EN MATIÈRE NUCLÉAIRE</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-13"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-14"><span class="HTitleText2">Modification de la <cite class="XRefExternalAct">Loi sur la responsabilité et l’indemnisation en matière nucléaire</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-15"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 1992 sur le transport des marchandises dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sûreté et la réglementation nucléaires</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-18"><span class="HTitleText2">Terminologie</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-19"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-20"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-21"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-24"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li></ul>
</li></ul>

</nav>

