<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à renforcer la justice militaire pour la défense du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA DÉFENSE NATIONALE</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-11.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-12.html#h-4"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>115 - </span><a href="page-12.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-12.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-12.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-12.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-12.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-12.html#h-10"><span class="HTitleText2">Loi modifiant la <cite class="XRefExternalAct">Loi sur la défense nationale</cite> et d’autres lois en conséquence</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-12.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-12.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2002 sur la sécurité publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="page-12.html#h-13"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-13.html#h-14"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

