<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le droit de vote des employés</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CANADIEN DU TRAVAIL</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES RELATIONS DE TRAVAIL AU PARLEMENT</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES RELATIONS DE TRAVAIL DANS LA FONCTION PUBLIQUE</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

