<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
LOI CONSTITUTIONNELLE DE 1867</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">I. Préliminaires</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-2"><span class="HTitleText1">II. Union</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-3"><span class="HTitleText1">III. Pouvoir exécutif</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-4"><span class="HTitleText1">IV. Pouvoir législatif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Le Sénat</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-1.html#h-6"><span class="HTitleText2">La Chambre des Communes</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Législation financière; Sanction royale</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="page-2.html#h-8"><span class="HTitleText1">V. Constitutions provinciales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="page-2.html#h-9"><span class="HTitleText2">Pouvoir exécutif</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Pouvoir législatif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="page-2.html#h-11"><span class="HTitleText3">1. Ontario</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-2.html#h-12"><span class="HTitleText3">2. Québec</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-2.html#h-13"><span class="HTitleText3">3. Ontario et Québec</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-2.html#h-14"><span class="HTitleText3">4. Nouvelle-Écosse et Nouveau-Brunswick</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-2.html#h-15"><span class="HTitleText3">5. Ontario, Québec et Nouvelle-Écosse</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-2.html#h-16"><span class="HTitleText3">6. Les quatre provinces</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-3.html#h-17"><span class="HTitleText1">VI. Distribution des pouvoirs législatifs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Pouvoirs du parlement</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-3.html#h-19"><span class="HTitleText2">Pouvoirs exclusifs des législatures provinciales</span></a>
</li>
<li><span class='sectionRange'>92A - </span><a href="page-3.html#h-20"><span class="HTitleText2">Ressources naturelles non renouvelables, ressources forestières et énergie électrique</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-3.html#h-21"><span class="HTitleText2">Éducation</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-3.html#h-22"><span class="HTitleText2">Uniformité des lois dans Ontario, la Nouvelle-Écosse et le Nouveau-Brunswick</span></a>
</li>
<li><span class='sectionRange'>94A - </span><a href="page-3.html#h-23"><span class="HTitleText2">Pensions de vieillesse</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-3.html#h-24"><span class="HTitleText2">Agriculture et Immigration</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="page-3.html#h-25"><span class="HTitleText1">VII. Judicature</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-3.html#h-26"><span class="HTitleText1">VIII. Revenus; dettes; actifs; taxe</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-4.html#h-27"><span class="HTitleText1">IX. Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-4.html#h-28"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-4.html#h-29"><span class="HTitleText2">Ontario et Québec</span></a>
</li></ul>
</li><li><span class='sectionRange'>145 - </span><a href="page-4.html#h-30"><span class="HTitleText1">X. Chemin de fer intercolonial</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-4.html#h-31"><span class="HTitleText1">XI. Admission des autres colonies</span></a>
</li>
<li><a href="page-5.html#h-32"><span class="scheduleLabel">PREMIÈRE ANNEXE</span> - <span class="scheduleTitleText"> - Districts électoraux d’Ontario</span></a>
</li>
<li><a href="page-6.html#h-33"><span class="scheduleLabel">DEUXIÈME ANNEXE</span> - <span class="scheduleTitleText"> - Districts Électoraux de Québec spécialement fixés</span></a>
</li>
<li><a href="page-7.html#h-34"><span class="scheduleLabel">TROISIÈME ANNEXE</span> - <span class="scheduleTitleText"> - Travaux et propriétés publiques de la province devant appartenir au Canada</span></a>
</li>
<li><a href="page-8.html#h-35"><span class="scheduleLabel">QUATRIÈME ANNEXE</span> - <span class="scheduleTitleText"> - Actif devenant la propriété commune d’Ontario et Québec</span></a>
</li>
<li><a href="page-9.html#h-36"><span class="scheduleLabel">CINQUIÈME ANNEXE</span></a>
</li>
<li><a href="page-10.html#h-37"><span class="scheduleLabel">SIXIÈME ANNEXE</span> - <span class="scheduleTitleText"> - Production primaire tirée des ressources naturelles non renouvelables et des ressources forestières</span></a>
</li></ul>
</li><li><span class='sectionRange'>1 - </span><a href="page-11.html#h-38">LOI DE 1982 SUR LE CANADA</a>
</li>
<li><span class='sectionRange'>1 - </span><a href="page-12.html#h-39">LOI CONSTITUTIONNELLE DE 1982</a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-12.html#h-40"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Charte canadienne des droits et libertés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-12.html#h-41"><span class="HTitleText2">Garantie des droits et libertés</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-12.html#h-42"><span class="HTitleText2">Libertés fondamentales</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-12.html#h-43"><span class="HTitleText2">Droits démocratiques</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-12.html#h-44"><span class="HTitleText2">Liberté de circulation et d’établissement</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-12.html#h-45"><span class="HTitleText2">Garanties juridiques</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-12.html#h-46"><span class="HTitleText2">Droits à l’égalité</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-12.html#h-47"><span class="HTitleText2">Langues officielles du Canada</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-12.html#h-48"><span class="HTitleText2">Droits à l’instruction dans la langue de la minorité</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-12.html#h-49"><span class="HTitleText2">Recours</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-12.html#h-50"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-12.html#h-51"><span class="HTitleText2">Application de la charte</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-12.html#h-52"><span class="HTitleText2">Titre</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-13.html#h-53"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Droits des peuples autochtones du Canada</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-13.html#h-54"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Péréquation et inégalités régionales</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-13.html#h-55"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Conférence constitutionnelle</span></a>
</li>
<li><span class='sectionRange'>37.1 - </span><a href="page-13.html#h-56"><span class="HLabel1">PARTIE IV.1</span> - <span class="HTitleText1">Conférences constitutionnelles</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-13.html#h-57"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Procédure de modification de la Constitution du Canada<span class="wb-invisible">Note de fin de page </span><sup>(102)</sup></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-13.html#h-58"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi constitutionnelle de 1867</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-13.html#h-59"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-14.html#h-60"><span class="scheduleTitleText">Annexe de la Loi constitutionnelle de 1982</span> </a>
</li></ul>
</li>
<li><a href="endNotes.html"><span class="scheduleTitleText">Notes</span> </a>
</li></ul>

</nav>

