<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2012 apportant des modifications techniques concernant l’impôt et les taxes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX BIENS DE FONDS DE PLACEMENT NON-RÉSIDENTS ET AUX FIDUCIES NON-RÉSIDENTES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-4"><span class="HTitleText2">Loi de 2000 modifiant l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-5"><span class="HTitleText2">Loi sur l’interprétation des conventions en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-6"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX SOCIÉTÉS ÉTRANGÈRES AFFILIÉES : RÈGLES SUR LES SURPLUS ET AUTRES MODIFICATIONS TECHNIQUES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-8"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-9"><span class="HTitleText2">Loi d’exécution du budget et de l’énoncé économique de 2007</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-10"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-11"><span class="HTitleText2">Cotisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-12"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX SOCIÉTÉS ÉTRANGÈRES AFFILIÉES : RÉORGANISATIONS ET DISTRIBUTIONS ET AUTRES MODIFICATIONS TECHNIQUES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-13"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-14"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-15"><span class="HTitleText2">Choix et cotisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-16"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">MODIFICATIONS DE LA LOI DE L’IMPÔT SUR LE REVENU RELATIVES AU BIJURIDISME</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-17"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">AUTRES MODIFICATIONS CONCERNANT LA LOI DE L’IMPÔT SUR LE REVENU ET DES TEXTES CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="#h-18"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-19"><span class="HTitleText2">Loi modifiant la Loi de l’impôt sur le revenu (ressources naturelles)</span></a>
</li>
<li><span class='sectionRange'>369 - </span><a href="#h-20"><span class="HTitleText2">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>370 - </span><a href="#h-21"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="#h-22"><span class="HTitleText2">Loi de 1997 modifiant l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-23"><span class="HTitleText2">Loi de 2000 modifiant l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>375 - </span><a href="#h-24"><span class="HTitleText2">Loi sur le soutien de la croissance de l’économie et de l’emploi au Canada</span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="#h-25"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>413 - </span><a href="#h-26"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">MESURES RELATIVES À LA TAXE DE VENTE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>413 - </span><a href="#h-27"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>417 - </span><a href="#h-28"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX ACCORDS FISCAUX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>417 - </span><a href="#h-29"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="#h-30"><span class="HTitleText2">Loi sur la taxe sur les produits et services des premières nations</span></a>
</li></ul>
</li><li><span class='sectionRange'>426 - </span><a href="#h-31"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><a href="#h-32"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

