<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Service administratif des tribunaux judiciaires, Loi sur le</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">SERVICE ADMINISTRATIF DES TRIBUNAUX JUDICIAIRES</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">ADMINISTRATEUR EN CHEF</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">POUVOIRS ET ATTRIBUTIONS DE L’ADMINISTRATEUR EN CHEF</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">JUGES EN CHEF</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">PERSONNEL</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">SPÉCIALISTES À CONTRAT</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText1">RAPPORT AU PARLEMENT</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LA COUR FÉDÉRALE</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-11"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LA COUR CANADIENNE DE L’IMPÔT</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-12"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LES JUGES</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-13"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de la Convention sur les mines antipersonnel</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Fonds de bienfaisance de l’armée</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la détermination de la participation et du contrôle canadiens</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord sur la Station spatiale internationale civile</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal de la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit d’auteur</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cris et les Naskapis du Québec</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’urgence sur les approvisionnements d’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’extradition</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Convention relative aux contrats de vente internationale de marchandises</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’interprétation</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des obtentions végétales</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures spéciales d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les textes réglementaires</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Cour suprême</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Convention des Nations Unies concernant les sentences arbitrales étrangères</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-56"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’autonomie gouvernementale des premières nations du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office des droits de surface du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-58"><span class="HTitleText2">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-59"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-60"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-61"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-62"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

