<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget et de l’énoncé économique de 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE SUR LES PRODUITS ET SERVICES ET LA TAXE DE VENTE HARMONISÉE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-4"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION CONCERNANT LA TAXE D’ACCISE SUR LES CARBURANTS RENOUVELABLES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES À L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-14.html#h-8"><span class="HTitleText2">Règles concernant l’application de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-14.html#h-9"><span class="HTitleText2">Loi sur l’interprétation des conventions en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-14.html#h-10"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-16.html#h-11"><span class="HTitleText2">Règlement sur le Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-16.html#h-12"><span class="HTitleText2">Règlement sur la rémunération assurable et la perception des cotisations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-16.html#h-13"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="page-18.html#h-14"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">ÉPARGNE-INVALIDITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="page-18.html#h-15"><span class="HTitleText2">Modifications relatives à l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="page-18.html#h-16"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-21.html#h-17"><span class="HTitleText3">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-21.html#h-18"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-21.html#h-19"><span class="HTitleText4">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-21.html#h-20"><span class="HTitleText4">Loi sur la sécurité de la vieillesse</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="page-22.html#h-21"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-22.html#h-22"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-22.html#h-23"><span class="HTitleText2">Loi canadienne sur l’épargne-invalidité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="page-22.html#h-24"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-23.html#h-25"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les allocations spéciales pour enfants</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-23.html#h-26"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="page-23.html#h-27"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">INCITATIF POUR L’ÉLIMINATION DES IMPÔTS PROVINCIAUX SUR LE CAPITAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>139 - </span><a href="page-23.html#h-28"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="page-23.html#h-29"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI SUR L’IMMUNITÉ DE LA BANQUE DES RÈGLEMENTS INTERNATIONAUX</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-24.html#h-30"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">RETRAITE PROGRESSIVE — MODIFICATIONS AUTRES QUE CELLES CONCERNANT L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="page-24.html#h-31"><span class="HTitleText2">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-24.html#h-32"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-24.html#h-33"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">GARANTIE DE MARCHÉ</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-24.html#h-34"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">OPÉRATIONS PÉTROLIÈRES AU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="page-24.html#h-35"><span class="HTitleText2">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-26.html#h-36"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="page-26.html#h-37"><span class="HTitleText3">Loi fédérale sur les hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-26.html#h-38"><span class="HTitleText3">Loi sur l’Office national de l’énergie</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>154 - </span><a href="page-26.html#h-39"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">MODIFICATIONS À LA LOI SUR LA PROTECTION DU REVENU AGRICOLE</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-26.html#h-40"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="page-26.html#h-41"><span class="HTitleText2">Modifications à la Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-28.html#h-42"><span class="HTitleText2">Modifications à la Loi d’exécution du budget de 2007</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-28.html#h-43"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-28.html#h-44"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-29.html#h-45"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="page-29.html#h-46"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">MODIFICATIONS À LA LOI CANADIENNE SUR L’ÉPARGNE-ÉTUDES</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-29.html#h-47"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">PARTENARIATS PUBLIC-PRIVÉ</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-29.html#h-48"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">MODIFICATIONS D’ORDRE FISCAL VISANT À METTRE EN OEUVRE L’ÉNONCÉ ÉCONOMIQUE DE 2007</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="page-29.html#h-49"><span class="HTitleText2">Modifications relatives à l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="page-29.html#h-50"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="page-29.html#h-51"><span class="HTitleText2">Modifications visant à mettre en oeuvre la réduction du taux de la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="page-29.html#h-52"><span class="HTitleText3">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="page-32.html#h-53"><span class="HTitleText2">Modifications connexes découlant de la réduction du taux de la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-32.html#h-54"><span class="HTitleText3">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-32.html#h-55"><span class="HTitleText3">Loi de 2001 sur l’accise</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="page-32.html#h-56"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-33.html#h-57"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

