<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 2009</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES À L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-19.html#h-4"><span class="HTitleText2">Loi d’exécution du budget de 2008</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-19.html#h-5"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="page-24.html#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX TAXES DE VENTE ET D’ACCISE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="page-24.html#h-7"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-24.html#h-8"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="page-25.html#h-9"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DU TARIF DES DOUANES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="page-25.html#h-10"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-28.html#h-11"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="page-28.html#h-12"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">ASSURANCE-EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="page-28.html#h-13"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-28.html#h-14"><span class="HTitleText2">Prestataires à l’étranger</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-28.html#h-15"><span class="HTitleText2">Projet pilote visant l’accroissement des prestations</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-28.html#h-16"><span class="HTitleText2">Taux de cotisation prévus par la Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-28.html#h-17"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-28.html#h-18"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-28.html#h-19"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="page-28.html#h-20"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">STABILITÉ ET EFFICACITÉ DU SYSTÈME FINANCIER</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="page-28.html#h-21"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-29.html#h-22"><span class="HLabel2">Section 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>233 - </span><a href="page-29.html#h-23"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-32.html#h-24"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>255 - </span><a href="page-32.html#h-25"><span class="HTitleText4">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="page-32.html#h-26"><span class="HTitleText4">Loi canadienne sur les paiements</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-32.html#h-27"><span class="HTitleText4">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="page-32.html#h-28"><span class="HTitleText4">Loi sur les liquidations et les restructurations</span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="page-32.html#h-29"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="page-32.html#h-30"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Loi sur le développement des exportations</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-33.html#h-31"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="page-33.html#h-32"><span class="HLabel2">Section 5</span> - <span class="HTitleText2">Loi sur le financement des petites entreprises du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="page-33.html#h-33"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-33.html#h-34"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="page-33.html#h-35"><span class="HLabel2">Section 6</span> - <span class="HTitleText2">Modification de la législation régissant les institutions financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>269 - </span><a href="page-33.html#h-36"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-34.html#h-37"><span class="HTitleText3">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-35.html#h-38"><span class="HTitleText3">Loi sur l’Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-35.html#h-39"><span class="HTitleText3">Loi sur l’association personnalisée le Bouclier vert du Canada</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="page-35.html#h-40"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="page-37.html#h-41"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-38.html#h-42"><span class="HTitleText3">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="page-38.html#h-43"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>295 - </span><a href="page-38.html#h-44"><span class="HLabel2">Section 7</span> - <span class="HTitleText2">Valeurs mobilières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>295 - </span><a href="page-38.html#h-45"><span class="HTitleText3">Réglementation des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-38.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Bureau de transition vers un régime canadien de réglementation des valeurs mobilières</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-39.html#h-47"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-39.html#h-48"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="page-39.html#h-49"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">PAIEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="page-39.html#h-50"><span class="HTitleText2">Fonds de stimulation de l’infrastructure</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="page-39.html#h-51"><span class="HTitleText2">Programme de financement de base de l’infrastructure des provinces et des territoires</span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="page-39.html#h-52"><span class="HTitleText2">Fonds Chantiers Canada — collectivités</span></a>
</li>
<li><span class='sectionRange'>303 - </span><a href="page-39.html#h-53"><span class="HTitleText2">Fonds pour l’infrastructure verte</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="page-39.html#h-54"><span class="HTitleText2">Fonds d’adaptation des collectivités</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-39.html#h-55"><span class="HTitleText2">Amélioration de l’infrastructure liée aux universités et aux collèges</span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="page-39.html#h-56"><span class="HTitleText2">Logement pour les premières nations</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="page-39.html#h-57"><span class="HTitleText2">Rénovation et modernisation du logement social</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-39.html#h-58"><span class="HTitleText2">Logement pour les aînés à faible revenu</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-39.html#h-59"><span class="HTitleText2">Logement pour les personnes handicapées</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-39.html#h-60"><span class="HTitleText2">Logement dans le Nord</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-39.html#h-61"><span class="HTitleText2">Inforoute Santé du Canada inc.</span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="page-39.html#h-62"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">LOI SUR LA PROTECTION DES EAUX NAVIGABLES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>317 - </span><a href="page-39.html#h-63"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="page-42.html#h-64"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les ponts et tunnels internationaux</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>342 - </span><a href="page-42.html#h-65"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">DISPOSITIONS DIVERSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="page-42.html#h-66"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Programme de protection des salariés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>342 - </span><a href="page-42.html#h-67"><span class="HTitleText3">Loi sur le Programme de protection des salariés</span></a>
</li>
<li><span class='sectionRange'>348 - </span><a href="page-42.html#h-68"><span class="HTitleText3"><cite class="XRefExternalRegulation">Règlement sur le Programme de protection des salariés</cite></span></a>
</li>
<li><span class='sectionRange'>355 - </span><a href="page-42.html#h-69"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="page-43.html#h-70"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>358 - </span><a href="page-43.html#h-71"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Aide financière octroyée aux étudiants par le gouvernement fédéral</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>358 - </span><a href="page-43.html#h-72"><span class="HTitleText3">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>365 - </span><a href="page-43.html#h-73"><span class="HTitleText3">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-44.html#h-74"><span class="HTitleText3">Modification corrélative à la Loi d’exécution du budget de 2008</span></a>
</li></ul>
</li><li><span class='sectionRange'>369 - </span><a href="page-44.html#h-75"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Sociétés d’État</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>369 - </span><a href="page-44.html#h-76"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="page-45.html#h-77"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="page-45.html#h-78"><span class="HTitleText4">Loi sur le Conseil des Arts du Canada</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="page-45.html#h-79"><span class="HTitleText4">Loi sur l’Office de financement de l’assurance-emploi du Canada</span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="page-45.html#h-80"><span class="HTitleText4">Loi sur la Société canadienne des postes</span></a>
</li>
<li><span class='sectionRange'>379 - </span><a href="page-45.html#h-81"><span class="HTitleText4">Loi sur la Commission canadienne du lait</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="page-45.html#h-82"><span class="HTitleText4">Loi sur la Fondation canadienne des relations raciales</span></a>
</li>
<li><span class='sectionRange'>381 - </span><a href="page-45.html#h-83"><span class="HTitleText4">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>383 - </span><a href="page-45.html#h-84"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">PAIEMENTS AUX PROVINCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>383 - </span><a href="page-45.html#h-85"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="page-47.html#h-86"><span class="HTitleText2">Paiement à la Nouvelle-Écosse</span></a>
</li></ul>
</li><li><span class='sectionRange'>393 - </span><a href="page-47.html#h-87"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">LOI SUR LE CONTRÔLE DES DÉPENSES</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="page-48.html#h-88"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">RÉMUNÉRATION ÉQUITABLE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>394 - </span><a href="page-48.html#h-89"><span class="HTitleText2">Loi sur l’équité dans la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="page-49.html#h-90"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="page-49.html#h-91"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>399 - </span><a href="page-49.html#h-92"><span class="HTitleText3">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="page-49.html#h-93"><span class="HTitleText3">Loi sur les relations de travail dans la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>406 - </span><a href="page-49.html#h-94"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>407 - </span><a href="page-49.html#h-95"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">LOI SUR LA CONCURRENCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>407 - </span><a href="page-49.html#h-96"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="page-54.html#h-97"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="page-54.html#h-98"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="page-54.html#h-99"><span class="HTitleText3">Loi sur le Tribunal de la concurrence</span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="page-54.html#h-100"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="page-54.html#h-101"><span class="HTitleText3">Loi dérogatoire de 1987 sur les conférences maritimes</span></a>
</li></ul>
</li><li><span class='sectionRange'>444 - </span><a href="page-54.html#h-102"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>445 - </span><a href="page-54.html#h-103"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">LOI SUR INVESTISSEMENT CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>445 - </span><a href="page-54.html#h-104"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="page-58.html#h-105"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="page-58.html#h-106"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>466 - </span><a href="page-58.html#h-107"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">LOI SUR LES TRANSPORTS AU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>466 - </span><a href="page-58.html#h-108"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="page-58.html#h-109"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>469 - </span><a href="page-58.html#h-110"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">LOI SUR LA PARTICIPATION PUBLIQUE AU CAPITAL D’AIR CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>469 - </span><a href="page-58.html#h-111"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>470 - </span><a href="page-58.html#h-112"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="page-58.html#h-113"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-59.html#h-114"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-60.html#h-115"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-61.html#h-116"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-62.html#h-117"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-63.html#h-118"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-64.html#h-119"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li>
<li><a href="page-65.html#h-120"><span class="scheduleLabel">ANNEXE 7</span> </a>
</li>
<li><a href="page-66.html#h-121"><span class="scheduleLabel">ANNEXE 8</span> </a>
</li>
<li><a href="page-67.html#h-122"><span class="scheduleLabel">ANNEXE 9</span> </a>
</li>
<li><a href="page-68.html#h-123"><span class="scheduleLabel">ANNEXE 10</span> </a>
</li>
<li><a href="page-69.html#h-124"><span class="scheduleLabel">ANNEXE 11</span> </a>
</li></ul>
</li></ul>

</nav>

