<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 sur les mesures d’urgence visant la COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2">Prélèvement sur le Trésor</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

