<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code criminel et la Loi sur le système correctionnel et la mise en liberté sous condition (conditions imposées aux délinquants)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE SYSTÈME CORRECTIONNEL ET LA MISE EN LIBERTÉ SOUS CONDITION</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

