<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la marine marchande du Canada, la Loi de 2001 sur la marine marchande du Canada, la Loi sur les aires marines nationales de conservation du Canada et la Loi sur les océans</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LA MARINE MARCHANDE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-2"><span class="HTitleText1">LOI DE 2001 SUR LA MARINE MARCHANDE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR LES AIRES MARINES NATIONALES DE CONSERVATION DU CANADA</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR LES OCÉANS</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

