<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à accroître la disponibilité des prêts agricoles et abrogeant la Loi sur les prêts destinés aux améliorations agricoles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES PRÊTS DESTINÉS AUX AMÉLIORATIONS AGRICOLES ET À LA COMMERCIALISATION SELON LA FORMULE COOPÉRATIVE</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES À LA LOI SUR LES BANQUES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText1">ABROGATION</span></a>
</li></ul>
</li></ul>

</nav>

