<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Régime de pensions du Canada, la Loi sur l’Office d’investissement du régime de pensions du Canada et la Loi de l’impôt sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification du Régime de pensions du Canada et de la Loi sur l’Office d’investissement du régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-15.html#h-3"><span class="HTitleText2">Loi sur l’Office d’investissement du régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-15.html#h-4"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-15.html#h-5"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="page-15.html#h-6"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1">Modifications connexes à la Loi de l’impôt sur le revenu</span></a>
</li>
<li><a href="page-17.html#h-7"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>
</li></ul>

</nav>

