<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la responsabilité en matière de carboneutralité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Cibles et plans</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">Dépôt et publication</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText1">Organisme consultatif</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">Ministre des Finances</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">Commissaire à l’environnement et au développement durable</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-12"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText1">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le vérificateur général</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

