<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant la péréquation et permettant au ministre des Finances de faire certains paiements en matière de santé</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-2"><span class="HTitleText1">RÈGLEMENT DE 1999 SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li></ul>
</li></ul>

</nav>

