<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel (aide médicale à mourir)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Code criminel</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Examen indépendant</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-4"><span class="HTitleText1">Examen</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-5"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

