<h2>D&eacute;signation ou changement de b&eacute;n&eacute;ficiaire</h2>
<p>Visant le R&eacute;gime des prestations suppl&eacute;mentaires de d&eacute;c&egrave;s Partie II de la loi sur la pension de la fonction publique</p>

<p>DIRECTIVES:</p>
<ul>
	<li>Remplir toutes parties non ombr&eacute;es. Lettres moul&eacute;es.</li>
	<li>Transmettre les copies 1 et 2 &agrave; l'addresse suivante :</li>
	<li>Approvisionnements et Services Canada C.P. 5010, Moncton, (N.-B.) E1C 8Z5</li>
	<li>La copie 3 doit &ecirc;tre transmise &agrave; votre bureau du personnel, si vous &ecirc;tes un employ&eacute; de la fonction publique.</li>
	<li>La Direction des pensions de retraite accusera r&eacute;ception de votre « D&eacute;signation ou changement de b&eacute;n&eacute;ficiaire »</li>
	<li>Vous devez contribuer au r&eacute;gime PSD pour remplir la pr&eacute;sente formule si non celle-ci sera invalide. Tant que vous contribuerez au r&eacute;gime, que vous soyez employ&eacute; ou retrait&eacute;, vous pouvez, &agrave; n'importe quel moment, d&eacute;savouer votre b&eacute;n&eacute;ficiaire, ou en nommer un nouveau</li>
	<li>La signature d'un t&eacute;moin est n&eacute;cessaire.</li>
</ul>

<p>Information requis:</p>
<ul>
	<li>Num&eacute;ro d'assurance sociale</li>
	<li>Num&eacute;ro de pension</li>
	<li>Date de naissance (jour, mois, ann&eacute;e)</li>
	<li>Sexe </li>
	<li>Nom de famille du participant, pr&eacute;nom(s)</li>
	<li>État civil (c&eacute;libataire, mari&eacute;(e), veuf(ve), autre)</li>
	<li>Adresse postale (rue, ville, province/pays, code postale)</li>
</ul>

<h3>Important</h3>
<p>Vous pouvez d&eacute;signer en tant que votre b&eacute;n&eacute;ficiaire:</p>
<ul>
	<li>Toute personne &acirc;g&eacute;e de plus de 18 ans au moment de la d&eacute;signation;</li>
	<li>Tout organisme ou l'institution de bienfaisance (&eacute;crire le nom de l'institution);</li>
	<li>Toute institution religieuse ou d'enseignement;</li>
	<li>Votre succession (&eacute;crire « succession » dans l'espace r&eacute;serv&eacute; au b&eacute;n&eacute;ficiaire)</li>
</ul>

<p>Toute d&eacute;signation ambigüe ou faite en faveur d'une personne inadmissible invalidera la pr&eacute;sente formule.</p>

<p>Par la pr&eacute;sente, j'annule toute d&eacute;signation de b&eacute;n&eacute;ficiaire ant&eacute;rieure et je nomme le b&eacute;n&eacute;ficiaire suivant:</p>
<ul>
	<li>Nom de famille du b&eacute;n&eacute;ficiaire</li>
	<li>pr&eacute;nom(s)</li>
	<li>Lien de parent&eacute;</li>
	<li>Adresse (rue, ville, province/pays, code postale)</li>
</ul>

<p>Note : Le b&eacute;n&eacute;ficiaire d&eacute;sign&eacute; peut avoir droit &agrave; certaines prestations de paiements forfaitaires payable au titre de la Partie I de la Loi sur la pension de la fonction publique.  La d&eacute;signation prend effet &agrave; la date &agrave; laquelle la pr&eacute;sente formule est remplie si celle-ci parvient &agrave; la Direction des pensions de retraite avant votre d&eacute;c&egrave;s.</p>

<p>Fait &agrave; (ville), province de _______ ce_____ jour  (mois), (ann&eacute;e).</p>
<p>Signature - participant</p>
<p>Signature - t&eacute;moin (autre que b&eacute;n&eacute;ficiaire)</p>