<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les allocations de retraite des parlementaires et la Loi sur le Parlement du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES ALLOCATIONS DE RETRAITE DES PARLEMENTAIRES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LE PARLEMENT DU CANADA</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

