
<h1 class="Part" id="h-3.141516">
<span class="HTitleText1">TABLE ANALYTIQUE</span>
</h1>
<h1 class="Part" id="h-3.141516">
<span class="HTitleText1">PROPOSITIONS VISANT À CORRIGER DES ANOMALIES, CONTRADICTIONS OU ERREURS RELEVÉES DANS LES LOIS DU CANADA ET À Y APPORTER D’AUTRES MODIFICATIONS MINEURES ET NON CONTROVERSABLES AINSI QU’À ABROGER CERTAINES DISPOSITIONS AYANT CESSÉ D’AVOIR EFFET</span>
</h1>
<h1 class="Part" id="h-3.141516">
<span class="HTitleText1">TITRE ABRÉGÉ</span>
</h1>
<p>1.</p>
<p class="TableOfProvisions">1. <cite class="XRefExternalAct">Propositions présentées en vue de la Loi corrective de 2014</cite>
</p>
<h1 class="Part" id="h-3.141516">
<span class="HLabel1">PARTIE 1</span>
<span class="HTitleText1">MODIFICATIONS</span>
</h1>
<p>
<strong>2.</strong>
</p>
<p class="TableOfProvisions">
<strong>2.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’accès à l’information</cite>
</strong>
</p>
<p>
<strong>3-4.</strong>
</p>
<p class="TableOfProvisions">
<strong>3-4.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’aéronautique</cite>
</strong>
</p>
<p>
<strong>5.</strong>
</p>
<p class="TableOfProvisions">
<strong>5.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les banques</cite>
</strong>
</p>
<p>
<strong>6-10.</strong>
</p>
<p class="TableOfProvisions">
<strong>6-10.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite>
</strong>
</p>
<p>
<strong>11.</strong>
</p>
<p class="TableOfProvisions">
<strong>11.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les produits agricoles au Canada</cite>
</strong>
</p>
<p>
<strong>12.</strong>
</p>
<p class="TableOfProvisions">
<strong>12.</strong> <strong>
<cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite>
</strong>
</p>
<p>
<strong>13.</strong>
</p>
<p class="TableOfProvisions">
<strong>13.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les corporations canadiennes</cite>
</strong>
</p>
<p>
<strong>14.</strong>
</p>
<p class="TableOfProvisions">
<strong>14.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la preuve au Canada</cite>
</strong>
</p>
<p>
<strong>15.</strong>
</p>
<p class="TableOfProvisions">
<strong>15.</strong> <strong>
<cite class="XRefExternalAct">Code canadien du travail</cite>
</strong>
</p>
<p>
<strong>16-17.</strong>
</p>
<p class="TableOfProvisions">
<strong>16-17.</strong> <strong>
<cite class="XRefExternalAct">Loi maritime du Canada</cite>
</strong>
</p>
<p>
<strong>18-22.</strong>
</p>
<p class="TableOfProvisions">
<strong>18-22.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite>
</strong>
</p>
<p>
<strong>23.</strong>
</p>
<p class="TableOfProvisions">
<strong>23.</strong> <strong>
<cite class="XRefExternalAct">Loi canadienne sur les organisations à but non lucratif</cite>
</strong>
</p>
<p>
<strong>24-29.</strong>
</p>
<p class="TableOfProvisions">
<strong>24-29.</strong> <strong>
<cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite>
</strong>
</p>
<p>
<strong>30-34.</strong>
</p>
<p class="TableOfProvisions">
<strong>30-34.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les transports au Canada</cite>
</strong>
</p>
<p>
<strong>35.</strong>
</p>
<p class="TableOfProvisions">
<strong>35.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite>
</strong>
</p>
<p>
<strong>36.</strong>
</p>
<p class="TableOfProvisions">
<strong>36.</strong> <strong>
<cite class="XRefExternalAct">Loi de mise en oeuvre de la Convention sur les armes chimiques</cite>
</strong>
</p>
<p>
<strong>37.</strong>
</p>
<p class="TableOfProvisions">
<strong>37.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le cabotage</cite>
</strong>
</p>
<p>
<strong>38.</strong>
</p>
<p class="TableOfProvisions">
<strong>38.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite>
</strong>
</p>
<p>
<strong>39-42.</strong>
</p>
<p class="TableOfProvisions">
<strong>39-42.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la concurrence</cite>
</strong>
</p>
<p>
<strong>43.</strong>
</p>
<p class="TableOfProvisions">
<strong>43.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’emballage et l’étiquetage des produits de consommation</cite>
</strong>
</p>
<p>
<strong>44.</strong>
</p>
<p class="TableOfProvisions">
<strong>44.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite>
</strong>
</p>
<p>
<strong>45-60.</strong>
</p>
<p class="TableOfProvisions">
<strong>45-60.</strong> <strong>
<cite class="XRefExternalAct">Code criminel</cite>
</strong>
</p>
<p>
<strong>61-64.</strong>
</p>
<p class="TableOfProvisions">
<strong>61-64.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les douanes</cite>
</strong>
</p>
<p>
<strong>65-75.</strong>
</p>
<p class="TableOfProvisions">
<strong>65-75.</strong> <strong>
<cite class="XRefExternalAct">Tarif des douanes</cite>
</strong>
</p>
<p>
<strong>76.</strong>
</p>
<p class="TableOfProvisions">
<strong>76.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la production de défense</cite>
</strong>
</p>
<p>
<strong>77.</strong>
</p>
<p class="TableOfProvisions">
<strong>77.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le ministère des Anciens Combattants</cite>
</strong>
</p>
<p>
<strong>78.</strong>
</p>
<p class="TableOfProvisions">
<strong>78.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le divorce</cite>
</strong>
</p>
<p>
<strong>79.</strong>
</p>
<p class="TableOfProvisions">
<strong>79.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’Agence de développement économique du Canada pour les régions du Québec</cite>
</strong>
</p>
<p>
<strong>80-82.</strong>
</p>
<p class="TableOfProvisions">
<strong>80-82.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la révision des limites des circonscriptions électorales</cite>
</strong>
</p>
<p>
<strong>83.</strong>
</p>
<p class="TableOfProvisions">
<strong>83.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’inspection de l’électricité et du gaz</cite>
</strong>
</p>
<p>
<strong>84.</strong>
</p>
<p class="TableOfProvisions">
<strong>84.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les explosifs</cite>
</strong>
</p>
<p>
<strong>85-94.</strong>
</p>
<p class="TableOfProvisions">
<strong>85-94.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les offices des produits agricoles</cite>
</strong>
</p>
<p>
<strong>95-98.</strong>
</p>
<p class="TableOfProvisions">
<strong>95-98.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite>
</strong>
</p>
<p>
<strong>99.</strong>
</p>
<p class="TableOfProvisions">
<strong>99.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les pêches</cite>
</strong>
</p>
<p>
<strong>100.</strong>
</p>
<p class="TableOfProvisions">
<strong>100.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’équité entre les sexes relativement à l’inscription au registre des Indiens</cite>
</strong>
</p>
<p>
<strong>101.</strong>
</p>
<p class="TableOfProvisions">
<strong>101.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite>
</strong>
</p>
<p>
<strong>102-109.</strong>
</p>
<p class="TableOfProvisions">
<strong>102-109.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la santé des animaux</cite>
</strong>
</p>
<p>
<strong>110-119.</strong>
</p>
<p class="TableOfProvisions">
<strong>110-119.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite>
</strong>
</p>
<p>
<strong>120.</strong>
</p>
<p class="TableOfProvisions">
<strong>120.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les Indiens</cite>
</strong>
</p>
<p>
<strong>121-123.</strong>
</p>
<p class="TableOfProvisions">
<strong>121-123.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite>
</strong>
</p>
<p>
<strong>124-125.</strong>
</p>
<p class="TableOfProvisions">
<strong>124-125.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les ponts et tunnels internationaux</cite>
</strong>
</p>
<p>
<strong>126.</strong>
</p>
<p class="TableOfProvisions">
<strong>126.</strong> <strong>
<cite class="XRefExternalAct">Loi d’interprétation</cite>
</strong>
</p>
<p>
<strong>127-130.</strong>
</p>
<p class="TableOfProvisions">
<strong>127-130.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les juges</cite>
</strong>
</p>
<p>
<strong>131.</strong>
</p>
<p class="TableOfProvisions">
<strong>131.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la réédiction de textes législatifs</cite>
</strong>
</p>
<p>
<strong>132.</strong>
</p>
<p class="TableOfProvisions">
<strong>132.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la Bibliothèque et les Archives du Canada</cite>
</strong>
</p>
<p>
<strong>133.</strong>
</p>
<p class="TableOfProvisions">
<strong>133.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’inspection des viandes</cite>
</strong>
</p>
<p>
<strong>134-135.</strong>
</p>
<p class="TableOfProvisions">
<strong>134-135.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’indemnisation des marins marchands</cite>
</strong>
</p>
<p>
<strong>136.</strong>
</p>
<p class="TableOfProvisions">
<strong>136.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la défense nationale</cite>
</strong>
</p>
<p>
<strong>137.</strong>
</p>
<p class="TableOfProvisions">
<strong>137.</strong> <strong>
<cite class="XRefExternalAct">Loi relative au supplément d’aide financière à Terre-Neuve</cite>
</strong>
</p>
<p>
<strong>138.</strong>
</p>
<p class="TableOfProvisions">
<strong>138.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la sûreté et la réglementation nucléaires</cite>
</strong>
</p>
<p>
<strong>139.</strong>
</p>
<p class="TableOfProvisions">
<strong>139.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les océans</cite>
</strong>
</p>
<p>
<strong>140.</strong>
</p>
<p class="TableOfProvisions">
<strong>140.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les brevets</cite>
</strong>
</p>
<p>
<strong>141-142.</strong>
</p>
<p class="TableOfProvisions">
<strong>141-142.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les pensions</cite>
</strong>
</p>
<p>
<strong>143.</strong>
</p>
<p class="TableOfProvisions">
<strong>143.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’activité physique et le sport</cite>
</strong>
</p>
<p>
<strong>144-148.</strong>
</p>
<p class="TableOfProvisions">
<strong>144-148.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la protection des végétaux</cite>
</strong>
</p>
<p>
<strong>149.</strong>
</p>
<p class="TableOfProvisions">
<strong>149.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite>
</strong>
</p>
<p>
<strong>150.</strong>
</p>
<p class="TableOfProvisions">
<strong>150.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite>
</strong>
</p>
<p>
<strong>151.</strong>
</p>
<p class="TableOfProvisions">
<strong>151.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite>
</strong>
</p>
<p>
<strong>152.</strong>
</p>
<p class="TableOfProvisions">
<strong>152.</strong> <strong>
<cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite>
</strong>
</p>
<p>
<strong>153.</strong>
</p>
<p class="TableOfProvisions">
<strong>153.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le parc marin du Saguenay — Saint-Laurent</cite>
</strong>
</p>
<p>
<strong>154.</strong>
</p>
<p class="TableOfProvisions">
<strong>154.</strong> <strong>
<cite class="XRefExternalAct">Loi sur l’administration des biens saisis</cite>
</strong>
</p>
<p>
<strong>155.</strong>
</p>
<p class="TableOfProvisions">
<strong>155.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les espèces en péril</cite>
</strong>
</p>
<p>
<strong>156-157.</strong>
</p>
<p class="TableOfProvisions">
<strong>156-157.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le tabac</cite>
</strong>
</p>
<p>
<strong>158.</strong>
</p>
<p class="TableOfProvisions">
<strong>158.</strong> <strong>
<cite class="XRefExternalAct">Loi de 1992 sur le transport des marchandises dangereuses</cite>
</strong>
</p>
<p>
<strong>159.</strong>
</p>
<p class="TableOfProvisions">
<strong>159.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite>
</strong>
</p>
<p>
<strong>160-161.</strong>
</p>
<p class="TableOfProvisions">
<strong>160-161.</strong> <strong>
<cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite>
</strong>
</p>
<p>
<strong>162-168.</strong>
</p>
<p class="TableOfProvisions">
<strong>162-168.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les forces étrangères présentes au Canada</cite>
</strong>
</p>
<p>
<strong>169-170.</strong>
</p>
<p class="TableOfProvisions">
<strong>169-170.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les allocations aux anciens combattants</cite>
</strong>
</p>
<p>
<strong>171-173.</strong>
</p>
<p class="TableOfProvisions">
<strong>171-173.</strong> <strong>
<cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite>
</strong>
</p>
<h1 class="Part" id="h-3.141516">
<span class="HLabel1">PARTIE 2</span>
<span class="HTitleText1">TERMINOLOGIE</span>
</h1>
<p>
<strong>174.</strong>
</p>
<p class="TableOfProvisions">
<strong>174.</strong> <strong>Remplacement de « Terre-Neuve »</strong>
</p>
<h1 class="Part" id="h-3.141516">
<span class="HLabel1">PARTIE 3</span>
<span class="HTitleText1">DISPOSITIONS DE COORDINATION</span>
</h1>
<p>
<strong>175.</strong>
</p>
<p class="TableOfProvisions">
<strong>175.</strong> <strong>2009, ch. 23</strong>
</p>
<p>
<strong>176.</strong>
</p>
<p class="TableOfProvisions">
<strong>176.</strong> <strong>2012, ch. 24</strong>
</p>
<p>
<strong>177.</strong>
</p>
<p class="TableOfProvisions">
<strong>177.</strong> <strong>Projet de loi C-31</strong>
</p>