<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Espèces en péril, Loi sur les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-4"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-5"><span class="HTitleText1">CONSEIL CANADIEN POUR LA CONSERVATION DES ESPÈCES EN PÉRIL</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-6"><span class="HTitleText1">APPLICATION DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="page-2.html#h-7"><span class="HTitleText1">PLAN D’ACTION POUR L’INTENDANCE</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-8"><span class="HTitleText1">INTENDANCE</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-9"><span class="HTitleText1">PROCESSUS D’INSCRIPTION DES ESPÈCES SAUVAGES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Comité sur la situation des espèces en péril au Canada</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Révision et rapports</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-12"><span class="HTitleText2">Liste des espèces en péril</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-4.html#h-13"><span class="HTitleText1">MESURES DE PROTECTION DES ESPÈCES SAUVAGES INSCRITES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Interdictions générales</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Rétablissement des espèces en voie de disparition, menacées et disparues du pays</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-4.html#h-16"><span class="HTitleText3">Programme de rétablissement</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-17"><span class="HTitleText3">Plan d’action</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Protection de l’habitat essentiel</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-7.html#h-19"><span class="HTitleText2">Gestion des espèces préoccupantes</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-7.html#h-20"><span class="HTitleText2">Accords et permis</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-8.html#h-21"><span class="HTitleText2">Révision des projets</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-8.html#h-22"><span class="HTitleText2">Décrets d’urgence</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-8.html#h-23"><span class="HTitleText2">Exceptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="page-9.html#h-24"><span class="HTitleText1">CONTRÔLE D’APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="page-9.html#h-25"><span class="HTitleText2">Agents de l’autorité</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-9.html#h-26"><span class="HTitleText2">Visite</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-9.html#h-27"><span class="HTitleText2">Destination des objets saisis</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-9.html#h-28"><span class="HTitleText2">Aide à donner aux agents de l’autorité</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-9.html#h-29"><span class="HTitleText2">Enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="page-10.html#h-30"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-11.html#h-31"><span class="HTitleText1">MESURES DE RECHANGE</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-12.html#h-32"><span class="HTitleText1">REGISTRE</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-12.html#h-33"><span class="HTitleText1">FRAIS ET DROITS</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-12.html#h-34"><span class="HTitleText1">RAPPORTS ET EXAMEN DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-13.html#h-35"><span class="HTitleText1">ÉVALUATION DES ESPÈCES SAUVAGES FIGURANT AUX ANNEXES</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-13.html#h-36"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="page-13.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les espèces sauvages du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-13.html#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur l’évaluation environnementale</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-13.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1994 sur la convention concernant les oiseaux migrateurs</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-13.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection d’espèces animales ou végétales sauvages et la réglementation de leur commerce international et interprovincial</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>141.1 - </span><a href="page-13.html#h-41"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-14.html#h-42"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-15.html#h-43"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - LISTE DES ESPÈCES EN PÉRIL</span></a>
</li>
<li><a href="page-16.html#h-44"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-17.html#h-45"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - ESPÈCES PRÉOCCUPANTES</span></a>
</li></ul>
</li></ul>

</nav>

