<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Revendications territoriales et autonomie gouvernementale du peuple tlicho</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">ACCORD</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">CADRE LÉGISLATIF</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">AFFECTATION DE FONDS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">FISCALITÉ</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">OFFICE DES RESSOURCES RENOUVELABLES DU WEKEEZHII</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText1">MODIFICATION DE LA LOI SUR LA GESTION DES RESSOURCES DE LA VALLÉE DU MACKENZIE</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-10"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-11"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97 - </span><a href="#h-12"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-13"><span class="HTitleText2">Loi sur l’arpentage des terres du Canada</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-14"><span class="HTitleText2">Loi canadienne sur l’évaluation environnementale</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-15"><span class="HTitleText2">Loi sur l’enregistrement des lobbyistes</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-16"><span class="HTitleText2">Loi sur les Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-17"><span class="HTitleText2">Loi sur les eaux des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-18"><span class="HTitleText2">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-19"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>107 - </span><a href="#h-20"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-21"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-22"><span class="HTitleText2">Loi sur l’enregistrement des lobbyistes</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-23"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-24"><span class="HTitleText2">Autres modifications</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-25"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

