<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2006 modifiant la taxe de vente</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA TAXE D’ACCISE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Modifications touchant la taxe sur les produits et services et la taxe de vente harmonisée</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-11.html#h-4"><span class="HTitleText2">Modifications touchant les taxes d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-11.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS TOUCHANT LE DROIT D’ACCISE SUR L’ALCOOL ET LES PRODUITS DU TABAC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="page-11.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-16.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-16.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-17.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-17.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-17.html#h-11"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LE DROIT POUR LA SÉCURITÉ DES PASSAGERS DU TRANSPORT AÉRIEN</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-18.html#h-12"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li></ul>
</li></ul>

</nav>

