<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le moratoire relatif aux pétroliers</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText1">Droits des peuples autochtones du Canada</span></a>
</li>
<li><span class='sectionRange'>3.2 - </span><a href="#h-5"><span class="HTitleText1">Obligation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText2">Obligation de faire rapport</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HTitleText2">Personnes désignées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText3">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-12"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2">Détention des bâtiments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText2">Vente des bâtiments</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-16"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText1">Poursuites par procédure sommaire</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><a href="#h-19"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

