<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-7.html#h-4"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-7.html#h-5"><span class="HTitleText2">Loi canadienne sur l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-8.html#h-6"><span class="HTitleText2">Règlement sur l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-8.html#h-7"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="page-8.html#h-8"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA TAXE D’ACCISE (MODIFICATIONS AUTRES QUE CELLES TOUCHANT LA TAXE SUR LES PRODUITS ET SERVICES ET LA TAXE DE VENTE HARMONISÉE)</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-9.html#h-9"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE SUR LES PRODUITS ET SERVICES ET LA TAXE DE VENTE HARMONISÉE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-9.html#h-10"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-10.html#h-11"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="page-10.html#h-12"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">AUTRES MESURES TOUCHANT LA FISCALITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="page-10.html#h-13"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-10.html#h-14"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-10.html#h-15"><span class="HTitleText2">Paiements à l’Ontario</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="page-10.html#h-16"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI SUR LES ALLÉGEMENTS FISCAUX GARANTIS</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-10.html#h-17"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="page-10.html#h-18"><span class="HTitleText2">Modification de la Loi</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-13.html#h-19"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-13.html#h-20"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="page-13.html#h-21"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-13.html#h-22"><span class="HTitleText3">Loi sur les paiements de péréquation compensatoires supplémentaires à la Nouvelle-Écosse et à Terre-Neuve-et-Labrador</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-14.html#h-23"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="page-14.html#h-24"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="page-15.html#h-25"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="page-15.html#h-26"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-15.html#h-27"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="page-15.html#h-28"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA SOCIÉTÉ CANADIENNE D’HYPOTHÈQUES ET DE LOGEMENT</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-15.html#h-29"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX CONTRATS FINANCIERS ADMISSIBLES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-15.html#h-30"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-16.html#h-31"><span class="HTitleText2">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-16.html#h-32"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-17.html#h-33"><span class="HTitleText2">Loi sur la compensation et le règlement des paiements</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-17.html#h-34"><span class="HTitleText2">Loi sur les liquidations et les restructurations</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-18.html#h-35"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-18.html#h-36"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-18.html#h-37"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="page-18.html#h-38"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">PAIEMENTS AUX PROVINCES ET AUX TERRITOIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="page-18.html#h-39"><span class="HTitleText2">Paiement à la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-18.html#h-40"><span class="HTitleText2">Fonds en fiducie pour la qualité de l’air et les changements climatiques</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-19.html#h-41"><span class="HTitleText2">Paiements de transition</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-19.html#h-42"><span class="HTitleText2">Immunisation contre le virus du papillome humain</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-19.html#h-43"><span class="HTitleText2">Garantie relative aux temps d’attente pour les patients</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-19.html#h-44"><span class="HTitleText2">Places en garderie</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-19.html#h-45"><span class="HTitleText2">Paiement au Yukon</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-19.html#h-46"><span class="HTitleText2">Paiement aux Territoires du Nord-Ouest</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="page-19.html#h-47"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">PAIEMENTS À CERTAINES ENTITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="page-19.html#h-48"><span class="HTitleText2">La Société canadienne pour la conservation de la nature</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-19.html#h-49"><span class="HTitleText2">Inforoute Santé du Canada Inc.</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-19.html#h-50"><span class="HTitleText2">CANARIE Inc.</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-19.html#h-51"><span class="HTitleText2">Génome Canada</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-19.html#h-52"><span class="HTitleText2">Paiements relatifs à l’Afghanistan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-19.html#h-53"><span class="HTitleText2"><span class="otherLang" lang="en">Rick Hansen Man in Motion Foundation</span></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-19.html#h-54"><span class="HTitleText2"><span class="otherLang" lang="en">The Perimeter Institute for Theoretical Physics</span></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-19.html#h-55"><span class="HTitleText2">La Fondation du Canada pour l’appui technologique au développement durable</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-19.html#h-56"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AUX INSTITUTIONS FINANCIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="page-19.html#h-57"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-20.html#h-58"><span class="HTitleText2">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-20.html#h-59"><span class="HTitleText2">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-20.html#h-60"><span class="HTitleText2">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-20.html#h-61"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="page-20.html#h-62"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LE MINISTÈRE DES TRAVAUX PUBLICS ET DES SERVICES GOUVERNEMENTAUX</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-20.html#h-63"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR L’AGENCE DE LA CONSOMMATION EN MATIÈRE FINANCIÈRE DU CANADA</span></a>
</li></ul>
</li></ul>

</nav>

