<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la statistique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Loi sur la statistique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-3"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>

