<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les brevets et la Loi sur les aliments et drogues</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES BREVETS</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES ALIMENTS ET DROGUES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-4"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li></ul>
</li></ul>

</nav>

