<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les brevets et la Loi sur les aliments et drogues</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES BREVETS</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI SUR LES ALIMENTS ET DROGUES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-3.html#h-4"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-4.html#h-5"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-5.html#h-6"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-6.html#h-7"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li></ul>
</li></ul>

</nav>

