<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 1 sur le plan d’action économique de 2013</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI DE L’IMPÔT SUR LE REVENU</cite>, DE LA <cite class="XRefExternalAct">LOI SUR LA COUR CANADIENNE DE L’IMPÔT</cite> ET DU <cite class="XRefExternalRegulation">RÈGLEMENT DE L’IMPÔT SUR LE REVENU</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Cour canadienne de l’impôt</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-4.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MESURES RELATIVES AUX TAXES DE VENTE ET D’ACCISE ET AUX DROITS D’ACCISE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-4.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-6.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="page-6.html#h-10"><span class="HTitleText3">Modification de la Loi</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-11"><span class="HTitleText3">Application</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-7.html#h-12"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DIVERSES MESURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-7.html#h-13"><span class="HLabel2">Section 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-7.html#h-14"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-8.html#h-15"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="page-8.html#h-16"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Institutions financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="page-8.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-9.html#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-9.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-9.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-9.html#h-21"><span class="HLabel2">Section 3</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-11.html#h-22"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Paiements à certaines entités ou à certaines fins</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-11.html#h-23"><span class="HTitleText3">Fondation canadienne des jeunes entrepreneurs</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-11.html#h-24"><span class="HTitleText3">Génome Canada</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-11.html#h-25"><span class="HTitleText3">Société canadienne pour la conservation de la nature</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-11.html#h-26"><span class="HTitleText3">Logement au Nunavut</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-11.html#h-27"><span class="HTitleText3">Indspire</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-11.html#h-28"><span class="HTitleText3">Fondation du Pallium Canada</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-11.html#h-29"><span class="HTitleText3">Institut national canadien pour les aveugles</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-11.html#h-30"><span class="HLabel2">Section 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Bureau de transition vers un régime canadien de réglementation des valeurs mobilières</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-11.html#h-31"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-11.html#h-32"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-11.html#h-33"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-11.html#h-34"><span class="HLabel2">Section 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="page-11.html#h-35"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-13.html#h-36"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi d’exécution du budget de 2009</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-13.html#h-37"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-13.html#h-38"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="page-13.html#h-39"><span class="HLabel2">Section 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-13.html#h-40"><span class="HLabel2">Section 8</span> - <span class="HTitleText2">Amélioration des prestations des anciens combattants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="page-13.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-13.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les allocations aux anciens combattants</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-14.html#h-43"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-14.html#h-44"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="page-14.html#h-45"><span class="HLabel2">Section 9</span> - <span class="HTitleText2">Immigration et protection des réfugiés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="page-14.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-14.html#h-47"><span class="HTitleText3">Aucun appel devant la Section d’appel des réfugiés</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-14.html#h-48"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="page-14.html#h-49"><span class="HLabel2">Section 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la citoyenneté</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>170 - </span><a href="page-14.html#h-50"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-14.html#h-51"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="page-14.html#h-52"><span class="HLabel2">Section 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sûreté et la réglementation nucléaires</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-14.html#h-53"><span class="HLabel2">Section 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Affaires étrangères, du Commerce et du Développement</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="page-14.html#h-54"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-15.html#h-55"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="page-15.html#h-56"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-15.html#h-57"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-15.html#h-58"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-15.html#h-59"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-15.html#h-60"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les immeubles fédéraux et les biens réels fédéraux</cite></span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-15.html#h-61"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les conflits d’intérêts</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-15.html#h-62"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la responsabilité en matière d’aide au développement officielle</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-15.html#h-63"><span class="HTitleText4"><cite class="XRefExternalAct">Loi fédérale sur le développement durable</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="page-15.html#h-64"><span class="HTitleText3">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-16.html#h-65"><span class="HTitleText3">Abrogation</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="page-16.html#h-66"><span class="HLabel2">Section 13</span> - <span class="HTitleText2">Ridley Terminals Inc.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="page-16.html#h-67"><span class="HTitleText3">Réorganisation et dessaisissement</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-17.html#h-68"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-17.html#h-69"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="page-17.html#h-70"><span class="HLabel2">Section 14</span> - <span class="HTitleText2">Transfert d’attributions au ministre du Patrimoine canadien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>213 - </span><a href="page-17.html#h-71"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la capitale nationale</cite></span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="page-17.html#h-72"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère du Patrimoine canadien</cite></span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-17.html#h-73"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-17.html#h-74"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur le Monument national de l’Holocauste</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="page-17.html#h-75"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="page-18.html#h-76"><span class="HLabel2">Section 15</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-18.html#h-77"><span class="HTitleText2">Secrétaires parlementaires et ministres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="page-18.html#h-78"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-18.html#h-79"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les traitements</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="page-18.html#h-80"><span class="HLabel2">Section 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-18.html#h-81"><span class="HLabel2">Section 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="page-18.html#h-82"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-18.html#h-83"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>230 - </span><a href="page-18.html#h-84"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Fondation canadienne des relations raciales</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-18.html#h-85"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’Office d’investissement des régimes de pensions du secteur public</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="page-18.html#h-86"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>233 - </span><a href="page-18.html#h-87"><span class="HLabel2">Section 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le soutien de la croissance de l’économie et de l’emploi au Canada</cite></span></a>
</li></ul>
</li><li><a href="page-19.html#h-88"><span class="scheduleLabel"><strong>ANNEXE</strong></span> </a>
</li></ul>
</li></ul>

</nav>

