<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur le Parlement du Canada, la Loi sur les traitements et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LE PARLEMENT DU CANADA</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI SUR LES TRAITEMENTS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Loi sur les allocations de retraite des parlementaires</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Loi référendaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-2.html#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

