<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les Indiens pour donner suite à la décision de la Cour supérieure du Québec dans l’affaire Descheneaux c. Canada (Procureur général)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Loi sur les Indiens</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-3"><span class="HTitleText1">Dispositions connexes</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-4"><span class="HTitleText1">Consultations et rapports</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-5"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

