<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Tribunal des revendications particulières</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">OBJET ET APPLICATION DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">TRIBUNAL DES REVENDICATIONS PARTICULIÈRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText2">Administration du Tribunal</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Attributions du Tribunal</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Revendications particulières</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText2">Audiences et décisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-10"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-11"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-12"><span class="HTitleText2">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-13"><span class="HTitleText2">Examen et rapport</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-14"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-15"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-16"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-17"><span class="HTitleText2">Loi sur les Cours fédérales</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-19"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-20"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-21"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-22"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

