<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi protégeant Canada contre les terroristes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR LE SERVICE CANADIEN DU RENSEIGNEMENT DE SÉCURITÉ</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-3"><span class="HTitleText1">LOI RENFORÇANT LA CITOYENNETÉ CANADIENNE</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-4"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI SUR L’ACCÈS À L’INFORMATION</span></a>
</li></ul>
</li></ul>

</nav>

