<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2007 sur le maintien des services ferroviaires</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">SERVICES FERROVIAIRES</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OBLIGATIONS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">PROROGATION DE CHAQUE CONVENTION COLLECTIVE</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HTitleText1">CHOIX DE L’OFFRE FINALE</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-7"><span class="HTitleText1">NOUVELLES CONVENTIONS COLLECTIVES</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-8"><span class="HTitleText1">FRAIS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-9"><span class="HTitleText1">MODIFICATION DES NOUVELLES CONVENTIONS COLLECTIVES</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-10"><span class="HTitleText1">EXÉCUTION</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

