<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le ministère de la Sécurité publique et de la Protection civile</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">MISE EN PLACE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3"><span class="HTitleText1">ATTRIBUTIONS DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-4"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Loi sur le Centre canadien de lutte contre les toxicomanies</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Loi sur la médaille canadienne du maintien de la paix</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-11"><span class="HTitleText2">Loi réglementant certaines drogues et autres substances</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Loi sur l’identification par les empreintes génétiques</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-15"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-16"><span class="HTitleText2">Loi sur les armes à feu</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-19"><span class="HTitleText2">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-4.html#h-20"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-21"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-22"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

