<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces et d’autre<?Pub Caret?>s lois en conséquence (paiements de péréquation aux provinces et financement des territoires)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText2">Loi de crédits n<sup>o</sup> 1 pour 2004-2005</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText2">Loi d’exécution du budget de 2004</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

