<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la gestion des ressources de la vallée du Mackenzie et la Loi fédérale sur les hydrocarbures et apportant des modifications corrélatives à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PARTIE 1</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la gestion des ressources de la vallée du Mackenzie</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-3"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-4"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-5"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le transfert de responsabilités aux Territoires du Nord-Ouest</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-6"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les revendications territoriales et l’autonomie gouvernementale du peuple tlicho</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-7"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accord définitif sur l’autonomie gouvernementale de Deline</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-8"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-9"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-10"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi fédérale sur les hydrocarbures</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-11"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-12"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

