<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi n<Sup>o</Sup> 1 d’exécution du budget de 2019</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et autres textes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-9.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-9.html#h-5"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-9.html#h-6"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-9.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’exportation et l’importation de biens culturels</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-9.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-10.html#h-9"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="page-14.html#h-10"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Mesures relatives à la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="page-14.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-15.html#h-12"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la comptabilité abrégée (TPS/TVH)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="page-15.html#h-13"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-16.html#h-14"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-16.html#h-15"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Secteur financier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-16.html#h-16"><span class="HLabel3">SOUS-SECTION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-16.html#h-17"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-16.html#h-18"><span class="HTitleText4"><cite class="XRefExternalAct">Loi modifiant certaines lois relatives aux institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-17.html#h-19"><span class="HTitleText4">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="page-17.html#h-20"><span class="HLabel3">SOUS-SECTION B</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur les paiements</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="page-17.html#h-21"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-17.html#h-22"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="page-17.html#h-23"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Renforcer le régime de lutte contre le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-17.html#h-24"><span class="HLabel3">SOUS-SECTION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-17.html#h-25"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-18.html#h-26"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="page-18.html#h-27"><span class="HLabel3">SOUS-SECTION B</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-18.html#h-28"><span class="HLabel3">SOUS-SECTION C</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-18.html#h-29"><span class="HLabel3">SOUS-SECTION D</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’administration des biens saisis</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-18.html#h-30"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-20.html#h-31"><span class="HTitleText4">Modifications corrélatives</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="page-20.html#h-32"><span class="HTitleText5"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-20.html#h-33"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les crimes contre l’humanité et les crimes de guerre</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-20.html#h-34"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-20.html#h-35"><span class="HLabel2">SECTION 3</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’équité en matière d’emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-20.html#h-36"><span class="HTitleText3">Modification de la loi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-20.html#h-37"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="page-20.html#h-38"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Paiements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-20.html#h-39"><span class="HTitleText3">Agir pour le climat</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-21.html#h-40"><span class="HTitleText3">Paiement en matière d’infrastructures</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-21.html#h-41"><span class="HTitleText3">Fédération canadienne des municipalités</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-21.html#h-42"><span class="HTitleText3">Shock Trauma Air Rescue Service</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="page-21.html#h-43"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Amélioration de la sécurité de la retraite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="page-21.html#h-44"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-22.html#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-22.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-23.html#h-47"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 1985 sur les normes de prestation de pension</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-23.html#h-48"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-23.html#h-49"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-24.html#h-50"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="page-24.html#h-51"><span class="HLabel2">SECTION 6</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="page-24.html#h-52"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-24.html#h-53"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="page-24.html#h-54"><span class="HLabel2">SECTION 7</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité de la vieillesse</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-24.html#h-55"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Surplus non autorisé</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="page-24.html#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de retraite des Forces canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-24.html#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-24.html#h-58"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de retraite de la Gendarmerie royale du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="page-24.html#h-59"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Modernisation de la réglementation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="page-24.html#h-60"><span class="HLabel3">SOUS-SECTION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-24.html#h-61"><span class="HLabel3">SOUS-SECTION B</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’inspection de l’électricité et du gaz</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-25.html#h-62"><span class="HLabel3">SOUS-SECTION C</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les aliments et drogues</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="page-25.html#h-63"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-28.html#h-64"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-28.html#h-65"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-28.html#h-66"><span class="HLabel3">SOUS-SECTION D</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-28.html#h-67"><span class="HLabel3">SOUS-SECTION E</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le poinçonnage des métaux précieux</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-29.html#h-68"><span class="HLabel3">SOUS-SECTION F</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’étiquetage des textiles</cite></span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-29.html#h-69"><span class="HLabel3">SOUS-SECTION G</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les poids et mesures</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>192 - </span><a href="page-29.html#h-70"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-29.html#h-71"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>198 - </span><a href="page-29.html#h-72"><span class="HLabel3">SOUS-SECTION H</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>198 - </span><a href="page-29.html#h-73"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-31.html#h-74"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-31.html#h-75"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-31.html#h-76"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="page-31.html#h-77"><span class="HLabel3">SOUS-SECTION I</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="page-31.html#h-78"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-32.html#h-79"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>217 - </span><a href="page-32.html#h-80"><span class="HLabel3">SOUS-SECTION J</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les produits antiparasitaires</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-32.html#h-81"><span class="HLabel3">SOUS-SECTION K</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la mise en quarantaine</cite></span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-32.html#h-82"><span class="HLabel3">SOUS-SECTION L</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les agents pathogènes humains et les toxines</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>222 - </span><a href="page-32.html#h-83"><span class="HLabel2">SECTION 10</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Gendarmerie royale du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222 - </span><a href="page-32.html#h-84"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="page-33.html#h-85"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="page-33.html#h-86"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="page-33.html#h-87"><span class="HLabel2">SECTION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le pilotage</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="page-33.html#h-88"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-40.html#h-89"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="page-40.html#h-90"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>266 - </span><a href="page-40.html#h-91"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la prévention de la pollution des eaux arctiques</cite></span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="page-40.html#h-92"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>268 - </span><a href="page-40.html#h-93"><span class="HTitleText3">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-40.html#h-94"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="page-40.html#h-95"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2">Commercialisation des services de contrôle de sûreté</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>270 - </span><a href="page-40.html#h-96"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la commercialisation des services de contrôle de sûreté</cite></span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-41.html#h-97"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>271 - </span><a href="page-41.html#h-98"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-41.html#h-99"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="page-41.html#h-100"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-41.html#h-101"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la sûreté des déplacements aériens</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>279 - </span><a href="page-41.html#h-102"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>280 - </span><a href="page-41.html#h-103"><span class="HLabel2">SECTION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation de l’industrie aérienne</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="page-42.html#h-104"><span class="HLabel2">SECTION 14</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="page-42.html#h-105"><span class="HLabel2">SECTION 15</span> - <span class="HTitleText2">Représentation ou conseil en matière d’immigration et de citoyenneté</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>292 - </span><a href="page-42.html#h-106"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="page-43.html#h-107"><span class="HTitleText3">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>293 - </span><a href="page-43.html#h-108"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la citoyenneté</cite></span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="page-43.html#h-109"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>298 - </span><a href="page-43.html#h-110"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>298 - </span><a href="page-43.html#h-111"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-43.html#h-112"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="page-43.html#h-113"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>301 - </span><a href="page-44.html#h-114"><span class="HLabel2">SECTION 16</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>301 - </span><a href="page-44.html#h-115"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-45.html#h-116"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="page-45.html#h-117"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>311 - </span><a href="page-45.html#h-118"><span class="HLabel2">SECTION 17</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="page-45.html#h-119"><span class="HLabel2">SECTION 18</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi nationale sur l’habitation</cite></span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-45.html#h-120"><span class="HLabel2">SECTION 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la stratégie nationale sur le logement</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>313 - </span><a href="page-45.html#h-121"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-46.html#h-122"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="page-46.html#h-123"><span class="HLabel2">SECTION 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la réduction de la pauvreté</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="page-46.html#h-124"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-46.html#h-125"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="page-46.html#h-126"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>318 - </span><a href="page-47.html#h-127"><span class="HLabel2">SECTION 21</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le bien-être des vétérans</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>318 - </span><a href="page-47.html#h-128"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="page-47.html#h-129"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>323 - </span><a href="page-47.html#h-130"><span class="HLabel2">SECTION 22</span> - <span class="HTitleText2">Prêts aux étudiants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>323 - </span><a href="page-47.html#h-131"><span class="HTitleText3"><cite class="XRefExternalAct">Loi fédérale sur les prêts aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>325 - </span><a href="page-47.html#h-132"><span class="HTitleText3"><cite class="XRefExternalAct">Loi fédérale sur l’aide financière aux étudiants</cite></span></a>
</li>
<li><span class='sectionRange'>327 - </span><a href="page-47.html#h-133"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>328 - </span><a href="page-47.html#h-134"><span class="HLabel2">SECTION 23</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>328 - </span><a href="page-47.html#h-135"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="page-49.html#h-136"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>334 - </span><a href="page-49.html#h-137"><span class="HLabel2">SECTION 24</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence Parcs Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>334 - </span><a href="page-49.html#h-138"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="page-49.html#h-139"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>336 - </span><a href="page-49.html#h-140"><span class="HLabel2">SECTION 25</span> - <span class="HTitleText2">Mesures diverses en matière autochtone</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="page-49.html#h-141"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Services aux Autochtones</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="page-49.html#h-142"><span class="HTitleText4">Édiction de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>336.1 - </span><a href="page-50.html#h-143"><span class="HTitleText3">Entrée en vigueur</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="page-50.html#h-144"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le ministère des Relations Couronne-Autochtones et des Affaires du Nord</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>337 - </span><a href="page-50.html#h-145"><span class="HTitleText4">Édiction de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>337.1 - </span><a href="page-51.html#h-146"><span class="HTitleText3">Entrée en vigueur</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="page-51.html#h-147"><span class="HLabel3">SOUS-SECTION C</span> - <span class="HTitleText3">Dispositions transitoires, modifications corrélatives, dispositions de coordination et abrogation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>338 - </span><a href="page-51.html#h-148"><span class="HTitleText4">Dispositions transitoires</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>338 - </span><a href="page-51.html#h-149"><span class="HTitleText5">Services aux Autochtones</span></a>
</li>
<li><span class='sectionRange'>341 - </span><a href="page-51.html#h-150"><span class="HTitleText5">Relations Couronne-Autochtones et Affaires du Nord</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="page-51.html#h-151"><span class="HTitleText5">Mentions et règlements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>347 - </span><a href="page-51.html#h-152"><span class="HTitleText4">Modifications corrélatives</span></a>
</li></ul>
</li><li><span class='sectionRange'>347 - </span><a href="page-51.html#h-153"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="page-51.html#h-154"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>357 - </span><a href="page-52.html#h-155"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les Indiens</cite></span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="page-52.html#h-156"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>362 - </span><a href="page-52.html#h-157"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les traitements</cite></span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="page-52.html#h-158"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les forces hydrauliques du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="page-52.html#h-159"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="page-52.html#h-160"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur l’autonomie gouvernementale des premières nations du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="page-52.html#h-161"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les immeubles fédéraux et les biens réels fédéraux</cite></span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-52.html#h-162"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur la transparence financière des Premières Nations</cite></span></a>
</li>
<li><span class='sectionRange'>370 - </span><a href="page-53.html#h-163"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur la modification et le remplacement de la Loi sur les Indiens</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="page-53.html#h-164"><span class="HTitleText4">Modifications terminologiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="page-54.html#h-165"><span class="HTitleText4">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="page-55.html#h-166"><span class="HTitleText4">Abrogation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>383 - </span><a href="page-55.html#h-167"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>384 - </span><a href="page-55.html#h-168"><span class="HLabel3">SOUS-SECTION D</span> - <span class="HTitleText3">Modifications diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>384 - </span><a href="page-55.html#h-169"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des terres des premières nations</cite></span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="page-55.html#h-170"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion du pétrole et du gaz et des fonds des Premières Nations</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="page-55.html#h-171"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’ajout de terres aux réserves et la création de réserves</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>387 - </span><a href="page-55.html#h-172"><span class="HLabel2">SECTION 26</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi fédérale sur le paiement rapide des travaux de construction</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>387 - </span><a href="page-55.html#h-173"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>388 - </span><a href="page-56.html#h-174"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-57.html#h-175"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-58.html#h-176"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-59.html#h-177"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-60.html#h-178"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li></ul>
</li></ul>

</nav>

