<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les relations de travail dans la fonction publique, la Loi sur la Commission des relations de travail et de l’emploi dans la fonction publique et d’autres lois et comportant d’autres mesures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la Commission des relations de travail et de l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la Gendarmerie royale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-4"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-4.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le statut de l’artiste</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’équité dans la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-5.html#h-14"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les relations de travail dans la fonction publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="page-5.html#h-15"><span class="HTitleText1">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-16"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-7.html#h-17"><span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

