<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur la santé et la sécurité dans la zone extracôtière</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Loi sur la santé et la sécurité dans la zone extracôtière</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>

</nav>

