<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Exécution du budget de 2001, Loi d’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">SÉCURITÉ DU TRANSPORT AÉRIEN</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Administration canadienne de la sûreté du transport aérien</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>4 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-2.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">DROIT POUR LA SÉCURITÉ DU TRANSPORT AÉRIEN</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-2.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit pour la sécurité des passagers du transport aérien</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-3.html#h-10"><span class="HTitleText3">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-4.html#h-13"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">ASSURANCE-EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-4.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-4.html#h-15"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Règlement sur l’assurance-emploi (pêche)</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-4.html#h-18"><span class="HTitleText3">Code canadien du travail</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-4.html#h-19"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-4.html#h-20"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-8.html#h-21"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">FONDS CANADIEN POUR L’AFRIQUE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-8.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Fonds canadien pour l’Afrique</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-9.html#h-23"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-9.html#h-24"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">FONDS CANADIEN SUR L’INFRASTRUCTURE STRATÉGIQUE</span></a>
</li></ul>
</li></ul>

</nav>

