<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi canadienne sur l’évaluation environnementale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI CANADIENNE SUR L’ÉVALUATION ENVIRONNEMENTALE</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-2"><span class="HTitleText1">INFORMATION PERTINENTE</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-3"><span class="HTitleText1">EXAMEN ET RAPPORT</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-4"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

