<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la croissance économique et la prospérité — Canada-Corée</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">DROIT DE POURSUITE</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MISE EN OEUVRE DE L’ACCORD</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Approbation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Groupes spéciaux, groupes d’experts, comités, sous-comités, groupes de travail et autres organes</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Décrets</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Protection des indications géographiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-15"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText2">Loi sur l’arbitrage commercial</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-17"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-18"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-19"><span class="HTitleText2">Loi sur le ministère de l’Emploi et du Développement social</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-20"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-21"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-22"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-23"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-24"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

