<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi portant mise en vigueur de l'Accord d'autonomie gouvernementale de la première nation de Westbank</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">EFFET DE L'ACCORD</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">APPLICATION D'AUTRES LOIS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-5"><span class="HTitleText1">PROCÉDURES JUDICIAIRES OU ADMINISTRATIVES</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-6"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-7"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l'accès à l'information</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l'enregistrement des lobbyistes</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-2.html#h-11"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-12"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

