<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Responsabilité en matière maritime, Loi sur la</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">BLESSURES CORPORELLES ET ACCIDENTS MORTELS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Définition et champ d’application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Responsabilité : personnes à charge</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-1.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">PARTAGE DE LA RESPONSABILITÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Définition et champ d’application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Prescription</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-2.html#h-11"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LIMITATION DE RESPONSABILITÉ EN MATIÈRE DE CRÉANCES MARITIMES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="page-2.html#h-12"><span class="HTitleText2">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-13"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-14"><span class="HTitleText2">Propriétaires de docks, canaux ou ports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-15"><span class="HTitleText2">Modification des limites de responsabilité</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-16"><span class="HTitleText2">Procédure</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-3.html#h-17"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">RESPONSABILITÉ EN MATIÈRE DE TRANSPORT DE PASSAGERS PAR EAU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-3.html#h-18"><span class="HTitleText2">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-19"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-20"><span class="HTitleText2">Règlements et décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-3.html#h-21"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">RESPONSABILITÉ EN MATIÈRE DE TRANSPORT DE MARCHANDISES PAR EAU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-3.html#h-22"><span class="HTitleText2">Définitions et disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-3.html#h-23"><span class="HTitleText2">Règles de La Haye-Visby</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-3.html#h-24"><span class="HTitleText2">Règles de Hambourg</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-25"><span class="HTitleText2">Procédure intentée au Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-4.html#h-26"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">RESPONSABILITÉ ET INDEMNISATION EN MATIÈRE DE POLLUTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-4.html#h-27"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-28"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-29"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Responsabilité en matière de pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-4.html#h-30"><span class="HTitleText3">Propriétaires de navires</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-31"><span class="HTitleText3">Règles spéciales concernant les navires assujettis à la Convention</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-32"><span class="HTitleText3">Enregistrement des jugements étrangers</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="page-6.html#h-33"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Indemnisation en matière de pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="page-6.html#h-34"><span class="HTitleText3">Fonds international d’indemnisation des dommages dus à la pollution par les hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-7.html#h-35"><span class="HTitleText3">Caisse d’indemnisation des dommages dus à la pollution par les hydrocarbures causée par les navires</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-36"><span class="HTitleText3">Administrateur et administrateur adjoint</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-37"><span class="HTitleText3">Responsabilité de la Caisse d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-7.html#h-38"><span class="HTitleText3">Demandes fondées sur l’article 51</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-8.html#h-39"><span class="HTitleText3">Demandes d’indemnisation des pertes de revenus</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-8.html#h-40"><span class="HTitleText3">Action en responsabilité contre le propriétaire du navire</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-9.html#h-41"><span class="HTitleText3">Limite de responsabilité de la Caisse d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-9.html#h-42"><span class="HTitleText3">Demandes de directives judiciaires</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-9.html#h-43"><span class="HTitleText3">Contributions à la Caisse d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-10.html#h-44"><span class="HTitleText3">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-10.html#h-45"><span class="HTitleText3">Intérêts sur les demandes en recouvrement de créances</span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="page-10.html#h-46"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-10.html#h-47"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="page-10.html#h-48"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">VALIDITÉ DE CERTAINS RÈGLEMENTS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>106 - </span><a href="page-10.html#h-49"><span class="HTitleText2">Règlements pris en vertu de la Loi sur la Société canadienne des ports</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-10.html#h-50"><span class="HTitleText2">Règlement pris en vertu de la Loi sur le pilotage</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="page-10.html#h-51"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">DISPOSITION TRANSITOIRE, MODIFICATIONS CORRÉLATIVES, MODIFICATION CONDITIONNELLE, ABROGATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="page-10.html#h-52"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-10.html#h-53"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="page-10.html#h-54"><span class="HTitleText3">Loi sur la prévention de la pollution des eaux arctiques</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-11.html#h-55"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-11.html#h-56"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-11.html#h-57"><span class="HTitleText3">Loi canadienne sur la protection de l’environnement (1999)</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-11.html#h-58"><span class="HTitleText3">Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-11.html#h-59"><span class="HTitleText3">Loi sur la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-11.html#h-60"><span class="HTitleText3">Loi sur l’indemnisation des marins marchands</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-11.html#h-61"><span class="HTitleText3">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-11.html#h-62"><span class="HTitleText3">Loi sur la marine marchande du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="page-11.html#h-63"><span class="HTitleText2">Modification conditionnelle</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-11.html#h-64"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-11.html#h-65"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-12.html#h-66"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-13.html#h-67"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-14.html#h-68"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - RÈGLES DE LA HAYE-VISBY</span></a>
</li>
<li><a href="page-15.html#h-69"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - RÈGLES DE HAMBOURG</span></a>
</li></ul>
</li></ul>

</nav>

