<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant à combattre la contrefaçon de produits</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LE DROIT D’AUTEUR</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES MARQUES DE COMMERCE</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-4"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-5"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques olympiques et paralympiques</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-10"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

