<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les transports au Canada et la Loi sur la sécurité ferroviaire et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LES TRANSPORTS AU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-7.html#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA SÉCURITÉ FERROVIAIRE</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-7.html#h-4"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="page-7.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la participation publique au capital d’Air Canada</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-7.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="page-8.html#h-8"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-8.html#h-9"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

