<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi électorale du Canada et la Loi sur la révision des limites des circonscriptions électorales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI ÉLECTORALE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI SUR LA RÉVISION DES LIMITES DES CIRCONSCRIPTIONS ÉLECTORALES</span></a>
</li></ul>
</li></ul>

</nav>

