<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Fondation du Canada pour l’appui technologique au développement durable, Loi sur la</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CONSTITUTION DE LA FONDATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-4"><span class="HTitleText1">ADMINISTRATEURS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-5"><span class="HTitleText1">MEMBRES</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-6"><span class="HTitleText1">PERSONNEL</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-7"><span class="HTitleText1">OPÉRATIONS</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-8"><span class="HTitleText1">QUESTIONS FINANCIÈRES ET VÉRIFICATION</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-9"><span class="HTitleText1">ASSEMBLÉE ANNUELLE</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-10"><span class="HTitleText1">RAPPORT ANNUEL</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-11"><span class="HTitleText1">LIQUIDATION</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-12"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-13"><span class="HTitleText1">DÉSIGNATION ET MODIFICATIONS CORRÉLATIVES</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-14"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

