<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 d’exécution du budget de 2006</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU (IMPOSITION DES DIVIDENDES)</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LES DROITS D’ACCISE SUR LA BIÈRE ET LE VIN CANADIENS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-5"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-6"><span class="HTitleText2">Loi sur l’accise</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

