<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les missions étrangères et les organisations internationales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LES MISSIONS ÉTRANGÈRES ET LES ORGANISATIONS INTERNATIONALES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-2"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><a href="#h-3"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

