<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les missions étrangères et les organisations internationales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR LES MISSIONS ÉTRANGÈRES ET LES ORGANISATIONS INTERNATIONALES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-2"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><a href="page-3.html#h-3"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

