<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les bons samaritains secourant les victimes de surdose</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Loi réglementant certaines drogues et autres substances</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

