<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution de l’énoncé économique de 2020</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span></span> - <span class="HTitleText1">Loi de l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Modification connexe à la Loi sur les allocations spéciales pour enfants</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-7"><span class="HLabel1">PARTIE 4</span></span> - <span class="HTitleText1">Loi sur les prêts aux apprentis</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-8"><span class="HLabel1">PARTIE 5</span></span> - <span class="HTitleText1">Loi sur les aliments et drogues</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-9"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-10"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-11"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Paiements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-12"><span class="HLabel1">PARTIE 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi autorisant certains emprunts</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-13"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-14"><span class="HTitleText2">Modification connexe à la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li></ul>
</li><li><a href="page-2.html#h-15"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

