<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la citoyenneté et une autre loi en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la citoyenneté</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-2"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-3"><span class="HTitleText1">Interdiction de prêter le serment de citoyenneté</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-4"><span class="HTitleText1">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-5"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

