<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel et d'autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-2"><span class="HTitleText1">LOI SUR LA PREUVE AU CANADA</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-3"><span class="HTitleText1">LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-4"><span class="HTitleText1">LOI SUR LA PROTECTION DE L'INFORMATION</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-5"><span class="HTitleText1">ADAPTATIONS</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-6"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

