<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le renforcement des peines pour les prédateurs d’enfants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-3"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA PREUVE AU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-4"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’ENREGISTREMENT DE RENSEIGNEMENTS SUR LES DÉLINQUANTS SEXUELS</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-5"><span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA BANQUE DE DONNÉES CONCERNANT LES DÉLINQUANTS SEXUELS À RISQUE ÉLEVÉ (INFRACTIONS SEXUELLES VISANT LES ENFANTS)</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-6"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-9"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-10"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

