<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère du Développement social</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MINISTÈRE DU DÉVELOPPEMENT SOCIAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Services entre ministères</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Comités</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Conseil national du bien-être social</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">PROTECTION DES RENSEIGNEMENTS PERSONNELS</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-11"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES ET CONNEXES, DISPOSITION DE COORDINATION, ABROGATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-12"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-13"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-14"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-15"><span class="HTitleText3">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-16"><span class="HTitleText3">Loi d’aide à l’exécution des ordonnances et des ententes familiales</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-17"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-18"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-19"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-20"><span class="HTitleText3">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-21"><span class="HTitleText3">Loi sur les traitements</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-22"><span class="HTitleText3">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-23"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-24"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-25"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

