<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifi<?Pub Caret?>ant la Loi sur le ministère du Patrimoine canadien et la Loi sur l’Agence Parcs Canada et apportant des modifications connexes à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">RESPONSABILITÉ À L’ÉGARD DE L’AGENCE PARCS CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Loi sur le ministère du Patrimoine canadien</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText2">Loi sur l’Agence Parcs Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText2">Loi sur les aires marines nationales de conservation du Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Loi sur les parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Loi de 2001 sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Loi sur la protection des gares ferroviaires patrimoniales</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText2">Loi sur les lieux et monuments historiques</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText2">Loi sur le parc marin du Saguenay — Saint-Laurent</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Loi sur les espèces en péril</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

