<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les traitements et apportant une modification corrélative à la Loi sur la gestion des finances publiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Loi sur les traitements</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText1">Modification corrélative à la Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-4"><span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>

</nav>

