<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur l’assurance-emploi (incarcération)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI SUR L’ASSURANCE-EMPLOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-3"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

