<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel (procédure pénale, langue de l’accusé, détermination de la peine et autres modifications)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">CODE CRIMINEL</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-2"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

