<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la pension de retraite des Forces canadiennes et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LA PENSION DE RETRAITE DES FORCES CANADIENNES</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-3"><span class="HTitleText2">Loi sur la modernisation de certains régimes d’avantages et d’obligations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-4"><span class="HTitleText2">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-5"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-6"><span class="HTitleText2">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-7"><span class="HTitleText2">Loi sur les régimes de retraite particuliers</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="#h-8"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-9"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-10"><span class="HTitleText2">Projet de loi C-25</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

