<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Impôt sur le revenu, Loi de 2000 modifiant l’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-48.html#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">HARMONISATION AVEC LE CODE CIVIL DU QUÉBEC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="page-48.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-51.html#h-5"><span class="HTitleText2">Règles concernant l’application de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-52.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>238 - </span><a href="page-52.html#h-7"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS TECHNIQUES DE LA LOI DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="page-53.html#h-8"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">RÈGLES CONCERNANT L’APPLICATION DE L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-53.html#h-9"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI MODIFIANT LA LOI DE L’IMPÔT SUR LE REVENU, LE RÉGIME DE PENSIONS DU CANADA, LA LOI SUR L’EXPORTATION ET L’IMPORTATION DE BIENS CULTURELS, LA LOI SUR L’INTERPRÉTATION DES CONVENTIONS EN MATIæRE D’IMPÔTS SUR LE REVENU, LA LOI SUR LA COUR CANADIENNE DE L’IMPÔT, LA LOI SUR L’ASSURANCE-CHÔMAGE, LA LOI DE MISE EN OEUVRE DE L’ACCORD ATLANTIQUE CANADA — TERRE-NEUVE, LA LOI DE MISE EN OEUVRE DE L’ACCORD CANADA — NOUVELLE-ÉCOSSE SUR LES HYDROCARBURES EXTRACÔTIERS ET CERTAINES LOIS CONNEXES</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="page-53.html#h-10"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI DE 1997 MODIFIANT L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-53.html#h-11"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">LOI DE 1998 MODIFIANT L’IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-53.html#h-12"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">RÉGIME DE PENSIONS DU CANADA</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-53.html#h-13"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">LOI SUR LES DOUANES</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-54.html#h-14"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">LOI SUR LA TAXE D’ACCISE</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="page-54.html#h-15"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">LOI SUR LA MODERNISATION DE CERTAINS RÉGIMES D’AVANTAGES ET D’OBLIGATIONS</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-54.html#h-16"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">LOI DE 1999 MODIFIANT LES TAXES DE VENTE ET D’ACCISE</span></a>
</li></ul>
</li></ul>

</nav>

