<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le précontrôle (2016)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Désignation des ministres</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Précontrôle par les États-Unis au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Désignation des zones de précontrôle et des périmètres de précontrôle</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Attributions dans la zone de précontrôle et le périmètre de précontrôle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText3">Précontrôle</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText3">Autres pouvoirs et justification</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Zone de précontrôle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText3">Accès</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-13"><span class="HTitleText3">Attributions</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-14"><span class="HTitleText2">Périmètre de précontrôle</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">Retrait</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-16"><span class="HTitleText2">Saisie et confiscation</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText2">Policiers et agents des services frontaliers</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-18"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-19"><span class="HTitleText2">Responsabilité civile et immunité</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-20"><span class="HTitleText2">Limite aux demandes d’extradition et d’arrestation provisoire</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-21"><span class="HTitleText2">Règlements, décrets et arrêtés</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-22"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Précontrôle par le Canada aux États-Unis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-23"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-24"><span class="HTitleText2">Précontrôle</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-25"><span class="HTitleText2">Détention, retenue et remise en vertu des lois des États-Unis</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-26"><span class="HTitleText2">Dispense de conformité à l’entrée au Canada</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-27"><span class="HTitleText2">Retrait</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-28"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-29"><span class="HTitleText2">Infractions — actions ou omissions dans la zone de précontrôle ou le périmètre de précontrôle</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-30"><span class="HTitleText2">Juridiction — infraction par un agent ou fonctionnaire canadien</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-31"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1">Modifications connexes au <cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>62.1 - </span><a href="#h-32"><span class="HLabel1">PARTIE 3.1</span> - <span class="HTitleText1">Examen indépendant</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-33"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Modification corrélative, abrogation et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-34"><span class="HTitleText2">Modification corrélative à <cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-35"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-36"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-37"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Emplacements où des zones de précontrôle et des périmètres de précontrôle au Canada peuvent être désignés</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

