<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les foyers familiaux situés dans les réserves et les droits ou intérêts matrimoniaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">OBJET ET APPLICATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">ADOPTION DE TEXTES LÉGISLATIFS PAR LES PREMIÈRES NATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Pouvoir des premières nations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-7"><span class="HTitleText2">Consultation populaire</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-2.html#h-9"><span class="HTitleText1">RÈGLES FÉDÉRALES PROVISOIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-2.html#h-10"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-11"><span class="HTitleText2">Foyer familial</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-2.html#h-12"><span class="HTitleText3">Droit d’occupation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-13"><span class="HTitleText3">Ordonnance de protection d’urgence</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-14"><span class="HTitleText3">Ordonnance d’occupation exclusive</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-15"><span class="HTitleText3">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="page-4.html#h-16"><span class="HTitleText2">Partage de la valeur des droits ou intérêts matrimoniaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="page-4.html#h-17"><span class="HTitleText3">Échec de la relation conjugale</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-5.html#h-18"><span class="HTitleText3">Décès de l’époux ou conjoint de fait</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-6.html#h-19"><span class="HTitleText2">Avis au conseil et observations du conseil</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-20"><span class="HTitleText2">Compétence</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-7.html#h-21"><span class="HTitleText2">Règles de pratique et de procédure</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-7.html#h-22"><span class="HTitleText2">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="page-7.html#h-23"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-24"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-7.html#h-25"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

