<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les agents pathogènes humains et les toxines</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">DÉFINITIONS ET CHAMP D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-4"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-5"><span class="HTitleText1">OBLIGATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HTitleText1">ANNEXES 1 À 4</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText1">ANNEXE 5</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-9"><span class="HTitleText1">CONSÉQUENCES D’UN AJOUT À UNE ANNEXE</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-10"><span class="HTitleText1">OBLIGATION D’AVISER LE MINISTRE</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-11"><span class="HTitleText1">PERMIS</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-12"><span class="HTitleText1">ACCÈS À L’ÉTABLISSEMENT VISÉ PAR LE PERMIS</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-13"><span class="HTitleText1">HABILITATION DE SÉCURITÉ</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-14"><span class="HTitleText1">AGENTS DE LA SÉCURITÉ BIOLOGIQUE</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-15"><span class="HTitleText1">EXEMPTIONS</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-16"><span class="HTitleText1">RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-17"><span class="HTitleText1">EXÉCUTION ET CONTRÔLE D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-18"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-19"><span class="HTitleText1">CRÉANCES</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-6.html#h-20"><span class="HTitleText1">POUVOIRS RÉGLEMENTAIRES</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-21"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-7.html#h-22"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-8.html#h-23"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - TOXINES</span></a>
</li>
<li><a href="page-9.html#h-24"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - AGENTS PATHOGÈNES HUMAINS DU GROUPE DE RISQUE 2</span></a>
</li>
<li><a href="page-10.html#h-25"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - AGENTS PATHOGÈNES HUMAINS DU GROUPE DE RISQUE 3</span></a>
</li>
<li><a href="page-11.html#h-26"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - AGENTS PATHOGÈNES HUMAINS DU GROUPE DE RISQUE 4</span></a>
</li>
<li><a href="page-12.html#h-27"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - AGENTS PATHOGÈNES HUMAINS ET TOXINES INTERDITS</span></a>
</li></ul>
</li></ul>

</nav>

