<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la protection des eaux transfrontalières</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI DU TRAITÉ DES EAUX LIMITROPHES INTERNATIONALES</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-3"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI SUR LES OUVRAGES DESTINÉS À L’AMÉLIORATION DES COURS D’EAU INTERNATIONAUX</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-3.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-4.html#h-5"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

