<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi améliorant la Nouvelle Charte des anciens combattants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES MESURES DE RÉINSERTION ET D’INDEMNISATION DES MILITAIRES ET VÉTÉRANS DES FORCES CANADIENNES</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR LES PENSIONS</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-4"><span class="HTitleText1">EXAMEN</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

