<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant des mesures supplémentaires liées à la COVID-19</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et <cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Paiement unique aux personnes handicapées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Anciens Combattants</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations spéciales pour enfants</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le bien-être des vétérans</cite></span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Prélèvement sur le Trésor</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-11"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les délais et autres périodes (COVID-19)</cite></span></a>
</li>
<li><a href="#h-12"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

