<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 d’exécution du budget de 2018</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et d’autres textes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’entraide juridique en matière criminelle</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi modifiant le Régime de pensions du Canada, la Loi sur l’Office d’investissement du régime de pensions du Canada et la Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-8"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-9"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> (mesures relatives à la TPS/TVH) et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les services financiers et les institutions financières (TPS/TVH)</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la méthode d’attribution applicable aux institutions financières désignées particulières (TPS/TVH)</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-13"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-14"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> (mesures relatives à l’accise), de la <cite class="XRefExternalAct">Loi sur le droit pour la sécurité des passagers du transport aérien</cite> et de la <cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit pour la sécurité des passagers du transport aérien</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="#h-18"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-19"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Simplification du <cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-20"><span class="HTitleText3">Modification du <cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-21"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-22"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-23"><span class="HLabel2">SECTION 2</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-24"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-25"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-26"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Secteur financier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-27"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Institutions financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-28"><span class="HTitleText4">Seuil d’importance</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-29"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-30"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-31"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-32"><span class="HTitleText4">Fonds de croissance des entreprises</span></a>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-33"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-34"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-35"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="#h-36"><span class="HTitleText4">Consentement électronique</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-37"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-38"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-39"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>155 - </span><a href="#h-40"><span class="HTitleText4">Modifications techniques</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="#h-41"><span class="HTitleText5"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2018</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-42"><span class="HTitleText5">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-43"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Modifications concernant la <cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-44"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-45"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la révision du système financier</cite></span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-46"><span class="HTitleText5">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-47"><span class="HTitleText5">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-48"><span class="HLabel3">SOUS-SECTION C</span> - <span class="HTitleText3">Renseignements protégés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-49"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Bureau du surintendant des institutions financières</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-50"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>169 - </span><a href="#h-51"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-52"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>174 - </span><a href="#h-53"><span class="HLabel2">SECTION 4</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-54"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Tarification des émissions de gaz à effet de serre et autres sujets visant la zone extracôtière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>176 - </span><a href="#h-55"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve-et-Labrador</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-56"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la tarification de la pollution causée par les gaz à effet de serre</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-57"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la santé et la sécurité dans la zone extracôtière</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-58"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 - </span><a href="#h-59"><span class="HLabel2">SECTION 6</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 - </span><a href="#h-60"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-61"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="#h-62"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Stratégie en matière de propriété intellectuelle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-63"><span class="HLabel3">SOUS-SECTION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-64"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-65"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-66"><span class="HTitleText4">Modifications connexes à la <cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-67"><span class="HTitleText4">Modification corrélative à la <cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord économique et commercial global entre le Canada et l’Union européenne</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-68"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-69"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-70"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Marques de commerce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-71"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-72"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-73"><span class="HTitleText4"><cite class="XRefExternalAct">Loi visant à combattre la contrefaçon de produits</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-74"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-75"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="#h-76"><span class="HLabel3">SOUS-SECTION C</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le droit d’auteur (avis de prétendue violation)</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-77"><span class="HLabel3">SOUS-SECTION D</span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Collège des agents de brevets et des agents de marques de commerce</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-78"><span class="HTitleText4">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-79"><span class="HTitleText4">Modifications corrélatives</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>248 - </span><a href="#h-80"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-81"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-82"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-83"><span class="HTitleText5"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>259 - </span><a href="#h-84"><span class="HTitleText4">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>264 - </span><a href="#h-85"><span class="HTitleText4">Entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="#h-86"><span class="HLabel3">SOUS-SECTION E</span> - <span class="HTitleText3">Modifications relativement à la conservation des droits d’utilisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="#h-87"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-88"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-89"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-90"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>273 - </span><a href="#h-91"><span class="HLabel3">SOUS-SECTION F</span> - <span class="HTitleText3">Renseignements protégés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>273 - </span><a href="#h-92"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-93"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-94"><span class="HTitleText4">Modification connexe de la <cite class="XRefExternalAct">Loi sur les produits antiparasitaires</cite></span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="#h-95"><span class="HTitleText4">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>278 - </span><a href="#h-96"><span class="HLabel3">SOUS-SECTION G</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Conseil national de recherches</cite></span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="#h-97"><span class="HLabel3">SOUS-SECTION H</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le droit d’auteur (réforme de la Commission du droit d’auteur)</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>280 - </span><a href="#h-98"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-99"><span class="HTitleText4">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="#h-100"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>302 - </span><a href="#h-101"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>303 - </span><a href="#h-102"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Prestations parentales et congés correspondants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>303 - </span><a href="#h-103"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>303 - </span><a href="#h-104"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-105"><span class="HTitleText4">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-106"><span class="HTitleText4">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>310 - </span><a href="#h-107"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>310 - </span><a href="#h-108"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="#h-109"><span class="HTitleText4">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-110"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>314 - </span><a href="#h-111"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur la budgétisation sensible aux sexes</cite></span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-112"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Régime de protection des consommateurs en matière financière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="#h-113"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>315 - </span><a href="#h-114"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-115"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>336 - </span><a href="#h-116"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence de la consommation en matière financière du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>351 - </span><a href="#h-117"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>352 - </span><a href="#h-118"><span class="HLabel2">SECTION 11</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des terres des premières nations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>352 - </span><a href="#h-119"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>384 - </span><a href="#h-120"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les foyers familiaux situés dans les réserves et les droits ou intérêts matrimoniaux</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>385 - </span><a href="#h-121"><span class="HLabel2">SECTION 12</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion financière des premières nations</cite></span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="#h-122"><span class="HLabel2">SECTION 13</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-123"><span class="HLabel2">SECTION 14</span> - <span class="HTitleText2">Équité salariale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>416 - </span><a href="#h-124"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’équité salariale</cite></span></a>
</li>
<li><span class='sectionRange'>417 - </span><a href="#h-125"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur l’équité salariale</cite></span></a>
</li>
<li><span class='sectionRange'>418 - </span><a href="#h-126"><span class="HTitleText3">Programme de contrats fédéraux pour l’équité salariale</span></a>
</li>
<li><span class='sectionRange'>419 - </span><a href="#h-127"><span class="HTitleText3">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>419 - </span><a href="#h-128"><span class="HTitleText4"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>427 - </span><a href="#h-129"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>428 - </span><a href="#h-130"><span class="HTitleText3">Disposition transitoire, modifications corrélatives, dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>428 - </span><a href="#h-131"><span class="HTitleText4">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>429 - </span><a href="#h-132"><span class="HTitleText4">Modifications corrélatives</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>429 - </span><a href="#h-133"><span class="HTitleText5"><cite class="XRefExternalAct">Loi d’exécution du budget de 2009</cite></span></a>
</li>
<li><span class='sectionRange'>435 - </span><a href="#h-134"><span class="HTitleText5"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>439 - </span><a href="#h-135"><span class="HTitleText4">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>440 - </span><a href="#h-136"><span class="HTitleText4">Entrée en vigueur</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="#h-137"><span class="HLabel2">SECTION 15</span> - <span class="HTitleText2">Modernisation du Code canadien du travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="#h-138"><span class="HLabel3">SOUS-SECTION A</span></span> - <span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>441 - </span><a href="#h-139"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>506 - </span><a href="#h-140"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 d’exécution du budget de 2017</cite></span></a>
</li>
<li><span class='sectionRange'>511 - </span><a href="#h-141"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 d’exécution du budget de 2017</cite></span></a>
</li>
<li><span class='sectionRange'>517 - </span><a href="#h-142"><span class="HTitleText4">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>529 - </span><a href="#h-143"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>534 - </span><a href="#h-144"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>535 - </span><a href="#h-145"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Chef de la conformité et de l’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>535 - </span><a href="#h-146"><span class="HTitleText4"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>622 - </span><a href="#h-147"><span class="HTitleText4">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>625 - </span><a href="#h-148"><span class="HTitleText4">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>626 - </span><a href="#h-149"><span class="HLabel2">SECTION 16</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Programme de protection des salariés</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>626 - </span><a href="#h-150"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>649 - </span><a href="#h-151"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>651 - </span><a href="#h-152"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>653 - </span><a href="#h-153"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>654 - </span><a href="#h-154"><span class="HLabel2">SECTION 17</span> - <span class="HTitleText2">Aide financière internationale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>654 - </span><a href="#h-155"><span class="HTitleText3">Modification de certaines lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>654 - </span><a href="#h-156"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les accords de Bretton Woods et des accords connexes</cite></span></a>
</li>
<li><span class='sectionRange'>655 - </span><a href="#h-157"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’Accord portant création de la Banque européenne pour la reconstruction et le développement</cite></span></a>
</li>
<li><span class='sectionRange'>656 - </span><a href="#h-158"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la responsabilité en matière d’aide au développement officielle</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>659 - </span><a href="#h-159"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’aide financière internationale</cite></span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-160"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>661 - </span><a href="#h-161"><span class="HLabel2">SECTION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Femmes et de l’Égalité des genres</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>661 - </span><a href="#h-162"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>662 - </span><a href="#h-163"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>662 - </span><a href="#h-164"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 3 de 1976 portant affection de crédits</cite></span></a>
</li>
<li><span class='sectionRange'>663 - </span><a href="#h-165"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>665 - </span><a href="#h-166"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>670 - </span><a href="#h-167"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>672 - </span><a href="#h-168"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les traitements</cite></span></a>
</li>
<li><span class='sectionRange'>673 - </span><a href="#h-169"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>675 - </span><a href="#h-170"><span class="HLabel2">SECTION 19</span> - <span class="HTitleText2">Ajout de terres aux réserves et création de réserves</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>675 - </span><a href="#h-171"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’ajout de terres aux réserves et la création de réserves</cite></span></a>
</li>
<li><span class='sectionRange'>676 - </span><a href="#h-172"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>679 - </span><a href="#h-173"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>679 - </span><a href="#h-174"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les droits fonciers issus de traités en Saskatchewan</cite></span></a>
</li>
<li><span class='sectionRange'>680 - </span><a href="#h-175"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la mise en oeuvre de mesures concernant le règlement de revendications au Manitoba</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>684 - </span><a href="#h-176"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>685 - </span><a href="#h-177"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>686 - </span><a href="#h-178"><span class="HLabel2">SECTION 20</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>687 - </span><a href="#h-179"><span class="HLabel2">SECTION 21</span> - <span class="HTitleText2">Phase 1 des mesures de réduction de la pauvreté</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>687 - </span><a href="#h-180"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la réduction de la pauvreté</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>688 - </span><a href="#h-181"><span class="HLabel2">SECTION 22</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>688 - </span><a href="#h-182"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>711 - </span><a href="#h-183"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>712 - </span><a href="#h-184"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>713 - </span><a href="#h-185"><span class="HLabel2">SECTION 23</span></span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la responsabilité en matière maritime</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>713 - </span><a href="#h-186"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>746 - </span><a href="#h-187"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>747 - </span><a href="#h-188"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-189"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-190"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

