<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la lutte contre le terrorisme</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR LA PREUVE AU CANADA</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR LA PROTECTION DE L’INFORMATION</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

