<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée du patrimoine national en matière de chasse, de piégeage et de pêche</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">JOURNÉE DU PATRIMOINE NATIONAL EN MATIÈRE DE CHASSE, DE PIÉGEAGE ET DE PÊCHE</span></a>
</li></ul>
</li></ul>

</nav>

