<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi corrective de 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits agricoles au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les corporations canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les organisations à but non lucratif</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les transports au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Service canadien du renseignement de sécurité</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de la Convention sur les armes chimiques</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emballage et l’étiquetage des produits de consommation</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la production de défense</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Anciens Combattants</cite></span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le divorce</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence de développement économique du Canada pour les régions du Québec</cite></span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la révision des limites des circonscriptions électorales</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’inspection de l’électricité et du gaz</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les explosifs</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les offices des produits agricoles</cite></span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’équité entre les sexes relativement à l’inscription au registre des Indiens</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la santé des animaux</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Indiens</cite></span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les ponts et tunnels internationaux</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’interprétation</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la réédiction de textes législatifs</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Bibliothèque et les Archives du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’inspection des viandes</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation des marins marchands</cite></span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Loi relative au supplément d’aide financière à Terre-Neuve</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sûreté et la réglementation nucléaires</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les océans</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pensions</cite></span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-56"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’activité physique et le sport</cite></span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des végétaux</cite></span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-58"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-59"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-60"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-61"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-62"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le parc marin du Saguenay — Saint-Laurent</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-63"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’administration des biens saisis</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les espèces en péril</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-65"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le tabac</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-66"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1992 sur le transport des marchandises dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-68"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-69"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les forces étrangères présentes au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations aux anciens combattants</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-71"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="#h-72"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">TERMINOLOGIE</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-73"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li></ul>
</li></ul>

</nav>

