<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2012 sur l’emploi et la croissance</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET DE RÈGLEMENTS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-4"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-5"><span class="HTitleText2">Règlement sur l’épargne-invalidité</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MESURES RELATIVES À LA TAXE DE VENTE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>74 - </span><a href="#h-7"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-8"><span class="HTitleText2">Loi sur l’emploi et la croissance économique</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les méthodes d’attribution des crédits de taxe sur les intrants (TPS/TVH)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="#h-10"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-11"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">DIVERSES MESURES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-12"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Institutions financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-13"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’emploi et la croissance économique</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-17"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-18"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Marine marchande</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-19"><span class="HTitleText3">Loi de 2001 sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-20"><span class="HTitleText3">Services rendus par les sociétés de classification</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-21"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-22"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Maintien de la stabilité et de la vigueur du secteur financier canadien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-23"><span class="HTitleText3">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-24"><span class="HTitleText3">Loi sur la compensation et le règlement des paiements</span></a>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-25"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Pêches</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-26"><span class="HTitleText3">Loi sur les pêches</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-27"><span class="HTitleText3">Loi sur l’emploi, la croissance et la prospérité durable</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-28"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-29"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-30"><span class="HLabel2">Section 5</span> - <span class="HTitleText2">Loi concernant un pont destiné à favoriser le commerce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-31"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-32"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi sur les ponts et tunnels internationaux</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-33"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-34"><span class="HLabel2">Section 6</span> - <span class="HTitleText2">Loi sur les accords de Bretton Woods et des accords connexes</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-35"><span class="HLabel2">Section 7</span> - <span class="HTitleText2">Régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-36"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-37"><span class="HTitleText3">Modification à la <cite class="XRefExternalAct">Loi sur le ministère des Ressources humaines et du Développement des compétences</cite></span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-38"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-39"><span class="HLabel2">Section 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Indiens</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-40"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-41"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>210 - </span><a href="#h-42"><span class="HLabel2">Section 9</span> - <span class="HTitleText2">Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-43"><span class="HLabel2">Section 10</span> - <span class="HTitleText2">Code canadien du travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="#h-44"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-45"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-46"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>233 - </span><a href="#h-47"><span class="HLabel2">Section 11</span> - <span class="HTitleText2">Loi sur l’indemnisation des marins marchands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>233 - </span><a href="#h-48"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-49"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-50"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>261 - </span><a href="#h-51"><span class="HTitleText4">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-52"><span class="HTitleText4">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>263 - </span><a href="#h-53"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>264 - </span><a href="#h-54"><span class="HLabel2">Section 12</span> - <span class="HTitleText2">Loi sur les douanes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>264 - </span><a href="#h-55"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-56"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="#h-57"><span class="HLabel2">Section 13</span> - <span class="HTitleText2">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>269 - </span><a href="#h-58"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-59"><span class="HTitleText3">Transfert de fonctionnaires et de postes</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-60"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-61"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>290 - </span><a href="#h-62"><span class="HTitleText4">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="#h-63"><span class="HTitleText4">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-64"><span class="HTitleText4">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="#h-65"><span class="HTitleText4">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-66"><span class="HTitleText4">Décret sur la désignation des administrateurs généraux de l’administration publique fédérale (Loi sur le Service canadien du renseignement de sécurité)</span></a>
</li></ul>
</li><li><span class='sectionRange'>297 - </span><a href="#h-67"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-68"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="#h-69"><span class="HLabel2">Section 14</span> - <span class="HTitleText2">Loi de mise en oeuvre de l’Accord sur le commerce intérieur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="#h-70"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-71"><span class="HTitleText3">Modification connexe à la <cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-72"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>307 - </span><a href="#h-73"><span class="HLabel2">Section 15</span> - <span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-74"><span class="HLabel2">Section 16</span> - <span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-75"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-76"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>315 - </span><a href="#h-77"><span class="HLabel2">Section 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne d’hypothèques et de logement</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-78"><span class="HLabel2">Section 18</span> - <span class="HTitleText2">Loi sur la protection des eaux navigables</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>316 - </span><a href="#h-79"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-80"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-81"><span class="HTitleText3">Abrogation</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="#h-82"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="#h-83"><span class="HTitleText4">Loi sur les commissions portuaires</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-84"><span class="HTitleText4">Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-85"><span class="HTitleText4">Loi sur la sécurité ferroviaire</span></a>
</li>
<li><span class='sectionRange'>342 - </span><a href="#h-86"><span class="HTitleText4">Loi maritime du Canada</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="#h-87"><span class="HTitleText4">Loi sur le Tribunal d’appel des transports du Canada</span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="#h-88"><span class="HTitleText4">Loi sur les aires marines nationales de conservation du Canada</span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-89"><span class="HTitleText4">Loi sur les ponts nécessaires au parachèvement de l’autoroute 30</span></a>
</li></ul>
</li><li><span class='sectionRange'>348 - </span><a href="#h-90"><span class="HTitleText3">Modification connexe à la Loi de 2002 sur la sécurité publique</span></a>
</li>
<li><span class='sectionRange'>349 - </span><a href="#h-91"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="#h-92"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>351 - </span><a href="#h-93"><span class="HLabel2">Section 19</span> - <span class="HTitleText2">Loi sur les grains du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>351 - </span><a href="#h-94"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-95"><span class="HTitleText3">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>390 - </span><a href="#h-96"><span class="HTitleText4">Loi modifiant la Loi sur les grains du Canada et la Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire et abrogeant la Loi sur les marchés de grain à terme</span></a>
</li>
<li><span class='sectionRange'>403 - </span><a href="#h-97"><span class="HTitleText4">Loi d’harmonisation n<sup>o</sup> 1 du droit fédéral avec le droit civil</span></a>
</li>
<li><span class='sectionRange'>404 - </span><a href="#h-98"><span class="HTitleText4">Loi d’harmonisation n<sup>o</sup> 2 du droit fédéral avec le droit civil</span></a>
</li></ul>
</li><li><span class='sectionRange'>405 - </span><a href="#h-99"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>410 - </span><a href="#h-100"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>411 - </span><a href="#h-101"><span class="HLabel2">Section 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les garanties internationales portant sur des matériels d’équipement mobiles (matériels d’équipement aéronautiques)</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>411 - </span><a href="#h-102"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-103"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>414 - </span><a href="#h-104"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>419 - </span><a href="#h-105"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les arrangements avec les créanciers des compagnies</cite></span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-106"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>424 - </span><a href="#h-107"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>425 - </span><a href="#h-108"><span class="HLabel2">Section 21</span> - <span class="HTitleText2">Loi canadienne sur l’évaluation environnementale (2012)</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-109"><span class="HLabel2">Section 22</span> - <span class="HTitleText2">Office de financement de l’assurance-emploi du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>433 - </span><a href="#h-110"><span class="HTitleText3">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="#h-111"><span class="HTitleText3">Loi sur le ministère des Ressources humaines et du Développement des compétences</span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="#h-112"><span class="HTitleText3">Loi sur l’Office de financement de l’assurance-emploi du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>442 - </span><a href="#h-113"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>446 - </span><a href="#h-114"><span class="HTitleText4">Suspension</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-115"><span class="HTitleText4">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="#h-116"><span class="HTitleText3">Loi sur l’emploi, la croissance et la prospérité durable</span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-117"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="#h-118"><span class="HTitleText3">Modifications corrélatives à la Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="#h-119"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="#h-120"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>464 - </span><a href="#h-121"><span class="HLabel2">Section 23</span> - <span class="HTitleText2">Régimes de pension du secteur public</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>464 - </span><a href="#h-122"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de retraite des Forces canadiennes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>464 - </span><a href="#h-123"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>473 - </span><a href="#h-124"><span class="HTitleText4">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les régimes de retraite particuliers</cite></span></a>
</li>
<li><span class='sectionRange'>474 - </span><a href="#h-125"><span class="HTitleText4">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>475 - </span><a href="#h-126"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>475 - </span><a href="#h-127"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>501 - </span><a href="#h-128"><span class="HTitleText4">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-129"><span class="HTitleText4">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-130"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-131"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les régimes de retraite particuliers</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>504 - </span><a href="#h-132"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de retraite de la Gendarmerie royale du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>504 - </span><a href="#h-133"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>513 - </span><a href="#h-134"><span class="HTitleText4">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les régimes de retraite particuliers</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>514 - </span><a href="#h-135"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>515 - </span><a href="#h-136"><span class="HLabel2">Section 24</span> - <span class="HTitleText2">Loi sur l’Agence du revenu du Canada</span></a>
</li></ul>
</li><li><a href="#h-137"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-138"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

