<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Immigration et la protection des réfugiés, Loi sur l’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HTitleText1">OBJET DE LA LOI</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HTitleText1">MISE EN APPLICATION</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-5"><span class="HTitleText1">CONCERTATION INTERGOUVERNEMENTALE</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">IMMIGRATION AU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-7"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Formalités préalables à l'entrée et sélection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-8"><span class="HTitleText3">Formalités préalables à l’entrée</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-9"><span class="HTitleText3">Sélection des résidents permanents</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-10"><span class="HTitleText3">Régime de parrainage</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-11"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-2.html#h-12"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Contrôle</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-13"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Entrée et séjour au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-2.html#h-14"><span class="HTitleText3">Entrée et séjour</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-15"><span class="HTitleText3">Statut et autorisation d’entrer</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-16"><span class="HTitleText3">Droits et obligations des résidents permanents et des résidents temporaires</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-17"><span class="HTitleText3">Attestation de statut</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-18"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-3.html#h-19"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Interdictions de territoire</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-20"><span class="HLabel2">Section 5</span> - <span class="HTitleText2">Perte de statut et renvoi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-4.html#h-21"><span class="HTitleText3">Constat de l’interdiction de territoire</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-22"><span class="HTitleText3">Enquête par la Section de l’immigration</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-23"><span class="HTitleText3">Perte du statut</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-24"><span class="HTitleText3">Exécution des mesures de renvoi</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-25"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="page-5.html#h-26"><span class="HLabel2">Section 6</span> - <span class="HTitleText2">Détention et mise en liberté</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-5.html#h-27"><span class="HLabel2">Section 7</span> - <span class="HTitleText2">Droit d'appel</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-28"><span class="HLabel2">Section 8</span> - <span class="HTitleText2">Contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-6.html#h-29"><span class="HLabel2">Section 9</span> - <span class="HTitleText2">Certificats et protection de renseignements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="page-6.html#h-30"><span class="HTitleText3">Examen à la demande du ministre et du solliciteur général</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-31"><span class="HTitleText3">Détention</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-7.html#h-32"><span class="HTitleText3">Examen dans le cadre d’une enquête ou d’un appel en matière d’immigration</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-33"><span class="HTitleText3">Examen dans le cadre du contrôle judiciaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>88 - </span><a href="page-7.html#h-34"><span class="HLabel2">Section 10</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="page-7.html#h-35"><span class="HTitleText3">Prêts</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-7.html#h-36"><span class="HTitleText3">Frais</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-7.html#h-37"><span class="HTitleText3">Cartes d’assurance sociale</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-7.html#h-38"><span class="HTitleText3">Réglementation de la représentation</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-7.html#h-39"><span class="HTitleText3">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-8.html#h-40"><span class="HTitleText3">Rapports au Parlement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="page-8.html#h-41"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">PROTECTION DES RÉFUGIÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="page-8.html#h-42"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Notions d’asile, de réfugié et de personnne à protéger</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-8.html#h-43"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Réfugiés et personnes à protéger</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="page-8.html#h-44"><span class="HTitleText3">Demande d’asile</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-8.html#h-45"><span class="HTitleText3">Examen de la recevabilité par l’agent</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-8.html#h-46"><span class="HTitleText3">Interruption de l’étude de la demande d’asile</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-9.html#h-47"><span class="HTitleText3">Procédure d’extradition</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-9.html#h-48"><span class="HTitleText3">Étrangers sans papier</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-9.html#h-49"><span class="HTitleText3">Décision sur la demande d’asile</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-9.html#h-50"><span class="HTitleText3">Perte de l’asile</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-9.html#h-51"><span class="HTitleText3">Annulation par la Section de la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-9.html#h-52"><span class="HTitleText3">Appel devant la Section d’appel des réfugiés</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="page-9.html#h-53"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Examen des risques avant renvoi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-9.html#h-54"><span class="HTitleText3">Protection</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-10.html#h-55"><span class="HTitleText3">Principe du non-refoulement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="page-10.html#h-56"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">EXÉCUTION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="page-10.html#h-57"><span class="HTitleText2">Organisation d’entrée illégale au Canada</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-10.html#h-58"><span class="HTitleText2">Infractions relatives aux documents</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-10.html#h-59"><span class="HTitleText2">Infractions générales</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-11.html#h-60"><span class="HTitleText2">Produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-11.html#h-61"><span class="HTitleText2">Règles visant les poursuites</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-11.html#h-62"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-11.html#h-63"><span class="HTitleText2">Agents d’application de la loi</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-12.html#h-64"><span class="HTitleText2">Agents de la paix</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="page-12.html#h-65"><span class="HTitleText2">Contraventions</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-12.html#h-66"><span class="HTitleText2">Créances de Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-12.html#h-67"><span class="HTitleText2">Exécution des créances</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-12.html#h-68"><span class="HTitleText2">Propriétaires et exploitants de véhicules et d’installations de transport</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="page-12.html#h-69"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">COMMISSION DE L’IMMIGRATION ET DU STATUT DE RÉFUGIÉ</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="page-12.html#h-70"><span class="HTitleText2">Composition de la Commission</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-13.html#h-71"><span class="HTitleText2">Siège et personnel</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-13.html#h-72"><span class="HTitleText2">Présidence de la Commission</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-13.html#h-73"><span class="HTitleText2">Fonctionnement</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-13.html#h-74"><span class="HTitleText2">Attributions communes</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-14.html#h-75"><span class="HTitleText2">Section de la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-14.html#h-76"><span class="HTitleText2">Section d’appel des réfugiés</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-14.html#h-77"><span class="HTitleText2">Section de l’immigration</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-14.html#h-78"><span class="HTitleText2">Section d’appel de l’immigration</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-14.html#h-79"><span class="HTitleText2">Mesures correctives et disciplinaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="page-14.html#h-80"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES, DISPOSITION DE COORDINATION, ABROGATIONS ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="page-14.html#h-81"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="page-15.html#h-82"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202 - </span><a href="page-15.html#h-83"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="page-15.html#h-84"><span class="HTitleText3">Loi sur les programmes de commercialisation agricole</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="page-15.html#h-85"><span class="HTitleText3">Loi sur la généalogie des animaux</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-15.html#h-86"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-15.html#h-87"><span class="HTitleText3">Loi d’exécution du budget de 1998</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-15.html#h-88"><span class="HTitleText3">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-15.html#h-89"><span class="HTitleText3">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-15.html#h-90"><span class="HTitleText3">Loi sur l’Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-15.html#h-91"><span class="HTitleText3">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="page-16.html#h-92"><span class="HTitleText3">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-16.html#h-93"><span class="HTitleText3">Loi sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="page-16.html#h-94"><span class="HTitleText3">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-16.html#h-95"><span class="HTitleText3">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="page-16.html#h-96"><span class="HTitleText3">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="page-16.html#h-97"><span class="HTitleText3">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="page-16.html#h-98"><span class="HTitleText3">Loi de mise en oeuvre de la Convention sur les armes chimiques</span></a>
</li>
<li><span class='sectionRange'>227.1 - </span><a href="page-16.html#h-99"><span class="HTitleText3">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-17.html#h-100"><span class="HTitleText3">Loi de mise en oeuvre du Traité d’interdiction complète des essais nucléaires</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-17.html#h-101"><span class="HTitleText3">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="page-17.html#h-102"><span class="HTitleText3">Loi sur le droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="page-17.html#h-103"><span class="HTitleText3">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-18.html#h-104"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="page-18.html#h-105"><span class="HTitleText3">Loi sur les mesures d’urgence</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-18.html#h-106"><span class="HTitleText3">Loi sur l’extradition</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-18.html#h-107"><span class="HTitleText3">Loi sur les services publicitaires fournis par des éditeurs étrangers</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-18.html#h-108"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-18.html#h-109"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="page-18.html#h-110"><span class="HTitleText3">Loi sur le Centre international des droits de la personne et du développement démocratique</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-19.html#h-111"><span class="HTitleText3">Loi sur Investissement Canada</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-19.html#h-112"><span class="HTitleText3">Loi sur les prestations d’adaptation pour les travailleurs</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="page-19.html#h-113"><span class="HTitleText3">Loi sur l’entraide juridique en matière criminelle</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="page-19.html#h-114"><span class="HTitleText3">Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="page-19.html#h-115"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="page-19.html#h-116"><span class="HTitleText3">Loi sur le pilotage</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-19.html#h-117"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="page-19.html#h-118"><span class="HTitleText3">Loi sur le recyclage des produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-19.html#h-119"><span class="HTitleText3">Loi sur les marques de commerce</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="page-19.html#h-120"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="page-19.html#h-121"><span class="HTitleText3">Terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>273.1 - </span><a href="page-19.html#h-122"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="page-20.html#h-123"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="page-20.html#h-124"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-21.html#h-125"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - SECTIONS E ET F DE L’ARTICLE PREMIER DE LA CONVENTION DES NATIONS UNIES RELATIVE AU STATUT DES RÉFUGIÉS</span></a>
</li></ul>
</li></ul>

</nav>

