<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à changer le nom de certaines circonscriptions électorales ainsi qu’à modifier la Loi sur la révision des limites des circonscriptions électorales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CIRCONSCRIPTIONS ÉLECTORALES DU QUÉBEC, DE L’ONTARIO, DE LA SASKATCHEWAN, DE L’ALBERTA ET DE LA COLOMBIE-BRITANNIQUE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Québec</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Ontario</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-6"><span class="HTitleText2">Alberta</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-7"><span class="HTitleText2">Colombie-Britannique</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-2.html#h-8"><span class="HTitleText1">MODIFICATION À LA <cite class="XRefExternalAct">LOI SUR LA RÉVISION DES LIMITES DES CIRCONSCRIPTIONS ÉLECTORALES</cite></span></a>
</li></ul>
</li></ul>

</nav>

