<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi électorale du Canada et la Loi de l'impôt sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">LOI ÉLECTORALE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-2"><span class="HTitleText1">LOI DE L'IMPÔT SUR LE REVENU</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

