<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la législation régissant les institutions financières et comportant des mesures connexes et corrélatives</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LES BANQUES</cite></span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-15.html#h-2"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LES ASSOCIATIONS COOPÉRATIVES DE CRÉDIT</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-20.html#h-3"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LES SOCIÉTÉS D’ASSURANCES</cite></span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="page-34.html#h-4"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">MODIFICATION DE LA <cite class="XRefExternalAct">LOI SUR LES SOCIÉTÉS DE FIDUCIE ET DE PRÊT</cite></span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="page-39.html#h-5"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">MODIFICATION D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>386 - </span><a href="page-39.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi modifiant certaines lois relatives aux institutions financières</cite></span></a>
</li>
<li><span class='sectionRange'>392 - </span><a href="page-39.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la banque du canada</cite></span></a>
</li>
<li><span class='sectionRange'>398 - </span><a href="page-39.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les lettres de change</cite></span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="page-40.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les sociétés par actions</cite></span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="page-40.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="page-42.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi canadienne sur les paiements</cite></span></a>
</li>
<li><span class='sectionRange'>435 - </span><a href="page-43.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence de la consommation en matière financière du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="page-43.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’association personnalisée le Bouclier vert du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>439 - </span><a href="page-43.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="page-43.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi nationale sur l’habitation</cite></span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="page-43.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="page-44.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les liquidations et les restructurations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="page-44.html#h-18"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>450 - </span><a href="page-44.html#h-19"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="page-44.html#h-20"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

