<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les marques olympiques et paralympiques</a><ul class="TocIndent"><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-1"><span class="HTitleText1">MODIFICATION DE LA PRÉSENTE LOI</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-2"><span class="HTitleText1">MODIFICATION CONNEXE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Loi sur les marques de commerce</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-2.html#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-3.html#h-5"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - MARQUES</span></a>
</li>
<li><a href="page-4.html#h-6"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - MARQUES</span></a>
</li>
<li><a href="page-5.html#h-7"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - EXPRESSIONS</span></a>
</li></ul>
</li></ul>

</nav>

