<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Régime de pensions du Canada et la Loi sur la sécurité de la vieillesse</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">RÉGIME DE PENSIONS DU CANADA</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LA SÉCURITÉ DE LA VIEILLESSE</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-4"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

