<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Droit criminel, Loi de 2001 modifiant le</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>696.1 - </span><a href="page-7.html#h-3"><span class="HLabel1">PARTIE XXI.1</span> - <span class="HTitleText1">DEMANDES DE RÉVISION AUPRÈS DU MINISTRE — ERREURS JUDICIAIRES</span></a>
</li>
<li><span class='sectionRange'>841 - </span><a href="page-9.html#h-4"><span class="HLabel1">PARTIE XXVIII</span> - <span class="HTitleText1">DISPOSITIONS DIVERSES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>841 - </span><a href="page-9.html#h-5"><span class="HTitleText2">Documents électroniques</span></a>
</li>
<li><span class='sectionRange'>848 - </span><a href="page-9.html#h-6"><span class="HTitleText2">Comparution à distance de l’accusé</span></a>
</li>
<li><span class='sectionRange'>849 - </span><a href="page-9.html#h-7"><span class="HTitleText2">Formules</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-9.html#h-8"><span class="HTitleText1">LOI SUR LA CAPITALE NATIONALE</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-9.html#h-9"><span class="HTitleText1">LOI SUR LA DÉFENSE NATIONALE</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-10.html#h-10"><span class="HTitleText1">LOI SUR LES JEUNES CONTREVENANTS</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-10.html#h-11"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-10.html#h-12"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

