<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant la protection des mers et ciel canadiens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’INDEMNISATION DE L’INDUSTRIE AÉRIENNE</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-4"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-2.html#h-5"><span class="HTitleText3">Loi sur les risques de guerre en matière d’assurance maritime et aérienne</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-6"><span class="HTitleText3">Terminologie</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-2.html#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR L’AÉRONAUTIQUE</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-8"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-3.html#h-10"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-11"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-12"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-3.html#h-13"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-14"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-3.html#h-15"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI MARITIME DU CANADA</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-16"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI SUR LA RESPONSABILITÉ EN MATIÈRE MARITIME</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="page-3.html#h-17"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="page-6.html#h-19"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1"><cite class="XRefExternalAct">LOI DE 2001 SUR LA MARINE MARCHANDE DU CANADA</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="page-6.html#h-20"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-8.html#h-21"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-8.html#h-22"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-9.html#h-23"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

