<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant le Code criminel (troubles mentaux) et modifiant d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-2"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="page-5.html#h-3"><span class="HTitleText2">Loi modifiant le Code criminel (troubles mentaux) et modifiant en conséquence la Loi sur la défense nationale et la Loi sur les jeunes contrevenants</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-4"><span class="HTitleText2">Loi modifiant le Code criminel (détermination de la peine) et d’autres lois en conséquence</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-5"><span class="HTitleText2">Loi modifiant le Code criminel, la Loi réglementant certaines drogues et autres substances et la Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-6"><span class="HTitleText2">Loi modifiant le Code criminel (victimes d’actes criminels) et une autre loi en conséquence</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-7"><span class="HTitleText2">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-7.html#h-8"><span class="HTitleText2">Loi sur la sûreté et la réglementation nucléaires</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-9"><span class="HTitleText2">Loi sur le système de justice pénale pour les adolescents</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="page-7.html#h-10"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-7.html#h-11"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

