<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2006 sur les droits d’exportation de produits de bois d’oeuvre,</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-4"><span class="HTitleText1">CHAMP D’APPLICATION</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5"><span class="HTitleText1">DROITS D’EXPORTATION DE PRODUITS DE BOIS D’OEUVRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-2.html#h-6"><span class="HTitleText2">Droits d’exportation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-3.html#h-8"><span class="HTitleText1">DROITS SUR LES REMBOURSEMENTS DE DÉPÔTS DOUANIERS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-9"><span class="HTitleText1">DISPOSITIONS GÉNÉRALES CONCERNANT LES DROITS ET LES AUTRES SOMMES À PAYER</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="page-3.html#h-10"><span class="HTitleText2">Personnel assurant l’exécution et le contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-11"><span class="HTitleText2">Inscription et agrément</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-4.html#h-12"><span class="HTitleText2">Déclarations et paiement des droits</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-14"><span class="HTitleText2">Frais administratifs prévus par la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-15"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-16"><span class="HTitleText2">Faillites et réorganisations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-17"><span class="HTitleText2">Sociétés de personnes</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-6.html#h-18"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-19"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-20"><span class="HTitleText2">Opposition aux cotisations</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-7.html#h-21"><span class="HTitleText2">Appel</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="page-8.html#h-22"><span class="HTitleText1">EXÉCUTION ET CONTRÔLE D’APPLICATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="page-8.html#h-23"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-9.html#h-24"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-9.html#h-25"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-10.html#h-26"><span class="HTitleText2">Enquête</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-10.html#h-27"><span class="HTitleText2">Renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-11.html#h-28"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-13.html#h-29"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="page-14.html#h-30"><span class="HTitleText1">PAIEMENTS AUX PROVINCES</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-14.html#h-31"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-14.html#h-32"><span class="HTitleText1">CESSATION D’EFFET</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-14.html#h-33"><span class="HTitleText1">AFFECTATION DE VERSEMENTS</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-14.html#h-34"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-15.html#h-35"><span class="HTitleText1">MODIFICATIONS À LA LOI SUR LES LICENCES D’EXPORTATION ET D’IMPORTATION</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-16.html#h-36"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="page-16.html#h-37"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-16.html#h-38"><span class="HTitleText2">Loi sur l’Agence du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-16.html#h-39"><span class="HTitleText2">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>125 - </span><a href="page-16.html#h-40"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-17.html#h-41"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li>
<li><a href="page-18.html#h-42"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - PERSONNES EXEMPTÉES</span></a>
</li></ul>
</li></ul>

</nav>

