<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi édictant la Loi sur l’évaluation d’impact et la Loi sur la Régie canadienne de l’énergie, modifiant la Loi sur la protection de la navigation et apportant des modifications corrélatives à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’évaluation d’impact</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="page-1.html#h-2"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-2.html#h-3"><span class="HTitleText2">Modifications à la <cite class="XRefExternalAct">Loi sur l’évaluation d’impact</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Abrogation</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-3.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la Régie canadienne de l’énergie</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-3.html#h-6"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-4.html#h-7"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-6.html#h-8"><span class="HTitleText2">Abrogation</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-6.html#h-9"><span class="HLabel1">PARTIE 3</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la protection de la navigation</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-6.html#h-10"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-12.html#h-11"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="page-13.html#h-12"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Modifications corrélatives, dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="page-13.html#h-13"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="page-13.html#h-14"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-13.html#h-15"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’administration de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-13.html#h-16"><span class="HTitleText3"><cite class="XRefExternalAct">Loi d’urgence sur les approvisionnements d’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-14.html#h-17"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-14.html#h-18"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-14.html#h-19"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-14.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-14.html#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-14.html#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le pipe-line du Nord</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-15.html#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les opérations pétrolières au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-17.html#h-24"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-17.html#h-25"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-17.html#h-26"><span class="HTitleText3"><cite class="XRefExternalAct">Loi fédérale sur les hydrocarbures</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-18.html#h-27"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-18.html#h-28"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-18.html#h-29"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’exploitation du champ Hibernia</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-18.html#h-30"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-18.html#h-31"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 1992 sur le transport des marchandises dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-18.html#h-32"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Office des droits de surface du Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-18.html#h-33"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des ressources de la vallée du Mackenzie</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-19.html#h-34"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-19.html#h-35"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les eaux du Nunavut et le Tribunal des droits de surface du Nunavut</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-19.html#h-36"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les espèces en péril</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-19.html#h-37"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’évaluation environnementale et socioéconomique au Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-19.html#h-38"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion du pétrole et du gaz et des fonds des Premières Nations</cite></span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-20.html#h-39"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les pénalités administratives en matière d’environnement</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-20.html#h-40"><span class="HTitleText3"><cite class="XRefExternalAct">Loi concernant un pont destiné à favoriser le commerce</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-20.html#h-41"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’aménagement du territoire et l’évaluation des projets au Nunavut</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-20.html#h-42"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le transfert de responsabilités aux Territoires du Nord-Ouest</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-20.html#h-43"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les Territoires du Nord-Ouest</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>186 - </span><a href="page-20.html#h-44"><span class="HTitleText2">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-21.html#h-45"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-22.html#h-46"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-23.html#h-47"><span class="scheduleLabel">Annexe</span> </a>
</li></ul>
</li></ul>

</nav>

