<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Harmonisation n<Sup>o</Sup> 1 du droit fédéral avec le droit civil, Loi d’</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">DROIT FÉDÉRAL ET DROIT CIVIL DE LA PROVINCE DE QUÉBEC</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Titre</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-4"><span class="HTitleText2">Code civil du Bas Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5"><span class="HTitleText2">Mariage</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI D’INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-7"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LES IMMEUBLES FÉDÉRAUX</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-8"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA FAILLITE ET L’INSOLVABILITÉ</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-9"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA RESPONSABILITÉ CIVILE DE L’ÉTAT ET LE CONTENTIEUX ADMINISTRATIF</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-10"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">MODIFICATIONS DIVERSES À D’AUTRES LOIS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="page-5.html#h-11"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’aéronautique</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-12"><span class="HTitleText2"><cite class="XRefExternalAct">Loi relative aux cessions d’aéroports</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-13"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la généalogie des animaux</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-6.html#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Bell Canada</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-6.html#h-16"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits agricoles au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil des Arts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-6.html#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-6.html#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre canadien de gestion</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-6.html#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence spatiale canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-6.html#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la production de défense</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-6.html#h-22"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de l’Industrie</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-7.html#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’urgence sur les approvisionnements d’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-7.html#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les explosifs</cite></span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-7.html#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi d’aide à l’exécution des ordonnances et des ententes familiales</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-27"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les offices des produits agricoles</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-7.html#h-28"><span class="HTitleText2"><cite class="XRefExternalAct">Loi relative aux aliments du bétail</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-7.html#h-29"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les armes à feu</cite></span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-7.html#h-30"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures extraterritoriales étrangères</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-7.html#h-31"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les grains du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-7.html#h-32"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les topographies de circuits intégrés</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-7.html#h-33"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’intérêt</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-8.html#h-34"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Fondation Jules et Paul-Émile Léger</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-8.html#h-35"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les prestations d’adaptation pour les travailleurs</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-8.html#h-36"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Commission du droit du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-8.html#h-37"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’inspection des viandes</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-8.html#h-38"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1987 sur les transports routiers</cite></span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-8.html#h-39"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre national des Arts</cite></span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="page-8.html#h-40"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office national de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-8.html#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le cinéma</cite></span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-9.html#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil national de recherches</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-9.html#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil de recherches en sciences naturelles et en génie</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-9.html#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité de la vieillesse</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-9.html#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés de caisse de retraite</cite></span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-46"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation des dommages causés par des pesticides</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-9.html#h-47"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les semences</cite></span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-9.html#h-48"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil de recherches en sciences humaines</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-9.html#h-49"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures économiques spéciales</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-9.html#h-50"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immunité des États</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-9.html#h-51"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-9.html#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les syndicats ouvriers</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-9.html#h-53"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Anciens combattants</cite></span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-10.html#h-54"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les forces étrangères présentes au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-10.html#h-55"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les espèces sauvages du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="page-10.html#h-56"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-10.html#h-57"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence des douanes et du revenu du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-11.html#h-58"><span class="HTitleText2"><cite class="XRefExternalAct">Loi maritime du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-12.html#h-59"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</cite></span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-12.html#h-60"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</cite></span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-13.html#h-61"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère du Patrimoine canadien</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-13.html#h-62"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-13.html#h-63"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-13.html#h-64"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Commission frontalière</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-13.html#h-65"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les opérations pétrolières au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-13.html#h-66"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la mise en oeuvre de mesures concernant le règlement de revendications au Manitoba</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-13.html#h-67"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence Parcs Canada</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-14.html#h-68"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les fonds renouvelables</cite></span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-14.html#h-69"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les biens de surplus de la Couronne</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-14.html#h-70"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Transports</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-14.html#h-71"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les forces étrangères présentes au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-14.html#h-72"><span class="HTitleText2">Terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>174 - </span><a href="page-14.html#h-73"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-15.html#h-74"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">DISPOSITION TRANSITOIRE ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="page-15.html#h-75"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-15.html#h-76"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

