<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2010 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">LOI DE 2010 SUR LA CONVENTION FISCALE CANADA-COLOMBIE</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LOI DE 2010 SUR LA CONVENTION FISCALE CANADA-GRÈCE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI DE 2010 SUR LA CONVENTION FISCALE CANADA-TURQUIE</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

