<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant le Code canadien du travail, la Loi fédérale sur l’aide financière aux étudiants, la Loi fédérale sur les prêts aux étudiants et la Loi sur l’emploi dans la fonction publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">CODE CANADIEN DU TRAVAIL</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI FÉDÉRALE SUR L’AIDE FINANCIÈRE AUX ÉTUDIANTS</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">LOI FÉDÉRALE SUR LES PRÊTS AUX ÉTUDIANTS</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR L’EMPLOI DANS LA FONCTION PUBLIQUE</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

