<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant certaines lois en matière d’identification par les empreintes génétiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">DÉFINITION</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">MODIFICATIONS À L’AUTRE LOI</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3"><span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-4.html#h-4"><span class="HTitleText1">LOI SUR L’IDENTIFICATION PAR LES EMPREINTES GÉNÉTIQUES</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-5.html#h-5"><span class="HTitleText1">LOI SUR LA DÉFENSE NATIONALE</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-6"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-7.html#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

