<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur la défense nationale et apportant des modifications connexes et corrélatives à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-8.html#h-2"><span class="HTitleText1">Modifications connexes au <cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-9.html#h-3"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="page-9.html#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-9.html#h-5"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-9.html#h-6"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les conventions de Genève</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-9.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les forces étrangères présentes au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-9.html#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-10.html#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Loi interdisant les armes à sous-munitions</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-10.html#h-10"><span class="HTitleText2"><cite class="XRefExternalAct">Charte canadienne des droits des victimes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="page-10.html#h-11"><span class="HTitleText1">Modifications connexes et dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-12.html#h-12"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-12.html#h-13"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

