<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Tribunal d’appel des transports du Canada, Loi sur le</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">TRIBUNAL D’APPEL DES TRANSPORTS DU CANADA</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-3"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-4"><span class="HTitleText1">MODIFICATIONS CONNEXES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="page-2.html#h-5"><span class="HTitleText2">Loi sur l’aéronautique</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-6"><span class="HTitleText2">Loi sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-7"><span class="HTitleText2">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-8"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-9"><span class="HTitleText2">Loi sur la sûreté du transport maritime</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-10"><span class="HTitleText2">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-7.html#h-11"><span class="HTitleText2">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-7.html#h-12"><span class="HTitleText2">Loi sur la sécurité ferroviaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="page-8.html#h-13"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71 - </span><a href="page-8.html#h-14"><span class="HTitleText2">Modification à la présente loi</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-8.html#h-15"><span class="HTitleText2">Projet de loi C-14</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-9.html#h-16"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

