<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les possibilités de la mise en valeur de la réserve de charbon Donkin</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">OBJET</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">APPLICATION</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">DÉLÉGATION</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText1">REDEVANCES</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">ACCORD</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText1">POUVOIRS RÉGLEMENTAIRES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText1">MODIFICATION CORRÉLATIVE À LA LOI DE MISE EN OEUVRE DE L’ACCORD CANADA — NOUVELLE-ÉCOSSE SUR LES HYDROCARBURES EXTRACÔTIERS</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - DÉLIMITATION DE LA RÉSERVE DE CHARBON DONKIN</span></a>
</li></ul>
</li></ul>

</nav>

