<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Taxes de vente et d’accise, Loi de 2001 modifiant les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR LA TAXE D’ACCISE</span></a>
</li></ul>
</li></ul>

</nav>

