<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 2005</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT L’IMPÔT SUR LE REVENU</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-3"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-4"><span class="HTitleText2">Règles concernant l’application de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-3.html#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LE DROIT POUR LA SÉCURITÉ DES PASSAGERS DU TRANSPORT AÉRIEN</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-3.html#h-6"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-7"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="page-3.html#h-8"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE SUR LES PRODUITS ET SERVICES ET LA TAXE DE VENTE HARMONISÉE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="page-3.html#h-9"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-4.html#h-10"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">MODIFICATIONS CONCERNANT LA TAXE D’ACCISE SUR LES BIJOUX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-4.html#h-11"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-4.html#h-12"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LES ARRANGEMENTS FISCAUX ENTRE LE GOUVERNEMENT FÉDÉRAL ET LES PROVINCES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-4.html#h-13"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-14"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-4.html#h-15"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">STRATÉGIE POUR LE NORD</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-4.html#h-16"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">VÉRIFICATEUR GÉNÉRAL DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-4.html#h-17"><span class="HTitleText2">Modification de la Loi sur le vérificateur général</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-5.html#h-18"><span class="HTitleText2">Modification de la Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-19"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-5.html#h-20"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la radiodiffusion</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-21"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-22"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Fondation canadienne des relations raciales</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-23"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Office d’investissement des régimes de pensions du secteur public</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="page-5.html#h-24"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-6.html#h-25"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">PAIEMENTS À CERTAINES ENTITÉS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-6.html#h-26"><span class="HTitleText2">Fondation autochtone de guérison</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-6.html#h-27"><span class="HTitleText2">Fondation Asie-Pacifique du Canada</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-6.html#h-28"><span class="HTitleText2">Académies canadiennes des sciences</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-29"><span class="HTitleText2">Canadian Cattlemen’s Association</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-30"><span class="HTitleText2">Fondation canadienne des jeunes entrepreneurs</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-31"><span class="HTitleText2">Fédération canadienne des municipalités</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-6.html#h-32"><span class="HTitleText2">Génome Canada</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-6.html#h-33"><span class="HTitleText2">Precarn Inc.</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="page-6.html#h-34"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">FONDATION ASIE-PACIFIQUE DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="page-6.html#h-35"><span class="HTitleText2">Loi sur la Fondation Asie-Pacifique du Canada</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-8.html#h-36"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="page-8.html#h-37"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">MODIFICATION DE LA LOI D’EXÉCUTION DU BUDGET DE 1998</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-8.html#h-38"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">PAIEMENTS POUR L’INFRASTRUCTURE</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-8.html#h-39"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">PAIEMENTS DE PÉRÉQUATION COMPENSATOIRES SUPPLÉMENTAIRES À LA NOUVELLE-ÉCOSSE ET À TERRE-NEUVE-ET-LABRADOR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="page-8.html#h-40"><span class="HTitleText2">Loi sur les paiements de péréquation compensatoires supplémentaires à la Nouvelle-Écosse et à Terre-Neuve-et-Labrador</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-9.html#h-41"><span class="HTitleText2">Modification connexe de la Loi d’exécution du budget de 2004</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-9.html#h-42"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">AGENCE CANADIENNE POUR L’INCITATION À LA RÉDUCTION DES ÉMISSIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-9.html#h-43"><span class="HTitleText2">Loi sur l’Agence canadienne pour l’incitation à la réduction des émissions</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-10.html#h-44"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="page-10.html#h-45"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-10.html#h-46"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-10.html#h-47"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-10.html#h-48"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-10.html#h-49"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="page-10.html#h-50"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-10.html#h-51"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="page-10.html#h-52"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">FONDS D’INVESTISSEMENT TECHNOLOGIQUE POUR LA LUTTE AUX GAZ À EFFET DE SERRE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="page-10.html#h-53"><span class="HTitleText2"><strong>Loi sur le Fonds d’investissement technologique pour la lutte aux gaz à effet de serre</strong></span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="page-11.html#h-54"><span class="HTitleText1">SUBVENTIONS ET CONTRIBUTIONS </span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-11.html#h-55"><span class="HTitleText1">COMITÉ CONSULTATIF </span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-11.html#h-56"><span class="HTitleText1">UNITÉS D’INVESTISSEMENT TECHNOLOGIQUE </span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97 - </span><a href="page-11.html#h-57"><span class="HTitleText2"><strong>Entrée en vigueur </strong></span></a>
</li></ul>
</li><li><a href="page-11.html#h-58"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA SOCIÉTÉ D’ASSURANCE-DÉPÔTS DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-12.html#h-59"><span class="HTitleText2">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-12.html#h-60"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-12.html#h-61"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">MODIFICATION DE LA LOI FÉDÉRALE SUR L’AIDE FINANCIÈRE AUX ÉTUDIANTS</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-12.html#h-62"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA MONNAIE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>113 - </span><a href="page-12.html#h-63"><span class="HTitleText2">Compte du fonds des changes</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-12.html#h-64"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-12.html#h-65"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="page-12.html#h-66"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LE MINISTÈRE DES TRAVAUX PUBLICS ET DES SERVICES GOUVERNEMENTAUX</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="page-12.html#h-67"><span class="HTitleText2">Loi sur le ministère des Travaux publics et des Services gouvernementaux</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-13.html#h-68"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="page-13.html#h-69"><span class="HLabel1">PARTIE 19</span> - <span class="HTitleText1">MODIFICATIONS RELATIVES AU TAUX DE COTISATION PRÉVU PAR LA LOI SUR L’ASSURANCE-EMPLOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-13.html#h-70"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-13.html#h-71"><span class="HTitleText2">Loi sur le ministère du Développement des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-13.html#h-72"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="page-14.html#h-73"><span class="HLabel1">PARTIE 20</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR L’ASSURANCE-EMPLOI — RÉGIMES PROVINCIAUX</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-14.html#h-74"><span class="HLabel1">PARTIE 21</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="page-14.html#h-75"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-14.html#h-76"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="page-14.html#h-77"><span class="HLabel1">PARTIE 22</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA SÉCURITÉ DE LA VIEILLESSE</span></a>
</li>
<li><a href="page-14.html#h-78"><span class="HLabel1">PARTIE 23</span> - <span class="HTitleText1">PAIEMENTS À CERTAINES PROVINCES ET AUX TERRITOIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="page-15.html#h-79"><span class="HTitleText2">Paiement au Québec</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-15.html#h-80"><span class="HTitleText2">Paiement à la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-15.html#h-81"><span class="HTitleText2">Paiement à la Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-15.html#h-82"><span class="HTitleText2">Paiement au Yukon</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-15.html#h-83"><span class="HTitleText2">Paiement aux Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-15.html#h-84"><span class="HTitleText2">Paiement au Nunavut</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

