<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Produits antiparasitaires, Loi sur les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">SA MAJESTÉ</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">MISSION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">COMITÉ CONSULTATIF</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">HOMOLOGATION DES PRODUITS ANTIPARASITAIRES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Demande d’homologation ou de modification d’homologation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Limites maximales de résidus</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Renseignements supplémentaires et obligation de communiquer</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Réévaluation et examen spécial</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Autres motifs de révocation ou de modification</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText2">Consultation publique</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText1">CONTRÔLE DE L’EXPORTATION</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">EXAMEN DES DÉCISIONS</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">AUTORISATION D’UTILISATION D’UN PRODUIT ANTIPARASITAIRE NON HOMOLOGUÉ</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">ACCÈS À L’INFORMATION</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HTitleText1">APPLICATION DE LA LOI</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText2">Inspecteurs et analystes</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText2">Rapport volontaire</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText2">Visite</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-23"><span class="HTitleText2">Perquisitions</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-24"><span class="HTitleText2">Saisies</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText2">Mesures consécutives à la saisie</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-26"><span class="HTitleText2">Mesures pour faire observer la loi</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-27"><span class="HTitleText2">Mesures d’élimination et de contrôle des risques</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-28"><span class="HTitleText2">Révision des ordres des inspecteurs</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-29"><span class="HTitleText2">Ordre du tribunal</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-30"><span class="HTitleText1">LIVRAISON DE DOCUMENTS</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-31"><span class="HTitleText1">DROITS ET AUTRES FRAIS</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-32"><span class="HTitleText1">LIMITATION DE RESPONSABILITÉ</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-33"><span class="HTitleText1">DROITS À PAYER POUR L’UTILISATION DE RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-34"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-35"><span class="HTitleText1">INFRACTIONS ET PEINES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-36"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-37"><span class="HTitleText2">Dispositions connexes</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-38"><span class="HTitleText1">RAPPORT AU PARLEMENT</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-39"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-40"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-41"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-42"><span class="HTitleText2"><cite class="XRefExternalAct">Loi relative aux aliments du bétail</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-43"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les engrais</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-44"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits dangereux</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-45"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’indemnisation du dommage causé par des pesticides</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-46"><span class="HTitleText1">ABROGATION</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-47"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

