<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la procréation assistée</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">PRINCIPES</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">DÉFINITIONS ET APPLICATION</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">ACTES INTERDITS</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">ACTIVITÉS RÉGLEMENTÉES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">RENSEIGNEMENTS PERSONNELS ET ACCÈS À L'INFORMATION</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-7"><span class="HTitleText1">RESPONSABILITÉS DU MINISTRE</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText1">AGENCE CANADIENNE DE CONTRÔLE DE LA PROCRÉATION ASSISTÉE</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-9"><span class="HTitleText1">MISE EN OEUVRE</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-10"><span class="HTitleText1">INSPECTION ET CONTRÔLE D'APPLICATION</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-11"><span class="HTitleText1">INFRACTIONS</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-12"><span class="HTitleText1">RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-13"><span class="HTitleText1">ACCORDS D'ÉQUIVALENCE</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-14"><span class="HTitleText1">EXAMEN PARLEMENTAIRE</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-15"><span class="HTitleText1">DISPOSITION TRANSITOIRE</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-16"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-17"><span class="HTitleText2">Loi sur l'accès à l'information</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-18"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-19"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-20"><span class="HTitleText2">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-21"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-22"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

