<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Eaux du Nunavut et le Tribunal des droits de surface du Nunavut, Loi sur les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">DÉFINITIONS</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">PRÉSÉANCE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">EAUX DU NUNAVUT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Portée et effet</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText2">Délégation et accords</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Office des eaux du Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText3">Mise en place</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-13"><span class="HTitleText3">Langues</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-14"><span class="HTitleText3">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-15"><span class="HTitleText3">Statut et pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText3">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-17"><span class="HTitleText3">Règles et règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-18"><span class="HTitleText3">Mission et rapports avec d’autres organismes</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-19"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Attribution de permis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-20"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HTitleText3">Demandes relatives aux permis</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText3">Procédure</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-23"><span class="HTitleText3">Conditions de délivrance</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-24"><span class="HTitleText3">Terres inuit</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-25"><span class="HTitleText3">Vallée du Mackenzie</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-26"><span class="HTitleText3">Conditions des permis</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-27"><span class="HTitleText3">Sûreté</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-28"><span class="HTitleText3">Expropriation</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-29"><span class="HTitleText3">Registre public</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-30"><span class="HTitleText3">Décisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-31"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-32"><span class="HTitleText3">Règlements et décrets</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-33"><span class="HTitleText3">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-34"><span class="HTitleText3">Infractions et peines</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-35"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">TRIBUNAL DES DROITS DE SURFACE DU NUNAVUT</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-36"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-37"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-38"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-39"><span class="HLabel2">Section 1</span> - <span class="HTitleText2">Mise en place du tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-40"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-41"><span class="HTitleText3">Langues</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-42"><span class="HTitleText3">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-43"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-44"><span class="HTitleText3">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-45"><span class="HTitleText3">Statut</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-46"><span class="HTitleText3">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-47"><span class="HTitleText3">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-48"><span class="HTitleText3">Saisine du Tribunal</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-49"><span class="HTitleText3">Procédure</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-50"><span class="HTitleText3">Dossiers</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-51"><span class="HTitleText3">Règles</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="#h-52"><span class="HLabel2">Section 2</span> - <span class="HTitleText2">Ordonnances relatives à l’entrée sur les terres inuit</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-53"><span class="HTitleText3">Exercice des droits miniers</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-54"><span class="HTitleText3">Activités commerciales</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-55"><span class="HTitleText3">Matériaux de construction</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-56"><span class="HTitleText3">Règles générales concernant les ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="#h-57"><span class="HLabel2">Section 3</span> - <span class="HTitleText2">Ordonnances relatives à l’entrée sur les terres non inuit</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="#h-58"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-59"><span class="HTitleText3">Exercice des droits miniers</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-60"><span class="HTitleText3">Règles générales concernant l’ordonnance</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-61"><span class="HLabel2">Section 4</span> - <span class="HTitleText2">Droit minier et pierre à sculpter</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-62"><span class="HTitleText3">Matières spécifiées des terres inuit</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-63"><span class="HTitleText3">Pierre à sculpter des terres domaniales</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-64"><span class="HLabel2">Section 5</span> - <span class="HTitleText2">Indemnités relatives aux ressources fauniques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="#h-65"><span class="HTitleText3">Définitions et terminologie</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-66"><span class="HTitleText3">Responsabilité de l’entrepreneur</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-67"><span class="HTitleText3">Demande au Tribunal</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-68"><span class="HTitleText3">Autres recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-69"><span class="HLabel2">Section 6</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-70"><span class="HTitleText3">Décisions du Tribunal</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-71"><span class="HTitleText3">Révision des ordonnances</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-72"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="#h-73"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">DISPOSITIONS TRANSITOIRES, MODIFICATIONS CORRÉLATIVES, DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>171 - </span><a href="#h-74"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-75"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>176 - </span><a href="#h-76"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-77"><span class="HTitleText3">Loi sur la prévention de la pollution des eaux arctiques</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-78"><span class="HTitleText3">Loi sur la gestion des ressources de la vallée du Mackenzie</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-79"><span class="HTitleText3">Loi autorisant l’émission et la vente des actions de la Commission d’énergie du Nord canadien</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-80"><span class="HTitleText3">Loi sur les eaux des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-81"><span class="HTitleText3">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-82"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-83"><span class="HTitleText3">Loi sur l’Office des droits de surface du Yukon</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-84"><span class="HTitleText3">Loi sur les eaux du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="#h-85"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-86"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-87"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-88"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

