<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur le tabac, la Loi sur la santé des non-fumeurs et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HLabel1">PARTIE 1</span></span> - <span class="HTitleText1">Loi sur le tabac</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="#h-3"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71 - </span><a href="#h-4"><span class="HTitleText2">Loi sur les aliments et drogues</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-5"><span class="HTitleText2">Loi modifiant la Loi sur le tabac</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-6"><span class="HTitleText2">Loi canadienne sur la sécurité des produits de consommation</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-7"><span class="HTitleText1">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-8"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-9"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-10"><span class="HLabel1">PARTIE 2</span></span> - <span class="HTitleText1">Loi sur la santé des non-fumeurs</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

