<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant l’enregistrement de renseignements sur les délinquants sexuels et modifiant le Code criminel et d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">OBJET ET PRINCIPES</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">DÉFINITIONS ET INTERPRÉTATION</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">OBLIGATIONS IMPOSÉES AUX DÉLINQUANTS SEXUELS</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">DEVOIRS DES PRÉPOSÉS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">GESTION DE RENSEIGNEMENTS</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">INTERDICTIONS</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">INFRACTIONS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText1">AUTORISATIONS, DÉSIGNATIONS ET RÈGLEMENTS</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText1">MODIFICATIONS CONNEXES : CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-11"><span class="HTitleText1">EXAMEN ET RAPPORT</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText1">MODIFICATIONS CORRÉLATIVES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-13"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2">Loi sur le casier judiciaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText1">DISPOSITION DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-16"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

