<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant certaines lois fédérales et édictant des mesures de mise en oeuvre de la convention sur les armes biologiques ou à toxines, en vue de renforcer la sécurité publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">LOI SUR L'AÉRONAUTIQUE</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">LOI SUR L'ADMINISTRATION CANADIENNE DE LA SÛRETÉ DU TRANSPORT AÉRIEN</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">LOI CANADIENNE SUR LA PROTECTION DE L'ENVIRONNEMENT (1999)</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-5"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">CODE CRIMINEL</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-6"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">LOI SUR LE MINISTÈRE DE LA CITOYENNETÉ ET DE L'IMMIGRATION</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-7"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">LOI SUR LE MINISTÈRE DE LA SANTÉ</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-8"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">LOI SUR LES EXPLOSIFS</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-9"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">LOI SUR LES LICENCES D'EXPORTATION ET D'IMPORTATION</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-10"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">LOI SUR LES ALIMENTS ET DROGUES</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-11"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">LOI SUR LES PRODUITS DANGEREUX</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-12"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">LOI SUR L'IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-13"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">LOI SUR LA SÛRETÉ DU TRANSPORT MARITIME</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-14"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">LOI SUR LA DÉFENSE NATIONALE</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-15"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">LOI SUR L'OFFICE NATIONAL DE L'ÉNERGIE</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-16"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">LOI SUR LA PROTECTION DES EAUX NAVIGABLES</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-17"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">LOI SUR LE BUREAU DU SURINTENDANT DES INSTITUTIONS FINANCIÈRES</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-18"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">LOI SUR LA PROTECTION DES RENSEIGNEMENTS PERSONNELS ET LES DOCUMENTS ÉLECTRONIQUES</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-19"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">LOI SUR LES PRODUITS ANTIPARASITAIRES</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-20"><span class="HLabel1">PARTIE 19</span> - <span class="HTitleText1">LOI SUR LE RECYCLAGE DES PRODUITS DE LA CRIMINALITÉ ET LE FINANCEMENT DES ACTIVITÉS TERRORISTES</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-21"><span class="HLabel1">PARTIE 20</span> - <span class="HTitleText1">LOI SUR LA QUARANTAINE</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-22"><span class="HLabel1">PARTIE 21</span> - <span class="HTitleText1">LOI SUR LES DISPOSITIFS ÉMETTANT DES RADIATIONS</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-23"><span class="HLabel1">PARTIE 22</span> - <span class="HTitleText1">LOIS SUR LA MARINE MARCHANDE DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la marine marchande du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="#h-26"><span class="HLabel1">PARTIE 23</span> - <span class="HTitleText1">CONVENTION SUR LES ARMES BIOLOGIQUES OU À TOXINES</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-27"><span class="HLabel1">PARTIE 24</span> - <span class="HTitleText1">MODIFICATIONS CORRÉLATIVES, DISPOSITIONS DE COORDINATION ET ENTRÉE EN VIGUEUR</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-28"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>107 - </span><a href="#h-29"><span class="HTitleText3">Loi sur l'accès à l'information</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-30"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-31"><span class="HTitleText3">Abrogations</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-32"><span class="HTitleText2">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-33"><span class="HTitleText3">Loi sur le Tribunal d'appel des transports du Canada</span></a>
</li>
<li><span class='sectionRange'>111.1 - </span><a href="#h-34"><span class="HTitleText3">Loi sur les produits antiparasitaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-35"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-36"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

