<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2013 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA-NAMIBIE</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA-SERBIE</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA-POLOGNE</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">ACCORD FISCAL CANADA-HONG KONG</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-6"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA-LUXEMBOURG</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-1.html#h-7"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1999 pour la mise en oeuvre de conventions fiscales</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-8"><span class="HTitleText2">Avenant et Accord Canada-Luxembourg, 2012</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-9"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">CONVENTION FISCALE CANADA-SUISSE</span></a>
</li>
<li><a href="page-3.html#h-10"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-4.html#h-11"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-5.html#h-12"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-6.html#h-13"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-7.html#h-14"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-8.html#h-15"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>

