<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modifiant la Loi sur les douanes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-2"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

