<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
<?Pub Caret?>Loi sur le développement et la conservation des parcs nationaux du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">RÉSERVE À VOCATION DE PARC NATIONAL DE L’ÎLE-DE-SABLE DU CANADA</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les parcs nationaux du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText2">Modifications corrélatives à la <cite class="XRefExternalAct">Loi de 2001 sur la marine marchande du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">AUTRES MODIFICATIONS À LA <cite class="XRefExternalAct">LOI SUR LES PARCS NATIONAUX DU CANADA</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Modifications</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

