<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi visant à protéger le système d’immigration du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-2"><span class="HTitleText1">LOI SUR L’IMMIGRATION ET LA PROTECTION DES RÉFUGIÉS</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-3"><span class="HTitleText1">LOI SUR DES MESURES DE RÉFORME ÉQUITABLES CONCERNANT LES RÉFUGIÉS</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-4"><span class="HTitleText1">LOI SUR LA SÛRETÉ DU TRANSPORT MARITIME</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-7.html#h-5"><span class="HTitleText1">LOI SUR LE MINISTÈRE DE LA CITOYENNETÉ ET DE L’IMMIGRATION</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-7.html#h-6"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-8.html#h-7"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-8.html#h-8"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

