<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 d’exécution du budget de 2004</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LE DROIT POUR LA SÉCURITÉ DES PASSAGERS DU TRANSPORT AÉRIEN</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">MODIFICATION DE LA LOI SUR LA TAXE SUR LES PRODUITS ET SERVICES DES PREMIÈRES NATIONS</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">MODIFICATION DE LA LOI DE L’IMPÔT SUR LE REVENU ET DE LOIS CONNEXES ET DISPOSITION DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-6"><span class="HTitleText2">Loi d’exécution du budget de 2003</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-7"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-8"><span class="HTitleText2">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-9"><span class="HTitleText2">Loi sur l’interprétation des conventions en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-10"><span class="HTitleText2">Loi sur la Cour canadienne de l’impôt</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-11"><span class="HTitleText2">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-12"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><a href="#h-13"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

