<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la législation relative aux avantages pour les anciens combattants et les enfants des anciens combattants décédés</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR L’AIDE EN MATIÈRE D’ÉDUCATION AUX ENFANTS DES ANCIENS COMBATTANTS DÉCÉDÉS</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES PENSIONS</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR LA PENSION DE RETRAITE DE LA GENDARMERIE ROYALE DU CANADA</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR LES ALLOCATIONS AUX ANCIENS COMBATTANTS</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText1">LOI PORTANT MODIFICATION DE LA LÉGISLATION CONCERNANT LES AVANTAGES POUR LES ANCIENS COMBATTANTS</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">DISPOSITIONS TRANSITOIRES</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

