<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
L<?Pub Caret1?>oi sur l’Équité entre les sexes relativement à l’inscription au registre des Indiens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LES INDIENS</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-3"><span class="HTitleText1">RAPPORT AU PARLEMENT</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">DISPOSITIONS CONNEXES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

