<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant certaines lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">TITRE ABRÉGÉ</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR L'AGENCE DES DOUANES ET DU REVENU DU CANADA</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">LOI SUR LES DOUANES</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">LOI SUR LA GESTION DES FINANCES PUBLIQUES</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText1">LOI SUR L'IMPORTATION DES BOISSONS ENIVRANTES</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">LOI SUR LA PENSION DE RETRAITE DES LIEUTENANTS-GOUVERNEURS</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-7"><span class="HTitleText1">LOI SUR LA MODERNISATION DE CERTAINS RÉGIMES D'AVANTAGES ET D'OBLIGATIONS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText1">LOI SUR LA TABLE RONDE NATIONALE SUR L'ENVIRONNEMENT ET L'ÉCONOMIE</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-9"><span class="HTitleText1">LOI SUR LE PARLEMENT DU CANADA</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText1">LOI SUR LES TRAITEMENTS</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">LOI SUR LES PRESTATIONS DE RETRAITE SUPPLÉMENTAIRES</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-12"><span class="HTitleText1">RÈGLEMENT SUR LE PRIX DES SERVICES CONSULAIRES SPÉCIALISÉS</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText1">DISPOSITIONS DE COORDINATION</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la pension de retraite des lieutenants-gouverneurs</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Projet de loi C-25</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText1">ENTRÉE EN VIGUEUR</span></a>
</li></ul>
</li></ul>

</nav>

