<nav role="navigation">
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur la réorganisation et l’aliénation de Eldorado Nucléaire Limitée et la Loi sur la participation publique au capital de Petro-Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">LOI SUR LA RÉORGANISATION ET L’ALIÉNATION DE ELDORADO NUCLÉAIRE LIMITÉE</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">LOI SUR LA PARTICIPATION PUBLIQUE AU CAPITAL DE PETRO-CANADA</span></a>
</li></ul>
</li></ul>

</nav>

