<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Déclaration des Nations Unies sur les droits des peuples autochtones</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Mesures visant la compatibilité des lois et l’atteinte des objectifs de la Déclaration</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Déclaration des Nations Unies sur les droits des peuples autochtones</span></a>
</li></ul>
</li></ul>

</nav>

