<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi sur les relations de travail dans le secteur public fédéral et d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les relations de travail dans le secteur public fédéral</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-2"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-3"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-4"><span class="HTitleText1">Modifications à la <cite class="XRefExternalAct">Loi sur l’équité dans la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-5"><span class="HTitleText1">Modifications à la <cite class="XRefExternalAct">Loi n° 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-6"><span class="HTitleText1">Modifications à la <cite class="XRefExternalAct">Loi n° 1 sur le plan d’action économique de 2014</cite></span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-7"><span class="HTitleText1">Modification à la <cite class="XRefExternalAct">Loi n° 1 sur le plan d’action économique de 2015</cite></span></a>
</li></ul>
</li></ul>

</nav>

